### PR TITLE
fix(numberinput): remove defaults from min and max

### LINKED ISSUE #13243: [Bug]: Number input component accidently has max set to 100 by default
### Package

@carbon/react

### Browser

_No response_

### Package version

1.21.0

### React version

18.2.0

### Description

Number input has 100 as maximum value even when `max` is not set.

Screenshot 2023-02-27 at 12 30 57 PM

### Reproduction/example

https://codesandbox.io/s/boring-fog-m498gt?file=/index.js

### Steps to reproduce

Remove `max` of ` <NumberInput>`

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tay1orjones**
Reverts #12768 

Closes https://github.com/carbon-design-system/carbon/issues/13243

### CODE REVIEW

File: packages/react/src/components/NumberInput/NumberInput.tsx [hunk 1]
```diff
@@ -209,8 +209,8 @@ const NumberInput = React.forwardRef(function NumberInput(
     invalid = false,
     invalidText,
     light,
-    max = 100,
-    min = 0,
+    max,
```
Comment (tw15egan) [inline packages/react/src/components/NumberInput/NumberInput.tsx:212]:
```suggestion
    max = Infinity,
```

Would this be a safe middle ground between the original issue and the breaking change?

**Review by tw15egan — APPROVED** [review]

File: packages/react/src/components/NumberInput/NumberInput.tsx (hunk 1 above)
Comment (tay1orjones) [reply packages/react/src/components/NumberInput/NumberInput.tsx:212]: Kind of. Even with this the `clamp` function will still return `NaN` if `min` is undefined.

**Review by andreancardona — APPROVED** [review]

**Review by dabrad26 — APPROVED** [review]

**Review by cknabe — APPROVED** [review]

**Review by francinelucca — APPROVED** [review]

**Review by hsu022210 — APPROVED** [review]

**Comment by tay1orjones** [comment]
This fix was included in [1.24.0-rc.0](https://www.npmjs.com/package/@carbon/react/v/1.24.0-rc.0)
