### PR TITLE
6001 combobox fix

### LINKED ISSUE #6001: [ComboBox] Unable to choose random item
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using the combo box you should be able to enter in a random string and have that be the selected value of the input. While you are able to type in a random string, this string never is surfaced in any event handler that can tell me that the user is done entering in the string. 
- `onChange` is only ever triggered if selection is part of the list of `items` or back to null
- `onInputChange` lets me get value of input but you can never know when user is done typing
- `onKeyPress` or any variant of will only surface the` key` (`keycode` is unavailable) and the `enter` key is only captured on opening the input. On close there is a `stopPropagation` added that does not allow me to capture the closing `enter` event. 

> Is this issue related to a specific component?

ComboBox

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would expect that `onChange` would have the value of the input on time of input closing. So random string values would be surfaced as well. Short of this, `onKeyPress` should be allowed to bubble up so I can at least trigger an action when the input is closed with a selection inside. 

My use case is creating tags from the input, either from list or random, when the user hits enter while still staying inside the input to enter a new value. details outlined [here](https://github.com/IBM/carbon-addons-iot-react/issues/1130)

> What browser are you working in?

> What version of the Carbon Design System are you using?

10.10.3 & 7.10.3

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

PAL for Watson IoT

## Steps to reproduce the issue

1. Go to combobox story
2. Open up action panel in storybook
3. Type random string and hit enter
4. See that no action was triggered for onChange

can also add `onKeypress` and just log out the evt. to console. Notice that when you hit enter on the open combo box there is no keypress logged. Internal code is stopping bubbling of this action.

## Notes
I would be willing to help with code if deemed appropriate

### PR DESCRIPTION
**Pull request by davidicus**
Closes #6001 

Unable to capture generated item from input because of bubbling swallowed. By removing users can tell when the enter key has been pressed which would signify the end of inputed string. 

#### Changelog

**Removed**

- removed `stopPropagration()` from `combobox.js`

#### Testing / Reviewing
verify that removing `stopPropagration` has no adverse effect

### CODE REVIEW

File: packages/react/src/components/ComboBox/ComboBox.js [hunk 1]
```diff
@@ -379,8 +379,6 @@ export default class ComboBox extends React.Component {
                   id,
                   placeholder,
                   onKeyDown: event => {
-                    event.stopPropagation();
-
                     if (match(event, keys.Enter)) {
```
Comment (joshblack) [inline packages/react/src/components/ComboBox/ComboBox.js]: I _think_ this will end up breaking for folks trying to enter in a field with a space (it will toggle the menu)

Should we do something like:

```js
if (matches(event, [keys.Enter, keys.Space])) {
  event.stopPropagation();
  if (match(event, keys.Enter)) {
    toggleMenu();
  }
}
```

**Review by joshblack — CHANGES_REQUESTED** [review]

File: packages/react/src/components/ComboBox/ComboBox.js (hunk 1 above)
Comment (davidicus) [reply packages/react/src/components/ComboBox/ComboBox.js]: yes. like we discussed, I added the check for space key to `stopPropagation`

**Comment by davidicus** [comment]
Ideally downshift would fire the `onChange` when the user hits enter key. This combined with passing along the input value during `onChange` would allow for custom entry as well as extension i am trying to add. I looked into downshift docs and not quite sure its possible to dictate to downshift when this should fire. If this is possible and someone could point me to the appropriate documentation I would be glad to modify this PR

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
Sorry for the delay @davidicus! Finally back in the office 👀

**Comment by davidicus** [comment]
Hi! Just checking to see if there is any more feedback or edits needed for approval.

**Comment by joshblack** [comment]
@davidicus thanks for checking in! I think one thing on your end will be the merge conflict but will bump @tw15egan and @dakahn to see if they have a sec to review today/this week 👀

**Comment by dakahn** [comment]
happy to review this when the conflicts are resolved

**Comment by davidicus** [comment]
@dakahn thanks. I have resolved the conflict.

**Review by tw15egan — APPROVED** [review]

**Comment by tw15egan** [comment]
just pinging @dakahn if you want to take a look at it before merging 👍
