### PR TITLE
fix(multiselect): set optional chaining for undefined multiselect

### LINKED ISSUE #16052: [Bug]: Crash in MultiSelect with undefined selectedItems
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.53.0

### React version

v18.2.0

### Description

This is admittedly user error, but it seems like it would be a good idea to protect against it. 
If `selectedItems` has an array with `undefined` in it, [this PR](https://github.com/carbon-design-system/carbon/pull/15633) will try to read `text` from undefined and crash with the stack below:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'text')
    at @carbon_react.js?v=72b18db9:100065:90
    at Array.map (<anonymous>)
    at @carbon_react.js?v=72b18db9:100065:71
```

I hit it b/c we had some bad test code, but figured it would be a good idea to just add some optional chaining in that MultiSelect code so it doesn't crash. 

### Reproduction/example

https://stackblitz.com/edit/github-caiwsw?file=src%2FApp.jsx

### Steps to reproduce

Create a multiselect
in `selectedItems`, have an item that is undefined or null.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Application/PAL

IBM Cloud Satellite

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by jesnajoseijk**
Closes #16052

Added optional chaining for undefined multi select value

#### Changelog

**New**

- {{new thing}}

**Changed**

- multiselect.tsx
- multiselect-test.js

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{MultiSelect component}}

### CODE REVIEW

File: packages/react/src/components/MultiSelect/tools/sorting.js [hunk 1]
```diff
@@ -16,7 +16,7 @@
  * @returns {number}
  */
 export const defaultCompareItems = (itemA, itemB, { locale }) =>
-  itemA.localeCompare(itemB, locale, {
+  itemA?.localeCompare(itemB, locale, {
```
Comment (tay1orjones) [inline packages/react/src/components/MultiSelect/tools/sorting.js]: Could you explain why this is necessary? My understanding is that this code is called via `sortItems`, which always runs each item through an `itemToString` function (`defaultItemToString`) that should return `''` if the item is undefined

https://github.com/carbon-design-system/carbon/blob/2ebd2cbac7ffa53492a75f655b374a4f37c73115/packages/react/src/components/MultiSelect/tools/sorting.js#L43-L45

Comment (jesnajoseijk) [reply packages/react/src/components/MultiSelect/tools/sorting.js]: @tay1orjones On the mentioned scenario in [16052](https://github.com/carbon-design-system/carbon/issues/16052),we are getting the below mentioned error as well.
Screenshot 2024-03-28 at 10 40 31 AM

Comment (tay1orjones) [reply packages/react/src/components/MultiSelect/tools/sorting.js]: Okay, a few suggestions would be to:

* Handle `undefined` upstream from this - could we filter out undefined values from `initialSelectedItems` within MultiSelect?
* Write a test for MultiSelect that reproduces the error, to indicate that whatever fix we land on here actually works as intended

Comment (jesnajoseijk) [reply packages/react/src/components/MultiSelect/tools/sorting.js]: @tay1orjones undefined items are filtered out from the items list  and the associated test case is added in the new PR

File: packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js [hunk 2]
```diff
@@ -37,6 +37,29 @@ describe('MultiSelect', () => {
...
+    const { container } = render(
+      <MultiSelect
+        id="custom-id"
+        label={label}
+        items={items}
+        itemToString={(item) => (item ? item.text : '')}
+      />
+    );
+    // eslint-disable-next-line testing-library/prefer-screen-queries
+    const labelNode = getByText(container, label);
```
Comment (tay1orjones) [inline packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js]: This should be possible with the allowed 
```js
screen.getByRole('combobox', { name: label })
```

File: packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js [hunk 3]
```diff
@@ -37,6 +37,29 @@ describe('MultiSelect', () => {
...
+
+    await userEvent.click(labelNode);
+
+    // eslint-disable-next-line testing-library/prefer-screen-queries
+    expect(getByText(container, 'joey')).toBeInTheDocument();
+    // eslint-disable-next-line testing-library/prefer-screen-queries
+    expect(getByText(container, 'johnny')).toBeInTheDocument();
+    // eslint-disable-next-line testing-library/prefer-screen-queries
+    expect(getByText(container, 'undefined')).not.toBeInTheDocument();
```
Comment (tay1orjones) [inline packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js]: The queries here should also be possible with the allowed 
```js
screen.getByRole('option', { name: 'joey' })
```

File: packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js [hunk 4]
```diff
@@ -37,6 +37,29 @@ describe('MultiSelect', () => {
...
+    const items = [{ text: 'joey' }, { text: 'johnny' }, { text: undefined }];
+    const label = 'test-label';
+    const { container } = render(
+      <MultiSelect
+        id="custom-id"
+        label={label}
+        items={items}
+        itemToString={(item) => (item ? item.text : '')}
+      />
+    );
```
Comment (tay1orjones) [inline packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js]: With those queries sorted you should be able to remove the container

```suggestion
    render(
      <MultiSelect
        id="custom-id"
        label={label}
        items={items}
        itemToString={(item) => (item ? item.text : '')}
      />
    );
```

File: packages/react/src/components/MultiSelect/MultiSelect.tsx [hunk 5]
```diff
@@ -373,14 +373,29 @@ const MultiSelect = React.forwardRef(
       selectedItems: selected,
     });
 
+    // Filter out items with an object having undefined values
+    const filteredItems = items.filter((item) => {
+      if (typeof item === 'object' && item !== null) {
+        for (const key in item) {
+          if (
+            Object.prototype.hasOwnProperty.call(item, key) &&
```
Comment (tay1orjones) [inline packages/react/src/components/MultiSelect/MultiSelect.tsx]: `hasOwn()` is a bit more intuitive and should be functionally the same I think

```suggestion
            Object.hasOwn(item, key) &&
```

File: packages/react/src/components/MultiSelect/MultiSelect.tsx [hunk 6]
```diff
@@ -373,14 +373,29 @@ const MultiSelect = React.forwardRef(
...
+            item[key] === undefined
+          ) {
+            return false; // Return false if any property has an undefined value
+          }
+        }
+      }
+      return true; // Return true if item is not an object with undefined values
+    });
+
```
Comment (tay1orjones) [inline packages/react/src/components/MultiSelect/MultiSelect.tsx]: I think it would make sense for this to be in a `useMemo` with `items` in the dependency array so it doesn't filter on every render.

**Review by tay1orjones — CHANGES_REQUESTED** [review]
Pretty close here! Just a couple other things I noticed

File: packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js (hunk 2 above)
Comment (jesnajoseijk) [reply packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js]: @tay1orjones  shortened this to just screen.getByRole('combobox') becuase name is coming in as  empty string and giving error as  :
TestingLibraryElementError: Unable to find an accessible element with the role "combobox" and name "test-label"

    Here are the accessible roles:

      combobox:

      Name "":
      <button
        aria-activedescendant=""
        aria-controls="downshift-:r0:-menu"
        aria-expanded="false"
        aria-haspopup="listbox"
        aria-labelledby="downshift-:r0:-label"
        class="cds--list-box__field"
        id="downshift-:r0:-toggle-button"
        role="combobox"
        tabindex="0"
        type="button"
      />

File: packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js [hunk 7]
```diff
@@ -37,6 +37,27 @@ describe('MultiSelect', () => {
...
+
+    const labelNode = screen.getByRole('combobox');
+    await userEvent.click(labelNode);
+
+    expect(screen.getByRole('option', { name: 'joey' })).toBeInTheDocument();
+    expect(screen.getByRole('option', { name: 'johnny' })).toBeInTheDocument();
+    expect(
+      screen.queryByRole('option', { name: 'undefined' })
+    ).not.toBeInTheDocument();
```
Comment (tay1orjones) [inline packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js:59]: We also have a global setting that fails tests if they call console.warn/error, so this test will definitely cover the old behavior you're fixing in this PR.

**Review by tay1orjones — APPROVED** [review]
Thanks for tackling this!

**Review by tw15egan — APPROVED** [review]
LGTM, thanks for contributing!
