### PR TITLE
fix(SideNav): pass additional props provided to SideNav to the rendered nav element

### LINKED ISSUE #7903: Sidenav should allow extra props to be passed to the rendered component
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

Sidenav should pass additional props to the rendered component, similar to what some of the other components are doing , for example Tab: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Tab/Tab.js#L165

Development effort.

### Justification

Allows for additional attributes to be passed to the component for greater control/accessibility compliance.

### Specific timeline issues / requests

Any time

### Available extra resources

I can open a PR if the proposal is accepted.

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._

### PR DESCRIPTION
**Pull request by gptt916**
Closes #7903

pass additional props provided to `SideNav` to the rendered `nav` element.

#### Changelog

**New**

- SideNav pass additional props to rendered element

#### Testing / Reviewing

- Create `SideNav` element
- in it's props, pass an arbitrary prop, like `data-loating-menu-container={true}`
- verify that this attribute is rendered in the `nav` element

### CODE REVIEW

File: packages/react/src/components/UIShell/SideNav.js [hunk 1]
```diff
@@ -122,6 +123,7 @@ const SideNav = React.forwardRef(function SideNav(props, ref) {
         {...accessibilityLabel}
         {...eventHandlers}>
```
Comment (tw15egan) [inline packages/react/src/components/UIShell/SideNav.js]:
```suggestion
        {...eventHandlers}
        {...other}>
```

File: packages/react/src/components/UIShell/SideNav.js [hunk 2]
```diff
@@ -122,6 +123,7 @@ const SideNav = React.forwardRef(function SideNav(props, ref) {
...
         {childrenToRender}
+        {...other}
```
Comment (tw15egan) [inline packages/react/src/components/UIShell/SideNav.js]:
```suggestion

```

**Comment by tw15egan** [comment]
@gptt916 I just pushed up a change that comments out some old code that was causing console warnings since it was now being passed down to `SideNav`.

Everything else looks good 👍🏻

**Review by tw15egan — APPROVED** [review]

**Review by dakahn — APPROVED** [review]
