### PR TITLE
fix(components): fix for RHL

### LINKED ISSUE #2630: Different appearances of components when using react-hot-loader
As stated in
https://github.com/carbon-design-system/carbon-components-react/blob/master/README.md:
"1.These components require the use of Webpack in your project"

Typically, development webpack configurations use react-hot-loader while production webpack configurations don't.

But carbon-components-react does not work with react-hot-loader, resulting in totally different appearances / behavior in development and production.

For example, in TableBody.js:
`if (child.type === TableRow)`

This will work fine in production where there is no hotloading, but not in development when there is hotloading.

The reason: https://github.com/gaearon/react-hot-loader/issues/304

The fix is explained in the section on _Checking Element types_ at https://github.com/gaearon/react-hot-loader/blob/master/README.md

This issue is similar to https://github.com/carbon-design-system/carbon-components-react/issues/857 but the difference is that it is not just the childrenOf and childrenOfType that are failing; components appear totally different.

### PR DESCRIPTION
**Pull request by asudoh**
This change fixes the issue that comes with unmatched component class ref vs. its RHL-proxied version. The issue was observed with running `<ComposedModal>` in Carbon website's component live demo pane, opening the modal and hitting the close button.

Applied a similar fix to `<DatePicker>`.

Fixes #2630.

#### Changelog

**Changed**

- Replaces direct `.type` check to component class with `React.createElement(ComponentClass).type`.

#### Testing / Reviewing

Testing should make sure `<ComposedModal>` and `<DatePicker>` are not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me

File: packages/react/src/components/DatePicker/DatePicker.js [hunk 1]
```diff
@@ -581,14 +581,20 @@ export default class DatePicker extends Component {
 
     const childArray = React.Children.toArray(children);
     const childrenWithProps = childArray.map((child, index) => {
-      if (index === 0 && child.type === DatePickerInput) {
+      if (
+        index === 0 &&
+        child.type === React.createElement(DatePickerInput).type
```
Comment (joshblack) [inline packages/react/src/components/DatePicker/DatePicker.js:586]: Would we have any prop type warnings if we do `createElement` without required props (I think `id` in this case)?

Comment (asudoh) [reply packages/react/src/components/DatePicker/DatePicker.js:586]: Good catch - Updated.

**Review by joshblack — APPROVED** [review]
