### PR TITLE
fix(17119): combobox not displaying selected option once search query is cleared

### LINKED ISSUE #17119: [Bug]: Carbon Combobox component not displaying selected option once search query is cleared
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox

### Package version

1.63.1

### React version

18.0.0

### Description

I noticed an issue in combobox component. Once we searches and select an item from list, it will be selected. But when we clear the search box and click outside, it seems the field has no value selected. Only when we expand the dropdown, we can see the item as checked.
When we search for an item which is not in the list and click outside, the selected value is populated back in the search field.
Attaching a video for reference.

https://github.com/user-attachments/assets/3aa0d2dc-15a6-4766-a46d-7b334bfafe93

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-combobox--playground&args=allowCustomValue:!false

### Steps to reproduce

- Select a value from combobox. The dropdown will be collapsed and the item will be displayed in search field.
- Now remove the search term from the field. and click outside. The value won't be displayed in the input field. but when expanded, there we can see the prev item is already in selected state.

When we search for some other item which is not in the list and click outside, the selected item will be populated back in the input field. Same behaviour is expected on clearing the input field when an item is already selected.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

IBM Data Product Hub

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by enricobguedes**
Closes https://github.com/carbon-design-system/carbon/issues/17119

#### Changelog

**New**

- Added new checks within combo box for empty inputs and no text highlights to invalidate user selection (return to empty state as intented).
- Added check for the blur functionality to do the same as the above, returning the component state to empty/not selected
- Both mimic the clearSelection state.

**Changed**

- N/A

**Removed**

- N/A

#### Testing / Reviewing

Using the Carbon storybook for react components, reviewers can test as shown in the original issue reported.

### CODE REVIEW

File: packages/react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -1013,6 +1016,15 @@ const ComboBox = forwardRef(
...
                   }
+                  if (!inputValue && highlightedIndex == -1) {
+                    if (event.key == 'Enter') {
+                      if (!event.currentTarget.value) {
+                        if (!isOpen) toggleMenu();
+                        selectItem(null);
+                        event.preventDownshiftDefault = true;
+                      }
+                    }
+                  }
```
Comment (guidari) [inline packages/react/src/components/ComboBox/ComboBox.tsx]: Can we simplify this if clause into a single condition? I might be wrong, but it looks like `inputValue` and `event.currentTarget.value` are the same, making this check a bit redundant.

I wonder if something like that would work:

```
if (!inputValue && highlightedIndex === -1 && event.key === 'Enter') {
  if (!isOpen) toggleMenu();
  selectItem(null);
  event.preventDownshiftDefault = true;
}
```

We would have to cover that with Jest and Playwright tests as well.

File: packages/react/src/components/ComboBox/ComboBox.tsx [hunk 2]
```diff
@@ -843,6 +843,9 @@ const ComboBox = forwardRef(
 
     const handleFocus = (evt: FocusEvent<HTMLDivElement>) => {
       setIsFocused(evt.type === 'focus');
+      if (!inputRef.current?.value && evt.type === 'blur') {
```
Comment (guidari) [inline packages/react/src/components/ComboBox/ComboBox.tsx:846]: Would `inputValue` work in this case? Just wondering...

File: e2e/components/ComboBox/ComboBox-test.avt.e2e.js [hunk 3]
```diff
@@ -91,7 +91,9 @@ test.describe('@avt ComboBox', () => {
     await expect(menu).toBeHidden();
     await expect(combobox).toBeFocused();
     await page.keyboard.press('Enter');
-    await expect(menu).toBeVisible();
+    // Expect to be hidden if no highlight or text in combobox.
+    await expect(menu).toBeHidden();
+    await page.keyboard.press('Space');
```
Comment (guidari) [inline e2e/components/ComboBox/ComboBox-test.avt.e2e.js]: Remove this test and keep the `await expect(menu).toBeVisible();`

**Review by guidari — CHANGES_REQUESTED** [review]
Looking good so far! Thanks for opening that! 🚀 

A couple things. Looks like the Combobox is not opening when pressing `Enter` anymore. Combobox should open when pressing `Enter`. The test should remaing the same in this case.

File: packages/react/src/components/ComboBox/ComboBox-test.js [hunk 4]
```diff
@@ -764,5 +764,17 @@ describe('ComboBox', () => {
 
       expect(input).toHaveDisplayValue('Apple');
     });
+
+    it('should remove input and enter new conditions', async () => {
```
Comment (guidari) [inline packages/react/src/components/ComboBox/ComboBox-test.js:769]: I'm not sure about this test. Is it testing the functionality you created?

Otherwise we could add a test like that, to test step by step the interaction with the Combobox.

You will noticed that if you remove the changes you made in the `Combox.tsx` this test will fail **(as expected)**, however it will pass with the current changes **(as expected)**

```
 it('should open the menu and select null when Enter is pressed with no input and no highlighted item', async () => {
      const onInputChange = jest.fn();

      render(<ComboBox {...mockProps} onInputChange={onInputChange} />);

      await userEvent.type(findInputNode(), 'apple');
      expect(findInputNode()).toHaveDisplayValue('apple');
      await userEvent.keyboard('[Enter]');

      // Delete the selected item
      await userEvent.keyboard('[Backspace]');
      await userEvent.keyboard('[Backspace]');
      await userEvent.keyboard('[Backspace]');
      await userEvent.keyboard('[Backspace]');
      await userEvent.keyboard('[Backspace]');
      // check for an empty value
      expect(findInputNode()).toHaveDisplayValue('');

      // blur
      await userEvent.keyboard('[Tab]');
      assertMenuClosed(mockProps);

      // open the menu
      await userEvent.click(findInputNode());
      assertMenuOpen(mockProps);

      // check if the `li` item are all false
      for (let i = 0; i < mockProps.items.length; i++) {
        const item = findMenuItemNode(i);
        console.log({ item });
        expect(item).toHaveAttribute('aria-selected', 'false');
      }
    });
    ```

Comment (enricobguedes) [reply packages/react/src/components/ComboBox/ComboBox-test.js:769]: Yes, this is the test I've created for this addition! I will add this extra evaluation then, thanks!

**Review by guidari — APPROVED** [review]

**Review by kennylam — APPROVED** [review]
LGTM, thanks!
