### PR TITLE
fix: added missing accessibility labels for pagination elements

### LINKED ISSUE #20042: [a11y]: Form control element has no associated label
### Package

@carbon/web-components

### Browser

Chrome

### Operating System

MacOS

### Package version

2.27.2

### React version

_No response_

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker

### Assistive technology

_No response_

### Description

Error: Form control element has no associated label
This error is seen for pagination buttons and select element in accessibility tool

### WCAG 2.1 Violation

_No response_

### Reproduction/example

Just open the storybook and run the accessibility check 

### Steps to reproduce

Just open the storybook and run the accessibility check 

### Suggested Severity

None

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by grishma-shah7**
Closes https://github.com/carbon-design-system/carbon/issues/20042

This PR includes:
1. bug fix for pagination button where aria label was not being set correctly due to condition.
Issue was that in web-components `button` component, we have a condition that if tooltipText is present AND the button is not disabled, we show the aria label. Otherwise it is missing. Issue comes up on pagination component, it uses the button with the tooltipText present, but when on page#1 the previous page button is disabled and hence there is no label associated with it. For the fix, we'll check if tooltipText is present, use that text as aria-label, otherwise keep as empty 

Before:
Screenshot 2025-11-19 at 3 12 36 PM

After:
Screenshot 2025-11-19 at 3 12 53 PM

2. `title` attribute missing on `select` component on pagination
To match the react component version, where the pagination select component has `title` attribute added as the value of the dropdown, have added the same for the web component select component

React:
Screenshot 2025-11-19 at 3 09 42 PM

Web-component before:
Screenshot 2025-11-19 at 3 11 22 PM

Web-component after:
Screenshot 2025-11-19 at 3 11 59 PM

### Changelog

**New**

- {{new thing}}

**Changed**

- {{changed thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add steps or a checklist for how reviewers can verify this PR works or not }}

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by grishma-shah7** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by heloiselui** [comment]
Hey, the DCO check is failing. It looks like the commit was made with a different account, try signing off the DCO with that account as well.

image

File: packages/web-components/src/components/button/button.ts [hunk 1]
```diff
@@ -404,6 +404,7 @@ class CDSButton extends HostListenerMixin(FocusMixin(LitElement)) {
             ?disabled="${disabled}"
             tabindex="${tabIndex}"
             type="${ifDefined(type)}"
+            aria-label="${ifDefined(tooltipText) ?? ''}"
```
Comment (heloiselui) [inline packages/web-components/src/components/button/button.ts]:
```suggestion
            aria-label="${ifDefined(tooltipText)}"
```

Comment (heloiselui) [reply packages/web-components/src/components/button/button.ts]: instead of always setting `aria-label="${ifDefined(tooltipText) ?? ''}"`, we can omit the attribute when no tooltip text exists. The previous version left an empty aria-label="" on every non-tooltip button, which overrides any text content and strips the accessible name. With `ifDefined(tooltipText)` alone, pagination buttons still get their tooltip text as the label, while regular buttons fall back to the default label behavior.

**Review by heloiselui — CHANGES_REQUESTED** [review]

File: packages/web-components/src/components/button/button.ts (hunk 1 above)
Comment (grishma-shah7) [reply packages/web-components/src/components/button/button.ts]: Agreed! Have addressed this change

**Review by 2nikhiltom — APPROVED** [review]
LGTM, thanks for following up 
 DCO check is still failing. looks like there are 2 different account, try signing off the DCO with that account as well

**Comment by grishma-shah7** [comment]
> LGTM, thanks for following up DCO check is still failing. looks like there are 2 different account, try signing off the DCO with that account as well

Hi @2nikhiltom that second account is not mine, not sure how but it seems like it picked up someone else's account
Can we do something for it, or would I need to create a new PR?

**Comment by grishma** [comment]
Can you please remove my email id from this thread? I have nothing to with
this repo

**Review by heloiselui — APPROVED** [review]
LGTM
