### PR TITLE
fix(Dropdown): add downshiftProps handling

### LINKED ISSUE #6243: Dropdown: No way to add add "onStateChange" functionality since  upgrading downshift
## What package(s) are you using?
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Before https://github.com/carbon-design-system/carbon/pull/5373, we used to be able to pass in a `downshiftProps` on the `Dropdown` component in order to give the dropdown custom behaviour.

For example, we would use it to tell it to make an API call to retrieve the items we display in the dropdown:
```
<Dropdown
    downshiftProps={{
        onStateChange: ({ ...props }) => {
            if (props.isOpen) {
                this.props.fetchItems()
            }
        }
    }}
/>
```

Now, that property has been removed with the upgrade of downshift, there is no replacement for passing this `onStateChange` property or any `onClick`-like behaviour.

This is a breaking change that we started noticing since `carbon-components-react@7.13.0`.

> Is this issue related to a specific component?

`Dropdown`.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect to be able to pass in a property to the `Dropdown` component which does what `downshiftProps` (respectively `onStateChange`) used to do. In this case, tell the `Dropdown` component what to do when someone clicks on it.

> What browser are you working in?

Chrome 83.0.4103.97

> What version of the Carbon Design System are you using?

`carbon-components-react@7.13.0`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue
N/A

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information
I think what's missing is the `onStateChange` property in `useSelect` ( https://github.com/downshift-js/downshift/tree/master/src/hooks/useSelect#onstatechange) here: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Dropdown/Dropdown.js#L58

### PR DESCRIPTION
**Pull request by dakahn**
Closes #6243 

In our update to v5 Downshift we broke functionality for passing in `downshiftProps` to our Dropdown component.

#### Testing / Reviewing

in Dropdown-story.js add something like
image

And then make a selection in Dropdown and check your console and make sure that did in fact work 🏄

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

File: packages/react/src/components/Dropdown/Dropdown.js [hunk 1]
```diff
@@ -44,12 +44,14 @@ function Dropdown({
...
   initialSelectedItem,
   selectedItem: controlledSelectedItem,
+  downshiftProps,
 }) {
   const selectProps = {
     items,
     itemToString,
     initialSelectedItem,
     onSelectedItemChange,
+    ...downshiftProps,
```
Comment (joshblack) [inline packages/react/src/components/Dropdown/Dropdown.js]: I think this should be the first thing in the object to match previous behavior e.g.

```js
const selectProps = {
  ...downshiftProps,
  items,
  // ...
}
```

**Review by joshblack — CHANGES_REQUESTED** [review]

**Review by joshblack — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅
