### PR TITLE
fix: `SelectableTile` onChange firing twice in react strict mode

### LINKED ISSUE #19521: [Bug]: SelectableTile onChange callback being called twice when the tile is clicked
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.83

### React version

19

### Description

onChange callback is called twice in dev environments when the tile is clicked or keypressed. This is due to the callback being processed inside the state update callback, which react will call twice in dev mode.

This can lead to many issues, but for me it leads to the following error as I am updating state in the callback.

`Cannot update a component (`xxx`) while rendering a different component (`ForwardRef(SelectableTile)`). To locate the bad setState() call inside `ForwardRef(SelectableTile)`, follow the stack trace as described in https://react.dev/link/setstate-in-render`

I am working around this issue by checking to see if I've already made the state update before trying again.

### Reproduction/example

https://stackblitz.com/edit/vitejs-vite-r8jcjzyb?file=src%2FApp.tsx

### Steps to reproduce

Have a selectableTile component with an onChange callback. Click the selectableTile, watch the callback get control 2x when in dev mode.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Gururajj77**
Closes #19521 

Fixed the onChange handler in the SelectableTile fires twice under React's strict mode by replacing render-time state sync with useEffect and centralizing selection logic

### Changelog

**New**

- Added useEffect to handle state sync with selected prop instead of doing it during render
- Added centralized handleSelectionChange function to manage all selection updates

**Changed**

- Moved state synchronization from render phase to useEffect to fix strict mode issues
- Updated event handlers to use proper TypeScript types
- Combined duplicate selection logic into single reusable function

**Removed**

- Removed render-time state sync logic that was causing double firing
- Removed unnecessary onChange handler from div element
- Removed prevSelected state that was used for render-time comparisons

#### Testing / Reviewing

To test the bug first, as we can't reproduce this in local directly
- providing the [stackblitz](https://stackblitz.com/edit/github-fdjpjsn2?file=src%2FApp.tsx,package.json,src%2Fmain.tsx&preset=node=) with the bug here to understand how `onChange` is fired twice
- in the main.tsx, remove the `<React.StrictMode>` tag, and test it again.
- see that `onChange` handler fires only once.

To test the fix:
- pull this PR down on local, and build the application.
- add this line in decorators array inside the `packages/react/.storybook/preview.js` file 

```
(Story) => (

<React.StrictMode>

<Story />

</React.StrictMode>

),

```

Image provided for the exact line and place to add this
image
- open the test story "Selectable on change test" and keep the console open.
- click on the tile to make sure that the `onChange` handler is fired once.

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/react/src/components/Tile/Tile.tsx [hunk 1]
```diff
@@ -497,48 +502,41 @@ export const SelectableTile = React.forwardRef<
...
+  );
+
+  function handleClick(evt: React.MouseEvent<HTMLDivElement>) {
     evt.preventDefault();
     evt?.persist?.();
     if (
       normalizedDecorator &&
       decoratorRef.current &&
-      decoratorRef.current.contains(evt.target)
+      decoratorRef.current.contains(evt.target as Node)
```
Comment (adamalston) [inline packages/react/src/components/Tile/Tile.tsx]: The type assertion isn't necessary. There's a type-safe way to implement this condition:

```suggestion
      evt.target instanceof Node &&
      decoratorRef.current.contains(evt.target)
```

File: packages/react/src/components/Tile/Tile.tsx [hunk 2]
```diff
@@ -497,48 +502,41 @@ export const SelectableTile = React.forwardRef<
     className
   );
 
-  function handleClick(evt) {
+  // Single function to handle selection changes
+  const handleSelectionChange = useCallback(
+    (evt: React.SyntheticEvent, newSelected: boolean) => {
+      setIsSelected(newSelected);
+      onChange(evt as React.ChangeEvent<HTMLDivElement>, newSelected, id);
```
Comment (adamalston) [inline packages/react/src/components/Tile/Tile.tsx]: The type assertion shouldn't be necessary. Is the `onChange` type correct? I’m asking since `ChangeEvent` isn’t typically used with `div` elements.

```diff
diff --git a/packages/react/src/components/Tile/Tile.tsx b/packages/react/src/components/Tile/Tile.tsx
index e0a6090e2..1ad036210 100644
--- a/packages/react/src/components/Tile/Tile.tsx
+++ b/packages/react/src/components/Tile/Tile.tsx
@@ -408,11 +408,11 @@ export interface SelectableTileProps extends HTMLAttributes<HTMLDivElement> {
   /**
    * The empty handler of the `<input>`.
    */
-  onChange?(
-    event: ChangeEvent<HTMLDivElement>,
+  onChange?: (
+    event: MouseEvent<HTMLDivElement> | KeyboardEvent<HTMLDivElement>,
     selected?: boolean,
     id?: string
-  ): void;
+  ) => void;
 
   /**
    * Specify the function to run when the SelectableTile is clicked
@@ -502,11 +502,13 @@ export const SelectableTile = React.forwardRef<
     className
   );
 
-  // Single function to handle selection changes
   const handleSelectionChange = useCallback(
-    (evt: React.SyntheticEvent, newSelected: boolean) => {
+    (
+      evt: MouseEvent<HTMLDivElement> | KeyboardEvent<HTMLDivElement>,
+      newSelected: boolean
+    ) => {
       setIsSelected(newSelected);
-      onChange(evt as React.ChangeEvent<HTMLDivElement>, newSelected, id);
+      onChange(evt, newSelected, id);
     },
     [onChange, id]
   );
```

File: packages/react/src/components/Tile/Tile.tsx [hunk 3]
```diff
@@ -497,48 +502,41 @@ export const SelectableTile = React.forwardRef<
...
-      return newSelected;
-    });
+
+    const newSelected = !isSelected;
+    handleSelectionChange(evt, newSelected);
     clickHandler(evt);
   }
 
-  function handleKeyDown(evt) {
+  function handleKeyDown(evt: React.KeyboardEvent<HTMLDivElement>) {
```
Comment (adamalston) [inline packages/react/src/components/Tile/Tile.tsx]: `KeyboardEvent` is already imported.

```suggestion
  function handleKeyDown(evt: KeyboardEvent<HTMLDivElement>) {
```

File: packages/react/src/components/Tile/Tile.tsx [hunk 4]
```diff
@@ -497,48 +502,41 @@ export const SelectableTile = React.forwardRef<
...
+  // Single function to handle selection changes
+  const handleSelectionChange = useCallback(
+    (evt: React.SyntheticEvent, newSelected: boolean) => {
+      setIsSelected(newSelected);
+      onChange(evt as React.ChangeEvent<HTMLDivElement>, newSelected, id);
+    },
+    [onChange, id]
+  );
+
+  function handleClick(evt: React.MouseEvent<HTMLDivElement>) {
```
Comment (adamalston) [inline packages/react/src/components/Tile/Tile.tsx]: `MouseEvent` is already imported.

```suggestion
  function handleClick(evt: MouseEvent<HTMLDivElement>) {
```

File: packages/react/src/components/Tile/Tile.tsx
Comment (adamalston) [inline packages/react/src/components/Tile/Tile.tsx:1]: Several JSDoc comments in this file refer to an `input`, but there isn’t one. Perhaps a new issue should be created to clarify or correct the documentation — I’m not sure. I only started investigating the discrepancy because the `onChange` JSDoc comment mentions an `input` and I couldn't find one. Any thoughts?

File: packages/react/src/components/Tile/Tile.tsx (hunk 2 above)
Comment (Gururajj77) [reply packages/react/src/components/Tile/Tile.tsx]: Have added these changes

File: packages/react/src/components/Tile/Tile.tsx (hunk 1 above)
Comment (Gururajj77) [reply packages/react/src/components/Tile/Tile.tsx]: Have added these changes

File: packages/react/src/components/Tile/Tile.tsx
Comment (Gururajj77) [reply packages/react/src/components/Tile/Tile.tsx:1]: I think we need to look and update the jsdoc comments

**Review by maradwan26 — APPROVED** [review]
Works as expected !!

**Review by 2nikhiltom — APPROVED** [review]
