### PR TITLE
fix(FileUploaderDropContainer): fix NPE selecting file

### LINKED ISSUE #4899: [DragAndDropFileUploader]: "click to upload" not working
The drag and drop file uploader isn't fully functional in the react storybook. If you go [here](https://carbon-components-react.netlify.com/iframe.html?id=fileuploader--drag-and-drop-upload-container-example-application), you can drag and drop files to upload but the "click to upload" function doesn't seem to be working.

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #4899.

#### Changelog

**Changed**

- Fix for NPE that happened by selecting a file in `<FileUploaderDropContainer>`.

#### Testing / Reviewing

Testing should make sure file uploader is not broken.

### CODE REVIEW

File: packages/react/src/components/FileUploader/FileUploader-test.js [hunk 1]
```diff
@@ -293,6 +299,20 @@ describe('FileUploaderDropContainer', () => {
 
       expect(evt.target.value).toEqual(null);
     });
+
+    it('Fires onAddFiles upon selecting a file', () => {
```
Comment (joshblack) [inline packages/react/src/components/FileUploader/FileUploader-test.js]:
```suggestion
    it('should call `onAddFiles` when a file is selected', () => {
```

File: packages/react/src/components/FileUploader/FileUploader-test.js [hunk 2]
```diff
@@ -293,6 +299,20 @@ describe('FileUploaderDropContainer', () => {
...
+      const fileFoo = new File(['foo'], 'foo.txt', { type: 'text/plain' });
+      const fileBar = new File(['bar'], 'bar.txt', { type: 'text/plain' });
+      const mockFiles = [fileFoo, fileBar];
+      const input = mountWrapper.find(`.${prefix}--file-input`);
+      const evt = { target: { files: mockFiles } };
+      input.simulate('change', evt);
+      expect(onAddFiles).toHaveBeenCalledTimes(1);
+      expect(onAddFiles.mock.calls[0][0].target.files).toEqual([
```
Comment (joshblack) [inline packages/react/src/components/FileUploader/FileUploader-test.js]: Maybe `expect(onAddFiles).toHaveBeenCalledWith` might be relevant here? Something like:

```js
expect(onAddFiles).toHaveBeenCalledWith(expect.objectContaining({
  target: {
    files: [fileFoo, fileBar],
  },
}));

**Review by joshblack — COMMENTED** [review]
Just some style comments, otherwise seems great!

**Review by dakahn — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

File: packages/react/src/components/FileUploader/FileUploader-test.js [hunk 3]
```diff
@@ -293,6 +299,24 @@ describe('FileUploaderDropContainer', () => {
 
       expect(evt.target.value).toEqual(null);
     });
+
+    it.only('should call `onAddFiles` when a file is selected', () => {
```
Comment (joshblack) [inline packages/react/src/components/FileUploader/FileUploader-test.js]:
```suggestion
    it('should call `onAddFiles` when a file is selected', () => {
```

**Review by joshblack — DISMISSED** [review]

**Comment by joshblack** [comment]
Should we remove the `FileUploaderDropContainer` story potentially in preference of the container example? Can't seem to get that one to work (and I don't think it has been working??) Just curious 🤔

**Comment by asudoh** [comment]
The story topic sounds orthogonal to this PR. `<FileUploaderDropContainer>` itself does not contain the UI of file list. The story for that component demonstrates that it can be integrated with other component, by showing `onChange` being fired upon adding files. If you go to Actions tab at the bottom or at the right, you'll see `onChange` when you add files.

**Comment by emyarod** [comment]
just for context, during previous reviews it was decided that the story would be static and the full application example would be available in [codesandbox](http://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/drag-and-drop-file-uploader)

**Review by emyarod — APPROVED** [review]
looks good to me

File: packages/react/src/components/FileUploader/FileUploader-test.js [hunk 4]
```diff
@@ -255,7 +255,13 @@ describe('FileUploader', () => {
 });
 
 describe('FileUploaderDropContainer', () => {
-  const dropContainer = <FileUploaderDropContainer className="extra-class" />;
+  const onAddFiles = jest.fn();
+  const dropContainer = (
```
Comment (joshblack) [inline packages/react/src/components/FileUploader/FileUploader-test.js]: We should move blocks where we create components into `beforeEach` or a similar generator function to prevent test flakiness

File: packages/react/src/components/FileUploader/FileUploaderDropContainer.js [hunk 5]
```diff
@@ -43,8 +43,8 @@ export default function FileUploaderDropContainer(props) {
    * @param {Event} evt - Event object, used to get the list of files added
    */
   const validateFiles = evt => {
-    const transferredFiles = [...evt.dataTransfer.files];
     if (evt.type === 'drop') {
+      const transferredFiles = [...evt.dataTransfer.files];
```
Comment (joshblack) [inline packages/react/src/components/FileUploader/FileUploaderDropContainer.js]: Would this be a good use-case for `Array.from`?

**Review by joshblack — CHANGES_REQUESTED** [review]

File: packages/react/src/components/FileUploader/FileUploader-test.js (hunk 4 above)
Comment (asudoh) [reply packages/react/src/components/FileUploader/FileUploader-test.js]: @joshblack Agreed on `beforAll()`/`beforeEach()` making tests more stable, but it's orthogonal to this PR. Do you want to enter an issue for that?

**Comment by tw15egan** [comment]
@joshblack is the test change request enough to warrant a separate issue? Or do you want it resolved in this PR before merging

**Comment by joshblack** [comment]
Let's address it before merging while we're in this part of the codebase and the change will be pretty quick 👍

**Comment by asudoh** [comment]
@joshblack is right that there is a change to test setup code, but the discussion of change in style of test setup code is orthogonal. I want the works not distracted by such kind of change requests.

**Comment by joshblack** [comment]
If it helps, was only thinking the change would involve:

```js
describe('FileUploaderDropContainer', () => {
  let onAddFiles;
  let dropContainer;
  let mountWrapper;

  beforeEach(() => {
    onAddFiles = jest.fn();
    dropContainer = (
      <FileUploaderDropContainer
        className="extra-class"
        onAddFiles={onAddFiles}
      />
    );
    mountWrapper = mount(dropContainer);
  });
```

We should definitely get this update in there while we're working on this part of the codebase given how minimal the change is.

**Comment by asudoh** [comment]
OK feel free to push a patch like that. Even though the change is minimal, I see it's distracting.

**Review by joshblack — APPROVED** [review]

**Comment by MaheshIBM** [comment]
Can anyone help me with which release this might have gone into.

**Comment by MaheshIBM** [comment]
I see the nightly release builds are failing. https://github.com/carbon-design-system/carbon/commit/d2619067329ea484d0d42442dab9638798f917dd/checks?check_suite_id=409159394

**Comment by joshblack** [comment]
Hi @MaheshIBM! 👋 This was included in our v10.9.0 release, can see the commit over in: https://github.com/carbon-design-system/carbon/releases/tag/v10.9.0

You can see our release schedule over at: https://github.com/carbon-design-system/carbon/wiki/Release-radar

Hope this helps!

**Comment by MaheshIBM** [comment]
@joshblack I see the commit was done after the v10.9.0 release which happened on Dec 19

image

The code in the tag does not seem to have the fix.

As per my understanding, I think this fix might go on 27th Jan 2020 as per screen shot below.

image

If I compare the tag with master, I can see the commit showing up in the compare which means its not in the tag.

https://github.com/carbon-design-system/carbon/compare/v10.9.1...master
or 
https://github.com/carbon-design-system/carbon/compare/v10.9.2...master

**Comment by joshblack** [comment]
@MaheshIBM good catch! Sorry about my mistake up above, not sure where I was finding this commit now. But yes, I believe it'll be in our next patch!
