### PR TITLE
fix: switch to onClick from onMouseDown in modal components

### LINKED ISSUE #16846: [Bug]:Unintended ListBox onClick behavior component when inside Modal
### Package

@carbon/react

### Browser

Chrome

### Package version

1.60.2

### React version

18

### Description

This behavior was noticed when clicking on the label of a `Dropdown` component inside the `MultiAddSelect` component in the carbon for ibm products library. The associated issue can be found [here](https://github.com/carbon-design-system/ibm-products/issues/5450).

After some investigation I tracked the behavior down to the `Modal` component. You'll notice that `Dropdown` doesn't suffer this strange behavior when outside the context of a modal, which you can see in [storybook](https://react.carbondesignsystem.com/?path=/story/components-dropdown--inline). However, when you do the same to a dropdown inside of a modal you'll see a slightly different behavior. You can see this behavior directly in [storybook](https://react.carbondesignsystem.com/?path=/story/components-modal--with-scrolling-content) by clicking on the label of either the dropdown or multiselect and holding down.

This behavior was introduced when `stopPropagation()` was added to the `handleMousedown` handlers in `Modal` and `ComposedModal`. After testing and debugging locally the problem can be fixed by switching from `onMouseDown` to `onClick`. I'm not an expert on the differences between `onMouseDown` vs `onClick` but from what I understand because `onMouseDown` fires first the `stopPropagation` inclusion may have started to disrupt the event handling within `Modal`. I tested this by removing `stopPropagation` in the handler and leaving it as `onMouseDown`. When including `stopPropagation` it appears as though `onClick` is needed instead to avoid this behavior.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-modal--with-scrolling-content

### Steps to reproduce

Scroll down inside the modal until you reach either the `MultiSelect` or `Dropdown` components. Click the label once to open the content. Once open, click and hold down on the label. The component should be in a closed state until you release the cursor, which is not the intended / expected behavior.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Application/PAL

c4p

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by davidmenendez**
Closes #16846

switches the outside click detector event in `Modal` and `ComposedModal` from `onMouseDown` to `onClick` in order to alleviate some strange behaviors noticed with components built on `ListBox` inside of modal components.

#### Changelog

**Changed**

- switched `onMouseDown` event to `onClick` in `Modal` and `ComposedModal`

#### Testing / Reviewing

- view the steps / description in the issue #16846 and follow the same steps against these changes

### CODE REVIEW

**Review by riddhybansal — APPROVED** [review]
This looks like a fix to me !!

**Review by Gururajj77 — APPROVED** [review]

File: packages/react/src/components/ComposedModal/ComposedModal.tsx [hunk 1]
```diff
@@ -421,7 +421,7 @@ const ComposedModal = React.forwardRef<HTMLDivElement, ComposedModalProps>(
         ref={ref}
         aria-hidden={!open}
         onBlur={!focusTrapWithoutSentinels ? handleBlur : () => {}}
-        onMouseDown={handleMousedown}
+        onClick={handleClick}
```
Comment (tay1orjones) [inline packages/react/src/components/ComposedModal/ComposedModal.tsx]: Before this change a consumer could pass in `onClick`, but with this change they'll no longer be able to do that. The reverse is also true for `onMouseDown`, but that's going to be less of a concern. I doubt anyone has placed `onMouseDown` on a modal, because it would never have been called before this change.

To fix we can either conditionally call rest.onClick from within `handleClick`, or use the composeEventHandlers helper we have. I think we could use optional chaining to avoid errors for when they're not supplying their own `onClick`? 🤔 

```js
onClick={composeEventHandlers([rest.?onClick, handleClick])}
```

**Review by tay1orjones — CHANGES_REQUESTED** [review]

File: packages/react/src/components/ComposedModal/ComposedModal.tsx (hunk 1 above)
Comment (davidmenendez) [reply packages/react/src/components/ComposedModal/ComposedModal.tsx]: great point! will fix 👍

**Comment by davidmenendez** [comment]
@tay1orjones resolved 👍

**Comment by tay1orjones** [comment]
@davidmenendez would you be up for writing a small test to ensure the consumer-provided onClick is called like we expect?

**Comment by davidmenendez** [comment]
@tay1orjones tests included 👍

**Review by guidari — APPROVED** [review]
LGTM! 🚀

**Comment by davidmenendez** [comment]
@tay1orjones when you have a chance 👍

**Review by alisonjoseph — APPROVED** [review]

**Comment by davidmenendez** [comment]
@tay1orjones 👀 😬

**Review by tay1orjones — APPROVED** [review]
Sorry for the delay, was out on vacation last week 😅
