### PR TITLE
fix(overflow-menu): support arrow key navigation

### LINKED ISSUE #1233: Overflow menu needs to be navigable using arrow keys
As a follow-on to #666:
- down and up arrows should move through the menu items
- ideally, the menu should also open on down arrow (move focus to first item) and up arrow (move focus to last item)
- since the menu items are semantically buttons (i.e. they perform an action when activated) and not links (i.e. they do not navigate to a new page when activated) they should _only_ be traversable with down/up arrow, and not tab

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1233

This PR adds up/down arrow key support for navigating the overflow menu component

#### Changelog

**New**

- arrow key navigation support

**Removed**

- event listener for deprecated `keypress` event

### CODE REVIEW

File: src/components/overflow-menu/overflow-menu.js [hunk 1]
```diff
@@ -214,33 +241,56 @@ class OverflowMenu extends mixin(createComponent, initComponentBySearch, evented
     const key = event.which;
     const { element, optionMenu, options } = this;
     const isOfMenu = optionMenu && optionMenu.element.contains(event.target);
+    const isExpanded = this.element.getAttribute('aria-expanded') === 'true';
```
Comment (asudoh) [inline src/components/overflow-menu/overflow-menu.js]: Would we want to make this in sync with:
https://github.com/IBM/carbon-components/blob/956bfa94ec822b6f58bb5912cd43ed1e7d56618f/src/components/overflow-menu/overflow-menu.js#L131
https://github.com/IBM/carbon-components/blob/956bfa94ec822b6f58bb5912cd43ed1e7d56618f/src/components/overflow-menu/overflow-menu.js#L264
https://github.com/IBM/carbon-components/blob/956bfa94ec822b6f58bb5912cd43ed1e7d56618f/src/components/floating-menu/floating-menu.js#L131
https://github.com/IBM/carbon-components/blob/956bfa94ec822b6f58bb5912cd43ed1e7d56618f/src/components/floating-menu/floating-menu.js#L214

File: src/components/overflow-menu/overflow-menu.js [hunk 2]
```diff
@@ -214,33 +241,56 @@ class OverflowMenu extends mixin(createComponent, initComponentBySearch, evented
...
+        this.changeState('hidden', getLaunchingDetails(event), () => {
+          if (isOfMenu) {
+            element.focus();
+          }
+        });
+        break;
+      // Enter || Space bar
+      case 13:
+      case 32: {
+        if (!isExpanded && document.activeElement !== this.element) {
```
Comment (asudoh) [inline src/components/overflow-menu/overflow-menu.js]:
```suggestion
        if (!isExpanded && this.element.ownerDocument.activeElement !== this.element) {
```

Background: The codebase avoids global `document`/`window` usage for the sake of scoping, we use `this.element.ownerDocument` for the former, `this.element.ownerDocument.defaultView` for the latter.

File: src/components/overflow-menu/overflow-menu.js [hunk 3]
```diff
@@ -214,33 +241,56 @@ class OverflowMenu extends mixin(createComponent, initComponentBySearch, evented
...
+    const isExpanded = this.element.getAttribute('aria-expanded') === 'true';
 
-    if (key === 27) {
-      this.changeState('hidden', getLaunchingDetails(event), () => {
-        if (isOfMenu) {
-          element.focus();
+    switch (key) {
+      // Esc
+      case 27:
+        this.element.removeAttribute('aria-expanded');
```
Comment (asudoh) [inline src/components/overflow-menu/overflow-menu.js]: Thought changing `aria-expanded`  is covered by: https://github.com/IBM/carbon-components/blob/956bfa94ec822b6f58bb5912cd43ed1e7d56618f/src/components/overflow-menu/overflow-menu.js#L144

Wondering if you saw otherwise?

File: src/components/overflow-menu/overflow-menu.js [hunk 4]
```diff
@@ -205,6 +196,42 @@ class OverflowMenu extends mixin(createComponent, initComponentBySearch, evented
...
+    const focused = this.element.ownerDocument.activeElement;
+    return focused.nodeType === Node.ELEMENT_NODE && focused.matches(this.options.selectorItem) ? focused : null;
+  };
+
+  /**
+   * Moves the focus up/down.
+   * @param {number} direction The direction of navigating.
+   */
+  navigate = direction => {
+    const items = [...document.querySelectorAll(this.options.selectorItem)];
```
Comment (asudoh) [inline src/components/overflow-menu/overflow-menu.js]:
```suggestion
    const items = [...this.element.ownerDocument.querySelectorAll(this.options.selectorItem)];
```

**Review by asudoh — COMMENTED** [review]
LGTM basically, some comments to ensure the consistency in the codebase - Thanks @emyarod!

File: src/components/overflow-menu/overflow-menu.js (hunk 1 above)
Comment (emyarod) [reply src/components/overflow-menu/overflow-menu.js]: @asudoh just to clarify, we want to replace the `aria-expanded` check with the `classList` check is that correct?

File: src/components/overflow-menu/overflow-menu.js (hunk 2 above)
Comment (emyarod) [reply src/components/overflow-menu/overflow-menu.js]: my mistake, I forgot about this usage

File: src/components/overflow-menu/overflow-menu.js (hunk 3 above)
Comment (emyarod) [reply src/components/overflow-menu/overflow-menu.js]: yes you are correct, this line is redundant

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod for your quick updates!

**Comment by asudoh** [comment]
@emyarod Would you be able to look at the unit test failures BTW? Thanks!

**Comment by emyarod** [comment]
yes they should be resolved now @asudoh

**Review by dakahn — APPROVED** [review]
Really great work. I like your commenting style a lot. 😺
