### PR TITLE
fix(overflow-menu): updated aria-label and roles, made ul a sibling

### LINKED ISSUE #2495: Accessibility markup problems in Carbon react overflow menu
In the [Carbon react overflow menu](http://react.carbondesignsystem.com/?selectedKind=OverflowMenu&selectedStory=basic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel):
1. the `div` containing the overflow icon needs to have `role="button"`, not `role="menu"`
2. the button needs a nice default label in case one is not provided, say `aria-label="Menu"`
3. the `ul` with `role="menu"` needs to have the same `aria-label` as the button
4. there's a `div` with `role="menuitem"` in the DOM for no apparent reason
(see screen snap, below. This may be the cause of https://github.com/IBM/carbon-components-react/issues/1237)
5. the `div` with `role="button"` (see 1) and the `ul` with `role="menu"` need to be siblings, i.e. the `ul` should immediately follow the button in the DOM, so that screen reader users can use their virtual cursor to read through the menu items without getting totally lost.

image

### PR DESCRIPTION
**Pull request by harpality**
addresses #2495

Updated a11y issues as requested.

#### Changelog

**New**

- line 551 added `{menuBody}` so that `<ul role=‘menu’>` is a sibling to `<div role=“button”>`. wrapped return in `<React.Fragment>`.
- line 500 added `aria-label=“Menu”` to`ul` for `menuBody` 

**Changed**

- line 534 changed `role=“menu”` to `role=“button”`
- line 541 changed `aria-label` from `{ariaLabel}` to `“Menu”`

**Removed**

- line 502 removed extra `<div role=“menuitem”>`

### CODE REVIEW

File: packages/react/src/components/OverflowMenu/OverflowMenu.js [hunk 1]
```diff
@@ -525,26 +526,29 @@ class OverflowMenu extends Component {
...
+          <div
+            {...other}
+            role="button"
+            aria-haspopup
+            aria-expanded={this.state.open}
+            className={overflowMenuClasses}
+            onKeyDown={this.handleKeyPress}
+            onBlur={this.handleBlur}
+            onClick={this.handleClick}
+            aria-label="Menu"
```
Comment (asudoh) [inline packages/react/src/components/OverflowMenu/OverflowMenu.js]: Instead of killing `ariaLabel`, do you want to change `defaultProps` to make `Menu` the default?

File: packages/react/src/components/OverflowMenu/OverflowMenu.js [hunk 2]
```diff
@@ -493,27 +492,29 @@ class OverflowMenu extends Component {
     );
 
     const menuBody = (
-      <ul className={overflowMenuOptionsClasses} tabIndex="-1" role="menu">
+      <ul
+        className={overflowMenuOptionsClasses}
+        tabIndex="-1"
+        role="menu"
+        aria-label="Menu">
```
Comment (asudoh) [inline packages/react/src/components/OverflowMenu/OverflowMenu.js]: Do you want to make this refer to `ariaLabel` prop?

**Review by asudoh — COMMENTED** [review]
Thanks @harpalassi for jumping in!

File: packages/react/src/components/OverflowMenu/OverflowMenu.js (hunk 2 above)
Comment (dakahn) [inline packages/react/src/components/OverflowMenu/OverflowMenu.js]:
```suggestion
        aria-label={ariaLabel}>
```

File: packages/react/src/components/OverflowMenu/OverflowMenu.js [hunk 3]
```diff
@@ -440,7 +440,6 @@ class OverflowMenu extends Component {
     const {
       id,
       tabIndex,
```
Comment (dakahn) [inline packages/react/src/components/OverflowMenu/OverflowMenu.js]:
```suggestion
      tabIndex,
      ariaLabel,
```

**Review by dakahn — CHANGES_REQUESTED** [review]
Great work @harpalassi. Thanks for the contrib. Typically we want to modify a component's API (all the props and various configs someone using the component might set) as little as possible unless we're dealing with a major release -- where we can make breaking changes. So yeah, making the `defaultProp` be `menu` is the way to go. 👍🏽

File: packages/react/src/components/OverflowMenu/OverflowMenu.js (hunk 3 above)
Comment (harpality) [reply packages/react/src/components/OverflowMenu/OverflowMenu.js]: Changes made - ariaLabel re-added.

File: packages/react/src/components/OverflowMenu/OverflowMenu.js (hunk 2 above)
Comment (harpality) [reply packages/react/src/components/OverflowMenu/OverflowMenu.js]: `{ariaLabel}` re-added, `Menu` added to `defaultProps` on line 209 and line 23 in `OverflowMenu-story.js`

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @harpalassi!

**Comment by asudoh** [comment]
BTW would you update the snapshot (again)...? Thanks!

**Review by dakahn — APPROVED** [review]
🏄 🏄 🏄 Way to go

File: packages/react/src/components/OverflowMenu/OverflowMenu.js [hunk 4]
```diff
@@ -493,27 +493,29 @@ class OverflowMenu extends Component {
     );
 
     const menuBody = (
-      <ul className={overflowMenuOptionsClasses} tabIndex="-1" role="menu">
+      <ul
+        className={overflowMenuOptionsClasses}
+        tabIndex="-1"
+        role="menu"
+        aria-label={ariaLabel}>
```
Comment (emyarod) [inline packages/react/src/components/OverflowMenu/OverflowMenu.js:500]:
```suggestion
        aria-label={ariaLabel || this.props['aria-label']}>
```

should we also pass in the standard aria attribute as an option?

File: packages/react/src/components/OverflowMenu/OverflowMenu.js [hunk 5]
```diff
@@ -525,26 +527,29 @@ class OverflowMenu extends Component {
...
+            id={id}
+            tabIndex={tabIndex}
+            ref={mergeRefs(ref, this.bindMenuEl)}>
+            <IconElement {...iconProps}>
+              {iconDescription && <title>{iconDescription}</title>}
+            </IconElement>
+            {open && wrappedMenuBody}
+          </div>
+        </ClickListener>
+        {menuBody}
```
Comment (emyarod) [inline packages/react/src/components/OverflowMenu/OverflowMenu.js]: the menu body is being rendered twice, once in a `<FloatingMenu>` (`wrappedMenuBody` on L548) and once without (`menuBody` on L551). but I don't think we can simply move the menu body and eliminate the floating menu wrapper without losing functionality like keyboard navigation

**Review by emyarod — CHANGES_REQUESTED** [review]
image

there's a visual bug where the overflow menu overlaps with the trigger button. this might be because the menu body is being rendered in two separate locations. this could also be affecting keyboard navigation

the aria attribute changes look good to me, but the fix for the screen reader getting lost (making the `ul[role="menu"]` a sibling of the `div[role="button"]`) is not so straightforward as replacing `wrappedMenuBody` with `menuBody` and moving it. instead I think we should modify the target of the `<FloatingMenu>` portal

we can probably split the fixes into a few PRs and scope this PR to just the aria label, `role`, and `div.menuitem` changes? or would you want to tackle the floating menu changes as well @harpalassi ?

**Comment by dakahn** [comment]
@emyarod yeah, let's split out that work, i'll add your findings to the and we can get another PR going for those larger floating menu changes. @harpalassi can you rollback your changes to the `ul`?

**Comment by harpality** [comment]
@dakahn sounds good - i just rolled back the changes to `ul`.

**Review by emyarod — APPROVED** [review]
looks good to me, I guess the `ariaLabel` prop is sufficient then

**Comment by emyarod** [comment]
snapshots need to be updated once again because of the latest changes

**Comment by asudoh** [comment]
The diff now seems to contain lots of relevant changes - @harpalassi Could you fix? Thanks!

**Comment by joshblack** [comment]
@asudoh just pushed up a merge 👍
