### PR TITLE
fix(overflow-menu): check if function exists before calling

### LINKED ISSUE #6705: Overflow using renderIcon throws error in Firefox on click outside
When using renderIcon the overflow sometimes throws an error when clicked outside

```
TypeError: target.matches is not a function
var target = event.target;
  259 |   var triggerEl = _this._triggerRef.current;
  260 | 
> 261 |   if (!menuBody.contains(target) && triggerEl && !target.matches(".".concat(prefix, "--overflow-menu,.").concat(prefix, "--overflow-menu-options"))) {
```

## What package(s) are you using?

- [ X ] `carbon-components`
- [ X ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Error occurs on click outside.

Using renderIcon

> What browser are you working in?

Firefox 79.0, 64bit

> What version of the Carbon Design System are you using?

    "carbon-components": {
      "version": "10.17.0",
    "carbon-components-react": {
      "version": "7.17.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Aspera

## Steps to reproduce the issue

1. Open overflow
2. Click outside
3. It might happen it might not. When it does happen it will happen every time you click outside until reload.

https://codesandbox.io/s/lucid-franklin-pedx0?file=/index.js

## Additional information

Screen Shot 2020-08-20 at 7 06 05 PM

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/6705

Check if `target.matches` exists before invoking it

#### Changelog

**Changed**

- Check if `target.matches` exists before invoking it

#### Testing / Reviewing

Using Firefox, open OverflowMenu, and open the menu. Then click anywhere outside the browser, return to the browser, and click anywhere inside to close the menu. There should not be an error.

### CODE REVIEW

**Comment by dabrad26** [comment]
I see similar target.matches in 
- pagination-nav
- init-component-by-search
- init-component-by-event
- init-component-by-launcher
- ui-shell/product-switcher
- dropdown
- data-table

Maybe should have this check for all the cases.  IDK what init-component is for, but I assume the others are similar to what overflow was doing.

File: packages/react/src/components/OverflowMenu/OverflowMenu.js [hunk 1]
```diff
@@ -405,14 +405,16 @@ class OverflowMenu extends Component {
...
           const { current: triggerEl } = this._triggerRef;
-          if (
-            !menuBody.contains(target) &&
-            triggerEl &&
-            !target.matches(
-              `.${prefix}--overflow-menu,.${prefix}--overflow-menu-options`
-            )
-          ) {
-            this.closeMenu();
+          if (target.matches) {
```
Comment (dabrad26) [inline packages/react/src/components/OverflowMenu/OverflowMenu.js]:
```suggestion
          if (typeof target.matches === 'function') {
```

Which is donehttps://github.com/carbon-design-system/carbon/blob/7a95a7d46c2a36c19fffafcbf1153c7ba19f7f7f/packages/components/src/globals/js/misc/event-matches.js#L19 (function type check).

**Review by dabrad26 — CHANGES_REQUESTED** [review]
IDK of a reason matches would be set to anything but function. But normally for libraries I go for overly cautious :/

**Review by dabrad26 — APPROVED** [review]

**Comment by tw15egan** [comment]
I agree, made it match `function` specifically. Not seeing any issues with those other components, I think the main reason this one was throwing was due to the positioning logic of the `FloatingMenu`. 

Thanks again for catching that and taking a look 👍

**Comment by dabrad26** [comment]
Thanks! I am a bit concerned with an event getting triggered in Firefox and then bubbling it in on viewport focus (with no target); that def seems like wrong behavior.  

I hope its a bug in Firefox and they fix it.  But if not I fear it could show as more issue later for other events that rely on target (even if not error can cause the expected behaviors to get impacted).  

One concern I saw was it seemed when clicking in Firefox dev tools around the events backed up and would then hit the app over and over once viewport got focus (causing freezing).  Seems very odd...  Will keep an eye on Firefox's bug reports and open if I don't see others talking about it.

**Review by dakahn — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
