### PR TITLE
fix(slider): add label to div

### LINKED ISSUE #11676: [Slider] [a11y]: role="slider" missing aria-label
### Package

carbon-components-react

### Browser

Chrome

### Operating System

MacOS

### Package version

7.57.2 (confirmed in latest pull)

### React version

16.14.x

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker

### Assistive technology

unknown

### Description

> Each form control must have an associated label

> Form control with "slider" role has no associated label

The `Slider` component is missing a label

### WCAG 2.1 Violation

unknown

### Reproduction/example

https://nbwiqvmnp--github--3000.local.webcontainer.io

### Steps to reproduce

use the Slider component

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by aledavila**
Closes #11676 
Reference: https://github.com/carbon-design-system/carbon/pull/11798 for v10 fix

#### Changelog

**New**

- add `aria-labelledby` to the div with `role=slider` 

#### Testing / Reviewing

Make sure slider is working as inteded. Make sure a11y no label for slider error is gone.

### CODE REVIEW

File: packages/react/src/components/Slider/Slider.js [hunk 1]
```diff
@@ -635,6 +635,7 @@ export default class Slider extends PureComponent {
                     aria-valuemin={min}
                     aria-valuenow={value}
                     style={thumbStyle}
+                    aria-labelledby={!ariaLabelInput ? labelId : null}
```
Comment (abbeyhrt) [inline packages/react/src/components/Slider/Slider.js]: Any reason for this being conditional? Testing it out, the violation comes back if `ariaLabelInput` is defined since there isn't anything labelling the element anymore

Comment (aledavila) [reply packages/react/src/components/Slider/Slider.js]: Ahh i see. No no reason I was actually copying the other div. I change it to just labelId

Comment (aledavila) [reply packages/react/src/components/Slider/Slider.js]: Ready for review @abbeyhrt

**Review by abbeyhrt — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]
