### PR TITLE
fix(web-components): respect preventDefault on cds-dropdown

### LINKED ISSUE #21872: [Bug]: cds-dropdown and cds-combo-box - calling event.preventDefault() on cds-dropdown-beingselected and cds-combo-box-beingselected does not prevent value change
### Package

@carbon/web-components

### Browser

_No response_

### Package version

v2.50.0

### React version

_No response_

### Description

The `cds-dropdown-beingselected` and `cds-combo-box-beingselected` events from `cds-dropdown` and `cds-combo-box` are documented as cancelable, implying that calling `event.preventDefault()` should prevent the selection from being committed. However, even when preventDefault() is called on these events, the component's value still updates — only the subsequent `cds-dropdown-selected` / `cds-combo-box-selected` events are suppressed.

This issue also affects the combo box clear button: clicking it still clears the value even when preventDefault() is called on `cds-combo-box-beingselected`.

Since `cds-combo-box` shares its selection logic with `cds-dropdown`, both cases are reported here together.

### Reproduction/example

https://stackblitz.com/edit/github-zo1jorxr?file=index.html

### Steps to reproduce

1. Open the StackBlitz example with a `cds-dropdown` and a `cds-combo-box`. The code have 2 listeners, one for the `cds-dropdown-beingselected` and other for the `cds-combo-box-beingselected`, both calling `event.preventDefault()`.
2. Open the dropdown and click on a item.
3. Observe that the value of the `cds-dropdown` change to the selected item.
4. Repeat the steps 2-3 using the combo box.
5. Now, after selecting a value, click in the clear button of the combo box, and observe that the value is cleared.

**Expected Result:**

When event.preventDefault() is called on `cds-dropdown-beingselected` or `cds-combo-box-beingselected`:
- The component's value should remain unchanged.
- The clear button action on the combo box should be cancelled and the value should not be cleared.
- The `cds-dropdown-selected` / `cds-combo-box-selected` events should not be emitted (this part already works correctly).

**Actual Result:**

- The component's value does change despite event.preventDefault() being called.
- For the combo box, clicking the clear button does clear the value despite event.preventDefault().
- The `cds-dropdown-selected` / `cds-combo-box-selected` events are correctly suppressed, but the internal state update is not prevented.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by nehaaprasad**
Closes #21872

- Fix cancelable beingselected behavior for cds-dropdown and cds-combo-box: preventDefault() now keeps the current value and input state; combo-box clear respects cancellation.

### Changelog
New

- Regression tests for prevented selection on cds-dropdown and prevented selection/clear on cds-combo-box.

Changed

- Combo-box clear: clear input only after a confirmed selection change; restore input when cds-combo-box-beingselected is canceled.

Removed

- Pre-clearing the filter input before running the cancelable beingselected flow (combo-box clear).

### Testing / Reviewing

[ ] yarn build in packages/web-components (or monorepo build that produces es/).
[ ] yarn test in packages/web-components (or run the new/updated __tests__ files).
[ ] Dropdown: open, pick an item with preventDefault() on cds-dropdown-beingselected — value and selection stay.
[ ] Combo-box: same for cds-combo-box-beingselected.
[ ] Combo-box: click clear with preventDefault() on cds-combo-box-beingselected — value and input stay.
[ ] Confirm normal select and clear still work without preventDefault().

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- ~[ ] Updated documentation and storybook examples~
- [x] Wrote passing tests that cover this change
- ~[ ] Addressed any impact on accessibility (a11y)~
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by adamalston — COMMENTED** [review]
Hi, could you restore the pull request description from the template and complete it?

**Comment by nehaaprasad** [comment]
@adamalston done

**Comment by adamalston** [comment]
Hi, the pull request template has not been fully restored. I suggest restoring it completely and filling in any remaining sections.

File: packages/web-components/src/components/combo-box/__tests__/combo-box-test.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+    el.addEventListener('cds-combo-box-beingselected', (event) => {
+      event.preventDefault();
+    });
+
+    const clearButton = el.shadowRoot.querySelector('#selection-button');
+    clearButton.click();
+    await el.updateComplete;
+
+    const input = el.shadowRoot.querySelector('#trigger-label');
```
Comment (sangeethababu9223) [inline packages/web-components/src/components/combo-box/__tests__/combo-box-test.js]:
```suggestion
    const input = el.shadowRoot.querySelector('#trigger-button');
```
Test is failing here. This should solve it.

Otherwise looks good to me!

**Review by sangeethababu9223 — CHANGES_REQUESTED** [review]

**Comment by heloiselui** [comment]
@nehaaprasad I also suggest add more tests to cover theses changes
image

**Review by heloiselui — APPROVED** [review]

**Review by riddhybansal — APPROVED** [review]
Thanks @heloiselui for adding more tests.

**Review by sangeethababu9223 — APPROVED** [review]

**Review by maradwan26 — APPROVED** [review]
LGTM
