### PR TITLE
fix(textarea): fix helper-text "max-width: 0px" on hidden render

### LINKED ISSUE #20417: [Bug]: Helper text in TextArea has 0px width if not visible during first render
### Package

@carbon/react

### Browser

Safari

### Package version

1.90.0

### React version

19

### Description

When a TextArea is present but not visible during its first render (for example in a TabPanel or a CreateTearsheetStep form C4IBMP), the container width for its helper text is determined as `0px` making it break after each letter.

Image

This might be related to #19971

### Reproduction/example

https://stackblitz.com/edit/github-jfti5w9t?file=src%2FApp.jsx

### Steps to reproduce

- Implement a TextArea in a way that it is present in the DOM but not visible during it's first render
- Pass a helper text
- Make it visible

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by maradwan26**
Closes #20417

This PR fixes a bug where TextArea would have a 0px width if not visible during first render using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) for both React and Web Components.

### Changelog

**New**

- Added test stories `TextArea/Test With Tab` and `TextArea/Text Area Visibility Test` to both React and WC
    - _**should be removed before merging**_

**Changed**

- _React:_ Refactored `useIsomorphicEffect()` in `TextArea.tsx` to use a `ResizeObserver` that observes the `wrapperRef` and applies the calculated width when needed
- _Web Components:_ Refactored `updated()` in `textarea.ts` to use a `ResizeObserver` that observes `text-area__wrapper` and applies the calculated width when needed
    - This replaces the previous usage of the private `_prevCols` variable that was used to determine when the width should be measured
    - A `disconnectedCallback()` function was also added to cleanup and disconnect the observer

**Removed**

- Removed private `prevCols` from `cds-textarea`

#### Testing / Reviewing

- Go to `TextArea/Test With Tab` story in both React and WC
- Helper-text should not have a max width of 0 and should render as expected
- Go to `TextArea/Text Area Visibility Test` story in both React and WC
- Toggling visibility and/or toggling cols should render the helper-text as expected
- There should be no regression

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [X] Reviewed every line of the diff
- [X] Updated documentation and storybook examples
- ~~[ ] Wrote passing tests that cover this change~~
- [X] Addressed any impact on accessibility (a11y)
- [X] Tested for cross-browser consistency
- [X] Validated that this code is ready for review and status checks should pass

> [!CAUTION]
> Test stories need to be removed before merging

### CODE REVIEW

File: packages/react/src/components/TextArea/TextArea.tsx [hunk 1]
```diff
@@ -226,19 +226,29 @@ const TextArea = frFn((props, forwardRef) => {
...
+        }
+      });
+    };
+
+    const resizeObserver = new ResizeObserver(([entry]) => {
+      applyWidth(entry.contentRect.width);
     });
+    resizeObserver.observe(wrapperRef.current);
+
+    return () => resizeObserver.disconnect();
```
Comment (tay1orjones) [inline packages/react/src/components/TextArea/TextArea.tsx]: Does this need to be guarded in case it's not defined from the early return up on line 236?


```suggestion
    return () => resizeObserver && resizeObserver.disconnect();
```

Comment (maradwan26) [reply packages/react/src/components/TextArea/TextArea.tsx]: I don't think so because the observer is defined after the early return on line 236

Comment (tay1orjones) [reply packages/react/src/components/TextArea/TextArea.tsx]: The cleanup function will always run on unmount

Comment (maradwan26) [reply packages/react/src/components/TextArea/TextArea.tsx]: Oh I see ok thanks, good catch!

**Review by tay1orjones — APPROVED** [review]

**Review by heloiselui — APPROVED** [review]
LGTM, just need to remove the test story!
