### PR TITLE
fix(Menu): prevent text input interruption when menu is open

### LINKED ISSUE #21226: [Bug]: Menu focus management interrupts text input when menu is open
### Package

@carbon/react

### Browser

_No response_

### Package version

v1.98

### React version

_No response_

### Description

When you type in the controls panel (eg., the label prop input) loses focus after each keystroke in the Menu component in React Storybook. Focus jumps back into the menu (first item like “Share with”), so you can only type one character at a time. This makes controls unusable.

https://github.com/user-attachments/assets/32820d9f-a25a-4999-820b-01cb211b274e

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-menu--default

### Steps to reproduce

1. Go to `React Storybook` > `Menu` > `Default`
2. In controls panel, click the label input
3. Try to type something there

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by heloiselui**
Closes #21226

Fixed the `Menu` focus behavior so typing in external text inputs (like `label prop `in Storybook Controls) is not interrupted when the menu is open.

### Changelog

**New**

- Added test for input focus while menu is open

**Changed**

- Updated root menu focus logic to preserve external input focus on rerender
- Updated submenu `ArrowRight` focus test to use `waitFor(...)` for stable async focus timing

**Removed**

- ~None~

#### Testing / Reviewing

- Go to `React Deploy Preview` > `Menu` > `Default`
 - In Controls panel:
  - Click the label input
  - Type several characters
Expected: input keeps focus and you can type normally

Pls, check also: 
- Keyboard check:
 - Click inside the story
 - Press `Tab` until `Share with` is focused
 - Press `ArrowRight`
We shouldn't have regression here, so I expected the submenu opens and keyboard focus moves correctly into submenu 

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [X] Reviewed every line of the diff
- ~[ ] Updated documentation and storybook examples~
- [X] Wrote passing tests that cover this change
- [X] Addressed any impact on accessibility (a11y)
- [X] Tested for cross-browser consistency
- [X] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by devadula-nandan — CHANGES_REQUESTED** [review]
@heloiselui i think when the label prop is changed. its updating focusableItems array. which repeatedly running the effect which seems to be the root cause. the lable update shouldn't be changing the focusable items in the first place. could you look at that?

snippets to reproduce the case
```
  useEffect(() => {
    console.log('effect runs', focusableItems); // prints 4 items and 10 items
    
    if (open) {
      const raf = requestAnimationFrame(() => {
        if (focusableItems.length > 0) {
          focusItem();
        }
      });

      return () => cancelAnimationFrame(raf);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, focusableItems]);
```

```
export const Default = (args) => {
  const [label, setLabel] = React.useState('Context Menu');
  const itemOnClick = action('onClick (MenuItem)');
  const selectableOnChange = action('onChange (MenuItemSelectable)');
  const radioOnChange = action('onChange (MenuItemRadioGroup)');

  const target = document.getElementById('storybook-root');

  React.useEffect(() => {
    const interval = setInterval(() => {
      const randomString = Math.random().toString(36).substring(2, 10);
      setLabel(`Menu ${randomString}`);
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <Menu
        {...args}
        label={label}
        target={target}
        x={document?.dir === 'rtl' ? 250 : 0}>
        <MenuItem label="Share with" renderIcon={FolderShared}>
          <MenuItemRadioGroup
            label="Share with"
            items={['None', 'Product team', 'Organization', 'Company']}
            defaultSelectedItem="Product team"
            onChange={radioOnChange}
          />
        </MenuItem>
        <MenuItemDivider />
        <MenuItem
          label="Cut"
          shortcut="⌘X"
          onClick={itemOnClick}
          renderIcon={Cut}
        />
        <MenuItem
          label="Copy"
          shortcut="⌘C"
          onClick={itemOnClick}
          renderIcon={Copy}
        />
        <MenuItem
          label="Paste"
          shortcut="⌘V"
          disabled
          onClick={itemOnClick}
          renderIcon={Paste}
        />
        <MenuItemDivider />
        <MenuItemGroup label="Font style">
          <MenuItemSelectable
            label="Bold"
            shortcut="⌘B"
            defaultSelected
            onChange={selectableOnChange}
            renderIcon={TextBold}
          />
          <MenuItemSelectable
            label="Italic"
            shortcut="⌘I"
            onChange={selectableOnChange}
            renderIcon={TextItalic}
          />
        </MenuItemGroup>
        <MenuItemDivider />
        <MenuItemRadioGroup
          label="Text decoration"
          items={['None', 'Overline', 'Line-through', 'Underline']}
          defaultSelectedItem="None"
          onChange={radioOnChange}
        />
        <MenuItemDivider />
        <MenuItem
          label="Delete"
          shortcut="⌫"
          kind="danger"
          onClick={itemOnClick}
          renderIcon={TrashCan}
        />
      </Menu>
      <button
        style={{ position: 'absolute', top: '100px', right: '100px' }}
        onClick={() => {
          const randomString = Math.random().toString(36).substring(2, 10);
          setLabel(`Menu ${randomString}`);
        }}>
        Update Label
      </button>
    </>
  );
};
```

https://github.com/user-attachments/assets/e90aff64-44f5-482a-83e4-0243f9d52ad8

its preferred to not run the effect at all in the first place rather than running it on label change and not calling focus method based on logic. what do you think?

**Comment by heloiselui** [comment]
> @heloiselui i think when the label prop is changed. its updating focusableItems array. which repeatedly running the effect which seems to be the root cause. the lable update shouldn't be changing the focusable items in the first place. could you look at that?
> its preferred to not run the effect at all in the first place rather than running it on label change and not calling focus method based on logic. what do you think?

Thanks, you were right.
Updating the label was retriggering the focus effect.
I fixed it by stabilizing `focusableItems` and keeping the focus guard, so typing in controls no longer loses focus.

File: packages/react/src/components/Menu/Menu.tsx [hunk 1]
```diff
@@ -411,15 +415,20 @@ const Menu = forwardRef<HTMLUListElement, MenuProps>(function Menu(
...
+        if (focusableItems.length > 0 && (!isRoot || menuContainsFocus)) {
           focusItem();
         }
       });
 
       return () => cancelAnimationFrame(raf);
     }
     // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, [open, focusableItems]);
+  }, [open, focusableItems, isRoot, position]);
```
Comment (devadula-nandan) [inline packages/react/src/components/Menu/Menu.tsx:431]: are these changes necessary? now that we memoized focusableItems?

**Review by devadula-nandan — COMMENTED** [review]
1 question

File: packages/react/src/components/Menu/Menu.tsx (hunk 1 above)
Comment (heloiselui) [reply packages/react/src/components/Menu/Menu.tsx:431]: Good question. So, affter memoizing `focusableItems`, `position` is still needed. When I tested without `position`, submenu `ArrowRight` focus regressed, and `isRoot` is stable per `Menu` instance, so it’s not strictly required for runtime behavior, but I kept it because it’s used inside the effect and keeps dependencies explicit/correct.

**Review by devadula-nandan — APPROVED** [review]
LGTM

**Review by sangeethababu9223 — APPROVED** [review]
LGTM!
