### PR TITLE
fix(content-switcher): call onChange with correct data with keyboard

### LINKED ISSUE #6119: Contentswitcher, onChange() event has wrong values when using arrow keys #1814
onChange={(e)}
e.name give the correct value when using the mouse click.
but when we use the arrow keys to navigate between switch content, it gives the previous value and not the current value and at the same time the focus is moving correctly.

## What package(s) are you using?
cloudpal version
@console/pal": "^1.134.1",
carbon-components-react@7.10.3
carbon-components@10.10.3

### PR DESCRIPTION
**Pull request by joshblack**
Closes #6119 

#### Changelog

**New**

**Changed**

- Update content switcher to call `onChange` with correct data when using keyboard
- Added tests for behavior to prevent regression

**Removed**

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
is this technically a breaking change? related https://github.com/carbon-design-system/carbon/issues/6162

**Comment by joshblack** [comment]
@emyarod good point, was thinking about that after seeing that proposal today.

I think technically it is, but the previous behavior is wrong so I wasn't sure what the right way forward may be.

**Comment by emyarod** [comment]
I think we just need to treat it as a breaking change (related previous incidents in the website and design language website https://github.com/carbon-design-system/carbon-website/issues/119 https://github.com/carbon-design-system/design-language-website/issues/273)

**Comment by tw15egan** [comment]
So is this being postponed until v11?

**Comment by joshblack** [comment]
Maybe the best question to ask here is if someone could use the as-is to implement a correct content switcher, or if it'd be too hard for the typical case?

It seems like it'd be challenging to use the incorrect behavior here with a code switcher, maybe you'd need to pass in `onKeyDown` with the `onChange` potentially? 

The reason this comes up is that if it's unreasonable for folks to implement/build a fix on top of the breaking behavior, then we could move forward with the change (since so no would be able to use it) but if there is an alternative way then we could rope this behind a feature flag, for sure.

**Comment by tw15egan** [comment]
I think if we communicate the reason for the breaking change (the behavior was impossible/difficult to implement as-is) then I'm okay with it.

**Comment by joshblack** [comment]
Cool, @emyarod said something similar over in Slack too. I think we could make a case for this being a justified change given that the behavior is incorrect, and achieving the correct behavior is difficult.

Let's go ahead and do that, I'll make sure to post a quick note too in our channel tomorrow.

**Comment by aledavila** [comment]
Is this something we want to start documetning in our code tabs. maybe at the bottom changes in x.x.x this was changed to get the behavior correctly? it seems like people never read our releases. Or as long as we communicate it in the release we can point them there ?

**Comment by joshblack** [comment]
bump @emyarod @tw15egan @aledavila when you get a chance 👀

**Review by emyarod — APPROVED** [review]
the change is fine. if we are pushing this ASAP we just need to be clear that it is a breaking change since this exact issue with content switcher has affected consumers like our own Carbon website multiple times (in the tickets I referenced)

**Review by tw15egan — APPROVED** [review]
Also good with the changes since this is making the correct implementation difficult. It would be great if we make sure we have some messaging around this so we don't break users without letting them know!

File: packages/react/src/components/ContentSwitcher/ContentSwitcher.js [hunk 1]
```diff
@@ -90,9 +91,15 @@ export default class ContentSwitcher extends React.Component {
             selectedIndex: nextIndex,
           },
           () => {
-            const switchRef = this._switchRefs[nextIndex];
+            const child = children[this.state.selectedIndex];
+            const switchRef = this._switchRefs[this.state.selectedIndex];
             switchRef && switchRef.focus();
-            this.props.onChange(data);
+            this.props.onChange({
+              ...data,
```
Comment (motou) [inline packages/react/src/components/ContentSwitcher/ContentSwitcher.js:109]: This introduces the unwanted attribute `key` (see line 80 above). Since the attributes will be overwritten completely by line 99-101, this line is not necessary.

**Comment by reeteshsingh93** [comment]
When can we expect this to get in?

**Comment by reeteshsingh** [comment]
Issue still persist
