### PR TITLE
fix(TableToolbarSearch): allow default values to be set

### LINKED ISSUE #3170: [TableToolbarSearch] `value` overwritten by empty state
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react` `v7.3.2`

## Detailed description

I’m trying to set a default value for the `DataTable` / `TableToolbarSearch` input field. Usually the props are passed down to the child components. In this case it’s the `Search` component, which offers the `defaultValue` and `value`. Unfortunately the `TableToolbarSearch` component initializes the `value` property by setting an empty state. Therefore, I can’t set a default value.

Related code line:
https://github.com/carbon-design-system/carbon/blob/3dabe8fd1272896f7c7d33ab2a451c7e15f5f90f/packages/react/src/components/DataTable/TableToolbarSearch.js#L46

## Steps to reproduce the issue

[Edit codesandbox](https://codesandbox.io/s/codesandbox-82cvg?fontsize=14)

## Additional information

Note: The Sandbox contains a little CSS bug fix for persistant mode, which I've described in #3108 already:

```css
      .bx--table-toolbar
        .bx--toolbar-action.bx--toolbar-search-container-persistant {
        width: 100%;
      }
```

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/3170

The `DefaultValue` prop was being ignored. This checks for the presence of a `DefaultValue`, and if it exists, it is used as the default state of `value`. On the initial load, it sets the expanded state to `true` and runs the `onChangeProp` to filter the table. Modified the `handleOnInputValueChange` in `DataTable.js` to account for non-event based sorting (table loads with a default value). 

Screen Shot 2020-01-17 at 2 10 40 PM

#### Changelog

**New**

- `DefaultValue` prop works as intended

**Changed**

- `handleOnInputValueChange` now has a `defaultValue` parameter

**Removed**

- `DefaultValue` being passed directly down to `Search`. If `DefaultValue` exists, it is immediately set to `value` which is then passed down. 

#### Testing / Reviewing

- Open `src/components/DataTable/stories/with-toolbar.js`
- Add `defaultValue="1"` to `TableToolbarSearch`
- Open the `With Toolbar` Storybook example, verify only 1 result shows up.
- Remove the value, verify all results show up.
- Add new value and verify the correct results show up.

### CODE REVIEW

File: packages/react/src/components/DataTable/TableToolbarSearch.js [hunk 1]
```diff
@@ -51,6 +51,13 @@ const TableToolbarSearch = ({
     }
   }, [controlled, expandedState]);
 
+  useEffect(() => {
+    if (defaultValue) {
+      setExpandedState(true);
+      onChangeProp('', defaultValue);
+    }
+  }, [defaultValue, onChangeProp]);
```
Comment (asudoh) [inline packages/react/src/components/DataTable/TableToolbarSearch.js]: Just want to double-check; Wondering if we want to react to change in `defaultValue`. The thought came up because `defaultValue` in `<input>` is effective only in creation time.

**Review by asudoh — APPROVED** [review]
Thank you for jumping in @tw15egan!

File: packages/react/src/components/DataTable/TableToolbarSearch.js (hunk 1 above)
Comment (tw15egan) [reply packages/react/src/components/DataTable/TableToolbarSearch.js]: I don't think it's a problem since it won't change. If I remove it I get a linting error:

Screen Shot 2020-01-17 at 4 06 44 PM

Comment (asudoh) [reply packages/react/src/components/DataTable/TableToolbarSearch.js]: Thank you for your thoughts - Lint error is something we can ignore as I believe. Wondering what you meant by "it won't change" - Does it translate to "our users _should not_ change `defaultValue` after creation"? The thought came because it's a React prop and thus component users can change it technically.

Comment (asudoh) [reply packages/react/src/components/DataTable/TableToolbarSearch.js]: Thank you for the update @tw15egan! (Seems that I signed this off already)

**Review by abbeyhrt — APPROVED** [review]
LGTM! 🎉

File: packages/react/src/components/DataTable/TableToolbarSearch.js [hunk 2]
```diff
@@ -51,6 +51,18 @@ const TableToolbarSearch = ({
     }
   }, [controlled, expandedState]);
 
+  //eslint-disable-next-line react-hooks/exhaustive-deps
+  useEffect(
+    () => {
+      if (defaultValue) {
+        setExpandedState(true);
```
Comment (joshblack) [inline packages/react/src/components/DataTable/TableToolbarSearch.js]: Would it help if we moved this up to line 42 to something like:

```jsx
  const [expandedState, setExpandedState] = useState(defaultExpanded || defaultValue);
```

File: packages/react/src/components/DataTable/TableToolbarSearch.js [hunk 3]
```diff
@@ -51,6 +51,18 @@ const TableToolbarSearch = ({
...
+        onChangeProp('', defaultValue);
```
Comment (joshblack) [inline packages/react/src/components/DataTable/TableToolbarSearch.js:63]: Do we need to call `onChange`  if they've provided us the default value?

**Review by joshblack — CHANGES_REQUESTED** [review]

File: packages/react/src/components/DataTable/TableToolbarSearch.js (hunk 3 above)
Comment (tw15egan) [reply packages/react/src/components/DataTable/TableToolbarSearch.js:63]: Without this call, the table was not automatically filtering the values on load.

**Comment by tw15egan** [comment]
@joshblack updated

File: packages/react/src/components/DataTable/TableToolbarSearch.js (hunk 3 above)
Comment (joshblack) [reply packages/react/src/components/DataTable/TableToolbarSearch.js:63]: Ah, got it. Given that this is in `useEffect` do we want the flicker while rendering the filtered list? Seems like we'd need a way to hoist up this default value so that this line is initialized appropriately, right? https://github.com/carbon-design-system/carbon/blob/dc860ba78dbac515a6910d05ed0e34fb941be797/packages/react/src/components/DataTable/state/getDerivedStateFromProps.js#L33

Comment (tw15egan) [reply packages/react/src/components/DataTable/TableToolbarSearch.js:63]: Hmm, not noticing any flicker on my end and its rendering properly... 🤔  also unsure about how to hoist that value up

Comment (joshblack) [reply packages/react/src/components/DataTable/TableToolbarSearch.js:63]: One option could be adding `defaultSearchValue` or something to DataTable and have it propagate down through an `inputValue` render prop but I totally get not wanting to go down that route.

The only reason I think it came up is that it seems like the render order becomes

- render `DataTable` with search value `''`
- render `TableToolbarSearch` with defaultValue `'foo'`
- run effect in `TableToolbarSearch` and update `DataTable` input value with `'foo'`
- re-render `DataTable` (which filters rows)

Just was curious if we could have this happen in one phase instead of two.

File: packages/react/src/components/DataTable/TableToolbarSearch.js [hunk 4]
```diff
@@ -52,6 +54,16 @@ const TableToolbarSearch = ({
     }
   }, [controlled, expandedState]);
 
+  useEffect(
+    () => {
+      if (defaultValue) {
+        onChangeProp('', defaultValue);
+      }
+    },
+    //eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (joshblack) [inline packages/react/src/components/DataTable/TableToolbarSearch.js:66]: If the `defaultValue` changes would we want to update the input value or no? Just was curious if that was why the ignore is here.

Comment (tw15egan) [reply packages/react/src/components/DataTable/TableToolbarSearch.js:66]: @asudoh and I went back and forth here. I originally had it updating if DefaultValue was updated. I don't really have a strong preference either way.

File: packages/react/src/components/DataTable/TableToolbarSearch.js (hunk 3 above)
Comment (tw15egan) [reply packages/react/src/components/DataTable/TableToolbarSearch.js:63]: I'm thinking we could get it into 1 phase as well, but I think I'd like to split that into a separate issue and get this functionality in to fix the issue. That work?

Comment (joshblack) [reply packages/react/src/components/DataTable/TableToolbarSearch.js:63]: For sure! The only concern I would have would be if the API for the components change as a result. It seemed (initially) that in order to get it all done in one render that we'd need to supply a prop to DataTable and then have it pass things down to `TableToolbarSearch`.

If we think the API will change as a result, it seems like it'd make sense to get it done in one go instead of potentially adding and then removing props like `defaultValue` if they're not relevant anymore.

Comment (tw15egan) [reply packages/react/src/components/DataTable/TableToolbarSearch.js:63]: Ah so just remove `defaultValue` from `TableToolbarSearch` altogether, and pass it down from `DataTable` instead?

Comment (joshblack) [reply packages/react/src/components/DataTable/TableToolbarSearch.js:63]: Honestly I'm curious what you think would make most sense here, just an idea. We could totally do something like:

```jsx
<DataTable defaultInputValue="foo">
  {({ onInputChange, inputValue }) => (
    <TableToolbarSearch onChange={onInputChange} value={inputValue} />
  )}
</DataTable>
```

But definitely haven't spent as much time in this part of the codebase recently so might not make sense? Let me know!

Comment (tw15egan) [reply packages/react/src/components/DataTable/TableToolbarSearch.js:63]: Tried a couple of different ways of implementing it, but personally, it seems more confusing than just letting users put a `defaultValue` on the `TableToolbarSearch` and it just works  🤷‍♂

File: packages/react/src/components/DataTable/TableToolbarSearch.js (hunk 4 above)
Comment (asudoh) [reply packages/react/src/components/DataTable/TableToolbarSearch.js:66]: Change in `defaultValue` in `<input>` doesn't update its value, so my suggestion is taking a cue from there.

**Comment by tw15egan** [comment]
@joshblack are we good with this?

**Review by joshblack — APPROVED** [review]
