### PR TITLE
fix(data-table): use unselectAll translation key if selection checkbox is indeterminate

### LINKED ISSUE #4556: DataTable with selection aria-label text should say "Unselect all rows" when aria-checked="mixed"
Steps:
1. [DataTable With selection Storybook](http://react.carbondesignsystem.com/?path=/story/datatable--with-selection)
2. Select some - but not all - of the rows by clicking on some of the checkboxes
3. Notice that the "select-all" checkbox at the top of the selection column contains a `-` because only some of the values are selected, and if you inspect this checkbox you can see that aria-checked="mixed". So far, so good.
4. The aria-label says "Select all rows", so one would expect that clicking on this checkbox would select all of the rows, but it does not - it Unselects all of the rows. So the aria-label is incorrect for the mixed state. Please change it to say "Unselect all rows" when aria-checked="mixed".

image

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4556 

#### Changelog

**Changed**

- check for `indeterminate` checkbox (as well as `checked` to determinate if `translationKeys.unselectAll` is used

#### Testing / Reviewing

Open the `carbon-components-react` deploy and follow the steps in #4556 -- directly select only a few rows, and then check the `aria-label` of the indeterminate icon. It *should* say "unselect all rows" instead of "select all rows"

### CODE REVIEW

**Comment by carmacleod** [comment]
Tested react version. Looks good! Thanks, @jendowns!

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

File: packages/react/src/components/DataTable/DataTable.js [hunk 1]
```diff
@@ -315,9 +315,10 @@ export default class DataTable extends React.Component {
     const checked = rowCount > 0 && selectedRowCount === rowCount;
     const indeterminate =
       rowCount > 0 && selectedRowCount > 0 && selectedRowCount !== rowCount;
-    const translationKey = checked
-      ? translationKeys.unselectAll
-      : translationKeys.selectAll;
+    const translationKey =
+      checked || indeterminate
```
Comment (joshblack) [inline packages/react/src/components/DataTable/DataTable.js:319]:
```suggestion
      (checked || indeterminate)
```

Does prettier end up taking away the parenthesis here? There seems to be some syntax ambiguity that adding these in might help with. Otherwise, seems great!

**Review by joshblack — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me

File: packages/react/src/components/DataTable/DataTable.js (hunk 1 above)
Comment (emyarod) [reply packages/react/src/components/DataTable/DataTable.js:319]: yeah prettier will remove parentheses there. by default it is evaluated as `(checked || indeterminate) ? ... : ...` rather than `checked || (indeterminate ? ... : ...)`
