### PR TITLE
fix(Button): close Icon only button tooltip, TooltipIcon when another button/tooltip is focused or hovered

### LINKED ISSUE #4560: [Button] - icon only button, two tooltips visible and overlapping each other
[Button] - icon only button, two tooltips visible and overlapping each other.

Icon only buttons are very common to be used on toolbars, or as buttons inside DataTable rows e.g. edit/delete actions.

Currently last clicked button icon only button has focus, and tooltip is visible on focus.
When I hover over another icon button, another tooltip is also visible, so both are present and overlapping each other:

image

Steps to recreate:
1. Create two icon only buttons next to each other.
2. Click on button one - button focused tooltip visible,
   or focus button using Tab
3. Hover over button two - both tooltips visible and in most cases overlaps since buttons are 48px size.

I think tooltip for focused button should disappear just after someone will hover over different icon only button. Other option is to remove the rule to show tooltip for focused icon only button.
Regarding accessibility, use of aria-label should be sufficient. I think screen readers will also correctly handle disabled button state, without a need of adding aria-disabled.

Set of icon only buttons are common in toolbars (just different icons):
image

## What package(s) are you using?

    "carbon-components": "10.7.3",
    "carbon-components-react": "7.7.3",
    "carbon-icons": "7.0.7",

### LINKED ISSUE #7040: Tooltip for Icon Button stays visible after button is clicked and mouse moves away
## Tooltip for Icon Button stays visible when button is clicked 

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
When an Icon Button is clicked, the tooltip stays visible even when the mouse is moved away from the button. This happens since the button has focus, but it looks very odd to the user.  I would expect for the tooltip to go away once the button is clicked.

What browser are you working in? Chrome / Firefox / IE / Edge

What version of the Carbon Design System are you using? carbon-components-react 7.17.0

What offering/product do you work on? Any pressing ship or release dates we should be aware of?  Part of the Cognos Analytics offering with a release of end of October. 

## Steps to reproduce the issue
This behaviour can be seen in the Carbon sample for the Icon Button https://react.carbondesignsystem.com/?path=/story/button--icon-button

1. Click on the button icon
2. Move your mouse away from the button

BUG:  The tooltip is still visible.

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/7040
Closes #4560

Adds focus and hover handlers to remove the tooltip when an icon-only button or `TooltipIcon` with focus is hovered off

#### Changelog

**New**

- `Button` and `Tooltip` now have `focus` and `mouseEnter` handlers to handle toggling the tooltip visibility. On `focus` / `mouseenter`, we check for any other open tooltips and close them.
- 

**Changed**

- `pointer-events: none` added to the `svg` inside of `Button` to prevent the `onMouseOut` function from firing when the cursor hovers over the internal `svg`
- Updated snapshots

#### Testing / Reviewing

Try testing out `Button` and `TooltipIcon` that have two elements next to each other. Try to get the tooltips to render over the other (this shouldn't be possible). Then check `Pagination` or `UI Shell w/ Actions` and ensure all functionality remains

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
currently the button loses focus on mouseout because of the blur event being called, but I'm not sure if focus should be removed entirely on mouse out. I believe the solution should just be to close the tooltip when the mouse leaves the tooltip trigger and preserve focus on the trigger element right?

**Comment by emyarod** [comment]
on a side note, the PR is only be about removing focus on hover right? I don't think the issue with overlaps is fully addressed

image

**Comment by tw15egan** [comment]
@emyarod how were you able to get them to overlap? The only way I was able to get them to overlap was if you hover one, then tab to the next one, which I don't think is a valid use-case.

And since the tooltip opens on click, and then you mouse-out (essentially taking your focus away from the button), is it an issue if we remove focus from the element? What would you suggest instead? We would need to toggle some class on mouseout that overrides the default focus styles

**Comment by emyarod** [comment]
I don't think it's unreasonable to account for a combination of keyboard and mouse navigation esp with the number of reports about the overlap issue, but we can tackle that in #4560 if this PR is only to deal with mouseout behavior. I only brought up the overlap issue because it's still present but the PR title is about overlap rather than mouseout. but in any case I believe focus should be retained on the element regardless of mouse movement. The tooltip opens on focus rather than click, and mouseout should have no effect on focus

**Comment by tw15egan** [comment]
@emyarod so would you just expect this PR to add a class to close a tooltip on mouse out?

**Comment by emyarod** [comment]
I was just saying that I would expect focus to not be removed by mouse movement, and it's unclear to me which issue or which part of the issue you want to scope your PR to

**Comment by tw15egan** [comment]
The point of the PR is to prevent tooltips from overlapping when a user clicks on a button, then hovers over a second button, the first tooltip should close. 

I did not think that hovering over one tooltip, then tabbing to a second button, would be an expected pattern. I can switch it so that it retains focus on mouse out (by toggling a new class that overrides the focus styles, since that is how the tooltips are triggered), but I was just curious on how you would expect that to be handled.

**Comment by emyarod** [comment]
I don't think the overlap issue can be split cleanly between #7040 and #4560, but I believe #7040 can be addressed by just meeting the requirement of removing the tooltip when a focused button is no longer hovered

Focusing and hovering on the tooltip trigger isn't so much a pattern as it is a possible interaction, so I don't think it's reasonable to rule out that kind of interaction. but again I don't think the overlap issue can be split cleanly from #4560 so that can be addressed elsewhere, was just confused from the PR title

**Comment by tw15egan** [comment]
PR has been updated, it should now close any other open tooltip when a new one is focused/hovered over. Ported the same changes to `TooltipIcon`, and lifted some of the logic from `TooltipIcon` to `Button`

File: packages/react/src/components/TooltipIcon/TooltipIcon.js [hunk 1]
```diff
@@ -57,7 +75,9 @@ const TooltipIcon = ({
       className={tooltipTriggerClasses}
       aria-describedby={tooltipId}
       onMouseEnter={composeEventHandlers([onMouseEnter, handleMouseEnter])}
-      onFocus={composeEventHandlers([onFocus, handleFocus])}>
+      onMouseLeave={composeEventHandlers([onMouseLeave, handleMouseLeave])}
+      onFocus={composeEventHandlers([onFocus, handleMouseEnter])}
```
Comment (tw15egan) [inline packages/react/src/components/TooltipIcon/TooltipIcon.js]: Added this to the `mouseEnter` block, but let me know if we want to handle this separately

**Review by dakahn — COMMENTED** [review]
@carmacleod  when using magnification (400x) on Windows 10 and focusing the button with the keyboard the tooltip is outside of the magnification viewport. 

image

When reorienting the viewport the user can use the mouse pointer (bringing the pointer to the edge of the screen drags the viewport around). With our new hoverout tooltip close functionality the user has to very carefully avoid the button when reorienting because if the mouse cursor passes into and out of it it'll close the tooltip requiring them refocus with keyboard and start the process over. :|

Not a violation per se, but also not technically what I'd consider an edge case. Thoughts?

**Comment by tw15egan** [comment]
@dakahn does the windows system zoom move the magnification based on focus? 

Testing on Mac it doesn't move the magnification area at all. Which I guess makes this bug less of a pain, since once the button is properly in focus they can easily tab or mouse over to see the tooltip properly. Just trying to understand the difference between the two OS's


btw the button focus animation looks really nice at 400% 😍 😄

**Comment by dakahn** [comment]
yeah when keyboard navving it orients the focused element into the top right.

**Review by emyarod — COMMENTED** [review]
the overlap can still occur with this interaction:

Kapture 2021-03-10 at 09 59 55

**Comment by tw15egan** [comment]
@emyarod nice catch, seems like that interaction is only triggered on the first call. If you hover back on the second one it causes the first to dismiss. I will take a look 🤔

**Comment by tw15egan** [comment]
Updated 👍🏻

**Comment by carmacleod** [comment]
@dakahn @tw15egan 
> @carmacleod when using magnification (400x) on Windows 10 and focusing the button with the keyboard the tooltip is outside of the magnification viewport. When reorienting the viewport the user can use the mouse pointer (bringing the pointer to the edge of the screen drags the viewport around). With our new hoverout tooltip close functionality the user has to very carefully avoid the button when reorienting because if the mouse cursor passes into and out of it it'll close the tooltip requiring them refocus with keyboard and start the process over. :|

This PR only satisfies 1 of the 3 points in [WCAG 2.1 Success Criterion 1.4.13 for Content on Hover or Focus](https://w3c.github.io/wcag21/guidelines/#content-on-hover-or-focus).
Getting the other 2 right will make magnification work much better. :)

- **Dismissable**: A mechanism is available to dismiss the additional content without moving pointer hover or keyboard focus...
   - [x] You're good to go on this one because Esc closes the tooltip whether it was triggered by focus or hover - nice.
- **Hoverable**: If pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional content disappearing;
   - [x] Fixing this will help a lot with the magnification problem. The user is supposed to be able to hover, get a tooltip, then move the mouse over to the tooltip without it disappearing.
- **Persistent**: The additional content remains visible until the hover or focus trigger is removed, the user dismisses it, or its information is no longer valid.
   - This is mostly satisfied, but it will also help with the magnification problem if you go with the suggestion I made in https://github.com/carbon-design-system/carbon/issues/7040#issuecomment-721418287:
     - [x] when the tooltip is triggered by _focus_, then it should be dismissed when _focus_ is removed (or if a _**different**_ tooltip is triggered by hover) << the key point here being to ignore hovers on the same element if the tooltip was triggered by focus.
     - [x] when the tooltip is triggered by _hover_, then it should be dismissed when _hover_ is removed (even if the button still has focus) << actually, you already do this point - yay!

**Comment by tw15egan** [comment]
@carmacleod thanks for taking the time to review this! I've just pushed a few updates that I think get us closer to that compliance.

Now, there is 

- Tooltip should stay open if it has focus unless another element is hovered/focused
- A slight timeout when the Tooltip is moused out before the tooltip is closed. Right now it's pretty short because I've also added...
- An `::after` pseudo element on the Tooltip itself to better trap hover events. Right now, it is simply a rectangle (which may be too big of an area), but could easily be updated to be a larger caret like area


Current: 
Screen Shot 2021-03-11 at 3 04 04 PM

Possible:
Screen Shot 2021-03-11 at 3 13 25 PM

File: packages/components/src/globals/scss/_tooltip.scss [hunk 2]
```diff
@@ -224,6 +224,39 @@
   $caret-width: rem(8px);
   $body-spacing: $caret-spacing + $caret-height;
 
+  // Use pseudo element to create invisible hover area to keep tooltip open on hover
+  .#{$prefix}--assistive-text::after {
+    position: absolute;
+    display: block;
+    content: '';
+    // clip-path: polygon(50% 100%, 0 0, 100% 0);
```
Comment (tw15egan) [inline packages/components/src/globals/scss/_tooltip.scss:232]: Will remove before the merge, but this is what we'd need to use if we want a chevron hover area instead of a rectangle

File: packages/react/src/components/Button/Button-story.js [hunk 3]
```diff
@@ -199,7 +199,10 @@ export const Playground = () => {
 };
 
 export const IconButton = () => (
-  <Button renderIcon={Add16} iconDescription="Icon Description" hasIconOnly />
+  <>
+    <Button renderIcon={Add16} iconDescription="Icon Description" hasIconOnly />
+    <Button renderIcon={Add16} iconDescription="Icon Description" hasIconOnly />
```
Comment (tw15egan) [inline packages/react/src/components/Button/Button-story.js]: Will revert before merge

File: packages/components/src/globals/scss/_tooltip.scss (hunk 2 above)
Comment (carmacleod) [reply packages/components/src/globals/scss/_tooltip.scss:232]: The rectangle works great!

If you ever do decide to go with a chevron-ish shape, please don't go with a "pointy tail" - perhaps something with a "flat tail" that is the same width as the button or icon?

image

**Review by carmacleod — APPROVED** [review]
+1
This looks nice and works really well!
Thanks @tw15egan !

**Review by emyarod — COMMENTED** [review]
an interaction question: when an element is no longer hovered, does a focused trigger element need to get its tooltip restored?

**Comment by tw15egan** [comment]
@emyarod do you have any examples of this in the wild? This seems like it could be pretty unexpected. For instance if you are focused on a icon in the header, then hover over a tooltip in the main body content, I don't think to would expect the tooltip to reappear at the top of the screen just because its was initially focused.

**Comment by emyarod** [comment]
there are many examples of this behavior in libraries like Bootstrap or Material UI etc. but none of the examples also implement the tooltip hiding behavior we are looking for (at the moment I don't know of any examples that do the tooltip hiding behavior at all). but in any case I don't know if hovering over another tooltip trigger is considered explicit dismissal of the original tooltip so that's why I asked the original question (cc @carmacleod). in my opinion the behavior that we are implementing by removing all other tooltips can be considered unexpected, so restoring the tooltip on the currently focused element if no other tooltips are activated makes sense to me

**Comment by tw15egan** [comment]
@emyarod do you have any links I could take a look at? Bootstrap seems to have two persistent tooltips (one hover, one focus) and the one with the focus simply never loses its tooltip, so not really an example that maps 1-1. 

According the @carmacleod :

> when the tooltip is triggered by focus, then it should be dismissed when focus is removed (**or if a different tooltip is triggered by hover**)

I still think reopening the previous tooltip would be more unexpected. If they wanted to have the tooltip reappear, they can simply hover back over it or toggle focus back and forth

**Comment by emyarod** [comment]
> Bootstrap seems to have two persistent tooltips (one hover, one focus) and the one with the focus simply never loses its tooltip, so not really an example that maps 1-1.

as far as I know there is no implementation of the tooltip hiding behavior so there is no 1-1 comparison, and that is what I was referring to when I wrote

> none of the examples also implement the tooltip hiding behavior we are looking for (at the moment I don't know of any examples that do the tooltip hiding behavior at all)

the statement you quoted mentions dismissal but that's why I'm looking for clarification on explicit dismissal since a hover action can be inadvertent whereas focus and click would be more deliberate

**Comment by carmacleod** [comment]
@emyarod @tw15egan 

It honestly never occurred to me that someone might expect the previous tooltip to come back. Personally, I wouldn't expect that.

I tried to find some hint in the WCAG wording and in other people's analysis of it that would help with this decision, but I can't find anything, so it may be more of a general UX issue.

However, I can give my personal opinion and do some guessing - feel free to disagree. ;)

- I think that users only want to see a tooltip for a very short length of time... just long enough to know what that button does or what the description of that input is.
- I think that if a user focuses one button/input/whatever and then hovers over another, they have essentially dismissed the previous tooltip and moved on, and they would be annoyed to have the previous tooltip reappear.
- So I think that you should NOT reopen the previously-closed tooltip, even if the element still has focus.

----

I think part of the confusion may stem from the basic [Carbon Tooltip component](https://carbon-components-react.netlify.app/iframe.html?id=components-tooltip--default-bottom), which (in my opinion) needs a complete redesign. It should not open on focus. It should not be called a Tooltip. The button's only purpose in life is to show some "info", so it should be explicitly clicked (with mouse, pointer, space, enter, etc) to show the extra content, and not show it on hover OR focus. It is a popup button that basically pops up a dialog, so the button should not use aria-describedby. Anyhow, all that's an issue for another day.

**Review by emyarod — APPROVED** [review]
thanks for the clarification! yeah the tooltip/toggletip refactor is still in the works afaik

**Review by dakahn — APPROVED** [review]
Great work all! 🏄🏽
