### PR TITLE
fix(cli): correct broken handling of Windows paths in `inline` command

### LINKED ISSUE #16963: Carbon build is not working
Hi!

I'm trying to install the carbon-design-system/carbon package and I'm facing this issue. Has anyone seen this before? Thank you

### Discussed in https://github.com/carbon-design-system/carbon/discussions/15418

<div type='discussions-op-text'>

<sup>Originally posted by **raphyluke** December 18, 2023</sup>
Hello everyone !
I actually don't know if it's normal or not so I prefer to create discussion instead of issue at first.

I followed fully the contribution guide to build carbon. The problem is that when I try to build it I have an error at a moment : 

```
> @carbon/grid:build

@carbon/colors: check ▐ ┏ check
@carbon/colors: check ▐ ┣ Running in: D:\open source\carbon\packages\colors
@carbon/colors: check ▐ ┣ Checking pattern: 'scss/*.scss', ignoring: ''       
@carbon/colors: check ▐ ┣ Compiling 0 files...
@carbon/colors: check ▐ ┣ Successfully compiled 0 files! 🎉
@carbon/colors: check ▐ ┗ Done in 0.01s
@carbon/grid: inline ▐ ┏ inline
@carbon/grid: inline ▐ ┣ Inlining sass dependencies
@carbon/grid: Error: No files match the pattern: D:\open source\carbon\packages\grid\scss\_inlined\_breakpoint.scss
@carbon/grid:     at D:\open source\carbon\node_modules\replace-in-file\lib\helpers\glob-async.js:27:23
@carbon/grid:     at f (D:\open source\carbon\node_modules\once\once.js:25:25)@carbon/grid:     at Glob.<anonymous> (D:\open source\carbon\node_modules\replace-in-file\node_modules\glob\glob.js:148:7)
@carbon/grid:     at Glob.emit (node:events:514:28)
@carbon/grid:     at Glob._finish (D:\open source\carbon\node_modules\replace-in-file\node_modules\glob\glob.js:194:8)
@carbon/grid:     at done (D:\open source\carbon\node_modules\replace-in-file\node_modules\glob\glob.js:179:14)
@carbon/grid:     at Glob._processSimple2 (D:\open source\carbon\node_modules\replace-in-file\node_modules\glob\glob.js:688:12)
@carbon/grid:     at D:\open source\carbon\node_modules\replace-in-file\node_modules\glob\glob.js:676:10
@carbon/grid:     at Glob._stat2 (D:\open source\carbon\node_modules\replace-in-file\node_modules\glob\glob.js:772:12)
@carbon/grid:     at lstatcb_ (D:\open source\carbon\node_modules\replace-in-file\node_modules\glob\glob.js:764:12)
@carbon/icon-helpers: bundle ▐ ┗ Done in 6.50s

 ————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Running target build for 28 projects failed       

   Tasks not run because their dependencies failed or --nx-bail=true:

   - class-prefix:build
   - custom-theme:build
   - id-prefix:build
   - incremental-migration-vite:build
   - examples-light-dark:build
   - examples-nextjs:build
   - v10-token-compat-in-v11:build
   - vite:build
   - carbon-components:build
   - carbon-components-react:build
   - @carbon/elements:build
   - @carbon/icons:build
   - @carbon/icons-react:build
   - @carbon/icons-vue:build
   - @carbon/pictograms:build
   - @carbon/pictograms-react:build
   - @carbon/themes:build
   - @carbon/type:build

   Failed tasks:

   - @carbon/grid:build
```

I didn't touch anything in the code, I just forked, installed and tried to build
Is it normal ? Is it a mistake from me ?

If someone can explain and say to me the solution, it will be appreciable, thank you :)</div>

### PR DESCRIPTION
**Pull request by nchevsky**
Fixes #16963 (closed with no resolution after the author disappeared).

Corrects broken handling of Windows paths in the `inline` command—used by the `@carbon/grid` build—by passing option [`glob.windowsPathsNoEscape`](https://github.com/adamreisnz/replace-in-file?tab=readme-ov-file#specify-glob-configuration) to [`replace-in-file`](https://www.npmjs.com/package/replace-in-file).

💡 This is the first in a series of patches to enable building all of Carbon on Windows natively, without WSL. 🚀

#### Testing / Reviewing

Build `@carbon/grid` on a native Windows environment, or take my word for it:

| Before ❌ | After ✅ |
| --- | --- |
| image | image |

### CODE REVIEW

File: packages/cli/src/commands/inline.js [hunk 1]
```diff
@@ -124,6 +124,7 @@ async function inlineSassDependencies(
       await replace({
         files: file.path,
         from: REPLACE_REGEX,
+        glob: { windowsPathsNoEscape: true },
         to(_, match) {
           return `@import '${
             isWin ? relativeImportPath.replace('\\', '/') : relativeImportPath
```
Comment (nchevsky) [inline packages/cli/src/commands/inline.js:130]: Option [`glob.windowsPathsNoEscape`](https://github.com/adamreisnz/replace-in-file?tab=readme-ov-file#specify-glob-configuration) instructs [`replace-in-file`](https://www.npmjs.com/package/replace-in-file) to interpret Windows paths as-is and avoid escaping backslashes found in the value of the `files` argument, which on Windows leads to double escaping and yields an invalid glob pattern that will never match anything:

image

Example of a `files` value from the `@carbon/grid` build:

image

Successful `@carbon/grid` build after the fix:

image

**Comment by tay1orjones** [comment]
@nchevsky thanks for putting this up! Does the full monorepo build work now or just the grid package? In either case what do you think about adding a new step to the ci workflow that runs on windows and ensures the build passes? It wouldn't have to be a required check, but would provide visibility into the status of windows support without having to manually test on a windows machine.

**Review by tay1orjones — APPROVED** [review]

**Comment by nchevsky** [comment]
> @nchevsky thanks for putting this up! Does the full monorepo build work now or just the grid package? In either case what do you think about adding a new step to the ci workflow that runs on windows and ensures the build passes? It wouldn't have to be a required check, but would provide visibility into the status of windows support without having to manually test on a windows machine.

@tay1orjones This PR only fixes `cli` and the dependent `grid` build. I have fixes for the rest of the monorepo, too, but I wanted to gauge interest before submitting the rest, as it takes significant effort to prepare each submision. There are quite a few remaining instances of bad path handling, and each needs a slightly different solution with an individual explanation. Now that this PR has been well-received, I can start preparing the rest. 🙂

That's a great idea about the build step! Unfortunately I'm spread very thin until April, but I'm happy to add that as we get closer to merging the last couple of path handling fixes. Does that sound reasonable?

**Review by annawen1 — APPROVED** [review]
confirmed working on windows machine, `@carbon/grid` builds!

**Review by preetibansalui — APPROVED** [review]
