### PR TITLE
fix(pagination): fix null error in update

### LINKED ISSUE #20695: [Bug]: showing console error when rendering a table
### Package

@carbon/web-components

### Browser

_No response_

### Package version

2.40.0

### React version

_No response_

### Description

**Showing console error on pagination when rendering a table**
 
**Details:**
 
After upgrading Carbon Web Components from v2.38.0 to v2.40.0, encountering the following console error when rendering a table:
```
core.mjs:6720 ERROR TypeError: Cannot set properties of null (setting 'value')
    at CDSPagination.updated (pagination.js:276:69)
    at CDSPagination._$didUpdate (reactive-element.js:938:14)
```
 
Issue reproducible in storybook

https://github.com/user-attachments/assets/16fc4e98-32c4-48e1-b394-9053a55445c8

https://github.com/user-attachments/assets/3eab8beb-66ba-4d85-a242-39108ee9e280

### Reproduction/example

https://github.com/user-attachments/assets/16fc4e98-32c4-48e1-b394-9053a55445c8

### Steps to reproduce

Step 1: update the carbon wc version from 2.38.0 to 2.40.0
Step 2: getting error on table rendering 

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by heloiselui**
Closes #20695

Fixes a console warning in `cds-pagination` caused by updating elements before render. The change does not affect any user-facing behavior.

### Changelog

**New**

- Added safe null checks in the `updated()` to ensure pagination selects exist before assigning values.
- Added test to cover the changes

**Changed**

- Added `if` checks for safer updates.
- Used `this.updateComplete` to avoid timing issues.

**Removed**

- ~None.~

#### Testing / Reviewing

-Go to `WC Deploy Preview` > `Pagination` > `Default`  
     - Open `DevTools` > `Console`, and ensure the error message no longer shows up. 
image

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [X] Reviewed every line of the diff
- ~[ ] Updated documentation and storybook examples~
- ~[ ] Wrote passing tests that cover this change~
- ~[ ] Addressed any impact on accessibility (a11y)~
- [X] Tested for cross-browser consistency
- [X] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]

File: packages/web-components/src/components/pagination/pagination.ts [hunk 1]
```diff
@@ -365,9 +365,13 @@ class CDSPagination extends FocusMixin(HostListenerMixin(LitElement)) {
       .constructor as typeof CDSPagination;
 
     if (changedProperties.has('pageSize')) {
-      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion , @typescript-eslint/no-explicit-any -- https://github.com/carbon-design-system/carbon/issues/20452
-      (this.shadowRoot!.querySelector(selectorPageSizesSelect) as any).value =
-        pageSize;
+      const pageSizeSelect = this.shadowRoot?.querySelector(
```
Comment (kennylam) [inline packages/web-components/src/components/pagination/pagination.ts:368]: Just for future reference (and maybe a future TODO to clean up all `querySelector` uses), selectors like this can be cached with the `@query` decorator. This also simplifies your logic a little bit.

```ts
@query(selectorPageSizesSelect) private _pageSizeSelect!: CDSSelect;
...

if (changedProperties.has('pageSize')) {
  this._pageSizeSelect.value blah blah blah
}
```

**Review by kennylam — APPROVED** [review]
LGTM! The comment I left doesn't need to be addressed now. I was thinking it could be some clean up work we do in the future.

File: packages/web-components/src/components/pagination/pagination.ts (hunk 1 above)
Comment (heloiselui) [reply packages/web-components/src/components/pagination/pagination.ts:368]: I'll open an issue so we can fix this, thank you so much for reviewing, Kenny!
