### PR TITLE
fix(uniqueId): replace uniqueId usage with internal useId

### LINKED ISSUE #19568: [Bug]: Adds an extra id for CodeSnippet component resulting in hydration error when using an inline type
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.78.0 - @carbon/react

### React version

19.0.0

### Description

Image

The image above shows the error message that I get when we use type inline - it adds two id's. 
https://github.com/carbon-design-system/carbon/blob/45c66dbf8488f98bbc38efa20b7f22dd591aee3f/packages/react/src/components/CodeSnippet/CodeSnippet.tsx#L205 
this is currently how the id is generated and would need to be fixed

### Reproduction/example

https://stackblitz.com/edit/github-to7sb4zh?file=src%2FApp.tsx

### Steps to reproduce

Use CodeSnippet and use type="inline" and an error pops up about id's

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #19568

`uniqueId()` is prone to hydration errors. It was created before we had the internal `useId` helper, which is much more robust.

### Changelog

**New**

- add deprecation warning to uniqueId

**Changed**

- replace all usages of uniqueId with useId

#### Testing / Reviewing

- Go to the CodeSnippet, FileUploader, TreeView stories and make sure they work the same as before

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] ~Updated documentation and storybook examples~
- [x] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [ ] ~Tested for cross-browser consistency~
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by kennylam — DISMISSED** [review]

File: packages/react/src/tools/uniqueId.ts [hunk 1]
```diff
@@ -4,10 +4,17 @@
  * This source code is licensed under the Apache-2.0 license found in the
  * LICENSE file in the root directory of this source tree.
  */
+import { warning } from '../internal/warning';
 
 let lastId = 0;
 
+export const uniqueIdDeprecationMessage = `The \`uniqueId()\` helper function from @carbon/react was called. This function should no longer be used.
+
+@carbon/react components should use the internal/useId.js hook instead. Other projects can use React's \`useId()\` hook: https://react.dev/reference/react/useId`;
```
Comment (tay1orjones) [inline packages/react/src/tools/uniqueId.ts:13]: This message extends to "other projects" because while `uniqueId` isn't exported from `@carbon/react`, it's possible (though unlikely) someone is using it directly from `@carbon/react/es/tools/uniqueId`. [Hyrum's Law](https://www.hyrumslaw.com/) and all...

**Review by kennylam — COMMENTED** [review]
Whoops, approved too soon. This `FileUploader` [story](https://deploy-preview-19585--v11-carbon-react.netlify.app/?path=/story/components-fileuploader--drag-and-drop-upload-single-container-example-application) throws an [error](https://react.dev/errors/321) when trying to upload a file.

**Comment by tay1orjones** [comment]
@kennylam that should be fixed 👍

**Review by kennylam — APPROVED** [review]
LGTM!

**Review by 2nikhiltom — APPROVED** [review]
LGTM ! No errors in stories
