### PR TITLE
fix(notification): trap focus in actionable notification WC

### LINKED ISSUE #19302: [a11y]: Actionable Notification does not trap focus
### Package

@carbon/web-components

### Browser

Chrome

### Operating System

MacOS

### Package version

1.81.0

### React version

_No response_

### Automated testing tool and ruleset

n/a

### Assistive technology

_No response_

### Description

Focus can be moved outside of Actionable Notification. From the storybook docs:

"This component grabs and traps focus until the action is acted upon or the notification is dismissed."

I think this may lead to potential WCAG 2.4.11 failures if the notification obscures another element on the page that is brought into focus without the notification being closed.

https://github.com/user-attachments/assets/959ddcff-2876-44b5-90b6-f9dd326177d7

### WCAG 2.1 Violation

2.4.11 (Focus not obscured)

### Reproduction/example

https://web-components.carbondesignsystem.com/?path=/story/components-notifications-actionable--default

### Steps to reproduce

1. Go to https://web-components.carbondesignsystem.com/?path=/story/components-notifications-actionable--default
2. Press TAB on keyboard until the action or close buttons of the notification come into focus (I recommend clicking "skip to canvas" to speed this up)
3. Continue pressing TAB and observe that focus can move outside of Notification without it closing

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by warrenmblood**
Closes #19302

Traps focus in `Actionable Notification` web component like it states in the storybook docs and prevents potential WCAG 2.4.11 violations.

### Changelog

**New**

- Implements sentinels to wrap focus similarly to `Modal` and `Tearsheet` web components
- Does not wrap focus when `role` attribute changed to something other than `alertdialog`

**Changed**

-  `selectorTabbable` includes `${prefix}-actionable-notification-button` and prevents sentinels from being selected

#### Testing / Reviewing

- View `Actionable Notification` web component in storybook
- Check focus trapping inside notification when pressing TAB
- Check focus trapping inside notification when pressing SHIFT+TAB

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] ~Updated documentation and storybook examples~
- [ ] ~Wrote passing tests that cover this change~
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/web-components/src/components/notification/actionable-notification.ts [hunk 1]
```diff
@@ -86,6 +143,72 @@ class CDSActionableNotification extends HostListenerMixin(
...
+      relatedTarget !== this &&
+      (this.contains(relatedTarget as Node) ||
+        (this.shadowRoot?.contains(relatedTarget as Node) &&
+          relatedTarget !== (startSentinelNode as Node) &&
+          relatedTarget !== (endSentinelNode as Node)));
+
+    // Performs focus wrapping if _all_ of the following is met:
+    // * This notification is open
+    // * The viewport still has focus
+    // * Notification body used to have focus but no longer has focus
```
Comment (tay1orjones) [inline packages/web-components/src/components/notification/actionable-notification.ts]: Should this also have parity with react in that it won't perform focus wrap if the `role` is configured to be something other than `alertdialog`? That was a semi-recent addition to the react `ActionableNotification`

**Review by tay1orjones — APPROVED** [review]
If you think my comment about the configurable `role` would be best suited in a separate PR, could you open a new issue for it? 

Otherwise LGTM!

File: packages/web-components/src/components/notification/actionable-notification.ts (hunk 1 above)
Comment (warrenmblood) [reply packages/web-components/src/components/notification/actionable-notification.ts]: I'll update this PR to match that behavior

**Review by 2nikhiltom — APPROVED** [review]

**Comment by warrenmblood** [comment]
> If you think my comment about the configurable `role` would be best suited in a separate PR, could you open a new issue for it?
> 
> Otherwise LGTM!

Updated changes in this PR to prevent focus wrapping when `role` attribute is configured to be something other than `alertdialog`

**Review by tay1orjones — COMMENTED** [review]
~I kinda forgot about tests for this. Would you mind adding some?~ eh ignore this - I'm realizing there isn't the playwright setup for wc like there is for the react package.

**Review by tay1orjones — APPROVED** [review]
