### PR TITLE
19906-Exception is thrown if all MenuItems of the ComboButton is disabled

### LINKED ISSUE #19906: [Bug]: Exception is thrown if all MenuItems of the ComboButton is disabled
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.85.1

### React version

v18.3.1

### Description

I am using the [ComboButton](https://react.carbondesignsystem.com/?path=/story/components-combobutton--default), where in my case I have one MenuItem that is visible when 'Additional actions' button is clicked. This MenuButton can sometimes be disabled. If it is disabled, and I open the menu, and press any key, it throws the following exception:

Image

Image

Since focusableItems are 0, the nodeToFocus variable is undefined. [This can be fixed by adding an optional chain operator after nodeToFocus.](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Menu/Menu.tsx#L253)

### Reproduction/example

https://stackblitz.com/edit/github-alpse8qy?file=src%2FApp.jsx

### Steps to reproduce

- Use ComboButton component
- Use MenuItem component as secondary action
- Disable MenuItem component
- Click 'Additional actions' icon on the ComboButton
- Press any key from your keyboard

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by roshaniMali5**
Closes #19906 

{{short description}}

### Changelog

**Changed**

- Updated condition of focusableItems

#### Testing / Reviewing

- Go to the deployment URL.
- Click on the ComboButton.
- Click on the StackBlitz URL of the primary action.
- Inspect the browser.
- Try to select the disabled menu item.
- Reference(Ref) error should not appear in the console.

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by heloiselui — APPROVED** [review]
LGTM

File: packages/react/src/components/Menu/Menu.tsx [hunk 1]
```diff
@@ -225,6 +225,13 @@ const Menu = forwardRef<HTMLUListElement, MenuProps>(function Menu(
   }
 
   function focusItem(e?: React.KeyboardEvent<HTMLUListElement>) {
+    const items = focusableItems;
+
+    if (!items || items.length === 0) return;
+
+    const validItems = items.filter((item) => item?.ref?.current);
+    if (validItems.length === 0) return;
```
Comment (kennylam) [inline packages/react/src/components/Menu/Menu.tsx]: Just a thought, `focusableItems` can be used directly right?

```suggestion
    const validItems = focusableItems?.filter(item => item?.ref?.current);
    if (!validItems?.length) return;
```

**Review by tay1orjones — APPROVED** [review]

**Review by riddhybansal — APPROVED** [review]
Looks good to me !! You just need to run "yarn format" for all things to pass

**Review by kennylam — APPROVED** [review]
