### PR TITLE
fix(NumberInput): pass down event change value

### LINKED ISSUE #7457: NumberInput's `onChange` event does not include the value in `event.target.value` when the arrows are used.
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using the arrows on the `NumberInput` component, the `event`
parameter of `onChange` does not contain the actual value in `event.target.value`. Instead, the value is only in `event.imaginaryTarget.value`. However, when typing the number directly in the component, both `event.target.value` and `event.imaginaryTarget.value` contain the correct number I am typing.

> Is this issue related to a specific component?

Yes, `NumberInput`.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would like to see `event.target.value` contain the correct number when typing directly and also when using the up and down arrows.

> What browser are you working in?

Firefox and Chrome

> What version of the Carbon Design System are you using?

carbon-components.react 7.17.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

Instantiate a `NumberInput`, add the `onChange={(event) => {...}}` property and print the `event.target.value`. Then use the arrows in the component. The printed value will be sometimes undefined, and sometimes empty string. By typing in the component, the values of the printed `event.target.value` will be the expected ones.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #7457

When using keyboard to update number input, users can now access the updated value. We are now passing down the value as a second parameter in the onChange handler.

#### Changelog

- now passing down `value` in the keyboard onChange handler.
- also now passing it down in the onClick even if `useControlledStateWithValue` is false.

#### Testing
- view storybook example and check your console. Make sure you can the accessed value is the current value for the number input. Can test for click/keyboard updates.

### CODE REVIEW

File: packages/react/src/components/NumberInput/NumberInput-story.js [hunk 1]
```diff
@@ -20,6 +20,7 @@ import NumberInput from '../NumberInput';
 import { NumberInput as OGNumberInput } from './NumberInput';
 import NumberInputSkeleton from '../NumberInput/NumberInput.Skeleton';
 import mdx from './NumberInput.mdx';
+import { console } from 'window-or-global';
```
Comment (emyarod) [inline packages/react/src/components/NumberInput/NumberInput-story.js]:
```suggestion
```

File: packages/react/src/components/NumberInput/NumberInput-story.js [hunk 2]
```diff
@@ -88,6 +89,7 @@ export const Default = () => {
       label="NumberInput label"
       helperText="Optional helper text."
       invalidText="Number is not valid"
+      onChange={(e, something) => console.log(something)} //TO-DO: remove before merging
```
Comment (emyarod) [inline packages/react/src/components/NumberInput/NumberInput-story.js]:
```suggestion
```

FYI storybook already shows the event object in the actions tab so this is probably not needed for testing!

File: packages/react/src/components/NumberInput/NumberInput.js [hunk 3]
```diff
@@ -289,8 +289,8 @@ class NumberInput extends Component {
             onClick && onClick(evt, { value, direction });
             onChange && onChange(evt, { value, direction });
           } else {
-            onClick && onClick(evt, direction);
-            onChange && onChange(evt, direction);
+            onClick && onClick(evt, { value, direction });
+            onChange && onChange(evt, { value, direction });
```
Comment (emyarod) [inline packages/react/src/components/NumberInput/NumberInput.js]: I believe this would be a breaking change since the function signature is changing so you probably want to keep the existing signature and add to it instead of changing its shape

**Review by emyarod — COMMENTED** [review]
would you mind looking into the failing tests? I believe it's related to the function signature change being a breaking change

File: packages/react/src/components/NumberInput/NumberInput.js (hunk 3 above)
Comment (jnm2377) [reply packages/react/src/components/NumberInput/NumberInput.js]: ah, makes sense. Will update! 👍🏽

File: packages/react/src/components/NumberInput/NumberInput.js [hunk 4]
```diff
@@ -289,8 +289,8 @@ class NumberInput extends Component {
             onClick && onClick(evt, { value, direction });
             onChange && onChange(evt, { value, direction });
           } else {
-            onClick && onClick(evt, direction);
-            onChange && onChange(evt, direction);
+            onClick && onClick(evt, { value, direction });
```
Comment (joshblack) [inline packages/react/src/components/NumberInput/NumberInput.js:292]: This might be something that we'll need to wrap behind a feature flag since this will act as a breaking change for the `onClick` prop. In other words, this usage would break with this change:

```js
<NumberInput
  onChange={(event, direction) => {
    if (direction === 'down') {
      // ...
    }
  })}
/>
```

File: packages/react/src/components/NumberInput/NumberInput-story.js [hunk 5]
```diff
@@ -80,16 +80,7 @@ export default {
...
-    <NumberInput
-      min={0}
-      max={100}
-      value={50}
-      label="NumberInput label"
-      helperText="Optional helper text."
-      invalidText="Number is not valid"
-    />
-  );
+  return <NumberInput {...props()} />;
```
Comment (tw15egan) [inline packages/react/src/components/NumberInput/NumberInput-story.js]: Can we keep this as-is so that the default story can be copy / pasted? We can add in additional props to the component if we want to display them, but we're trying to only use the `...props()` syntax in the `Playground` example

File: packages/react/src/components/NumberInput/NumberInput-story.js [hunk 6]
```diff
@@ -88,6 +88,9 @@ export const Default = () => {
       label="NumberInput label"
       helperText="Optional helper text."
       invalidText="Number is not valid"
+      id="number-input-id"
+      onClick={action('onClick')}
+      onChange={action('onChange')}
```
Comment (emyarod) [inline packages/react/src/components/NumberInput/NumberInput-story.js]:
```suggestion
```

I think this is fine to remove if the aim is to keep the default story for easy copy pasting

File: packages/react/src/components/NumberInput/NumberInput.js [hunk 7]
```diff
@@ -257,7 +257,7 @@ class NumberInput extends Component {
           if (useControlledStateWithValue) {
             onChange(evt, { value });
           } else if (onChange) {
-            onChange(evt);
+            onChange(evt, { value: Number(value) });
```
Comment (emyarod) [inline packages/react/src/components/NumberInput/NumberInput.js]: should this return the same params as `handleArrowClick`?

File: packages/react/src/components/NumberInput/NumberInput-test.js [hunk 8]
```diff
@@ -466,13 +470,20 @@ describe('NumberInput', () => {
         downArrow.simulate('click');
         expect(onClick).toBeCalled();
         expect(onChange).toBeCalled();
-        expect(onClick).toHaveBeenCalledWith(expect.anything(), 'down');
+        expect(onClick).toHaveBeenCalledWith(
+          expect.anything(),
+          'down',
+          expect.anything()
```
Comment (emyarod) [inline packages/react/src/components/NumberInput/NumberInput-test.js]: since this is the value should we make this assertion more specific? (number and/or string)

**Review by joshblack — CHANGES_REQUESTED** [review]
This looks great! I think the one note is just what @emyarod had shared already, would be great for `onClick` and `onChange` to have the same signatures. For v10 I guess that could be:

```ts
onClick(evt, direction, value);
onChange(evt, direction, value);
```

But in v11 it would be:

```
onClick(evt, { direction, value });
onChange(evt, { direction, value });
```

?

File: packages/react/src/components/NumberInput/NumberInput-test.js (hunk 8 above)
Comment (jnm2377) [reply packages/react/src/components/NumberInput/NumberInput-test.js]: I think, ideally, yes @emyarod I'm not entirely sure why `direction` isn't passed down as a param here originally. I can add it if we want them to be the same. thoughts? @joshblack

Comment (emyarod) [reply packages/react/src/components/NumberInput/NumberInput-test.js]: was this meant to be a reply to a different review comment (https://github.com/carbon-design-system/carbon/pull/8243/files/18dba3ae39f5e3e6826c9b48536849a7c9dc47c7#r605683234)?

Comment (jnm2377) [reply packages/react/src/components/NumberInput/NumberInput-test.js]: oops, yes. 😓 @emyarod

File: packages/react/src/components/NumberInput/NumberInput.js (hunk 7 above)
Comment (emyarod) [reply packages/react/src/components/NumberInput/NumberInput.js]: @jnm2377 to answer [your question](https://github.com/carbon-design-system/carbon/pull/8243#discussion_r612565905) they should both return the same params

**Review by joshblack — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
