### PR TITLE
fix(Tag): adds various fixes for screen reader accessibility; adds AAT

### LINKED ISSUE #4427: AVT 3 - Tag w/ Filter React Component VO on macOS and iOS the Clear Filter button is not announced correctly.
## Environment
macOS Mojave version 10.14.6
Chrome Version Version 77.0.3865.90
Carbon React Version 7.7.1

## Description
1. Control-Option-Shift-Down Arrow to enter the Web area
2. Control-Option Right Arrow. VO announces the label and that it is a text element.
3. Tab to the "X". VO does not say anything.
4. Press Command-R to reload the page
5. Press Tab to the "X", VO announces, "Clear Filter, you are currently on a group. To interact with items in this group press Control-Option-Shift-Down Arrow."
Screen Shot 2019-10-22 at 2 15 40 PM

**Expected Result:**
After tabbing to the "X", VO should announce, "Clear Filter, button"

## Environment
iOS Version 13.1.3 with Safari and VO
Carbon React Version 7.7.1

## Description
Swipe Right to the "X". VO announces "Clear Filter Image."
**Expected Result:** 
AfterSwiping Right to the "X", VO should announce, "Clear Filter, button"

### PR DESCRIPTION
**Pull request by dakahn**
Closes #4427 

#### Changelog

**New**

- added button reset to styling
- added AAT tests for DAP and Axe
- added AAT tests for `aria-label`

**Changed**

- changed `<span role="button">` to simply `<button>`
- `title` prop is now used in `aria-label`
- updated Storybook story to be more clear

**Removed**

- removed `aria-label` on close icon
- removed `title` attribute on filtered Tag

#### Testing / Reviewing

Tester should verify:
A) component speaks properly in JAWS latest on Windows 10 in Chrome, Edge, and Firefox latest
B) component speaks properly in VoiceOver on Safari in macOS and iOS
C) #4427 is satisfied

### CODE REVIEW

File: packages/react/src/components/Tag/Tag-test.js [hunk 1]
```diff
@@ -10,10 +10,42 @@ import Tag from '../Tag';
...
+    });
+
+    it('should have no DAP violations', async () => {
+      const { container } = render(<Tag>This is not a tag</Tag>);
+      await expect(container).toHaveNoDAPViolations('Tag');
+    });
+  });
+
+  describe('with a screenreader', () => {
+    afterEach(cleanup);
```
Comment (joshblack) [inline packages/react/src/components/Tag/Tag-test.js]:
```suggestion
```

Should be covered by the `afterEach` above!

File: packages/react/src/components/Tag/Tag.js [hunk 2]
```diff
@@ -41,19 +41,21 @@ const Tag = ({
...
+      }
       {...other}>
       {children !== null && children !== undefined ? children : TYPES[type]}
-      <Close16 aria-label={title || 'Clear filter'} />
-    </span>
+      <Close16 />
+    </button>
   ) : (
-    <span className={tagClasses} {...other}>
+    <button className={tagClasses} {...other}>
```
Comment (joshblack) [inline packages/react/src/components/Tag/Tag.js:56]: Do the other tag types need to be a `button`?

File: packages/react/src/components/Tag/Tag.js [hunk 3]
```diff
@@ -41,19 +41,21 @@ const Tag = ({
...
-    <span
-      role="button"
+    <button
       className={tagClasses}
-      title={title || 'Clear filter'}
-      tabIndex="0" // eslint-disable-line jsx-a11y/no-noninteractive-tabindex
+      aria-label={
+        title !== undefined
+          ? `${title} ${children}`
+          : `Clear filter ${children}`
```
Comment (joshblack) [inline packages/react/src/components/Tag/Tag.js:49]: Is this so that we don't have a mismatch with the visual and accessible labels? Would there a preferred way to separate these or is this the ideal? Would we ever want something like:

```html
<span class="tag">
  <button>Clear</button>
  Text for tag
</span>
```

File: packages/react/src/components/Tag/Tag-test.js [hunk 4]
```diff
@@ -10,10 +10,42 @@ import Tag from '../Tag';
 import TagSkeleton from '../Tag/Tag.Skeleton';
 import { shallow } from 'enzyme';
 import { settings } from 'carbon-components';
+import { render, cleanup } from '@carbon/test-utils/react';
+import { afterEach } from 'jest-circus';
```
Comment (joshblack) [inline packages/react/src/components/Tag/Tag-test.js]:
```suggestion
```

Good ole VSCode most likely lol, `afterEach` should be a global from `jest` already 👍

**Review by joshblack — CHANGES_REQUESTED** [review]

File: packages/react/src/components/Tag/Tag-test.js [hunk 5]
```diff
@@ -10,10 +10,40 @@ import Tag from '../Tag';
...
+    });
+
+    it('should have no DAP violations', async () => {
+      const { container } = render(<Tag>This is not a tag</Tag>);
+      await expect(container).toHaveNoDAPViolations('Tag');
+    });
+  });
+
+  describe('with a screenreader', () => {
+
```
Comment (joshblack) [inline packages/react/src/components/Tag/Tag-test.js]:
```suggestion
```

File: packages/react/src/components/Tag/Tag.js (hunk 2 above)
Comment (dakahn) [reply packages/react/src/components/Tag/Tag.js:56]: Nah, I don't think so. They're non-interactable generally.

File: packages/react/src/components/Tag/Tag.js (hunk 3 above)
Comment (dakahn) [reply packages/react/src/components/Tag/Tag.js:49]: Well, since we don't _technically_ have a visual label for the X icon remove button this was just so it spoke clearly (as defined in the issue) in VO etc

Comment (dakahn) [reply packages/react/src/components/Tag/Tag.js:49]: title is -- not what we want here, but removing or not incorporating the prop is a breaking change.

File: packages/react/src/components/Tag/Tag-test.js [hunk 6]
```diff
@@ -10,10 +10,39 @@ import Tag from '../Tag';
...
+    });
+
+    it('should have no DAP violations', async () => {
+      const { container } = render(<Tag>This is not a tag</Tag>);
+      await expect(container).toHaveNoDAPViolations('Tag');
+    });
+  });
+
+  describe('with a screenreader', () => {
+    it('filtered variant should have appropriate aria-label', () => {
```
Comment (joshblack) [inline packages/react/src/components/Tag/Tag-test.js:37]:
```suggestion
    it('should have an accessible label when used as a filter', () => {
```

File: packages/react/src/components/Tag/Tag-test.js [hunk 7]
```diff
@@ -10,10 +10,39 @@ import Tag from '../Tag';
...
+      const { container } = render(<Tag filter>This is not a tag</Tag>);
+
+      const button = container.querySelector('[aria-label]');
+      expect(button).toBeInstanceOf(HTMLElement);
+
+      const ariaLabel = button.getAttribute('aria-label');
+      expect(ariaLabel).toBeDefined();
+
+      expect(ariaLabel).toEqual('Clear filter This is not a tag');
```
Comment (joshblack) [inline packages/react/src/components/Tag/Tag-test.js]: I'm a little torn on this assertion just because `Clear filter` could change to whatever language we want, would it make sense for us to have the check be that the accessibility label just includes `children` text? Something like:

```jsx
const children = 'tag content';
const { container } = render(<Tag filter>{children}</Tag>);

// No need to support both, but might be worthwhile so we could use either `aria-label` or `aria-labelledby`
// here. Optionally, could add a DOM helper like `getAccessibleLabel` or `getLabel` or something else that works
const button = container.querySelector('[aria-label], [aria-labelledby]');

const accessibilityLabel = button.getAttribute('aria-label') || button.getAttribute('aria-labelledby');

// This check would mirror our "Accessibility label must contain at least all of visible label"
// requirement
expect(accessibilityLabel).toEqual(
  expect.stringContaining(children)
);
```

**Review by joshblack — CHANGES_REQUESTED** [review]

**Review by abbeyhrt — APPROVED** [review]
I was only able to test on Safari and Chrome with VO since I don't have access to a Windows VM but it was good in those browsers!

File: packages/react/src/components/Tag/Tag-test.js (hunk 7 above)
Comment (dakahn) [reply packages/react/src/components/Tag/Tag-test.js]: Totally agree. And great thinking ahead 💯

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
@dakahn looks like it hit the following test failure:

image

**Comment by dakahn** [comment]
Yeah, looks like if the tested element contains text it needs to be wrapped in a `<main>` tag moving forward 👍

**Comment by asudoh** [comment]
@dakahn Is this PR ready for re-review? Thanks!
