### PR TITLE
 fix(breadcrumb): change breadcrumb to ordered list

### LINKED ISSUE #1608: Improving Breadcrumb accessibility
Please see the [APG pattern for Breadcrumb](http://w3c.github.io/aria-practices/examples/breadcrumb/index.html) and consider revising the [Carbon Breadcrumb](https://www.carbondesignsystem.com/experimental/breadcrumb/code) in the following ways (that are shown in the APG example):
- use a list (_ordered_ list is the most semantically correct, because the order of the links matters) to contain the links (use css to hide the bullets and make the list horizontal). The advantage of this is that a screen reader can tell the user how many links are in the breadcrumb (i.e. it counts the items in the list. It would not count the children of a div because there is no semantic reason to do so).
- add `aria-current="page"` to the final link in the breadcrumb, so that screen readers can tell the user that this is the breadcrumb's current page.

### PR DESCRIPTION
**Pull request by aledavila**
Closes #1608 

Changed breadcrumb to an ordered list and nested it in a nav element. 
Breadcrumb must be in a [landmark region](https://aat.w3ibm.mybluemix.net/token/dcaf9b63-6731-42ae-a97e-f1bb1f9966c2/f58137a1-1d9f-4676-97fd-170855fe35fe/latest///doc/w3/help/en-US/idhi_accessibility_check_g1157.html). 
 

#### Changelog

**New**

- nested in `nav`

**Changed**

- changed to `ol` and items to `li`

#### Testing / Reviewing

Make sure it is not broken and accessibility tests pass.

### CODE REVIEW

**Comment by aledavila** [comment]
@abbeyhrt per your question. The VO on the '/' only happens if you happen to click on it not if you are tabbing through them. The issue is that it is created using a psuedo element on breadcrumb item itself. This is part of the bigger issue to remove pseudo elements from our code base

File: packages/react/src/components/Breadcrumb/Breadcrumb.js [hunk 1]
```diff
@@ -25,8 +25,10 @@ const Breadcrumb = ({
   });
 
   return (
-    <nav className={className} {...rest}>
-      {children}
+    <nav aria-label="Breadcrumb">
+      <ol className={className} {...rest}>
```
Comment (dakahn) [inline packages/react/src/components/Breadcrumb/Breadcrumb.js]: Do we want `className` here as opposed to on the nav?

Comment (aledavila) [reply packages/react/src/components/Breadcrumb/Breadcrumb.js]: The class applies a flex (and nothing else) and since it needs to be on the parent of the children I left it there. I can apply a classname attribute if people need to target it for some reason. but the ol still needs to have the flex

Comment (dakahn) [reply packages/react/src/components/Breadcrumb/Breadcrumb.js]: Great! Thanks for clarifying.

**Comment by abbeyhrt** [comment]
@aledavila It's happening for me when I tab through them too but I checked the WAI-ARIA breadcrumb example and it does the same thing so I think it's actually okay! It might be a setting I have on VO.

**Review by abbeyhrt — APPROVED** [review]
This looks good to me! I checked VO as well and all seemed good 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @aledavila!

File: packages/react/src/components/Breadcrumb/Breadcrumb.js [hunk 2]
```diff
@@ -24,9 +25,15 @@ const Breadcrumb = ({
...
   });
 
+  const classNameNav = cx({
+    [customClassNameNav]: !!customClassNameNav,
+  });
+
   return (
-    <nav className={className} {...rest}>
-      {children}
+    <nav className={classNameNav} aria-label="Breadcrumb">
```
Comment (emyarod) [inline packages/react/src/components/Breadcrumb/Breadcrumb.js]:
```suggestion
    <nav className={customClassNameNav} aria-label="Breadcrumb">
```

we can just pass this in directly right?

**Review by joshblack — CHANGES_REQUESTED** [review]
I bet we don't need a class name for the nav, `className` as a prop really only relates to the top-level node anyway in the return so if it becomes a `nav` should be fine.

File: packages/react/src/components/Breadcrumb/Breadcrumb.js [hunk 3]
```diff
@@ -25,8 +25,10 @@ const Breadcrumb = ({
   });
 
   return (
-    <nav className={className} {...rest}>
-      {children}
+    <nav aria-label="Breadcrumb">
```
Comment (joshblack) [inline packages/react/src/components/Breadcrumb/Breadcrumb.js]:
```suggestion
    <nav className={className} aria-label="Breadcrumb" {...rest}>
```

Also, should `aria-label` be configurable?

File: packages/react/src/components/Breadcrumb/Breadcrumb.js (hunk 1 above)
Comment (joshblack) [inline packages/react/src/components/Breadcrumb/Breadcrumb.js]: We should be able to remove `{..rest}` from here and only specify `ol` class name here 👀

**Review by joshblack — CHANGES_REQUESTED** [review]

File: packages/react/src/components/Breadcrumb/Breadcrumb.js (hunk 3 above)
Comment (aledavila) [reply packages/react/src/components/Breadcrumb/Breadcrumb.js]: good catch

File: packages/react/src/components/Breadcrumb/Breadcrumb.js [hunk 4]
```diff
@@ -25,13 +26,20 @@ const Breadcrumb = ({
   });
 
   return (
-    <nav className={className} {...rest}>
-      {children}
+    <nav aria-label={ariaLabel ? ariaLabel : 'Breadcrumb'}>
```
Comment (emyarod) [inline packages/react/src/components/Breadcrumb/Breadcrumb.js]: if the aria label should be applied to `nav`, we should account for users that are directly setting the `aria-label` attribute since right now it looks like doing so would set `aria-label` on the `ol`

**Review by emyarod — COMMENTED** [review]
since it would be a new prop we might be able to avoid adding the `ariaLabel` prop altogether and just stick with handling the standard `aria-label` (unless we do want to continue with the camelcase aria attribute convention)

File: packages/react/src/components/Breadcrumb/Breadcrumb.js (hunk 4 above)
Comment (dakahn) [reply packages/react/src/components/Breadcrumb/Breadcrumb.js]: How can we account for them previously setting `aria-label` via `...rest`?

Comment (dakahn) [reply packages/react/src/components/Breadcrumb/Breadcrumb.js]: what does this look like ideally? do we have another component that we want to base this one?

**Review by dakahn — APPROVED** [review]

File: packages/react/src/components/Breadcrumb/Breadcrumb.js [hunk 5]
```diff
@@ -25,13 +25,18 @@ const Breadcrumb = ({
...
+      <ol className={className}>{children}</ol>
```
Comment (joshblack) [inline packages/react/src/components/Breadcrumb/Breadcrumb.js:30]: Should the `ol` have `customClassName` or should the `nav`? Would have assumed `nav` since it's the outermost element

Comment (aledavila) [reply packages/react/src/components/Breadcrumb/Breadcrumb.js]: Yea the nav would make more sense should we remove it from the ol? My question is since that targets the list specifically (ie flex)?

Comment (aledavila) [reply packages/react/src/components/Breadcrumb/Breadcrumb.js:30]: Yea that makes sense thanks for the explanation I've added it to the outer tag

File: packages/react/src/components/Breadcrumb/Breadcrumb.js (hunk 4 above)
Comment (emyarod) [reply packages/react/src/components/Breadcrumb/Breadcrumb.js]: it would look like `<Breadcrumb aria-label="label">` using the standard hyphenated attribute rather than `<Breadcrumb ariaLabel="label">`. you can see the standard attribute being targeted in the [`AriaLabelPropType` helper](https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/prop-types/AriaPropTypes.js)

File: packages/react/src/components/Breadcrumb/Breadcrumb.js [hunk 6]
```diff
@@ -13,25 +13,31 @@ import { settings } from 'carbon-components';
...
     </nav>
   );
 };
 
 Breadcrumb.propTypes = {
+  /**
+   * Specify the label for the control
+   */
+  ariaLabel: PropTypes.string,
```
Comment (joshblack) [inline packages/react/src/components/Breadcrumb/Breadcrumb.js]:
```suggestion
 'aria-label': PropTypes.string,
```

**Comment by aledavila** [comment]
@joshblack just needs your review

**Review by joshblack — APPROVED** [review]
