### PR TITLE
fix: pictogram rendering bugs

### LINKED ISSUE #4080: [pictograms-react] Rendering issues and cleanup
The `@carbon/pictograms/svg` shows that we have the appropriate raw assets, however they're not getting built properly by `@carbon/pictograms-react`.

In implementing the pictograms page of the website some issues were uncovered. 
https://cds-pictograms.now.sh/guidelines/iconography/pictograms/

1. Rendering issues
- Some icons have their path data replaced with a single white square:

    Screen Shot 2019-09-24 at 5 03 13 PM

    ```
    <g fill="none" stroke="#000" stroke-linejoin="round" stroke-miterlimit="10" stroke-width=".72"></g>
    ```
- Others are obstructed by a black path. 
    Screen Shot 2019-09-24 at 5 02 58 PM

    ```
    <path d="M0 0h48v48H0z"></path>
    ```

    Removing the path reveals the pictogram beneath:

    Screen Shot 2019-09-24 at 5 03 07 PM

2. Pictograms React components are given the displayName `Icon`

### PR DESCRIPTION
**Pull request by vpicone**
Closes #4080 

white boxes: We were both moving attributes to group elements while trying to take them away, this prevented us from adequately stripping/collapsing wrapper groups with more than one layer.

black boxes: we were only removing rectangles that matched the icon sizes: `['16', '20', '24', '32']`. Since we're not gonna need bespoke pictogram sizes, extending this again shouldn't be necessary.

Preview link: https://carbon-pictograms.now.sh/guidelines/iconography/pictograms

### CODE REVIEW

File: packages/icon-build-helpers/src/builders/vanilla/svgo.js [hunk 1]
```diff
@@ -171,9 +171,6 @@ const plugins = [
   {
     cleanupNumericValues: true,
   },
-  {
-    moveElemsAttrsToGroup: true,
```
Comment (joshblack) [inline packages/icon-build-helpers/src/builders/vanilla/svgo.js:175]: Random, what does this option do?

File: packages/icon-build-helpers/src/builders/vanilla/svgo.js [hunk 2]
```diff
@@ -44,7 +44,7 @@ const plugins = [
           }
         }
 
-        const sizes = ['16', '20', '24', '32'];
```
Comment (joshblack) [inline packages/icon-build-helpers/src/builders/vanilla/svgo.js:47]: Do we need to worry about any other artboard sizes? 🤔

**Review by joshblack — COMMENTED** [review]
Left some questions above!

File: packages/icon-build-helpers/src/builders/vanilla/svgo.js (hunk 1 above)
Comment (vpicone) [reply packages/icon-build-helpers/src/builders/vanilla/svgo.js:175]: Just added it to my note, it does the reverse of what the one below it is trying to do. I think this is why weren't able to properly strip the unused group tags.

**Comment by vpicone** [comment]
@joshblack you're too quick, I answered both in the PR comment

**Comment by vpicone** [comment]
@joshblack Also added a `Pictogram` component to the react build helpers so we don't get the `Icon` display name in dev tools. The components directory of icon-build helpers only had `Icon`, but needed some adjustments in `builder.js` to account for other components.

**Comment by vpicone** [comment]
There’s also 13 pictograms without categories. They’re under “undefined” at the preview link.

**Review by joshblack — COMMENTED** [review]
~Ignore this lol~

**Comment by joshblack** [comment]
@vpicone my preference would be to treat all of them as `Icon` components under the hood if we could, is there any way that we could consolidate things under `<Icon>`? The only worry being that we're duplicating logic between them so naturally would have to update both any time an update came in, with this being the case might make sense for them to just be the same component.

**Comment by vpicone** [comment]
@joshblack ah I was thrown off by the components directory. My thought was they’re going to have a different height/width behavior as well as a different display name would warrant them having distinct components.

**Comment by joshblack** [comment]
What would be the difference for `width`/`height`? Wasn't sure off the top of my head 👀

**Comment by vpicone** [comment]
If we had unified `size` prop to the icon component that would restrict sizes to the intended set. That wouldn’t be relevant/included in a pictogram component.

**Comment by joshblack** [comment]
@vpicone wouldn't the case be that we just wouldn't pass in those props, or they would be `undefined` or bespoke, for the pictogram use-case? In other words:

```jsx
// Icons
<Icon width={20} height={20} />
<Icon size="md" />

// Pictograms
<Icon width={64} height={48} />
<Icon />
```

**Comment by vpicone** [comment]
That size prop would be broken for pictograms. Using it would result in rendering smaller than they are intended to be shown. It also wouldn’t make sense having “lg” render smaller than the default size.

**Comment by joshblack** [comment]
@vpicone didn't mean for the prop values themselves to have any meaning really, just was trying to demonstrate that folks can pass them in or not and the underlying SVG would be fine. If we don't want folks to pass along a `size` prop then we don't forward that prop in the generated pictogram component 👍

**Comment by vpicone** [comment]
@joshblack but we’re still calling them icons? Should they have a different display name/prop types?

**Comment by joshblack** [comment]
@vpicone we could change the underlying name to `SVG` or something if you think it'd be less confusing, functionally these components seems to fill the same space so just was seeing if there was anything we could do to share the logic.

**Comment by chrisconnors-ibm** [comment]
@vpicone let me track down the `undefined`

**Comment by chrisconnors-ibm** [comment]
Across what attributes is search operating? It should be the same as icons scope and ordering.

**Comment by vpicone** [comment]
@chrisconnors-ibm it is, with the removal of subcategories.

**Comment by vpicone** [comment]
@joshblack what about the prop types? How would we differentiate that for icons vs pictograms

**Comment by joshblack** [comment]
@vpicone I had assumed with the generated components, what do you think? `Icon` was originally intended to render any SVG asset with the correct a11y props.

**Comment by vpicone** [comment]
@joshblack I think I just got confused with the component directory, I assumed it meant other components would go there not just `Icon`. I think yeah given `Icons` are a specific thing with different usage guidelines and props than `Pictograms`, we should rename the hardcoded `Icon` stuff to be something more inclusive of both components.

**Comment by chrisconnors-ibm** [comment]
(although I bet the two we're adding in #4041  in in are the only ones with aliases)

**Comment by vpicone** [comment]
@joshblack I removed the Pictogram component stuff, I think maybe I'm just misunderstanding how this abstraction is supposed to work. Opened #4090 to discuss further.

This now just fixes rendering bugs from the svgo optimization.

**Review by abbeyhrt — APPROVED** [review]

**Review by joshblack — APPROVED** [review]
