### PR TITLE
fix(tile): use layer in story

### LINKED ISSUE #11744: [Bug]: Tile with interactive element, text input background not showing
### Package

@carbon/react

### Browser

Chrome

### Package version

Latest

### React version

Latest

### Description

In Tile - expandable with interactive element demo, 
https://react.carbondesignsystem.com/?path=/story/components-tile--expandable-with-interactive
the text input inside expanded region is not showing correct field color. Expecting the field of input to be white, perhaps through using the correct layer or inline theming. 
image

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-tile--expandable-with-interactive

### Steps to reproduce

1. Go to https://react.carbondesignsystem.com/?path=/story/components-tile--expandable-with-interactive
2. Click on tile's chevron to expand the tile 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #11744 

#### Changelog

**Changed**

- update tile story to wrap input in a `Layer`

#### Testing / Reviewing

View the tile--expandable-with-interactive story, the input should have the proper background color across all 4 themes.

### CODE REVIEW

File: packages/react/src/components/Tile/Tile-story.js [hunk 1]
```diff
@@ -165,7 +166,9 @@ export const Expandable = () => (
     <TileBelowTheFoldContent>
       <div style={{ height: '400px' }}>
         Below the fold content here
-        <TextInput id="test2" invalidText="A valid value is required" />
+        <Layer>
+          <TextInput id="test2" invalidText="A valid value is required" />
+        </Layer>
```
Comment (tw15egan) [inline packages/react/src/components/Tile/Tile-story.js]: We'll need to add this to the `next` story as well, not currently showing correctly in the preview

**Review by tw15egan — CHANGES_REQUESTED** [review]

File: packages/react/src/components/Tile/Tile-story.js (hunk 1 above)
Comment (tay1orjones) [reply packages/react/src/components/Tile/Tile-story.js]: Thanks for the catch! Updated

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by sstrubberg — APPROVED** [review]
