### PR TITLE
fix(modal): find primary focus element for selectorPrimaryFocus

### LINKED ISSUE #4088: Modal: `selectorPrimaryFocus` doesn't work, when used together with `focusTrap`
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

I want to focus specific element by using provided `selectorPrimaryFocus`. But it doesn't work if I use `focusTrap` as well.

> Is this issue related to a specific component?

Modal

> What did you expect to happen?

custom element should be focused

> What happened instead?

close button was focused

> What would you like to see changed?

```javascript
focusTrapOptions={{ initialFocus: this.initialFocus }}>
```
`initialFocus` from focus trap library doesn't have any arguments, which makes `this.initialFocus` to skip handling `selectorPrimaryFocus` (line#223)

> What browser are you working in?

any browser

> What version of the Carbon Design System are you using?

latest

## Steps to reproduce the issue

1. https://codesandbox.io/s/codesandbox-lwl17
2. input will be focused (_might need to refresh inside code sandbox to see input inside modal focused_)
3. change `focusTrap` to be `true` and refresh
4. close button will be focused

## Additional information

not related, but you have different refs assigned to the same variable:
* line#313 `ref={this.button}`
* line#362 `inputref={this.button}`

### PR DESCRIPTION
**Pull request by metonym**
Closes #4088 

In the `initialFocus` method, `selectorPrimaryFocus` does not return a node for `focus-trap-react` to focus because `focusContainerElement` is undefined.

#### Changelog

**New**

- added 'Trap Focus' example to Modal story

**Changed**

- find the primary focus node if `focusContainerElement` is falsy and `focusTrap` is true

**Removed**

- removed old logic to return the `primaryFocusElement`

#### Testing / Reviewing

Check the added 'Trap Focus' example in the Modal story. The example is a near verbatim reproduction of that provided in #4088 .

The second `TextInput` should be focused.

### CODE REVIEW

File: packages/react/src/components/Modal/Modal.js [hunk 1]
```diff
@@ -220,12 +220,12 @@ export default class Modal extends Component {
   }
 
   initialFocus = focusContainerElement => {
-    const primaryFocusElement = focusContainerElement
-      ? focusContainerElement.querySelector(this.props.selectorPrimaryFocus)
-      : null;
-    if (primaryFocusElement) {
-      return primaryFocusElement;
+    if (!focusContainerElement && this.props.focusTrap) {
```
Comment (asudoh) [inline packages/react/src/components/Modal/Modal.js]: Do you want to assign `this.innerModal.current` to `focusContainerElement` if `focusContainerElement` isn't there, given missing `focusContainerElement` seems your concern? This function is called for `this.props.focusTrap === false` scenario, so we cannot re-write this function for `this.props.focusTrap === true` scenario. Thanks!

Comment (metonym) [reply packages/react/src/components/Modal/Modal.js]: Changed in https://github.com/carbon-design-system/carbon/pull/4172/commits/90c86911f1be36421b4b41b90cd478e26111d61e

Comment (asudoh) [reply packages/react/src/components/Modal/Modal.js]: Would you want to keep NPE guard for `containerElement` just in case? It was originally for before-mount/after-unmount scenarios (though there may not be the case).

Comment (metonym) [reply packages/react/src/components/Modal/Modal.js]: Added the guard back in https://github.com/carbon-design-system/carbon/pull/4172/commits/742ebde8eccedeb31c8a2c44ec9fa7301417c993

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @metonym for all the updates!

**Review by aledavila — APPROVED** [review]

**Comment by elbrus** [comment]
Hi,
I have a bit related use case and I wonder what you guys think.

Let's say there is a form displayed inside Modal and one of the fields (like TextInput) in the form is auto focused.
Right now once Modal is opened focus is moved from the field to a close button. A way to avoid it would be to specify `selectorPrimaryFocus` with a field, which needs focus.
But I wonder is it really a proper way, how it should be handled? Maybe it would be better, if Modal would check is there anything focused inside, and in case it isn't proceed with a current behavior?

**Comment by asudoh** [comment]
Hi 👋 would you want to create a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox to better explain your use case?

**Comment by elbrus** [comment]
> Hi 👋 would you want to create a reduced case based on https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox to better explain your use case?

here it is: https://codesandbox.io/embed/codesandbox-rs2ue
open modal > close button focused, even if autoFocus is specified on TextInput
the only way to avoid it is to use selectorPrimaryFocus (uncomment it in example)

my question: is it the right way, how Modal should act?

**Comment by asudoh** [comment]
I see; `autofocus` is for setting keyboard focus on a particular element when page load. Given our modal is not a "page", it won't be in effect.
