### PR TITLE
fix(Button): remove deprecated prop from default props

### LINKED ISSUE #3413: OOTB ComposedModal reporting warning about deprecated `small` prop in Button component
## What package(s) are you using?

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Using the `ComposedModal` component, there's a warning emitted to the console about using the deprecated `small` prop on the `Button` component. No where am I specify `small` on a `Button` instance, so it looks like the `ComposedModal` is using the deprecated prop internally somewhere.

> Is this issue related to a specific component?

`ComposedModal`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect to not get warnings about deprecation from OOTB components internally.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components: 10.4.1
carbon-components-react: 7.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud Identity

## Steps to reproduce the issue
See code sandbox below

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

https://codesandbox.io/s/codesandbox-9wt7n

## Additional information

Here's the console warning:
>Warning: 
The prop `small` for Button has been deprecated in favor of `size`. Please use `size="small"` instead.

### LINKED ISSUE #3427: [Button]: Default value set for deprecated property
## What package(s) are you using?

- [x] `carbon-components` `10.4.1`
- [x] `carbon-components-react` `7.4.1`

## Detailed description

The console warns about deprecated `small` property for Buttons.
This is caused by the default setting of the property inside the Button component.

https://github.com/carbon-design-system/carbon/blob/9d0e8284f96f3e63fc2432ea7213049d09b550ad/packages/react/src/components/Button/Button.js#L208

## Steps to reproduce the issue

1. Use React carbon component Button.
2. See the console.log

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3413 
Closes #3427

related: #2719

This PR removes a deprecated prop from the default props defined for `<Button>`

#### Changelog

**Removed**

- deprecated `small` prop from `Button.defaultProps`

#### Testing / Reviewing

Ensure that no deprecation warnings are emitted for components that depend on `<Button>`

### CODE REVIEW

**Review by joshblack — COMMENTED** [review]
When was this prop deprecated? Was it in v9 or in v10?

**Comment by lovemecomputer** [comment]
@joshblack when we added a field height variant, we ended up with 3 height variants: `default`, `field`, and `small`. so the boolean for small was deprecated in favor of the prop `size=<default/field/small>`. it was near the end of our work on v10 release

**Review by lovemecomputer — DISMISSED** [review]

**Comment by joshblack** [comment]
Got it, so was deprecated in v9 then? Just wanted to make sure we weren't removing a prop that folks may be using because of accidental spread onto DOM nodes.

**Comment by lovemecomputer** [comment]
i was confused and dismissed my approval—this prop was deprecated in v10 and should be removed in v11

File: packages/react/src/components/Button/Button.js [hunk 1]
```diff
@@ -205,7 +205,6 @@ Button.defaultProps = {
   tabIndex: 0,
   type: 'button',
   disabled: false,
-  small: false,
```
Comment (joshblack) [inline packages/react/src/components/Button/Button.js:208]: Maybe we could add the deprecate helper here and just make sure it doesn't get spread onto any underlying nodes since this was deprecated in v9?

Comment (emyarod) [reply packages/react/src/components/Button/Button.js:208]: but do we still need the default value if we've already removed `.isRequired` for this prop?

Comment (joshblack) [reply packages/react/src/components/Button/Button.js:208]: Totally fair!

**Review by joshblack — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!
