### PR TITLE
feat(TooltipDefinition): port vanilla WCAG 2.1 fixes

### LINKED ISSUE #3420: TooltipDefinition no longer supports Nodes for tooltipText prop
TooltipDefinition no longer supports Nodes for tooltipText prop

## What package(s) are you using?

- [X] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The `TooltipDefinition` component no longer supports Node objects for the `tooltipText` prop. It now only supports strings. This is a breaking change within major version 10. It came in here: https://github.com/carbon-design-system/carbon/commit/2571ed5051a45a335796365fe09f74e419d07192#diff-916183444c3885c676548407d734df75R74

We were using the Node structure to allow multiple DOM nodes within the tooltip, so we could apply alignment and styling to the text. This is no longer possible with only being able to supply strings.

For example, this is how we used TooltipDefinition's support of Node objects in the `tooltipText` prop previously:
image

Note the bold formatting, and alignment of the tooltip text content.

> Is this issue related to a specific component?

`TooltipDefinition`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected continued support of `PropTypes.Node` for the `tooltipText` prop.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components: 10.4.1
carbon-components-react: 7.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud Identity

## Steps to reproduce the issue

Render a `TooltipDefinition` using a Node object for the `tooltipText` prop instead of a string.
> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

### LINKED ISSUE #3813: [React Definition Tooltip] Carry over a11y fixes from Vanilla
updates to definition tooltip were added to Vanilla and need carried over to react
https://github.com/carbon-design-system/carbon/pull/3151

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3813
Closes #3420

This PR ports the changes from #3151 to the React package and restores support for child nodes (#3420)

#### Testing / Reviewing

Ensure the definition tooltip appears and functions properly

### CODE REVIEW

File: packages/react/src/components/TooltipDefinition/TooltipDefinition.js [hunk 1]
```diff
@@ -70,8 +78,9 @@ TooltipDefinition.propTypes = {
 
   /**
    * Provide the text that will be displayed in the tooltip when it is rendered.
+   * TODO: rename this prop (will be a breaking change)
    */
-  tooltipText: PropTypes.string.isRequired,
+  tooltipText: PropTypes.node.isRequired,
```
Comment (joshblack) [inline packages/react/src/components/TooltipDefinition/TooltipDefinition.js:83]: Should this be `PropTypes.node`? Would have assumed tooltips can only be a string, especially if this is wrapped in `bx--assistive-text`

**Review by joshblack — CHANGES_REQUESTED** [review]
Looks great, just one questions 👍

File: packages/react/src/components/TooltipDefinition/TooltipDefinition.js (hunk 1 above)
Comment (emyarod) [reply packages/react/src/components/TooltipDefinition/TooltipDefinition.js:83]: this is reverting a breaking change that came within v10 (#3420)

**Review by joshblack — APPROVED** [review]

File: packages/react/src/components/TooltipDefinition/TooltipDefinition.js (hunk 1 above)
Comment (elizabethsjudd) [reply packages/react/src/components/TooltipDefinition/TooltipDefinition.js:83]: @emyarod is there a way to add a deprecation warning here since users should be switching from to the interactive tooltip if they want node children?

**Review by dakahn — APPROVED** [review]

File: packages/react/src/components/TooltipDefinition/TooltipDefinition.js (hunk 1 above)
Comment (emyarod) [reply packages/react/src/components/TooltipDefinition/TooltipDefinition.js:83]: @elizabethsjudd yeah I suppose we could add a prop types validator, will have to look more into that

**Review by elizabethsjudd — APPROVED** [review]

**Review by shixiedesign — APPROVED** [review]
From what I understand, this PR should not affect visuals & behaviors of this component. I verified those are consistent as before. Thank you!
