### PR TITLE
fix(select): use aria-describedby and visually hide label

### LINKED ISSUE #20649: [a11y]: (WebComponents) CDS-Select - There is no way to visually hide the label while maintaining accesiblity
### Package

@carbon/web-components

### Browser

Chrome

### Operating System

Windows

### Package version

2.27.1

### React version

N/A

### Automated testing tool and ruleset

Chrome Lighthouse

### Assistive technology

_No response_

### Description

When `label-text` is provided, and `hide-label` is true. The following Lighthouse error is reported:

 `Select elements do not have associated label elements.`

There doesn't seem to be any workaround to apply an aria-label to the html select component, which forces the user to render a label or have this error.

Possible solution: When hide-label is true, use label-text as aria-label (if provided).

### WCAG 2.1 Violation

WCAG 2.1 (A), WCAG 2.0 (A), WCAG 2.2 (A), Section 508, Trusted Tester, EN 301 549

### Reproduction/example

https://stackblitz.com/edit/github-xfkunee4-qfyqlqf8?file=index.html

### Steps to reproduce

Set `label-text` to 'Any value'
Set `hide-label` tor true

Scan component

### Suggested Severity

None

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by olihf-dematic**
Closes #20649

Fixes the HTML select element in CDS-Select never having a defined `aria-label` even when `label-text` is provided

### Changelog

**New**

- `select`: Apply `aria-label` when `hide-label` is true, and `label-text` is defined

**Changed**

- N/A

**Removed**

- N/A

#### Testing / Reviewing

- On the storybook playground for CDS-Select (:
 - Ensure `label-text` is defined
 - Set `hide-label` to true
 - Verify an aria-label, with content `label-text` is applied to the html select element

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- ~[ ] Updated documentation and storybook examples~
- ~[ ] Wrote passing tests that cover this change~
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by olihf-dematic** [comment]
I have read the DCO document and I hereby sign the DCO.

File: packages/web-components/src/components/select/select.ts [hunk 1]
```diff
@@ -448,6 +448,7 @@ class CDSSelect extends FormMixin(LitElement) {
         id="input"
         class="${inputClasses}"
         ?disabled="${disabled}"
+        aria-label="${ifDefined(hideLabel ? labelText : undefined)}"
```
Comment (ariellalgilmore) [inline packages/web-components/src/components/select/select.ts]: Thanks for the submission! Ideally we would try to make sure the markup is the same as the [react select](https://react.carbondesignsystem.com/?path=/story/components-select--default&args=hideLabel:!true). Looks like instead of removing the `label` we should instead add a `cds--visually-hidden` class: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Select/Select.tsx#L217. and then looks like the `aria-describedby` should be pointing to the helper-text. With these updates then I don't think we need to add the `aria-label`

**Review by ariellalgilmore — CHANGES_REQUESTED** [review]

File: packages/web-components/src/components/select/select.ts (hunk 1 above)
Comment (olihf-dematic) [reply packages/web-components/src/components/select/select.ts]: Hi, this makes sense. I've updated the PR to use the `cds--visually-hidden` class, and removed the `aria-label`

For the `aria-describedby` I've updated this to match the react version pointing to `helper-text`, but giving priority to `error-text`. I also noted that the `aria-describedby` was not actually linked to anything, as the `error-text` id wasn't applied to anything. So I've added these ids to the helper and error-text. These don't exactly match the react version, due to shadow dom encapsulation meaning they only need to be unique to that shadow dom.

**Review by ariellalgilmore — APPROVED** [review]
Thank you for the updates! this looks great!

**Review by Gururajj77 — APPROVED** [review]
LGTM
