### PR TITLE
fix: some regressions, ai-label, combo-box

### LINKED ISSUE #179: [Bug]: AI tooltip closes when link or button is clicked
### Browser

_No response_

### Package version

0.3.2

### React version (if applicable)

18.3.1

### Description

When embedded link/button inside AI tooltip is clicked, the pop-up closes without triggering the link/button.

Link and buttons should be clickable and keyboard accessible inside the AI tooltip.

See https://ibm-systems-z.slack.com/archives/C07RV4MPJNL/p1741800795808009 for more details.

### Reproduction/example

When embedded link/button inside AI tooltip is clicked, the pop-up closes without triggering the link/button.

### Steps to reproduce

1.  Use writeableElements.aiTooltipAfterDescriptionElement to insert a carbon link or button in the AI tooltip
2. Click the link or button then observe popup closes right away

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon-ai-chat/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by devadula-nandan**
Closes https://github.com/carbon-design-system/carbon-ai-chat/issues/179

This pr re-works on #20094 fixing a regression on toggletip

And completely reverts #19274 as it was observed to bring focus issues.

by making some reverting changes from the associated pr's, i was able to restore the below behaviors.

toggle tip focus out must close it as per [docs](https://carbondesignsystem.com/components/toggletip/accessibility/#keyboard-interactions)
focus loss issue on ai-label upon interaction.

the ideal solution imo for #19274 is to handle ai-lable interaction on cds-dropdown, to check if the target is an instance of ai-label and call the necessary methods. and the dropdown inheritance on combo-box and multi-select must automatically fix them by delegating the parent behaviors after component specific behaviors in the respective components.
i have made some exploration on this [here](https://github.com/carbon-design-system/carbon/pull/20566)
everything works fine except multi select which is updating twice for some reason and due to 2 updates the ai-label closes. dropdown and combo-box works as expected

### Changelog

**Changed**

- refactors

**Removed**

- did some clean up

#### Testing / Reviewing

all the acceptance criteria must be met on the 2 mentioned issues.
a test story was added, and awaiting for a first pass, to let the team verify.

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/web-components/src/components/ai-label/ai-label.ts [hunk 1]
```diff
@@ -74,59 +74,12 @@ class CDSAILabel extends CDSToggleTip {
...
-      this.open = false;
-      this.requestUpdate();
-    }
-  };
-
   protected _handleClick = () => {
-    const activeElement = document.activeElement;
-    if (activeElement instanceof HTMLElement) {
-      activeElement.blur();
-    }
```
Comment (devadula-nandan) [inline packages/web-components/src/components/ai-label/ai-label.ts:110]: these lines bought some focus issues, which messed up a11y

modified a test. guard railing this behavior

https://github.com/user-attachments/assets/c9a532b5-14d3-4134-a693-23f1fd293669

File: packages/web-components/src/components/ai-label/ai-label.ts [hunk 2]
```diff
@@ -74,59 +74,12 @@ class CDSAILabel extends CDSToggleTip {
...
-  protected _handleAIKeydown = (event: KeyboardEvent) => {
-    if (event.key === 'Enter' || event.key === ' ' || event.key === 'Escape') {
-      event.stopPropagation();
-    }
-
-    if (event.key === 'Escape') {
-      event.preventDefault();
-      this.open = false;
-      this.requestUpdate();
+      super._handleClick();
```
Comment (devadula-nandan) [inline packages/web-components/src/components/ai-label/ai-label.ts:82]: we don't have to write duplicate handlers which may run twice. just use super.methods() from the inherited class as per OOPS

File: packages/web-components/src/components/ai-label/ai-label.ts [hunk 3]
```diff
@@ -173,8 +125,7 @@ class CDSAILabel extends CDSToggleTip {
               ?autoalign=${autoalign}
               kind="ghost"
               size="sm"
-              @click="${this._handleClick}"
-              @keydown="${this._handleAIKeydown}">
```
Comment (devadula-nandan) [inline packages/web-components/src/components/ai-label/ai-label.ts:177]: `@keydown` already inherited from toggletip

File: packages/web-components/src/components/dropdown/dropdown.ts [hunk 4]
```diff
@@ -199,7 +200,10 @@ class CDSDropdown extends ValidityMixin(
     if (!this.open) {
       switch (action) {
         case DROPDOWN_KEYBOARD_ACTION.TRIGGERING:
-          this._handleUserInitiatedToggle(true);
+          // Only toggle if the event target is not a CDSAILabel
+          if (!(event.target instanceof CDSAILabel)) {
+            this._handleUserInitiatedToggle(true);
+          }
```
Comment (devadula-nandan) [inline packages/web-components/src/components/dropdown/dropdown.ts]: this fixes https://github.com/carbon-design-system/carbon/issues/19274#issuecomment-2999740366

File: packages/web-components/src/components/toggle-tip/toggletip.ts [hunk 5]
```diff
@@ -85,9 +85,9 @@ class CDSToggletip extends HostListenerMixin(FocusMixin(LitElement)) {
       : this.removeAttribute('has-actions');
   }
 
-  protected _handleClick = () => {
+  protected _handleClick() {
```
Comment (devadula-nandan) [inline packages/web-components/src/components/toggle-tip/toggletip.ts:88]: changed to allow calling super.methods() in the inheriting class

File: packages/web-components/src/components/toggle-tip/toggletip.ts [hunk 6]
```diff
@@ -110,13 +110,33 @@ class CDSToggletip extends HostListenerMixin(FocusMixin(LitElement)) {
...
   protected _handleFocusOut(event: FocusEvent) {
-    const path = event.composedPath();
-    if (path.includes(this as unknown as EventTarget)) {
+    if (this.contains(event.relatedTarget as Node)) {
+      return;
+    }
+
+    if (this._deepShadowContains(this, event.relatedTarget)) {
       return;
     }
```
Comment (devadula-nandan) [inline packages/web-components/src/components/toggle-tip/toggletip.ts:119]: this fixes https://github.com/carbon-design-system/carbon/pull/20094#issuecomment-3301841899

we verify 2 things here

1) verifies if `relatedTarget` is a simple nested child

2) verifies if `relatedTarget` is a child inside deeply nested shadow boundaries

in these 2 cases, we don't want to close, and we return

File: packages/web-components/src/components/toggle-tip/toggletip.ts [hunk 7]
```diff
@@ -110,13 +110,33 @@ class CDSToggletip extends HostListenerMixin(FocusMixin(LitElement)) {
...
+
+    return this._deepShadowContains(
+      root,
+      (el as HTMLElement).assignedSlot ||
+        el.parentNode ||
+        (el.getRootNode() as ShadowRoot).host ||
+        null
+    );
+  }
+
```
Comment (devadula-nandan) [inline packages/web-components/src/components/toggle-tip/toggletip.ts:139]: a recursive function which takes provided root, and element, and returns true if the element is found in any one of the nested shadow boundary

**Review by devadula-nandan — COMMENTED** [review]
added few comments explaining the changes

**Comment by devadula-nandan** [comment]
and finally this build fixes our app

https://github.com/user-attachments/assets/6935bdb8-65a7-4eca-afc5-da6f292fcc56

**Review by tay1orjones — APPROVED** [review]
Stellar ✨🙌  Thanks for diving into these. LGTM

**Comment by devadula-nandan** [comment]
i have removed the test story, and is ready for a second pass

**Review by maradwan26 — APPROVED** [review]
