### PR TITLE
fix(OverflowMenu): check for custom closeMenu method

### LINKED ISSUE #6412: If I use Dropddown or ComboBox in TableToolbarMenu, the popup menu will be closed upon selecting an option
## What package(s) are you using?

- [x] `@carbon/icons-react - 10.13.0`
- [x] `carbon-components - 10.15.0`
- [x] `carbon-components-react - 7.15.0`

## Detailed description

> Describe in detail the issue you're having.

Basically whenever I select an option in `Dropdown` or `Combobox`, the `TableToolbarMenu` popup will be closed. This behavior is not seen with `Select`

> What did you expect to happen? What happened instead? What would you like to
> see changed?  
  
I expect the behavior to be the same with `Select`  
  
> What browser are you working in?   
  
Chrome

> What version of the Carbon Design System are you using?  
  
10.15.0

> Please create a reduced test case in CodeSandbox
>
> - React:
>   https://codesandbox.io/s/carbon-components-react-7uqsd?file=/src/index.js

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6412

This PR prevents custom `closeMenu` methods from being overwritten by the default method in order to support a wider range of interactions on the overflow menu

#### Changelog

**Changed**

- check for OverflowMenuItem `closeMenu` before cloning the element and assigning a default value for the function

#### Testing / Reviewing

confirm that adding a custom `closeMenu` method on an `OverflowMenuItem` will not be overwritten

### CODE REVIEW

File: packages/react/src/components/OverflowMenu/OverflowMenu.js [hunk 1]
```diff
@@ -494,7 +494,7 @@ class OverflowMenu extends Component {
     const childrenWithProps = React.Children.toArray(children).map(
       (child, index) =>
         React.cloneElement(child, {
-          closeMenu: this.closeMenu,
+          closeMenu: child.props.closeMenu || this.closeMenu,
```
Comment (joshblack) [inline packages/react/src/components/OverflowMenu/OverflowMenu.js:497]: Would we need to run both functions instead of deferring to a given `child` `closeMenu`? Seems like `this.closeMenu` has some state logic that we want to run but I might be misunderstanding 👀

Comment (emyarod) [reply packages/react/src/components/OverflowMenu/OverflowMenu.js:497]: the main intention is to allow a function that is different from or replaces the default `closeMenu` (without expanding the component API). if the user still wants to run the existing logic they can use the existing `onClose` prop. maybe it would be more preferable to just add a boolean prop that controls whether or not the menu will close on selection of an item?

**Review by joshblack — APPROVED** [review]

**Review by aledavila — APPROVED** [review]
