### PR TITLE
fix(checkbox/datatable): fixed checkbox `checked` state regression

### LINKED ISSUE #19563: [Bug]: WC Checkbox regression on checked state
### Package

@carbon/web-components

### Browser

Chrome

### Package version

v2.30.0

### React version

_No response_

### Description

the checkbox doesn't seem to update its visual appearance based on checked state, which used to happen in version 2.27.1.
as per the comment 
https://github.com/carbon-design-system/tanstack-carbon/pull/43#issuecomment-2934374275

in the provided stackblitz, we can see the checkbox doesn't seem to update in version 2.30.0, but updates on 2.27.1

### Reproduction/example

provided in steps to reproduce

### Steps to reproduce

open the examples in both versions
check the check box and click on apply filters
clear the filters and observe the checkbox works as expected in previous version.

v2.27.1 stackblitz (works as expected)
https://stackblitz.com/edit/github-cjs27zds-abtdx5js?file=package.json

v2.30.0 stackblitz (doesn't work as expected)
https://stackblitz.com/edit/github-cjs27zds?file=package.json

also seen in storybook as per this comment https://github.com/carbon-design-system/carbon/issues/18504#issuecomment-2940565582

https://github.com/user-attachments/assets/7baee0ff-4caf-439b-9c71-a2d9528d9ef6

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### LINKED ISSUE #19820: selection variant of the data table acts wonky and it affects the batch action toolbar selected counter.

### LINKED ISSUE #20058: [Bug]: checkboxes in data table not respecting select all state
### Package

@carbon/web-components

### Browser

_No response_

### Package version

2.34.1

### React version

_No response_

### Description

Checkboxes in rows are not responding to changes from the select all toggle in the table header, and ignoring the true value for the [checked] input after you interact with them atleast once.

This recording is from the web components story book:
https://web-components.carbondesignsystem.com/?path=/story/components-datatable-selection--default

https://github.com/user-attachments/assets/4b8bf498-bf9e-4486-a3a3-5e7d840a8bc6

### Reproduction/example

https://stackblitz.com/edit/github-ns5ma9yw?file=package.json

### Steps to reproduce

- Select any table row
- Select all rows from table header
- Deselect all rows from table header

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by maradwan26**
Closes #19563
Closes #19820
Closes #20058 

There was a regression problem with the `checkbox` component's `checked` state not updating properly in many use cases, including the selection feature in `data-table`. This PR fixes this issue.

### Changelog

**Changed**

- Changed `?checked` to `.checked` in the rendering of `checkbox.ts` since the `?` would only conditionally render the `checked` attribute which was the cause of this issue.
- Modified test cases to account for this new change

#### Testing / Reviewing

- Go to `DataTable/Selection/Default` in the WC deploy preview
- Selections and Select All should work properly
- Go to `DataTable/Batch Actions/Default` in the WC deploy preview
- Selections and Select All should work properly
- There should no regression.

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [X] Reviewed every line of the diff
- ~~[ ] Updated documentation and storybook examples~~
- [X] Wrote passing tests that cover this change
- [X] Addressed any impact on accessibility (a11y)
- [X] Tested for cross-browser consistency
- [X] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by riddhybansal — APPROVED** [review]
LGTM 💯

File: packages/web-components/src/components/checkbox/checkbox.ts [hunk 1]
```diff
@@ -263,6 +265,7 @@ class CDSCheckbox extends FocusMixin(FormMixin(LitElement)) {
         part="input"
         class="${`${prefix}--checkbox`}"
         aria-readonly="${String(Boolean(readonly))}"
+        .checked="${checked}"
         ?checked="${checked}"
```
Comment (kennylam) [inline packages/web-components/src/components/checkbox/checkbox.ts]: `?checked="${checked}"` should be removed right?

Comment (maradwan26) [reply packages/web-components/src/components/checkbox/checkbox.ts]: @kennylam 

`?checked="${checked}"` was needed to pass these two test cases: [Test 1](https://github.com/carbon-design-system/carbon/blob/main/packages/web-components/src/components/checkbox/__tests__/checkbox-test.js#L32-L41),  [Test 2](https://github.com/carbon-design-system/carbon/blob/main/packages/web-components/src/components/checkbox/__tests__/checkbox-test.js#L51-L63). This was because using `?checked` passes the attribute down to the `<input>` while `.checked` doesn't and just keeps it in `cds-checkbox`. However, I don't think the functionality of the component is affected if `?checked` is kept or removed, its just the test cases.

So the two options are either to keep `?checked` along with `.checked` like how it is right now, or remove `?checked` and change the test-cases so that the CI passes.

What do you think?

Comment (2nikhiltom) [reply packages/web-components/src/components/checkbox/checkbox.ts]: I think in this case we could modify the test in this case

**Review by 2nikhiltom — APPROVED** [review]

**Comment by maradwan26** [comment]
@2nikhiltom @kennylam 

`?checked` has been removed and the test cases were modified so that the CI passes, everything should still work
