### PR TITLE
fix: focus and onClick issue on HeaderMenuItem

### LINKED ISSUE #19401: [Bug]: onClick doesn't work on a `HeaderMenu` 's sub item, in safari browser.
### Package

@carbon/react

### Browser

Safari

### Package version

v11

### React version

v1.81.0

### Description

the `onClick` handler isn't getting triggered when the `HeaderMenuItem` is a sub item of `HeaderMenu`, and this problem only occurs in safari browser, where as the `onClick` works fine in chrome and edge browser.  

### Reproduction/example

https://stackblitz.com/edit/github-idy2xfcw-sujb6u1f?file=src%2FApp.tsx,package.json

### Steps to reproduce

1. Open the stackblitz reproduction link in safari browser.
2. Try to click on the "Test" inside the example sub-menu.
3. Notice that, an alert is supposed to pop up.
4. Try the same steps in chrome, the alert comes up.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### LINKED ISSUE #19436: [Bug]: onClick doesn't work on a HeaderMenuItem if there is no href prop
### Package

@carbon/react

### Browser

Firefox, Safari, Chrome

### Package version

1.81.0+

### React version

v18.3.1 (also seen on v19)

### Description

The`onClick` handler is not getting triggered for a `HeaderMenuItem` if it does not have an `href` prop. This only happens from `@carbon/react` `1.81.0` onwards, and broke our existing usage which should trigger a function to pop up a dialog and not change the page.

(Example adapted from https://github.com/carbon-design-system/carbon/issues/19401 which is similar but Safari-specific, and _did_ have `href` prop I took out of my reproduction example)

A workaround has been to provide an `href` prop, but as we don't want the page to reload/change, we've had to use `preventDefault()` in the `onClick` function.

### Reproduction/example

https://stackblitz.com/edit/github-idy2xfcw-flabvycf?file=package.json

### Steps to reproduce

1. Open the stackblitz reproduction link in any browser
2. Try to click on the "Test" button inside the example submenu
3. Nothing happens, but an alert should pop up
4. Change `@carbon/react` in `package.json` down to `1.80.0` and rerun
5. Try the "Test" button again and the alert shows up

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by 2nikhiltom**
Closes https://github.com/carbon-design-system/carbon/issues/19436 
Closes https://github.com/carbon-design-system/carbon/issues/19401

Added back the TabIndex default value to 0 if not passed 

### Changelog

**New**

Added test cases and story for testing/reviewing 

**Changed**

  sets default value to 0 inside the function body 
  const resolvedTabIndex = tabIndex ?? 0;

#### Testing / Reviewing

ci should pass
verify that HeaderMenuItem is focusable via keyboard navigation and onClick is called (verify in console )

⚠️ BEFORE MERGE ⚠️
- [ ] story to be removed before merging 

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by adamalston — COMMENTED** [review]
On https://github.com/carbon-design-system/carbon/issues/19436#issuecomment-2896437571, do we know why the default was deleted?

**Comment by 2nikhiltom** [comment]
Hey @adamalston 
Spoke with @Gururajj77  - the change appeared to be unintentional while resolving TypeScript issues during the React v19 dependency update. [commit reference ](https://github.com/carbon-design-system/carbon/pull/18207/commits/9c618f0102625d85fe7654f455515bf6a3bb202c#diff-8b93f9787f715c2503776cee486b1c59f63d2949c31c67b0e69cabb87a5629ee)

**Comment by tay1orjones** [comment]
@adamalston I looked through it again and didn't see anything of note. It's possible the tabindex change was output from one of the codemods for react 19 or the related typescript updates.

File: packages/react/src/components/UIShell/HeaderMenuItem.tsx [hunk 1]
```diff
@@ -57,6 +57,7 @@ const HeaderMenuItem = forwardRef(function HeaderMenuItem<
   ref: ForwardedRef<E>
 ) {
   const prefix = usePrefix();
+  const resolvedTabIndex = tabIndex ?? 0;
```
Comment (tay1orjones) [inline packages/react/src/components/UIShell/HeaderMenuItem.tsx:60]: Could this be a default function parameter like it was before?

```diff
     role,
-    tabIndex,
+    tabIndex = 0,
     ...rest
```

Comment (2nikhiltom) [reply packages/react/src/components/UIShell/HeaderMenuItem.tsx:60]: The default parameter `tabIndex = 0` causes TypeScript intersection type conflicts in this polymorphic component. 
 The intersection of base props  ( tabIndex?: number | undefined )and element-specific props becomes overly strict, even though both expect the same `number` type for `tabIndex`
 
image

Or we can remove `tabIndex` from your base props and let it come from the element naturally.

**Review by tay1orjones — APPROVED** [review]

**Review by riddhybansal — APPROVED** [review]
LGTM 💯

**Comment by ariellalgilmore** [comment]
hey @2nikhiltom looks like the test story accidentally got merged here
