### PR TITLE
fix: update outside click behavior for modals

### LINKED ISSUE #13712: [a11y]: Modal: Follow guidance on dismissing the modal by clicking elsewhere
Originally outlined in #12727:

> A modal dialog, by definition, is supposed to be the only operable thing on the screen. Theoretically, the area outside the modal should be _inert_. Clicking it should do nothing.
> Modals by design have a Cancel (or No) button as well as the X button to close, both of which allow affordances for a user to easily dismiss. There does not seem to be a good reason to allow the area outside the modal to be interactive.
> 
> The only [functional demonstration in the React storybook](https://react.carbondesignsystem.com/?path=/story/components-modal--with-state-manager) IS dismissable by clicking outside, even though Carbon says such [transactions modals](https://carbondesignsystem.com/components/modal/usage/#transactional-modal) are not dismissed by clicking outside.
> 
> The issue is made a bit problematic since Carbon also introduces the idea of a passive modal, which _can_ be dismissed in this way. In my [discussion on Modals](https://github.com/carbon-design-system/carbon/discussions/12726) I recommend that the Passive modal be called something else. There are lots of non-modal dialog prompts and interactions where clicking outside can dismiss content. I just feel that a modal dialog may not be the place to allow it.
> Note: I am trying to get clarity from ARIA authorities on whether clicking outside is even _allowed_ in a modal dialog. Their response may help inform the approach here. **Sev: discussion**
> 
> At the least, only the passive should be dismissable by clicking outside, to match the Carbon documentation.

### PR DESCRIPTION
**Pull request by adamalston**
Closes https://github.com/carbon-design-system/carbon/issues/13712

Updated outside click behavior for modals.

### Changelog

**New**

- Added documentation regarding passive modals.

**Changed**

- Updated outside click behavior for modals.
- Fixed accessibility issues in tests.
- Fixed discrepencies in modal docs.

#### Testing / Reviewing

I left a `TODO` with a question that hopefully someone can answer.

```sh
yarn test packages/react
```

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/react/src/components/ComposedModal/ComposedModal.tsx [hunk 1]
```diff
@@ -335,8 +336,16 @@ const ComposedModal = React.forwardRef<HTMLDivElement, ComposedModalProps>(
       const { target } = evt;
       const mouseDownTarget = onMouseDownTarget.current;
       evt.stopPropagation();
+      const containsModalFooter = Children.toArray(childrenWithProps).some(
+        (child) => isComponentElement(child, ModalFooter)
+      );
+      const isPassive = !containsModalFooter;
+      const shouldCloseOnOutsideClick =
+        (isPassive && preventCloseOnClickOutside !== false) ||
```
Comment (riddhybansal) [inline packages/react/src/components/ComposedModal/ComposedModal.tsx]: const shouldCloseOnOutsideClick = isPassive 
  ? preventCloseOnClickOutside !== false  
  : preventCloseOnClickOutside === true;

File: packages/react/src/components/Modal/Modal.tsx [hunk 2]
```diff
@@ -959,7 +959,19 @@ Modal.propTypes = {
...
    */
-  preventCloseOnClickOutside: PropTypes.bool,
+  preventCloseOnClickOutside: (
+    props: ModalProps,
+    propName: string,
+    componentName: string
+  ) => {
+    if (!props.passiveModal && props[propName] === false) {
+      return new Error(
+        `${componentName}: \`${propName}\` should not be \`false\` when \`passiveModal\` is \`false\`. Non-passive ${componentName}s should not be dismissible by clicking outside.`
```
Comment (riddhybansal) [inline packages/react/src/components/Modal/Modal.tsx]: Should we add test case that mock console.error to verify the error is thrown when passiveModal={false} and preventCloseOnClickOutside={false}, and that valid prop combinations don't trigger errors.

**Review by riddhybansal — CHANGES_REQUESTED** [review]

File: packages/react/src/components/Modal/Modal.mdx [hunk 3]
```diff
@@ -58,6 +64,17 @@ text.
 
 <ArgTypes />
 
+{/* <!-- prettier-ignore-start --> */}
+
+{/*
+TODO: Why are there `ComposedModal` docs in the `Modal` docs?
+The documentation is being duplicated between this file and
+`packages/react/src/components/ComposedModal/ComposedModal.mdx`.
+Currently, there are differences between the `ComposedModal` docs in these two files.
```
Comment (tay1orjones) [inline packages/react/src/components/Modal/Modal.mdx]: See the discussion at https://github.com/carbon-design-system/carbon/pull/6804

At this point it's probably worth separating the content to only apply to Modal. A nice addition could be to mention ComposedModal near the top of the page. and vice versa in ComposedModal.mdx

```diff
`<Modal>` allows you to use its bespoke set of contents. `children` prop maps to
the modal body content. You can also use `modalLabel`, `modalHeading`,
`secondaryButtonText` and `primaryButtonText` props to change the corresponding
text.
+ 
+ For a more composable approach to modals, see the [ComposedModal](...link/to/composedmodal.mdx).
```

Comment (tay1orjones) [reply packages/react/src/components/Modal/Modal.mdx]: This can be a separate PR, or create an issue

**Review by tay1orjones — APPROVED** [review]
+1 on the test for the proptype validator function, but I don't think it's a blocker to merge. It's somewhat implicitly tested by the allowed values used in the existing and new tests.

File: packages/react/src/components/Modal/Modal.mdx (hunk 3 above)
Comment (adamalston) [reply packages/react/src/components/Modal/Modal.mdx]: https://github.com/carbon-design-system/carbon/issues/19624

File: packages/react/src/components/Modal/Modal.tsx (hunk 2 above)
Comment (adamalston) [reply packages/react/src/components/Modal/Modal.tsx]: Do prop validators not work in React 19? I see other components that include them and also have error logging functionality. It looks like some of these changes originated in https://github.com/carbon-design-system/carbon/pull/18207, specifically in files like `packages/react/src/components/Button/Button.tsx`, `packages/react/src/components/Tabs/Tabs.tsx`, etc.

Example:

https://github.com/carbon-design-system/carbon/blob/624890b679409d619b1c8c6e99ad5cf041ad7917/packages/react/src/components/Tabs/Tabs.tsx#L142-L146

https://github.com/carbon-design-system/carbon/blob/624890b679409d619b1c8c6e99ad5cf041ad7917/packages/react/src/components/Tabs/Tabs.tsx#L198-L205

**Review by riddhybansal — APPROVED** [review]
