### PR TITLE
fix(Modal): require `aria-labelledby`

### LINKED ISSUE #2270: Modal's aria-label[ledby] and aria-describedby
While looking at [a Carbon React Modal accessibility issue](https://github.com/IBM/carbon-components-react/issues/1932), I decided to compare the React Modal to the [Vanilla Modal](https://www.carbondesignsystem.com/components/modal/code). I noticed that the Vanilla Carbon Modal does connect up `aria-labelledby` and `aria-describedby`, however there are a couple of potential problems:
1. Apparently the Carbon `modalLabel` is optional? That is very strange. Is the `modalHeading` expected to be the dialog title, then? Usually, the text at the top of a dialog is considered to be the dialog name, i.e. "Find" dialog, "Open File" dialog, "Create New User" dialog, "Login" dialog. There must always be a valid `aria-label` or `aria-labelledby` on a dialog, so that screen readers can announce the dialog's name when it becomes visible. So please either make the Carbon `modalLabel` required and just hook it up automatically to `aria-labelledby`, or hook up the Carbon `modalHeading` to `aria-labelledby`.
**[Edit**: just noticed the `modalAriaLabel` prop. I guess you could document that one of `modalLabel` (visible dialog name) or `modalAriaLabel` (invisible dialog name) must be provided.**]**
2. Usually, `aria-describedby` points to the sentence or sentences that describe what the dialog is for, or how to use the dialog, i.e. like the "Lorem ipsum" text that Carbon has in the "bx--modal-content" element in the example. (It could also point to the `modalHeading` plus the text).

I would suggest that any redesign includes thinking about how a Modal's label and description could be marked up for accessibility. Note that:
a) `aria-label[ledby]` is not optional. If a Carbon Modal does not have a `modalLabel`, then `aria-labelledby` needs to point to the `modalHeading`. **[Edit**: or you could use `modalAriaLabel` if it was provided.**]**
b) `aria-describedby` is optional, but if there is [a heading and] some text that describes how to use the dialog, then `aria-describedby` should point to it.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2270

This PR makes the `modalAriaLabel` prop required and sets values for `aria-labelledby` depending on the value of the `modalLabel`, `modalHeading`, or `modalAriaLabel` props

cc @carmacleod for testing

#### Testing / Reviewing

Ensure the modal is marked up for a11y

### CODE REVIEW

**Comment by carmacleod** [comment]
Hi @emyarod. I can't look at the React version, because the preview failed, but I did look at the [Vanilla preview](https://deploy-preview-2851--the-carbon-components.netlify.com/?nav=modal). A couple of comments:
- Please change the string of the label from "Optional label" to "Modal label". (since it's not optional, the string shouldn't imply that it is).
- I remembered that `aria-describedby` can take multiple space-separated ids - yay! So the "Modal heading" AND the modal content paragraph can both be used as the Modal's description by:
  - giving the `bx--modal-content div` (or its paragraph child) an id (say, `id="modal-mqgsow5eh1f-content"`)
  - setting the `aria-describedby` for the Modal as follows:
`aria-describedby="modal-mqgsow5eh1f-heading modal-mqgsow5eh1f-content"`

**Comment by joshblack** [comment]
I'm a little confused by the diff here, why are we setting `aria-labelledby` uncondtionally? I think we would need: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/prop-types/AriaPropTypes.js which states that either `aria-label` or `aria-labelledby` **must** be passed in.

In addition, `aria-labelledby` must be an `id` that refers to a node in the document versus arbitrary text. Same constraint for `aria-describedby` (although support for this is limited right @carmacleod?)

I think the change to `modalAriaLabel` is a good start, but I think we should follow the `AriaPropTypes` pattern here and say that we must have one of `aria-label` or` aria-labelledby` (correct me if I'm wrong here @carmacleod!)

**Comment by emyarod** [comment]
`aria-labelledby` is set unconditionally because of some confusion around this point of feedback:

> `aria-label[ledby]` is not optional. If a Carbon Modal does not have a `modalLabel`, then `aria-labelledby` needs to point to the `modalHeading`. **[Edit**: or you could use `modalAriaLabel` if it was provided.**]**

regarding the optional label vs modal heading, I think we need some clarification from design about the label/title/heading structure of the Carbon modals cc @carbon-design-system/design

**Comment by emyarod** [comment]
`aria-labelledby` is set unconditionally because of some confusion around this point of feedback:

> `aria-label[ledby]` is not optional. If a Carbon Modal does not have a `modalLabel`, then `aria-labelledby` needs to point to the `modalHeading`. **[Edit**: or you could use `modalAriaLabel` if it was provided.**]**

I'm still a bit confused on how we want to proceed, given there are so many options for values we can substitute for the aria labels, but I've made some changes. if the React diff looks ok then I will make the changes in vanilla as well @carmacleod @joshblack 

regarding the optional label vs modal heading, I think we need some clarification from design about the label/title/heading structure of the Carbon modals cc @carbon-design-system/design

**Comment by carmacleod** [comment]
Sorry, folks. I was confused about what to do about the design seeming to have 2 possible "dialog title strings", and I see that my confusion was mirrored in my words. Hopefully, I can clarify a bit.

I was trying to say that:
1. A Modal requires a label.
  - the label can be visible (preferred), and if it is then it must be pointed to with `aria-labelledby`
  - or the label can be invisible (if design can argue that the UX is still ok), which can be accomplished using `aria-label`

2. If the Modal has descriptive text, then that text should be pointed to with `aria-describedby`.

In case it's helpful, note that both `aria-labelledby` and `aria-describedby` can take multiple ID refs (separated by spaces).

So... I leave the decision totally up to you about how you want to hook up 3 things (modalLabel, modalHeading, and ... "modalContentText"?) to 2 aria attributes (aria-label[ledby] and aria-describedby).

Regarding prop naming and documentation, one possibility that might be clearest is to tell authors that `modalLabel` is required, and there's an optional boolean prop called `modalLabelVisible` (that defaults to **true**). In this case, you wouldn't need the `modalAriaLabel` prop at all. The implementation would be something like:
If `modalLabelVisible` is **true**, then  set `aria-labelledby` to the id of the `modalLabel` element
else if `modalLabelVisible` is **false**, then set `aria-label` to the value of `modalLabel`.

Otherwise, if you really want to keep the `modalAriaLabel` prop, then you would need to make your documentation very clear... something like, "You must set either `modalLabel` or `modalAriaLabel` but not both. If `modalLabel` is set then the modal's label will be visible. If `modalAriaLabel` is set then the modal's label will not be visible, but it will be available for assistive technology users."

(Hope this helps, and doesn't just add to the confusion).

**Comment by emyarod** [comment]
thanks for clarifying @carmacleod. given that there is the line that says "optional label" in the vanilla example, I assume the actual label would be the "Modal heading" line. but I will need to double check to make sure which (if any) of those lines are required in the design spec, so I know which value to use for `aria-label` cc @carbon-design-system/design 

currently I have changed it so that the `aria-label` is taking its value from the modal heading, based on my assumption above that the heading is always required but the "label" (the line above the heading in the design) is optional

**Comment by carmacleod** [comment]
> the aria-label is taking its value from the modal heading

I assume you mean the aria-labelledby is set to the id of the modal heading.  :)
(try to use aria-labelledby whenever there's a visible label)

So, if the author does provide the "optional label", do you care if screen readers don't read it?
Because they won't read it unless it's referenced by an aria attribute somehow.
If authors would expect it to be read (because even though it's optional, it's still the string at the top of the dialog), then you might want to set `aria-labelledby="optional-label-id modal-heading-id"`?

**Comment by emyarod** [comment]
> I assume you mean the aria-labelledby is set to the id of the modal heading. :)

yes my mistake, that's what I meant. right now this is reflected in my React modal changes in the current PR (although netlify is not building the preview for it)

I will defer to our designers for more clarification and guidance on modal content. It's not clear if the "optional label" or heading is required or not. I think it would help us decide now to proceed with hooking up the aria attributes depending on which lines are required

**Comment by asudoh** [comment]
@carbon-design-system/design Any thoughts on:

> I will defer to our designers for more clarification and guidance on modal content. It's not clear if the "optional label" or heading is required or not.

Thanks!

**Comment by aagonzales** [comment]
Label is optional, heading is required.

**Comment by asudoh** [comment]
Thanks @aagonzales! @emyarod Does her response makes this PR WIP or ready for review? Thanks!

**Comment by emyarod** [comment]
@asudoh @aagonzales's response is in line with [my initial assumption](https://github.com/carbon-design-system/carbon/pull/2851#issuecomment-497743423), so I believe this PR is ready for review

cc @carmacleod

**Review by shixiedesign — APPROVED** [review]
Modal is not affected visually. Looks good.

**Comment by snidersd** [comment]
Retested without violations. Thanks!

**Comment by carmacleod** [comment]
Tested in Chrome with JAWS and NVDA - they say "Optional label  dialog  Modal heading" when the dialog opens, which is good. (I sort of wish we could add the Lorem ipsum text to the aria-describedby, too, but I guess that content is user-supplied, and Carbon wouldn't really have any way of knowing whether it was plain text?).

I just have a few questions and notes:
- what happens if the Optional label is not given? Is there an example somewhere that I can test?
- where is the documentation describing the props? (I'd like to read it to see if it is clear about when to set modalLabel and when to set modalAriaLabel).
- in Modal.js, note that `aria-labelledby` needs to be an id... and I think `modalAriaLabel` would be a string, right? If so, please delete `|| modalAriaLabel` in the following code:
```javascript
        aria-labelledby={
          this.props[`aria-labelledby`] ||
          modalLabel ||  /* << this is an id, right? not a text string? */
          modalHeading ||  /* << this is an id, right? not a text string? */
          modalAriaLabel   /* << pretty sure this is a text string; if so, please delete */
        }
```
- in ModalWrapper-test.js, the following line of code sets `aria-labelledby` to a string (unless "Test" and "Modal" and "Label" are 3 ids, which I think is unlikely...). So... unless this is testing error handling, it is not a valid test.
```javascript
            aria-labelledby="Test Modal Label"
```

**Comment by emyarod** [comment]
> what happens if the Optional label is not given? Is there an example somewhere that I can test?

you would be able to edit it in the storybook knobs but netlify has not been able to deploy the react storybook for a while now

> where is the documentation describing the props? (I'd like to read it to see if it is clear about when to set modalLabel and when to set modalAriaLabel).

prop information is all contained within the component file itself, but the README for this component can be updated for more clarity

will examine your final two points as well, thanks for the feedback @carmacleod!

File: packages/react/src/components/Modal/Modal.js [hunk 1]
```diff
@@ -297,7 +306,13 @@ export default class Modal extends Component {
         ref={this.innerModal}
         role="dialog"
         className={`${prefix}--modal-container`}
-        aria-label={modalAriaLabel}
+        aria-label={this.props[`aria-label`] || modalAriaLabel}
+        aria-labelledby={
+          this.props[`aria-labelledby`] ||
+          modalLabel ||
```
Comment (joshblack) [inline packages/react/src/components/Modal/Modal.js]: These should be `id` values versus text values, I believe

File: packages/react/src/components/Modal/Modal.js [hunk 2]
```diff
@@ -297,7 +306,13 @@ export default class Modal extends Component {
         ref={this.innerModal}
         role="dialog"
         className={`${prefix}--modal-container`}
-        aria-label={modalAriaLabel}
+        aria-label={this.props[`aria-label`] || modalAriaLabel}
```
Comment (joshblack) [inline packages/react/src/components/Modal/Modal.js]:
```suggestion
        aria-label={this.props['aria-label'] || modalAriaLabel}
```

**Review by joshblack — CHANGES_REQUESTED** [review]

File: packages/react/src/components/Modal/Modal.js (hunk 1 above)
Comment (carmacleod) [reply packages/react/src/components/Modal/Modal.js]: Yep.
- `aria-label` is text
- `aria-labelledby` is an id (actually, a space-separated list of ids)

Comment (emyarod) [reply packages/react/src/components/Modal/Modal.js]: thanks! should be resolved now

**Comment by emyarod** [comment]
> where is the documentation describing the props? (I'd like to read it to see if it is clear about when to set modalLabel and when to set modalAriaLabel).

back to this point @carmacleod, since design has now clarified that the "label" is optional, should we set the fallback for `modalAriaLabel` to be the required "header" content?

File: packages/react/src/components/Modal/Modal.js [hunk 3]
```diff
@@ -297,7 +306,8 @@ export default class Modal extends Component {
         ref={this.innerModal}
         role="dialog"
         className={`${prefix}--modal-container`}
-        aria-label={modalAriaLabel}
+        aria-label={this.props['aria-label'] || modalAriaLabel}
+        aria-labelledby={this.props.id || null}
```
Comment (joshblack) [inline packages/react/src/components/Modal/Modal.js]: Would we just want to support `aria-label`? I think `this.props.id` might trip it up since it's referring to the modal node in this context, which has `role="presentation"`.

**Review by joshblack — CHANGES_REQUESTED** [review]

**Comment by carmacleod** [comment]
> back to this point @carmacleod, since design has now clarified that the "label" is optional, should we set the fallback for modalAriaLabel to be the required "header" content?

I don't actually know. I was hoping that design would help with that. :)

The question to ask is: "What is the dialog's name?"
i.e. What do people call this thing when they are talking about it?

Or, phrased a different way, knowing that a screen reader will say "NAME dialog", what should NAME be?

If the "label" is given, then NAME is the "label".

If the "label" is _not_ given then "modalAriaLabel" _must be_ given, and then NAME is the "modalAriaLabel".

Does Carbon have error conditions if a required prop is not given?

Anyhow, assuming that you must have a fallback, the next question is, "Would people call the dialog by its header if neither label was given?"

If yes, then ok, use the header as the fallback name. But if you do that, please make sure that you do not also use the header as the description, because that would be redundant.

File: packages/react/src/components/Modal/Modal.js (hunk 3 above)
Comment (emyarod) [reply packages/react/src/components/Modal/Modal.js]: yeah that makes sense, removed `aria-labelledby`

**Comment by emyarod** [comment]
yeah based on the response from design my assumption is that the header should be the fallback for `modalAriaLabel` then, since it is always required and appears more prominently in the modal when both are provided

**Review by tw15egan — APPROVED** [review]
Looks good once merge conflicts are resolved

**Review by jnm2377 — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Comment by asudoh** [comment]
@emyarod Do you think the key comments from @carmacleod have been addressed...? Thanks!

**Comment by emyarod** [comment]
@asudoh yes I believe so, but would like final sign off before merging

**Comment by joshblack** [comment]
bump @carmacleod if you have a second! 😄

**Comment by jnm2377** [comment]
@carmacleod can you re-review so we can merge?

**Comment by carmacleod** [comment]
Hi, so sorry to take so long to reply.
I tried playing with the "knobs" in the react version, and I guess I don't understand whether they are supposed to show exact markup changes, but if so, then I have a couple of comments:
- if I completely delete the modalAriaLabel text, then I would have assumed that `aria-labelledby` would point to the visible modalLabel element, but there's no aria-labelledby attribute present at all
- please do not set aria-label to the empty string, ever. Always delete the attribute if it does not contain any text.

Would you be able to change the example strings a tiny bit to make it clearer what is going on with modalLabel vs modalAriaLabel ? Maybe something like in the following screen snapshot ?

Carbon React Modal with modalLabel="Optional Visible Label (dialog name)" and modalAriaLabel="Invisible label to be read by screen readers (only if Visible Label is not given)"

Ideally, the author would only set one prop or the other and not both, but if they set both, and if the implementation sets both aria attributes, then aria-label overrides the visible label, and aria-labelledby overrides the aria-label (so the visible label would "win").

**Comment by carmacleod** [comment]
I tried changing the labelText and aria-label text in the "knobs" for the [toggle PR](https://github.com/carbon-design-system/carbon/pull/2885) and I think that, for consistency, you may want the modalLabel/modalAriaLabel behavior to be the same, i.e., if there's a visible modalLabel, and the author also sets modalAriaLabel, then ignore the modalAriaLabel.

**Comment by carmacleod** [comment]
In case it's ever helpful in future...  :)

I guess if I was designing this modal from scratch, I probably wouldn't even surface `aria-label` to the API.
The modal would have a prop for the modalLabel (required, with no fallback - i.e. if not given, then error) and another prop for whether the modalLabel was visible or invisible (default visible). The implementation could then decide whether to use `aria-label` or `aria-labelledby` based on the value of the modalLabelVisible prop, i.e., if modalLabelVisible=true, use `aria-labelledby`; if modalLabelVisible=false, use `aria-label`. I think that would clarify things a bit for both the author and the code, and it would ensure that the dialog always had a name.

The modalHeading prop would still be required.

For the description, I would probably have a new prop for the "Lorem ipsum" text. That way, the `aria-describedby` could point to both the required heading _and_ any descriptive text. (What we have now is that it only points to the header, even when the modal content has some nice descriptive text, and so a screen reader user won't hear the descriptive text when the dialog opens).

**Comment by emyarod** [comment]
>  if modalLabelVisible=true, use aria-labelledby; if modalLabelVisible=false, use aria-label

thanks for the feedback! I just implemented something along these lines, would you mind confirming that it's behaving as expected?

**Comment by emyarod** [comment]
@carmacleod do you mind taking another look?

File: packages/react/src/components/Modal/Modal.js [hunk 4]
```diff
@@ -303,12 +312,28 @@ export default class Modal extends Component {
...
+    })();
+
     const modalBody = (
       <div
         ref={this.innerModal}
         role="dialog"
         className={`${prefix}--modal-container`}
-        aria-label={modalAriaLabel}
+        aria-label={
+          modalLabel
```
Comment (dakahn) [inline packages/react/src/components/Modal/Modal.js:332]: Good stuff 👍 I'll have to remember this technique for if this if/else labeling pattern comes up again in the future.

**Review by dakahn — APPROVED** [review]

**Comment by asudoh** [comment]
@carmacleod Merging, but please don't hesitate to chime in and point out anything!
