### PR TITLE
fix(tabs): manaul mode incorrect `cds-tabs-selected` event trigger

### LINKED ISSUE #21854: [Bug]: cds-tabs with selection-mode="manual" dispatches cds-tabs-selected event on keyboard navigation, but tab is not selected
### Package

@carbon/web-components

### Browser

_No response_

### Package version

v2.50.0

### React version

_No response_

### Description

When using the cds-tabs component with the selection-mode prop set to "manual", navigating between tabs using the keyboard (e.g., arrow keys) dispatches the cds-tabs-selected event with the value of the focused tab in event.detail.item.value. However, the tab is not actually selected (the selection does not change), which is inconsistent with expected behavior. The event should only be dispatched when a tab is selected, not just focused.

The problem reported in [21027](https://github.com/carbon-design-system/carbon/issues/21027) is related but not the same problem reported in this issue. In this case, the problem is not that manual selection mode is not working, but rather that it is triggering the cds-tabs-selected event even though the selected tab has not changed. The stackblitz example has selection-mode= manual, and when navigating with the keyboard between tabs, it does not actually change the selected tab but emits the cds-tabs-selected event whenever the focus changes to another tab, as can be seen in the console.

Image

### Reproduction/example

https://stackblitz.com/edit/github-whgbjhq7?file=index.html

### Steps to reproduce

1. Use the reproduction example code
2. Focus the cds-tabs component.
3. Use the left/right arrow keys to move focus between tabs.
4. Observe the console output and the selected tab.

**Expected Result:**
The cds-tabs-selected event should only be dispatched when a tab is actually selected (e.g., via Enter/Space), not just when it is focused with arrow keys. The selected tab should update accordingly.

**Actual Result:**
The _cds-tabs-selected event is dispatched_ on focus change (arrow keys), but the selected tab does not change.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by sangeethababu9223**
Closes #21854

Fixed an issue where cds-tabs with selection-mode="manual" was incorrectly dispatching the cds-tabs-selected event during keyboard navigation (arrow keys), even though the tab was not actually being selected. In manual selection mode, the event should only fire when the user explicitly activates a tab (via Enter/Space key or mouse click), not during navigation.

### Changelog

**New**

- Added event action logging to [tabs.stories.ts](vscode-webview://1m2h4vdv6ve1t1tjigepoe9ahjdukocub76ggj559iu2j36vf2q5/packages/web-components/src/components/tabs/tabs.stories.ts) for better debugging in Storybook
- Added test coverage for manual selection mode behavior in [content-switcher-test.js](vscode-webview://1m2h4vdv6ve1t1tjigepoe9ahjdukocub76ggj559iu2j36vf2q5/packages/web-components/src/components/content-switcher/__tests__/content-switcher-test.js)

**Changed**

- Modified [content-switcher.ts](vscode-webview://1m2h4vdv6ve1t1tjigepoe9ahjdukocub76ggj559iu2j36vf2q5/packages/web-components/src/components/content-switcher/content-switcher.ts) to prevent cds-content-switcher-selected event from firing during keyboard navigation when selection-mode="manual"
- Updated [tabs.ts](vscode-webview://1m2h4vdv6ve1t1tjigepoe9ahjdukocub76ggj559iu2j36vf2q5/packages/web-components/src/components/tabs/tabs.ts) to use _handleUserInitiatedSelectItem() with 'activation' interaction type for Enter/Space key activation in manual mode
- Added new 'activation' interaction type to distinguish between navigation and explicit selection actions
- Enhanced event handling logic to differentiate between keyboard navigation (focus only) and activation (selection)

#### Testing / Reviewing

- Manual mode: Go to `Manual` story under `Tabs` in WC Storybook. Verify cds-tabs-selected event does NOT fire on arrow key navigation, but DOES fire on Enter/Space key or click (check Actions panel in Storybook)
- Automatic mode: Go to `Default` story under `Tabs`  in WC Storybook. Verify cds-tabs-selected event fires on arrow key navigation and click (check Actions panel in Storybook)
- Ensure all tests pass without failures

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] ~Updated documentation and storybook examples~
- [x] Wrote passing tests that cover this change
- [ ] ~Addressed any impact on accessibility (a11y)~
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/web-components/src/components/tabs/tabs.ts [hunk 1]
```diff
@@ -171,7 +171,10 @@ export default class CDSTabs extends HostListenerMixin(CDSContentSwitcher) {
             `${prefix}-tab[highlighted]`
           );
           if (focusedTab) {
-            this._selectionDidChange(focusedTab);
+            this._handleUserInitiatedSelectItem(
+              focusedTab as CDSTab,
+              'activation'
+            );
```
Comment (adamalston) [inline packages/web-components/src/components/tabs/tabs.ts:182]: Could you add a coverage for the manual-mode `Enter` and `Space` path here? This change switches activation from `_selectionDidChange` to `_handleUserInitiatedSelectItem`, but the only new coverage I see is for `content-switcher`, so `cds-tabs`' own keyboard override and event behavior don't appear to be covered.

Or is this a case where tests haven't been added yet for `cds-tabs`?

File: packages/web-components/src/components/tabs/tabs.ts
Comment (adamalston) [inline packages/web-components/src/components/tabs/tabs.ts:1]: How should `selection-mode="manual"` handle `Home` and `End` in `cds-tabs`? This change makes arrow-key navigation activation only, but `Home` and `End` still appear to select immediately, so the `manual-mode` keyboard model may still be inconsistent.

File: packages/web-components/src/components/tabs/tabs.ts (hunk 1 above)
Comment (sangeethababu9223) [reply packages/web-components/src/components/tabs/tabs.ts:182]: Yes, we don't have a test set up for tabs, I belive we'll be adding it once the parity work is completed.

File: packages/web-components/src/components/tabs/tabs.ts
Comment (sangeethababu9223) [reply packages/web-components/src/components/tabs/tabs.ts:1]: Good point. In react version it only changes focus, so the same is expected in WC version as well. Updated the logic to match this behaviour.

Comment (sangeethababu9223) [reply packages/web-components/src/components/tabs/tabs.ts:1]: This needed some further refactoring and is slightly out of scope for the current PR, so I’ve moved it to a separate PR: https://github.com/carbon-design-system/carbon/pull/22043

**Review by heloiselui — APPROVED** [review]
LGTM! I see you opened follow-up PR #22043  to address Adam’s Home/End manual-mode concern, and the approach there looks aligned with React parity.

We also need add tests, but this will be added once the parity work is completed.

**Review by maradwan26 — APPROVED** [review]
LGTM
