### PR TITLE
fix: update compareItems type in MultiSelect

### LINKED ISSUE #18199: [Bug]: `MultiSelect` `compareItems` parameter types are not correct
### Package

@carbon/react

### Browser

_No response_

### Package version

1.67.1

### React version

_No response_

### Description

The types for the `compareItems` prop's parameters are not correct. Each parameter is a `string`, not an `ItemType`.

### Reproduction/example

https://stackblitz.com/edit/github-79u5xe?file=src%2FApp.tsx

### Steps to reproduce

See reproduction and type error.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

DataPower

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by adamalston**
Closes https://github.com/carbon-design-system/carbon/issues/18199

Updated `compareItems` type in `MultiSelect`.

#### Changelog

**New**

- Added `defaultCompareItems` tests.

**Changed**

- Updated `compareItems` type in `MultiSelect`.

#### Testing / Reviewing

- Run the test that was added.
- Use `compareItems` in a TypeScript file similar to the reproduction in the issue and check for errors.

### CODE REVIEW

File: packages/react/src/components/MultiSelect/MultiSelectPropTypes.ts [hunk 1]
```diff
@@ -46,14 +46,14 @@ interface SharedOptions {
   locale: string;
 }
 
+interface CompareItems {
+  (itemA: string, itemB: string, options: SharedOptions): number;
```
Comment (tay1orjones) [inline packages/react/src/components/MultiSelect/MultiSelectPropTypes.ts:50]: Are we losing some strictness here by moving the items from `ItemType` to `string`?

**Review by tay1orjones — APPROVED** [review]
One question but nothing to hold up a merge. Thanks for this contribution!

File: packages/react/src/components/MultiSelect/MultiSelectPropTypes.ts (hunk 1 above)
Comment (adamalston) [reply packages/react/src/components/MultiSelect/MultiSelectPropTypes.ts:50]: Wasn't that the problem, that the items had type `ItemType` instead of `string`? Aren't the items going through `itemToString` before they go to the comparison function?

**Review by ariellalgilmore — APPROVED** [review]
LGTM
