### PR TITLE
fix: address accessibility for pagination and select

### LINKED ISSUE #21932: [a11y]: Resolve accessibility issues in the Pagination component
### Package

@carbon/web-components, @carbon/react

### Browser

Chrome

### Operating System

MacOS

### Package version

v2.51.1

### React version

_No response_

### Automated testing tool and ruleset

storybook

### Assistive technology

_No response_

### Description

There's a few accessibility issues occurring in the [Pagination](https://web-components.carbondesignsystem.com/?path=/story/components-pagination--default) component that AI Chat needs resolved.

I have a more detailed outline in an [issue](https://github.com/carbon-design-system/carbon-ai-chat/issues/1068) in the carbon for AI repo. Basically we just need to resolve the accessibility issues that we're seeing in the storybook.

I'm going to start working on a fix for this if you want to just assign it to me 👍 

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://web-components.carbondesignsystem.com/?path=/story/components-pagination--default

### Steps to reproduce

Go to the [pagination component storybook](https://web-components.carbondesignsystem.com/?path=/story/components-pagination--default) and examine the results from the accessibility tab

### Suggested Severity

None

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by davidmenendez**
Closes #21932 

Resolves accessibility violations from the `cds-pagination` web-component

Screenshot 2026-04-01 at 3 49 11 PM

### Changelog

**New**

- added the `label-styles-disable` prop to the `cds-select` web-component to account for use-cases where the user doesn't want the label to use the default `cds--label` class & styles

**Changed**

- in `cds-pagination` the default value for `itemsPerPageText` has been removed
- in `cds-pagination` the `label` elements adjacent to the `cds-select` components were moved to use the `label-text` slots in `cds-select`
- in `cds-select` the `id` prop now has no default value and is appropriately applied to the underlying `label` and `select` elements. prior to this it was just using the hardcoded value of `input`

#### Testing / Reviewing

- verify `yarn test` passes
- verify that the `pagination` component has no violations in the accessibility tab in storybook

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by davidmenendez** [comment]
testing _is_ passing locally, but i'm dumb and forgot you have to rebuild before retesting to test the latest changes 😂 

i will fix those tests ASAP

File: packages/web-components/src/components/pagination/pagination.ts [hunk 1]
```diff
@@ -485,17 +485,16 @@ class CDSPagination extends FocusMixin(HostListenerMixin(LitElement)) {
...
           ?disabled=${disabled || pageSizeInputDisabled}
           id="page-size-select"
           left-select
           pagination
           size="${size}"
           inline
-          value="${pageSize}">
+          value="${pageSize}"
+          label-styles-disable>
+          <span slot="label-text"> ${itemsPerPageText} </span>
```
Comment (adamalston) [inline packages/web-components/src/components/pagination/pagination.ts]: With these changes, does the "Items per page" text appear as expected?

File: packages/web-components/src/components/select/select.ts
Comment (adamalston) [inline packages/web-components/src/components/select/select.ts:1]: Regarding this code:

https://github.com/carbon-design-system/carbon/blob/d0dd91b3b871817a857f2d2c006aef2128144a57/packages/web-components/src/components/select/select.ts#L62-L63

How is the custom `id` handled when `_inputNode` still queries `#input` here? Once you render the inner `select` with a user provided `id`, this lookup no longer resolves to the control, so the AI label branch in `updated` stops adding `${prefix}--select-input-has--ai-label`.

https://github.com/carbon-design-system/carbon/blob/d0dd91b3b871817a857f2d2c006aef2128144a57/packages/web-components/src/components/select/select.ts#L391

Comment (davidmenendez) [reply packages/web-components/src/components/select/select.ts:1]: i totally missed that! thank you for pointing that out. i will adjust that 👍

File: packages/web-components/src/components/pagination/pagination.ts (hunk 1 above)
Comment (davidmenendez) [reply packages/web-components/src/components/pagination/pagination.ts]: yes i verified that it's rendering as expected 👍

File: packages/web-components/src/components/select/select.ts
Comment (davidmenendez) [reply packages/web-components/src/components/select/select.ts:1]: updated. `_selectNode` and `_inputNode` were redundant selectors, so i just removed `_inputNode` and updated 391 to reference `_selectNode` 👍

**Review by maradwan26 — APPROVED** [review]
LGTM!

File: packages/web-components/src/components/select/select.ts [hunk 2]
```diff
@@ -233,7 +227,7 @@ class CDSSelect extends FormMixin(LitElement) {
    * ID to link the `label` and `select`
    */
   @property()
-  id = '';
+  id = 'input';
```
Comment (adamalston) [inline packages/web-components/src/components/select/select.ts]: Should you avoid reusing the host `id` property for the internal `select` id here? Setting the default to `input` makes every untouched `cds-select` look like it already has an explicit id, which can break wrappers that only generate labels or aria ids when no id was provided.

File: packages/web-components/src/components/pagination/pagination.ts (hunk 1 above)
Comment (adamalston) [reply packages/web-components/src/components/pagination/pagination.ts]: https://github.com/carbon-design-system/carbon/commit/da0205e7fc4e33f199608ee3c0a39af7dd825b3b was created after https://github.com/carbon-design-system/carbon/pull/21942#discussion_r3024990125 was left. Was there an issue, or are the two unrelated?

File: packages/web-components/src/components/pagination/pagination.ts [hunk 3]
```diff
@@ -485,17 +485,18 @@ class CDSPagination extends FocusMixin(HostListenerMixin(LitElement)) {
...
           left-select
           pagination
           size="${size}"
           inline
-          value="${pageSize}">
+          value="${pageSize}"
+          label-styles-disable>
+          <span class="${prefix}--pagination__text" slot="label-text"
+            >${itemsPerPageText}</span
+          >
```
Comment (adamalston) [inline packages/web-components/src/components/pagination/pagination.ts]: Should the existing `label-text` slot be preserved? Replacing it with a hard-coded `<span slot="label-text">` means consumers can no longer pass their own label content (e.g., a toggletip) to the page size control.

**Comment by adamalston** [comment]
The pull request template is incomplete.

File: packages/web-components/src/components/pagination/pagination.ts (hunk 1 above)
Comment (davidmenendez) [reply packages/web-components/src/components/pagination/pagination.ts]: yeah it was just so extremely minor i missed it until i put it under a microscope 🔬

**Comment by davidmenendez** [comment]
@adamalston changes made

File: packages/styles/scss/components/pagination/_pagination.scss
Comment (adamalston) [inline packages/styles/scss/components/pagination/_pagination.scss:1]: Does this pull request need https://github.com/carbon-design-system/carbon/labels/status%3A%20visual%20review%20%F0%9F%94%8D given the changes in this file?

File: packages/web-components/src/components/pagination/pagination.ts [hunk 4]
```diff
@@ -286,7 +286,7 @@ class CDSPagination extends FocusMixin(HostListenerMixin(LitElement)) {
    * The translatable text indicating the number of items per page.
    */
   @property({ attribute: 'items-per-page-text' })
-  itemsPerPageText = 'Items per page:';
+  itemsPerPageText = '';
```
Comment (adamalston) [inline packages/web-components/src/components/pagination/pagination.ts:289]: Is there test coverage for the case where `items-per-page-text` is not provided, now that the default label has been removed? I ask because this prop is not marked as required, so there's no indication that it must be defined.

The Storybook examples still pass `Items per page:`, so I'm not seeing coverage for consumers who omit the prop and may now render the page size select without a label.

File: packages/web-components/src/components/select/select.ts [hunk 5]
```diff
@@ -469,7 +473,7 @@ class CDSSelect extends FormMixin(LitElement) {
 
     const input = html`
       <select
-        id="input"
+        id=${id}
```
Comment (adamalston) [inline packages/web-components/src/components/select/select.ts]: Two things:

1. Should the remaining examples (see examples below) that omit an `id` be updated?
2. Should a test be added to cover the `id` requirement?

The changelog in https://github.com/carbon-design-system/carbon/pull/21942#issue-4189890031 calls out this breaking change, but usages of `cds-select` and `cds-fluid-select` without an `id` now leave the internal `select` unlabeled. The updated tests appear to cover only the opt-in `id` path.

Examples:

- https://github.com/carbon-design-system/carbon/blob/b4cb7bc74a94a7d3e3399321efcd29ccb31644e5/packages/web-components/src/components/form/form.stories.ts#L145
- https://github.com/carbon-design-system/carbon/blob/b4cb7bc74a94a7d3e3399321efcd29ccb31644e5/packages/web-components/src/components/modal/modal.stories.ts#L194
- https://github.com/carbon-design-system/carbon/blob/b4cb7bc74a94a7d3e3399321efcd29ccb31644e5/packages/web-components/src/components/fluid-select/fluid-select.stories.ts#L118-L126

**Comment by davidmenendez** [comment]
@adamalston updated

* added missing id attribute to select components and stories
* added test to pagination to test case when no label is supplied
* added test to select to test case when no id is supplied

**Comment by davidmenendez** [comment]
I've been thinking about the id concern. looking across the web-components package and there are numerous places where the id attribute is set as a prop but not set to be required, are given a default value `id = 'checkbox'; // checkbox.ts`, or are set to `''` and not even used like in `textarea.ts`

I agree that this should be fixed and understand it may be a breaking change. If that's the case then this may be something we want to sort out in a separate issue and PR. For the sake of this PR, it might be easier to omit the changes associated with removing the default id value and address it separately.

Thoughts?

**Comment by adamalston** [comment]
I think that sounds reasonable. Once an approach is finalized, maybe it could be standardized.

**Comment by davidmenendez** [comment]
changes made 👍

**Comment by davidmenendez** [comment]
would love to get this merged in ASAP if someone can take a look. thanks! 👍

File: packages/web-components/src/components/select/select.mdx [hunk 6]
```diff
@@ -55,23 +55,25 @@ import '@carbon/web-components/es/components/form/index.js';
 ```html
 <cds-form-item>
   <cds-select
+    id="id for label"
```
Comment (emyarod) [inline packages/web-components/src/components/select/select.mdx]: this shouldn't have spaces right?

File: packages/web-components/src/components/select/select.ts (hunk 2 above)
Comment (adamalston) [inline packages/web-components/src/components/select/select.ts]: I think https://github.com/carbon-design-system/carbon/pull/21942#discussion_r3041464940 was addressed. However, some changes were later reverted, understandably, and the issue now appears to have resurfaced.

Does anything need to be updated? My understanding of the current implementation is that unless each consumer overrides this `id`, it may lead to duplicate values. That could cause problems with selectors and ARIA references.

File: packages/web-components/src/components/pagination/pagination.ts (hunk 4 above)
Comment (adamalston) [reply packages/web-components/src/components/pagination/pagination.ts:289]: Should this prop be marked as required now that it's not set by default?

File: packages/web-components/src/components/select/select.ts (hunk 2 above)
Comment (davidmenendez) [reply packages/web-components/src/components/select/select.ts]: based on my understanding of how the shadow dom works, i think it's technically ok due to the encapsulation that web components provide. it's probably still best for users to implement their own select components with unique ids, but i don't think it will actually cause issue to use the same id in different shadow roots.

it's not flagged as an issue by the accessibility checker in the pagination component when both of the select ids are removed

Screenshot 2026-04-14 at 2 40 19 PM

since this is a preexisting implementation i think it would be better to discuss further in a separate issue 👍 

sources:

* [link 1](https://stackoverflow.com/questions/72258610/is-it-semantically-correct-to-have-multiple-inner-elements-with-the-same-id-in)
* [link 2](https://stackoverflow.com/questions/56023322/are-duplicate-ids-allowed-in-separate-shadow-roots#:~:text=Duplicate%20IDs%20in%20Shadow%20Roots:%20It%20is,shadow%20root%20acts%20as%20an%20isolated%20document.)
* Bob

File: packages/web-components/src/components/pagination/pagination.ts (hunk 4 above)
Comment (davidmenendez) [reply packages/web-components/src/components/pagination/pagination.ts:289]: it's not currently required in the [react version](https://react.carbondesignsystem.com/?path=/story/components-pagination--default&args=itemsPerPageText:) so i think this is working as intended

File: packages/web-components/src/components/pagination/__tests__/pagination-test.js [hunk 7]
```diff
@@ -148,10 +148,25 @@ describe('cds-pagination', () => {
...
     `);
 
-    const label = el.shadowRoot?.querySelector(`.cds--pagination__text`);
+    const label = el.shadowRoot?.querySelector(
+      '.cds--pagination__left div[slot="label-text"]'
+    );
     expect(label?.textContent?.trim()).to.equal('éléments par page');
   });
 
+  it('should respect items-per-page-text attribute when not supplied', async () => {
```
Comment (adamalston) [inline packages/web-components/src/components/pagination/__tests__/pagination-test.js:157]:
```suggestion
  it('should default to an empty label when `items-per-page-text` is omitted', async () => {
```

**Review by adamalston — APPROVED** [review]
