### PR TITLE
fix: focus issue in menu

### LINKED ISSUE #16994: [Bug]: Inconsistent focus for menu if more than one menu item have nested menu items.
### Package

@carbon/react

### Browser

_No response_

### Package version

1.61.0

### React version

_No response_

### Description

In Menu component if we have more than one item with nested items in it, the focus(Highlights) become inconsistent. 

### Reproduction/example

Please check attached video

### Steps to reproduce

https://github.com/user-attachments/assets/0501fab7-5d8a-4c57-a29b-af789a81b2d9

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by preetibansalui**
Closes #16994 

Fix the inconsistency in menu where it has more than 2 menu items with submenus.

**Changed**

The issue was causing because of delay in [closing the submenu](https://github.com/carbon-design-system/carbon/pull/16466). 

Added floating ui - safePolygon so menu will not close when user hover on submenu.
Added floating ui - FloatingFocusManager to manage the focus.

### CODE REVIEW

**Review by guidari — APPROVED** [review]
LGTM! 🚀

File: packages/react/src/components/Menu/MenuItem.tsx [hunk 1]
```diff
@@ -97,26 +102,40 @@ export const MenuItem = forwardRef<HTMLLIElement, MenuItemProps>(
...
+      placement: rtl ? 'left-start' : 'right-start',
+      whileElementsMounted: autoUpdate,
+      middleware: [offset({ mainAxis: -6, crossAxis: -6 })],
+    });
+    const { getReferenceProps, getFloatingProps } = useInteractions([
+      useHover(floatingContext, {
+        enabled: true,
+        handleClose: safePolygon({
+          requireIntent: true,
+        }),
```
Comment (tay1orjones) [inline packages/react/src/components/Menu/MenuItem.tsx]: Here I'm trying to get to `Italic`, but can't get there even though I'm in the triangle. The `Share with` item is being invoked when I expect it to be ignored. Maybe the [`blockPointerEvents` option](https://floating-ui.com/docs/usehover#blockpointerevents) could help?


https://github.com/user-attachments/assets/7aebcc5a-a9ce-41e6-b94d-f3c2058f0dd1

File: packages/react/src/components/OverflowMenu/next/OverflowMenu-test.js [hunk 2]
```diff
@@ -99,7 +97,11 @@ describe('OverflowMenu (enable-v12-overflowmenu)', () => {
     );
     await userEvent.type(screen.getByRole('button'), 'enter');
     expect(screen.getByRole('button')).toHaveAttribute('aria-expanded', 'true');
-    await userEvent.click(document.body);
+
+    await act(async () => {
+      await userEvent.click(document.body);
+    });
```
Comment (tay1orjones) [inline packages/react/src/components/OverflowMenu/next/OverflowMenu-test.js:119]: Is this for pulling focus out of the menu? I didn't think calls to `userEvent` needed to be wrapped in `act()`.

File: packages/react/src/components/Menu/MenuItem.tsx [hunk 3]
```diff
@@ -136,32 +155,19 @@ export const MenuItem = forwardRef<HTMLLIElement, MenuItemProps>(
...
-      setBoundaries({ x: -1, y: -1 });
     }
 
     function handleClick(
       e: KeyboardEvent<HTMLLIElement> | MouseEvent<HTMLLIElement>
     ) {
       if (!isDisabled) {
         if (hasChildren) {
+          setSubmenuOpen(true);
           openSubmenu();
```
Comment (tay1orjones) [inline packages/react/src/components/Menu/MenuItem.tsx]: `setSubmenuOpen` is already called inside `openSubmenu`

```suggestion
          openSubmenu();
```

**Review by tay1orjones — CHANGES_REQUESTED** [review]
This is such an excellent improvement! Just a couple things I noticed

File: packages/react/src/components/Menu/MenuItem.tsx (hunk 1 above)
Comment (preetibansalui) [reply packages/react/src/components/Menu/MenuItem.tsx]: [blockPointerEvents](https://floating-ui.com/docs/usehover#blockpointerevents) was blocking the entire menu from any event.  its happening only when any other pointer comes under the safePolygon. If you try it with` Share with ` It works fine. So I added a `delay` of 100ms to avoid the issue.

**Review by tay1orjones — APPROVED** [review]
