### PR TITLE
fix(composedmodal): add role to content container

### LINKED ISSUE #6122: [ComposedModal] Inner content container missing role
## Detailed description
The inner content container of `ComposedModal` is missing `role="dialog`. This can prevent assistive technology from identifying the modal content as separated from the rest of the page.

> What version of the Carbon Design System are you using?
7.11.3

> What did you expect to happen?
Assistive technology, such as screen readers, to identify the modal content container as `role="dialog"`.

> What happened instead?
Attribute `role` is missing from content container element.

> What WCAG 2.1 checkpoint does the issue violate?
https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_overview#focus-order

### PR DESCRIPTION
**Pull request by kennylam**
Fixes #6122 

Add WAI-ARIA role to `ComposedModal`

#### Changelog

**New**

- `role="dialog"` to `ComposedModal` inner container

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
is there an associated ticket for this PR? it looks like the negative tabindex on the modal container is being completely replaced with a `role`

**Comment by kennylam** [comment]
> is there an associated ticket for this PR? it looks like the negative tabindex on the modal container is being completely replaced with a `role`

@emyarod No associated ticket, this was brought up as an accessibility issue in our project. But if you'd like me to open an issue for it here I can do that.

And yes, `role` replaces the negative `tabindex` so screen readers can identify the element when focused. See same fix https://github.com/carbon-design-system/carbon-components-react/pull/667.

**Comment by emyarod** [comment]
@kennylam got it, yeah a related issue would be great for context especially if we need to revisit this PR in the future (https://github.com/carbon-design-system/carbon/blob/master/.github/CONTRIBUTING.md#7-make-a-pull-request)

**Comment by kennylam** [comment]
@emyarod Done!

File: packages/react/src/components/ComposedModal/ComposedModal.js [hunk 1]
```diff
@@ -244,7 +244,7 @@ export default class ComposedModal extends Component {
           className={`${prefix}--visually-hidden`}>
           Focus sentinel
         </span>
-        <div ref={this.innerModal} className={containerClass} tabIndex={-1}>
+        <div ref={this.innerModal} className={containerClass} role="dialog">
```
Comment (asudoh) [inline packages/react/src/components/ComposedModal/ComposedModal.js:247]: Thank you for jumping in @kennylam! Is the removal of `tabIndex={-1}` intentional?

Comment (kennylam) [reply packages/react/src/components/ComposedModal/ComposedModal.js:247]: Hi @asudoh, yes otherwise the element would not be tab focusable and things like screen readers would miss them, no?

Comment (asudoh) [reply packages/react/src/components/ComposedModal/ComposedModal.js:247]: Uh, to make it keyboard-focusable it requires `tabIndex={0}`. (`tabIndex={-1}` means programmatic focusable - Ref: https://blog.whatwg.org/focusing-on-focus) However, as long as there is at least one keyboard-focusable element user can focus into the modal and use screen reader cursor to read out the content AFAIK.

Having that said, I now feel like removal of `tabIndex={-1}` is fine.. I dug the code history and [`tabIndex={-1}` is there from the beginning](https://github.com/carbon-design-system/carbon-components-react/commit/00f31557c556760757bde71c3740188b004b3dbc) (with no explicit reason mentioned there).

**Review by asudoh — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by dakahn — APPROVED** [review]

**Comment by dakahn** [comment]
Tested in JAWS 2020 and NVDA on Windows 10 in Chrome latest and didn't see any gnarly deprecations or unexpected behavior. I like the way this improves how the modal speaks as well
