### PR TITLE
fix(tile): update props to remove errors, update tile maxheight

### LINKED ISSUE #4609: React warnings in console with ExpandableTile
Here's a code sandbox.  You can see all the versions in there.
https://codesandbox.io/s/codesandbox-gx69y?fontsize=14

Here's a screen shot of the error in the code sandbox.  The console is not expanded by default.  You have to click on the error number.
image

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4609 

#### Changelog

**Changed**

- define `expanded` and `onBeforeClick` explicitly so they aren't included in misc props that get passed to the component & cause 2 errors identified in #4609 
- set default *number* values for `tileMaxHeight` and `tilePadding` to prevent the `NaN` error identified in https://github.com/carbon-design-system/carbon/issues/4609#issuecomment-551970266

Also, optional but recommended:
- `expanded` state shares a name with `expanded` prop. So to prevent confusion/collision, I suggest ~removing `const { expanded } = this.state` and just referencing `this.state.expanded` instead.~ using `const { expanded: isExpanded` } = this.state`

### CODE REVIEW

File: packages/react/src/components/Tile/Tile.js [hunk 1]
```diff
@@ -503,29 +504,29 @@ export class ExpandableTile extends Component {
...
       tilePadding, // eslint-disable-line
       handleClick, // eslint-disable-line
       tileCollapsedIconText, // eslint-disable-line
       tileExpandedIconText, // eslint-disable-line
+      onBeforeClick, // eslint-disable-line
       light,
       ...other
     } = this.props;
 
-    const { expanded } = this.state;
```
Comment (jendowns) [inline packages/react/src/components/Tile/Tile.js:515]: IMHO this is confusing because there is a prop called `expanded` already 😅 
So I suggest removing it and just referencing the state with `this.state.expanded` instead.

Comment (asudoh) [reply packages/react/src/components/Tile/Tile.js:515]: Or you can do: `const { expanded: expandedState } = this.state`?

**Review by asudoh — APPROVED** [review]
LGTM just a small suggestion - Thanks @jendowns!

File: packages/react/src/components/Tile/Tile.js (hunk 1 above)
Comment (jendowns) [reply packages/react/src/components/Tile/Tile.js:515]: Thanks @asudoh! I went ahead and updated the code per your suggestion.

**Review by emyarod — APPROVED** [review]
looks good to me

File: packages/react/src/components/Tile/Tile.js [hunk 2]
```diff
@@ -503,29 +504,31 @@ export class ExpandableTile extends Component {
...
+    const { expanded: expandedState } = this.state;
```
Comment (joshblack) [inline packages/react/src/components/Tile/Tile.js]: Maybe we could use this name to match our other conventions?

```suggestion
    const { expanded: isExpanded } = this.state;
```

**Review by joshblack — CHANGES_REQUESTED** [review]

**Comment by jendowns** [comment]
Thanks @joshblack! Just applied your suggestion 👍

**Review by joshblack — APPROVED** [review]
