### PR TITLE
fix(slider): treat value of 0 as valid instead of falsy

### LINKED ISSUE #21611: [Bug]: slider initialized with 0 treated as falsy instead of true zero
### Package

@carbon/web-components

### Browser

Chrome

### Package version

latest

### React version

_No response_

### Description

When initializing a slider with value 0, it seems to be treated as a falsy value instead of really meant zero.

https://web-components.carbondesignsystem.com/?path=/story/components-slider--default&args=max:10;min:-10;step:1;value:0

In the example above, when the value is set to 0, it seems to misinterpret the value and puts the knob to leftmost, while the user might want it to be in the middle. If you drag the knob to middle it shows the desired value 0.

This is working as expected in browser native `input type=range`: https://codepen.io/chadluo/pen/myENKbN

### Reproduction/example

https://web-components.carbondesignsystem.com/?path=/story/components-slider--default&args=max:10;min:-10;step:1;value:0

### Steps to reproduce

1. create a slider with negative min
2. set the value to 0
3. observe the knob is initialized to the leftmost, while it is expected in middle

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by MarianaAa01**
Closes #21611 

When the slider is initialized with value 0 and a negative min, the knob is placed at the leftmost position instead of the correct position. This happens because `if (value)` treats 0 as falsy, falling back to ` _cachedRate` instead of computing the correct rate.

### Changelog

**Changed**

- Fixed slider value handling when value is 0 by replacing the falsy check `if (value)` with an explicit check `if (value || value === 0)`, ensuring 0 is treated as a valid value instead of falling back to _cachedRate.

#### Testing / Reviewing

- Initialize <cds-slider> with value="0" and confirm el.value === 0.
- Confirm the thumb reflects aria-valuenow="0" on initial render.
- Simulate click at 50% of the track and ensure value remains 0.
- Simulate click at 90% of the track and verify the value updates proportionally.

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] ~Updated documentation and storybook examples~
- [x] Wrote passing tests that cover this change
- [ ] ~Addressed any impact on accessibility (a11y)~
- [ ] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by MarianaAa01** [comment]
I have read the DCO document and I hereby sign the DCO.

File: packages/web-components/src/components/slider/slider.ts [hunk 1]
```diff
@@ -108,7 +108,7 @@ class CDSSlider extends HostListenerMixin(FormMixin(FocusMixin(LitElement))) {
   private get _rate() {
     const { max, min, value } = this;
     // Copes with out-of-range value coming programmatically or from `<cds-slider-input>`
-    if (value) {
+    if (value != null) {
```
Comment (adamalston) [inline packages/web-components/src/components/slider/slider.ts]: Is `''` supposed to pass this check?

Comment (MarianaAa01) [reply packages/web-components/src/components/slider/slider.ts]: Is it better then to do `if (value || value === 0)` or to do `if (value !== null || value !== undefined || value !== '')`? Because it looks as if the functionality inside the if statement expects `value` to be a number but currently it accepts any non falsy value.

Comment (adamalston) [reply packages/web-components/src/components/slider/slider.ts]: `value || value === 0` is the safer change here.

`value !== null || value !== undefined || value !== ''` would always evaluate to `true`, so it would not guard anything. Even if that were changed to `&&`, it would still allow `NaN` through.

Longer term, after this bug is fixed, this code could probably be improved with `Number.isFinite(value)` so it only accepts numeric values. That's a separate change though.

File: packages/web-components/src/components/slider/__tests__/slider-test.js [hunk 2]
```diff
@@ -493,4 +493,51 @@ describe('cds-slider', () => {
...
+    await el.updateComplete;
+    expect(el.value).to.equal(0);
+
+    slider.dispatchEvent(
+      new MouseEvent('click', { clientX: 90, bubbles: true })
+    );
+    await el.updateComplete;
+    const expectedValue = -10 + (90 / 100) * (10 - -10);
+    expect(el.value).to.equal(expectedValue);
+  });
```
Comment (adamalston) [inline packages/web-components/src/components/slider/__tests__/slider-test.js:546]: Should there be an assertion that verifies the initial rendered position for `value` is `0`? The getter change affects `_rate`, so the observable behavior is that the thumb renders at the wrong position on initial load, but this test only checks `el.value` and click behavior, which seems like it would have passed without the fix.

File: packages/web-components/src/components/slider/slider.ts [hunk 3]
```diff
@@ -136,7 +136,7 @@ class CDSSlider extends HostListenerMixin(FormMixin(FocusMixin(LitElement))) {
   private get _rateUpper() {
     const { max, min, unstable_valueUpper } = this;
     // Copes with out-of-range value coming programmatically or from `<cds-slider-input>`
-    if (unstable_valueUpper) {
+    if (unstable_valueUpper != null) {
```
Comment (adamalston) [inline packages/web-components/src/components/slider/slider.ts]: I don't see this change covered in the test. Am I missing something? If not, could you add coverage?

File: packages/web-components/src/components/slider/__tests__/slider-test.js (hunk 2 above)
Comment (MarianaAa01) [reply packages/web-components/src/components/slider/__tests__/slider-test.js:546]: I've added `expect(thumbWrapper.style.left).to.equal('50%')` to verify the initial rendered position. It runs after `updateComplete` but before any click events, so it covers the initial load behavior this fix addresses. Let me know if this looks good!

File: packages/web-components/src/components/slider/__tests__/slider-test.js [hunk 4]
```diff
@@ -493,4 +493,55 @@ describe('cds-slider', () => {
...
+      height: 0,
+      x: 0,
+      y: 0,
+      toJSON: () => {},
+    });
+
+    const thumb = el.shadowRoot.querySelector('#thumb');
+    expect(thumb).to.exist;
+    expect(thumb.getAttribute('aria-valuenow')).to.equal('0');
+    expect(thumbWrapper.style.left).to.equal('50%');
```
Comment (adamalston) [inline packages/web-components/src/components/slider/__tests__/slider-test.js:532]: Possibly related to https://github.com/carbon-design-system/carbon/pull/21864#discussion_r2982791813. This assertion fails for me locally.

```sh
yarn workspace @carbon/web-components exec web-test-runner --files src/components/slider/__tests__/slider-test.js
```

```console
 ❌ cds-slider > should correctly initialize with value 0 and respond to track click
      AssertionError: expected '0%' to equal '50%'
      + expected - actual

      -0%
      +50%

      at n.<anonymous> (src/components/slider/__tests__/slider-test.js:532:40)
```

Comment (MarianaAa01) [reply packages/web-components/src/components/slider/__tests__/slider-test.js:532]: Could it be that since the comment mentions value can come from `<cds-slider-input>`, it might arrive as a string and cause unexpected results in the calculation?

I just wrapped `value` with `Number()` directly in the calculation to keep it consistent with how `max` and `min` are already handled. All tests pass with this, what do you think?

Comment (adamalston) [reply packages/web-components/src/components/slider/__tests__/slider-test.js:532]: The type conversion explanation makes sense.

**Review by devadula-nandan — APPROVED** [review]

**Review by heloiselui — APPROVED** [review]
