### PR TITLE
fix(ComposedModal): add accessible name and aria-label prop

### LINKED ISSUE #6543: Carbon Compose Modal accessibility violation
## Detailed description

experiencing same/similar issue that was in ticket https://github.com/carbon-design-system/carbon/issues/4587. `An interactive element/widget must have an accessible name.` violation is thrown on top level of compose modal component. can be seen in both sample application below and in story book here https://react.carbondesignsystem.com/?path=/story/composedmodal--example-usage-with-trigger-button

> What version of the Carbon Design System are you using?

 - versions, also found in codesandbox: 
    "carbon-components": "10.16.0",
    "carbon-components-react": "7.16.0",
    "carbon-icons": "7.0.7",
    "react": "16.3.1",
    "react-dom": "16.3.1",

> What did you expect to happen?

- no accessibility violations

> What WCAG 2.1 checkpoint does the issue violate?

https://aat.w3ibm.mybluemix.net/token/4950d599-abf0-4c72-b249-9eed7e3bf02e/82ec2f72-e53b-4c22-98b3-faab6bd311db/archives/2020JanDeploy//doc/w3/help/en-US/idhi_accessibility_check_g1156.html

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/carbon-components-react-du1ip?file=/src/index.js
## Additional information

Screen Shot 2020-07-24 at 9 21 44 AM

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/6543

Fixes a11y issues with `ComposedModal`

#### Changelog

**New**

- `ariaLabel` prop for `ComposedModal`
-  `aria-modal` attribute added

**Changed**

- `ModalHeader` now uses `h2` and `h3` instead of `p` elements

#### Testing / Reviewing

Ensure there are no a11y violations with Composed Modal

### CODE REVIEW

File: packages/react/src/components/ComposedModal/ComposedModal.js [hunk 1]
```diff
@@ -33,6 +34,11 @@ export default class ComposedModal extends Component {
   endSentinel = React.createRef();
 
   static propTypes = {
+    /**
+     * Specify the aria-label for bx--modal-container
+     */
+    ariaLabel: PropTypes.string,
```
Comment (joshblack) [inline packages/react/src/components/ComposedModal/ComposedModal.js]: This is definitely a point where the codebase is split, but would you want to do `aria-label` if doing the DOM attribute and `label` if we're setting it automatically for folks?

In other words, if someone is explicitly setting an ARIA label then they use `aria-label` as the prop.

File: packages/react/src/components/ComposedModal/ComposedModal.js [hunk 2]
```diff
@@ -22,6 +22,7 @@ export default class ComposedModal extends Component {
   state = {};
 
   static defaultProps = {
+    ariaLabel: 'modal-container',
```
Comment (joshblack) [inline packages/react/src/components/ComposedModal/ComposedModal.js]: Definitely a bummer that we can't make this required without breaking people, would there be a good prop that we could derive a meaningful label from, potentially?

Comment (tw15egan) [reply packages/react/src/components/ComposedModal/ComposedModal.js]: I originally didn't think we'd be able to, but after taking a deeper look I've modified the code a bit so that it will only generate one if a user does not specify their own `aria-label` and will be based on the `label`, matching `Modal` functionality

**Comment by tw15egan** [comment]
@joshblack updated!

**Review by dakahn — APPROVED** [review]
Great work. Reads well in testing with NVDA on Firefox latest Windows 10

**Comment by tw15egan** [comment]
@joshblack let me know if this solution works 👍

**Review by joshblack — APPROVED** [review]
