### PR TITLE
fix(a11y): dap errors with MultiSelect.Filterable

### LINKED ISSUE #6570: DAP errors with MultiSelect.Filterable
I am seeing this with
"carbon-components": "10.14.0",
"carbon-components-react": "7.14.0",

It is also reproducible with the Carbon React storybook.

image

### PR DESCRIPTION
**Pull request by rjhenriquez**
Closes #6570

This PR fixes accessibility violations with MultiSelect.Filterable

#### Changelog

**Changed**

MultiSelect component

#### Testing / Reviewing

Open the DAB tool in the [Multiselect Filterable component](http://localhost:9000/?path=/story/multiselect--filterable)
Make sure all violations are cleared

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Makes sense to me with `role="option"` on the items. Any second thoughts on the changes @dakahn ? Seems like group was added back in the refactor of downshift earlier this year

File: packages/react/src/components/MultiSelect/FilterableMultiSelect.js [hunk 1]
```diff
@@ -398,9 +398,9 @@ export default class FilterableMultiSelect extends React.Component {
                       aria-controls={`${id}__menu`}
                       aria-autocomplete="list"
                       ref={(el) => (this.inputNode = el)}
+                      id={`${id}-input`}
```
Comment (joshblack) [inline packages/react/src/components/MultiSelect/FilterableMultiSelect.js:401]: Might make sense for the passed in `id` to be on the `<input>` instead of the field since folks seem to use it to target the input in selenium-based tests 👀

**Review by dakahn — APPROVED** [review]
seems cool to me, i'll do a deeper pass whenever we update this with the `useMultiselect` hook
