### PR TITLE
fix(number-input): adjust invalid logic and add proptype check for value

### LINKED ISSUE #4294: Number input does not correctly apply `aria-invalid` & `data-invalid` when error is present
## Detailed description

`carbon-components-react`: `7.7.0`

The way the `aria-invalid` and `data-invalid` attributes are written in the `NumberInput` React component, the *only* way that these two attributes can be added to the underlying input element is if the `invalid` prop is updated to `true` by the user:

https://github.com/carbon-design-system/carbon/blob/4b03c81d2fa321c356a10432ad192242d78ae172/packages/react/src/components/NumberInput/NumberInput.js#L387-L389

As it stands right now, if you go the storybook demo & enter something invalid into the number input, `aria-invalid` and `data-invalid` are not added to the input:
Screen Shot 2019-10-10 at 1 45 37 PM

Again this is because the `invalid` prop is false (as shown below in the React Chrome extension). Though the value of `invalid` in this case is understandable because it is user-provided info...
Screen Shot 2019-10-10 at 1 44 54 PM

## Possible solution
I think an invalid state could perhaps be tracked within this component, as a way of properly applying `aria-invalid` and `data-invalid`? 🤔

### LINKED ISSUE #4996: NumberInput: Initial value cannot be empty string due to PropTypes
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

PropTypes for both value and defaultValue are set to Number so you cannot have it's initial value as an empty string despite the allowEmpty property. The following is logged to the console:

`Warning: Failed prop type: Invalid prop `value` of type `string` supplied to 'NumberInput', expected 'number'.`

## Additional information

https://codesandbox.io/s/pensive-dhawan-wh9vs

### LINKED ISSUE #4997: NumberInput: Empty string (with allowEmpty) only valid if range includes 0
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Due to the following check in `NumberInput.js`:

` (!allowEmpty && this.state.value === '') ||
      this.state.value > max ||
      this.state.value < min`

The allowEmpty check is separate from the range so the empty string gets treated as zero for the min/max range check, meaning that an empty string is only consider valid (despite allowEmpty) if the range includes zero

## Additional information

https://codesandbox.io/s/beautiful-wind-h7viq

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #4294 
Closes #4997 
Closes #4996  

Done during mob programming with @joshblack. 
This PR adjusts the way that `data-invalid` and `aria-invalid` were being set by assigning all invalidation logic to  `isInputInvalid` and adjusts the min/max valid check so that `allowEmpty` works as expected. This expands the proptype check for `value` and `defaultValue` to include string so that the allowEmpty state of '' doesn't create a warning and then adds a check in `getDerivedStateFromProps` so that a user can't enter any string except an empty one.  

#### Changelog

**New**

- test for updating value to empty string when `allowEmpty` is true
- `isInputInvalid` logic

**Changed**

-  proptype for `value` and `defaultValue` 

**Removed**

- {{removed thing}}

#### Testing / Reviewing

Verify that the Number Input works as expected and that it resolves the issues from #4294, #4997, #4996. Mainly check that if `allowEmpty` is true, the error doesn't show up for the empty state and verify that `aria-invalid` and `data-invalid` correspond to when a number is invalid.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
A triple whammy, nice work! Tested a few scenarios and they all work as expected 👍 ✅

**Comment by asudoh** [comment]
@abbeyhrt Thank you for jumping in! Let me take some time to review this given it seems change in some key logic in the component. Don't hesitate to ping me if you don't hear back in a reasonable amount of time.

File: packages/react/src/components/NumberInput/NumberInput.js [hunk 1]
```diff
@@ -171,14 +156,16 @@ class NumberInput extends Component {
...
-  /**
-   * The DOM node refernce to the `<input>`.
-   * @type {HTMLInputElement}
-   */
-  _inputRef = null;
-
   static getDerivedStateFromProps({ min, max, value = 0 }, state) {
     const { prevValue } = state;
+
+    if (typeof value === 'string' && value === '' && state.value !== '') {
```
Comment (asudoh) [inline packages/react/src/components/NumberInput/NumberInput.js]:
```suggestion
    if (!useControlledStateWithValue && value === '' && prevValue !== '') {
```

* Returning non-`null` value, which means changing the state to the returning value, whenever `value` prop is an empty string and `value` state is not an empty string causes canceling any state update (to non-empty string, e.g. upon up/down buttons or user's type) if `value` prop is an empty string. The problem is observed with `<NumberInput value="" />` where it doesn't allow user to make any edit at all. Wondering if you simply wanted to detect update in `value` prop to an empty string, which led to my suggestion above. Note that `gDSFP` is called for state update requests in addition to prop updates.
* `useControlledStateWithValue` flag must make the entire `gDSFP` no-op (by returning `null`). The purpose of flag `useControlledStateWithValue` is not doing any `value` state update from `value` prop
* `typeof value === 'string'` is redundant if we are doing strict equal check of `value` with an empty string (given strict equal check involves type checking)

File: packages/react/src/components/NumberInput/NumberInput.js [hunk 2]
```diff
@@ -310,12 +318,25 @@ class NumberInput extends Component {
...
+    // If the user supplied `invalid` through props, we'll defer to the passed in value
+    if (invalid) {
+      isInputInvalid = true;
+    } else {
+      // Otherwise, if we don't allow an empty value then we check to see
+      // if the value is empty, or if it is out of range
+      if (!allowEmpty && this.state.value === '') {
+        isInputInvalid = true;
+      } else {
+        if (this.state.value > max || this.state.value < min) {
```
Comment (asudoh) [inline packages/react/src/components/NumberInput/NumberInput.js]:
```suggestion
        if (this.state.value !== '' && (this.state.value > max || this.state.value < min)) {
```

Looks that #4997 was not fixed in this PR's code. #4997 specifically asks for the following scenario:

> ... meaning that an empty string is only consider valid (despite `allowEmpty`) if **the range includes zero**

The problem is observed by setting `10` to `min`, `100` to `max`, and `true` to `allowEmpty`. Above suggested change seems to fix the problem.

**Review by asudoh — COMMENTED** [review]
Put a few comments, please don't hesitate to ping me if you have any questions. Thank you again for jumping in @abbeyhrt!

File: packages/react/src/components/NumberInput/NumberInput.js (hunk 2 above)
Comment (abbeyhrt) [reply packages/react/src/components/NumberInput/NumberInput.js]: Ah yeah, good catch and thanks for looking into this!

File: packages/react/src/components/NumberInput/NumberInput.js (hunk 1 above)
Comment (asudoh) [reply packages/react/src/components/NumberInput/NumberInput.js]: @abbeyhrt Any thoughts on this...? Thanks!

Comment (abbeyhrt) [reply packages/react/src/components/NumberInput/NumberInput.js]: I'll make the changes for the last two points, those seem good to me 👍 Could you help me understand your first point?  The intent behind it was to prevent anybody from setting the value to anything but an empty string or a number, could you provide steps for me to reproduce the problem if `value` is set to an empty string?

**Review by asudoh — APPROVED** [review]
Thanks @abbeyhrt for all the updates!
