### PR TITLE
fix(CodeSnippet): use tooltip styles for feedback and add animation

### LINKED ISSUE #4604: (code snippet) Need to inherit tooltip component for feedback message.
Currently the tooltip that appears for the feedback message does not have the correct spacing and the text is very close to the container.

Example:

We need to be using the tooltip component in these scenarios for code snippet.

### LINKED ISSUE #4954: CodeSnippet's copy button is not positioned correctly
The CodeSnippet's copy button is not positioned correctly in `single` mode. It looks like the `.bx--copy-btn` class is overriding the `position` style to `relative` rather than the old value of `absolute`.

Using:
Chrome: Version 75.0.3770.142 (Official Build) (64-bit)
`carbon-components@10.9.0`
`carbon-components-react@7.9.0`

Screenshot:
Screen Shot 2020-01-06 at 10 18 55 AM

It looks like the style is coming from the `CopyButton` component. My import order is:
```
...
@import 'carbon-components/scss/components/code-snippet/code-snippet';
@import 'carbon-components/scss/components/copy-button/copy-button';
...
```

### PR DESCRIPTION
**Pull request by emyarod**
Closes #4604

Closes #4954

ref #4711 #4715

This PR styles the code snippet and `<Copy />` component to use tooltip visual style rules along with the tooltip fade animations

#### Testing / Reviewing

Ensure each code snippet variant looks and functions as expected

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
The hover color change is not showing up on the single line and multi line code snippets in react and vanilla.

File: packages/react/src/components/Copy/Copy.js [hunk 1]
```diff
@@ -6,91 +6,98 @@
...
+  onClick,
+  ...other
+}) {
+  const [animation, setAnimation] = useState('');
+  const timeoutId = useRef(undefined);
+  const classNames = classnames(className, {
+    [`${prefix}--copy-btn--animating`]: animation,
+    [`${prefix}--copy-btn--${animation}`]: animation,
+  });
+  const feedbackClassNames = classnames(
```
Comment (asudoh) [inline packages/react/src/components/Copy/Copy.js]: Seems that we no longer need to use `classnames` here...?

File: packages/react/src/components/Copy/Copy.js [hunk 2]
```diff
@@ -6,91 +6,98 @@
...
+    `${prefix}--assistive-text`,
+    `${prefix}--copy-btn__feedback`
+  );
+  const handleClick = event => {
+    setAnimation('fade-in');
+    timeoutId.current = setTimeout(() => {
```
Comment (asudoh) [inline packages/react/src/components/Copy/Copy.js]: Need to do `clearTimeout()` for existing `timeoutId`.

**Review by asudoh — COMMENTED** [review]
Just a couple of things - Thanks @emyarod!

File: packages/react/src/components/Copy/Copy.js (hunk 1 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js]: removed for `Copy` and `CopyButton`

File: packages/react/src/components/Copy/Copy.js (hunk 2 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js]: fixed for `Copy` and `CopyButton`

Comment (asudoh) [reply packages/react/src/components/Copy/Copy.js]: Thanks! Some additional thing we need (my apologies not being clear enough):

1. Check if `timeoutId.current` exists at here
2. Clearing `timeoutId.current` in `setTimeout()` callback

**Review by asudoh — COMMENTED** [review]
Thank you for your quick update @emyarod!

**Review by laurenmrice — APPROVED** [review]
lgtm 👍

File: packages/react/src/components/CopyButton/CopyButton.js [hunk 3]
```diff
@@ -6,8 +6,9 @@
  */
 
 import PropTypes from 'prop-types';
-import React, { useState, useRef, useEffect } from 'react';
+import React, { useState, useEffect, useCallback } from 'react';
 import classnames from 'classnames';
+import debounce from 'lodash/debounce';
```
Comment (joshblack) [inline packages/react/src/components/CopyButton/CopyButton.js]: I believe we use the direct package in our `dependencies` instead of the namespace

```suggestion
import debounce from 'lodash.debounce';
```

File: packages/components/src/globals/scss/_keyframes.scss [hunk 4]
```diff
@@ -1,5 +1,5 @@
 //
-// Copyright IBM Corp. 2016, 2018
+// Copyright IBM Corp. 2019
```
Comment (joshblack) [inline packages/components/src/globals/scss/_keyframes.scss]: We should be careful around copyright banner changes, I believe the specific syntax needs to be `Original copyright year, last meaningful update year`. If we want to change it to 2016, 2019 definitely understand but should be across the board to our files and should maintain that two year format as requested by Daniel back in the day.

File: packages/react/src/components/Copy/Copy.js [hunk 5]
```diff
@@ -6,91 +6,101 @@
...
+    [`${prefix}--copy-btn--animating`]: animation,
+    [`${prefix}--copy-btn--${animation}`]: animation,
+  });
+  const handleFadeOut = useCallback(
+    debounce(() => {
+      setAnimation('fade-out');
+    }, feedbackTimeout),
+    [feedbackTimeout]
+  );
+  const handleClick = useCallback(
```
Comment (joshblack) [inline packages/react/src/components/Copy/Copy.js]: Style-nit: don't use `useCallback` unless it's for identity or we can show we have a performance problem without it.

File: packages/react/src/components/Copy/Copy.js [hunk 6]
```diff
@@ -6,91 +6,101 @@
...
+    event => {
+      setAnimation('fade-in');
+      onClick(event);
+      handleFadeOut();
+    },
+    [onClick, handleFadeOut]
+  );
+  const handleAnimationEnd = event => {
```
Comment (joshblack) [inline packages/react/src/components/Copy/Copy.js:41]: Style-nit: use function declarations for event handlers

File: packages/react/src/components/Copy/Copy.js [hunk 7]
```diff
@@ -6,91 +6,101 @@
...
+      {...other}>
+      {children}
+      <span
+        className={`${prefix}--assistive-text ${prefix}--copy-btn__feedback`}>
+        {feedback}
+      </span>
+    </button>
+  );
+}
+Copy.propTypes = {
```
Comment (joshblack) [inline packages/react/src/components/Copy/Copy.js:73]: Style-nit: newline

```suggestion

Copy.propTypes = {
```

File: packages/react/src/components/Copy/Copy.js [hunk 8]
```diff
@@ -6,91 +6,101 @@
...
-    );
-  }
-}
+  /**
+   * Specify an optional `onClick` handler that is called when the underlying
+   * <button> is clicked
+   */
+  onClick: PropTypes.func,
+};
+Copy.defaultProps = {
```
Comment (joshblack) [inline packages/react/src/components/Copy/Copy.js:102]: Style-nit: newline

```suggestion

Copy.defaultProps = {
```

File: packages/react/src/components/Copy/Copy.js [hunk 9]
```diff
@@ -6,91 +6,101 @@
...
+      handleFadeOut();
+    },
+    [onClick, handleFadeOut]
+  );
+  const handleAnimationEnd = event => {
+    if (event.animationName === 'hide-feedback') {
+      setAnimation('');
+    }
+    if (other.handleAnimationEnd) {
+      other.handleAnimationEnd(event);
```
Comment (joshblack) [inline packages/react/src/components/Copy/Copy.js]: Where is `other.handleAnimationEnd` coming from?

File: packages/react/src/components/Copy/Copy.js [hunk 10]
```diff
@@ -6,91 +6,101 @@
...
-    if (typeof this.timeoutId !== 'undefined') {
-      clearTimeout(this.timeoutId);
-      delete this.timeoutId;
-    }
-  }
+  return (
+    <button
+      type="button"
+      className={classNames}
+      onClick={handleClick}
```
Comment (joshblack) [inline packages/react/src/components/Copy/Copy.js]: One thing we may want to start doing is using `composeEventHandlers` instead of proxying the call to `onClick` in the handler so that the consumer could prevent the event from firing if they wanted to.

```suggestion
      onClick={composeEventHandlers([onClick, handleClick])}
```

File: packages/react/src/components/Copy/Copy.js [hunk 11]
```diff
@@ -6,91 +6,101 @@
...
+  feedbackTimeout,
+  onClick,
+  ...other
+}) {
+  const [animation, setAnimation] = useState('');
+  const classNames = classnames(className, {
+    [`${prefix}--copy-btn--animating`]: animation,
+    [`${prefix}--copy-btn--${animation}`]: animation,
+  });
+  const handleFadeOut = useCallback(
```
Comment (joshblack) [inline packages/react/src/components/Copy/Copy.js:31]: Would it make sense for this work to be in an effect parameterized by `animation` changing? Something like:

```jsx
useEffect(() => {
  if (animation !== 'fade-in') {
    return;
  }

  const timeoutId = window.setTimeout(() => {
    setAnimation('fade-out');
  }, [feedbackTimeout]);

  return () => {
    window.clearTimeout(timeoutId);
  };
}, [animation, feedbackTimeout]);
```

**Review by joshblack — DISMISSED** [review]

File: packages/react/src/components/Copy/Copy.js (hunk 5 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js]: `useCallback` is necessary here for referential equality. without it the tooltip will not fade out because the `debounce` code receives a new callback function reference (since component will rerender before the `handleFadeOut` method fires)

File: packages/react/src/components/Copy/Copy.js (hunk 6 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js:41]: just wondering is there a reason behind this? a function declaration would be hoisted, so in that case we might as well be advocating for all function declarations to be made at the top of their scopes

File: packages/react/src/components/Copy/Copy.js (hunk 10 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js]: in this case wouldn't preventing the event handler interfere with the desired component UX?

File: packages/react/src/components/Copy/Copy.js (hunk 11 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js:31]: does this eliminate our debouncing then? I moved towards using debounce to eliminate the need for managing timers and refs

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Review by aledavila — APPROVED** [review]
lgtm

File: packages/react/src/components/Copy/Copy.js (hunk 11 above)
Comment (joshblack) [reply packages/react/src/components/Copy/Copy.js:31]: Got it, is `handleFadeOut` called multiple time which is why we need debounce here?

File: packages/react/src/components/Copy/Copy.js (hunk 5 above)
Comment (joshblack) [reply packages/react/src/components/Copy/Copy.js]: Totally got that for `handleFadeOut`, is the usage of it inside of `handleClick` causing this, or is it something else?

File: packages/react/src/components/Copy/Copy.js (hunk 6 above)
Comment (joshblack) [reply packages/react/src/components/Copy/Copy.js:41]: I think at this point it's just as a style consistency point tbh, if we have hard numbers one way or another could definitely update the style guide!

File: packages/react/src/components/Copy/Copy.js (hunk 10 above)
Comment (joshblack) [reply packages/react/src/components/Copy/Copy.js]: It could, but would assume that the consumer understands this and is intercepting it and preventing it intentionally. Let me know if that is a bad assumption here

File: packages/react/src/components/Copy/Copy.js (hunk 11 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js]: yeah for both the click handler and fadeout handler it's for cleanup purposes

File: packages/react/src/components/Copy/Copy.js (hunk 6 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js:41]: if it isn't part of the style guide yet I think there should be a discussion about that rule. I lean more towards function expressions in these cases to avoid function hoisting

File: packages/react/src/components/Copy/Copy.js (hunk 5 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js]: I originally replied in the wrong thread but yeah for both the click handler and fadeout handler it's for cleanup purposes

File: packages/react/src/components/Copy/Copy.js (hunk 11 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js:31]: yeah the tooltip needs to persist if the button is clicked again and should fade out after the timeout expires for the most recent click of the button. with `useEffect` all clicks following the first click are ignored until the tooltip fades out (based on the timeout from the very first click). so we debounce the click and fadeout handlers because they can fire multiple times

**Review by abbeyhrt — APPROVED** [review]

**Comment by joshblack** [comment]
@asudoh Please confirm if review comments have been addressed before dismissing a review. The most recent comments were from 2 days ago when the previous interaction was a month back and I had not had a chance to respond yet. Feel free to reach out on Slack in our squad channel 👍

File: packages/react/src/components/Copy/Copy.js (hunk 6 above)
Comment (joshblack) [reply packages/react/src/components/Copy/Copy.js:41]: @emyarod it is in the style guide over in: https://github.com/carbon-design-system/carbon/blob/master/docs/style.md#writing-a-component

Feel free to bring up reasons against it in our Slack channel or a PR! We only use this style since it's what React is currently using in their official documentation and there weren't any glaring reasons to stray from it.

File: packages/react/src/components/Copy/Copy.js (hunk 11 above)
Comment (joshblack) [reply packages/react/src/components/Copy/Copy.js:31]: Hmm, this seems like a use-case we could achieve with `useEffect`, right? What would make the clicks become ignored? It seemed like on click we want to update the animation state and then enqueue a timeout, cancelling it if the button is clicked and creating a new one. Is there something else that I'm missing here? 👀

File: packages/components/src/components/code-snippet/_code-snippet.scss [hunk 12]
```diff
@@ -50,6 +52,37 @@
...
+    .#{$prefix}--copy-btn__feedback {
+      @include tooltip--content('icon');
+      clip: auto;
+      margin: auto;
+      overflow: visible;
+      display: none;
+    }
+    @include tooltip--placement('icon', 'bottom', 'center');
+
+    &.#{$prefix}--copy-btn--animating::before,
```
Comment (joshblack) [inline packages/components/src/components/code-snippet/_code-snippet.scss:70]: I know this was merged but is there any way we can un-nest styles?

**Comment by asudoh** [comment]
I expect responses to review comments are treated as request for re-reviews, and expect that reviewers respond in timely manner. Otherwise reviews are seen as stale.

File: packages/react/src/components/Copy/Copy.js (hunk 11 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js:31]: if the timeout management occurs in `useEffect` doesn't that require another render? patching with `useEffect` results in `clearTimeout` firing after the timeout has already completed

gif

File: packages/react/src/components/Copy/Copy.js (hunk 6 above)
Comment (emyarod) [reply packages/react/src/components/Copy/Copy.js:41]: I don't see anything about avoiding function expressions for event handlers in the style guide or the React documentation. can you elaborate on that?

File: packages/components/src/components/code-snippet/_code-snippet.scss (hunk 12 above)
Comment (emyarod) [reply packages/components/src/components/code-snippet/_code-snippet.scss:70]: will be addressed in https://github.com/carbon-design-system/carbon/pull/5006

**Comment by vpicone** [comment]
@joshblack @asudoh i think clicking the “request re-review” button should count as requesting a re-review. 

We all get a lot of notifications, missing a single reply shouldn’t count as an implicit approval.

**Comment by asudoh** [comment]
I read through all notifications of this repo.

**Comment by alisonjoseph** [comment]
Just wanted to quickly jump in here and say that yes we should all be timely in reviewing and responding to PRs/comments, but we should also feel empowered to reach out on slack and poke someone if it seems they’ve missed something. (especially around the holidays when notifications could easily get missed) 🙏
