### PR TITLE
fix(date-picker-input): remove duplicate error/warn icons in fluid mode

### LINKED ISSUE #21023: [Bug]: visual bug on FluidDatePickerInput when invalid prop is true
### Package

@carbon/react

### Browser

_No response_

### Package version

1.95.0

### React version

_No response_

### Description

Image

When invalid prop is sent on FluidDatePickerInput - two error icons are visible 

```
<FluidDatePicker datePickerType="simple" invalid>
        <FluidDatePickerInput
          placeholder="mm/dd/yyyy"
          labelText={'hello'}
          id="date-picker-simple"
          invalidText="helloimerror"
        />
      </FluidDatePicker>
```

### Reproduction/example

https://stackblitz.com/edit/github-urmuucqu?file=src%2FApp.jsx&preset=node=

### Steps to reproduce

pass invalid prop to FluidDatePickerInput

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by harishjanardhanan**
Closes https://github.com/carbon-design-system/carbon/issues/21023

### Changelog

- Changed

- Removed fluid specific icon render in `DatePicker` component.
- Kept icon only in `DatePickerInput` component for both fluid and non-fluid DatePicker.

Screen recording of story:

https://github.com/user-attachments/assets/b3d28603-090d-4f7a-ad11-be4d64537683

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by harishjanardhanan** [comment]
@emyarod @maradwan26 Could you please review this?

cc - @2nikhiltom @heloiselui

File: packages/react/src/components/DatePicker/DatePicker-test.js [hunk 1]
```diff
@@ -301,48 +301,6 @@ describe('DatePicker', () => {
...
-            placeholder="mm/dd/yyyy"
-            labelText="Date Picker label"
-          />
-        </DatePicker>
-      </FormContext.Provider>
-    );
-    expect(screen.getByText('Warning message')).toBeInTheDocument();
-    expect(screen.queryByText('Invalid date')).not.toBeInTheDocument();
-  });
-
```
Comment (maradwan26) [inline packages/react/src/components/DatePicker/DatePicker-test.js:345]: Is there a reason why these 2 tests were removed?

**Review by maradwan26 — COMMENTED** [review]
The fix functionally looks good to me, just had one question.

File: packages/react/src/components/DatePicker/DatePicker-test.js (hunk 1 above)
Comment (harishjanardhanan) [reply packages/react/src/components/DatePicker/DatePicker-test.js:345]: As we have removed the icon render in the component, this tests makes no sense. That's why.
It would be handled in `DatePickerInput` component

Comment (maradwan26) [reply packages/react/src/components/DatePicker/DatePicker-test.js:345]: I see, okay. Should the `invalidText` and `warnText` props be removed from DatePicker/FluidDatePicker, then? They currently do nothing and only work in DatePickerInput

Comment (harishjanardhanan) [reply packages/react/src/components/DatePicker/DatePicker-test.js:345]: Have removed `invalidText` and `warnText` from `DatePicker` props. Please review.

**Review by maradwan26 — APPROVED** [review]
LGTM!

**Comment by harishjanardhanan** [comment]
@emyarod @kennylam Please have a look at this once you are available.
cc - @2nikhiltom @heloiselui @maradwan26

**Review by heloiselui — APPROVED** [review]
LGTM!

**Comment by heloiselui** [comment]
@Kritvi-bhatia17 could you take a look at this PR from a design perspective?

**Review by riddhybansal — APPROVED** [review]

**Comment by harishjanardhanan** [comment]
Please add this in merge queue.
Thanks!

**Comment by Kritvi-bhatia17** [comment]
> @Kritvi-bhatia17 could you take a look at this PR from a design perspective?

Although the PR is now closed, I had a chance to review it. The error and warning states appear to be visually resolved. I did notice a few additional observations that could potentially be addressed in a follow‑up issue (I will create that):

**Fluid simple date picker**
- The divider appears to be missing when both the invalid and error states are enabled.
- The focus stroke does not wrap the entire date picker.
- We may need to confirm whether the component should have a fixed width.
image

**Default simple date picker**
- The error and warning messages do not appear to be rendering.
image
