### PR TITLE
fix(ListBox): address DAP violations

### LINKED ISSUE #2827: AVT 1 - React Dropdown has 2 DAP violations
## Environment
Tested on macOS Mojave 10.14.5, Version 74.0.3729.157 (Official Build) (64-bit), with VoiceOver

## Description
DAP found 2 violations (see screenshot)
Screen Shot 2019-05-23 at 2 13 05 PM
Axe-Core found the same issues (see screenshot)
Screen Shot 2019-05-23 at 2 18 12 PM

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2827

This PR addresses a couple of DAP violations in the listbox components

#### Changelog

**Changed**

- add `aria-owns` and `aria-controls` attributes only when the referenced element is rendered

**Removed**

- unneeded list box menu icon `role`

#### Testing / Reviewing

Ensure the listbox components pass a11y testing

### CODE REVIEW

File: packages/react/src/components/ListBox/ListBoxField.js [hunk 1]
```diff
@@ -24,8 +24,8 @@ const ListBoxField = ({ children, id, ...rest }) => (
     role="combobox"
     aria-haspopup="listbox"
     aria-expanded={rest[`aria-expanded`]}
-    aria-owns={`${id}__menu`}
-    aria-controls={`${id}__menu`}
+    aria-owns={(rest[`aria-expanded`] && `${id}__menu`) || null}
```
Comment (joshblack) [inline packages/react/src/components/ListBox/ListBoxField.js:27]: Could we add some tests for these conditionals just to verify what needs to be happening?

File: packages/react/src/components/ListBox/ListBoxMenuIcon.js [hunk 2]
```diff
@@ -28,13 +28,12 @@ const defaultTranslations = {
  * state of the menu for a given `ListBox`
  */
 const ListBoxMenuIcon = ({ isOpen, translateWithId: t }) => {
-  const className = cx({
-    [`${prefix}--list-box__menu-icon`]: true,
+  const className = cx(`${prefix}--list-box__menu-icon`, {
```
Comment (joshblack) [inline packages/react/src/components/ListBox/ListBoxMenuIcon.js:31]: Any reason for the style change? Might help to keep calls to `cx` monomorphic if we can

**Review by joshblack — CHANGES_REQUESTED** [review]

File: packages/react/src/components/ListBox/ListBoxMenuIcon.js (hunk 2 above)
Comment (asudoh) [reply packages/react/src/components/ListBox/ListBoxMenuIcon.js:31]: Looks that this change simply distinguishes constant styles vs. conditional styles.

Comment (joshblack) [reply packages/react/src/components/ListBox/ListBoxMenuIcon.js:31]: Not sure I understand, these are equivalent ways of expressing the same output. I left the note of monomorhpism because `classnames` supports variadic args. If we can defer to one style then it can be optimized in v8 (albeit by an arbitrary amount for this code path). If it's a code style question, then we should bring it up and discuss.

Comment (asudoh) [reply packages/react/src/components/ListBox/ListBoxMenuIcon.js:31]: In case you are thinking of V8 optimization with one style, would you elaborate that? Thanks!

**Review by asudoh — APPROVED** [review]
LGTM :+1: - Thanks @emyarod!

**Comment by asudoh** [comment]
@emyarod Seems that you have done test updates, is it correct? Thanks!

**Comment by emyarod** [comment]
yeah it looks like my comment was created as a pending review comment instead of a single comment. added a test for the dynamic props

**Review by joshblack — APPROVED** [review]

**Review by dakahn — APPROVED** [review]
Thank you so much! Looks great to me on my end. Tested in latest Chrome with DAP Feb 2019 ruleset and I don't see the aforementioned violations. 🏄🏽‍♂️

**Comment by astha-jain** [comment]
Is this solution available for v9 as well?

**Comment by emyarod** [comment]
@astha-jain no this only addresses v10. you can open a ticket referencing this PR and #2827 and we can backport the fix to v9

**Comment by astha-jain** [comment]
@emyarod I created https://github.com/carbon-design-system/carbon/issues/3481. Thank you.
