### PR TITLE
fix(Tag): added new prop titleText to specify title on clear

### LINKED ISSUE #4025: Tag component doesn't offer internationalization / localization hook
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Need to provide a localized version of the title for the filtered tag. Currently always shows `clear filter`

> Is this issue related to a specific component?

Tag component.
The same issue is also present in the multiselect component, where the text `clear all selected items` cannot be overridden. 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

A prop to accept a localized string that will be used for the title element.

> What browser are you working in?

Firefox / Chrome

> What version of the Carbon Design System are you using?

carbon-components-react": "7.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Agile service manager RTM 21/10/2019

## Additional information
Multiselect component 

image

Tag component
image

### PR DESCRIPTION
**Pull request by ankitious**
Closes #4025

#### Changelog

**New**

- Added titleText prop to specify title text on clear button

Testing / Reviewing

- Go to Tab with filter
- Specify titleText prop as a string
- hover over clear button, text should be visible.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
for the sake of consistency can we refactor this to follow the `translateWithId` pattern we have in the rest of the library?

for reference: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/ListBox/ListBoxField.js

**Comment by asudoh** [comment]
@emyarod `translateWithId` is there only for limited set of components - So probably we can leave it as-is?

**Review by joshblack — COMMENTED** [review]
~Ignore me!~

**Review by joshblack — COMMENTED** [review]
Would we want to use the `title` prop directly for this? Wasn't sure if it's being used elsewhere in the component but would be fine to use it directly

**Comment by ankitious** [comment]
@joshblack `title` is not used anywhere else in component, so I have replaced `titleText` to `title` prop. Thanks!

**Comment by ankitious** [comment]
@joshblack I have changed props name to `title`, or  do we want to follow `translateWithId ` pattern suggested by @emyarod 

Please provide your suggestion. Thanks!

**Comment by joshblack** [comment]
@ankitious should be good with `title` here, as I think it's analogous to how we expose labels for folks to customize 😄

**Review by joshblack — APPROVED** [review]

File: packages/react/src/components/Tag/Tag.js [hunk 1]
```diff
@@ -35,11 +43,11 @@ const Tag = ({ children, className, type, filter, disabled, ...other }) => {
   return filter ? (
     <span
       className={tagClasses}
-      title="Clear filter"
+      title={title ? title : 'Clear filter'}
```
Comment (emyarod) [inline packages/react/src/components/Tag/Tag.js]: alternatively we can set a default value for `title` or do

```suggestion
      title={title || 'Clear filter'}
```

to avoid ternary operator

same on line 50

**Review by emyarod — APPROVED** [review]
looks good to me, just one small nitpick

File: packages/react/src/components/Tag/Tag.js (hunk 1 above)
Comment (joshblack) [reply packages/react/src/components/Tag/Tag.js]: Just pushed!

Comment (emyarod) [reply packages/react/src/components/Tag/Tag.js]: wait @joshblack line 50 as well

**Comment by joshblack** [comment]
cc @dakahn including you to double-check a11y on this if you have a sec, I think the component itself may already have an issue given that there is no button for the icon. If there are issues for this, and we're planning on addressing them in the a11y project, does the proposed solution here align with whatever the ideal is? Trying to think if we should be using `aria-label` here now, or not.

**Review by dakahn — APPROVED** [review]
This is fine. Being able to customize the title attribute doesn't really jam up anything we had planned. The aria seems to be adequate in so far as it's read properly by NVDA on Firefox.
