### PR TITLE
fix: BreadcrumbItem aria-current PropType fix

### LINKED ISSUE #15034: [Bug]: Proptype for aria-current in BreadcrumbItem is incorrect
### Package

@carbon/react

### Browser

_No response_

### Package version

v1.40.0

### React version

_No response_

### Description

The PropType definition for 'aria-current' is to broad.  it is currently defined as `'aria-current': PropTypes.oneOfType([PropTypes.string, PropTypes.bool])` however it will need to be modified to match `AriaAttributes['aria-current']`.  This is causing issues with adding Typescript typings as well as the possibility of breaking if the user uses a specific type of <BreadcrumbItem> and sets a non standard 'aria-current' value.

### Reproduction/example

https://codesandbox.io/s/carbon-aria-current-f9lcrj?file=/src/App.js

### Steps to reproduce

This does not show a break, however you can see that eslint is complaining that non standard strings can be used.  There is a code path where the BreadcrumbItem can create a <Link> component and pass it the aria-current value.  <Link> is already typed and only accepts the standard 'aria-current' values as shown below. 
image

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

Cloud

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Tresau**
Closes #15034 

BREAKING CHANGE as it makes a PropType more specific.

The PropType for 'aria-current' in BreadcrumbItem is to broad, this change makes the definition more specific to match AriaAttributes['aria-current'].  Depends on #15033 as this PR is branched from that issue.

#### Changelog

**New**

- n/a

**Changed**

- aria-current proptypes of BreadcrumItem from `string, bool` to `bool, 'false', 'true', 'page', 'step', 'location', 'date', 'time'`

**Removed**

- n/a

#### Testing / Reviewing

Verify that the storybook has updated PropTypes
Verify tests pass
image

### CODE REVIEW

**Comment by Tresau-IBM** [comment]
This will require a snapshot update but I am not certain how best to alter it.

**Comment by alisonjoseph** [comment]
@Tresau-IBM you should able to run `yarn test -u` to update the snapshot, there is also a merge conflict that popped up

**Comment by Tresau-IBM** [comment]
> @Tresau-IBM you should able to run `yarn test -u` to update the snapshot, there is also a merge conflict that popped up

Thank you, will address merge conflict and update snapshot, thank you

File: packages/react/src/components/Breadcrumb/BreadcrumbItem.tsx [hunk 1]
```diff
@@ -0,0 +1,140 @@
...
+import cx from 'classnames';
+import Link from '../Link';
+import { OverflowMenuHorizontal } from '@carbon/icons-react';
+import { usePrefix } from '../../internal/usePrefix';
+import { ForwardRefReturn } from '../../types/common';
+import { Text } from '../Text';
+
+export interface BreadcrumbItemProps
+  extends React.HTMLAttributes<HTMLLIElement> {
+  'aria-current'?: AriaAttributes['aria-current'];
```
Comment (tay1orjones) [inline packages/react/src/components/Breadcrumb/BreadcrumbItem.tsx]: The TypeScript types aren't bound by semver right now and are provided on an as-is basis. I think it's fine to specify this here. It won't be classified as a breaking change.

File: packages/react/src/components/Breadcrumb/BreadcrumbItem.tsx [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+    PropTypes.oneOf([
+      'false',
+      'true',
+      'page',
+      'step',
+      'location',
+      'date',
+      'time',
+    ] as const),
+  ]),
```
Comment (tay1orjones) [inline packages/react/src/components/Breadcrumb/BreadcrumbItem.tsx]: I'm not sure this warrants a breaking change either. [The spec](https://www.w3.org/TR/wai-aria-1.2/#aria-current) is quite clear on what values are allowed, though there is one exception (I bolded below for emphasis)

> The [aria-current](https://www.w3.org/TR/wai-aria-1.2/#aria-current) [attribute](https://www.w3.org/TR/wai-aria-1.2/#dfn-attribute) is a token type. **Any value not included in the list of allowed values SHOULD be treated by [assistive technologies](https://www.w3.org/TR/wai-aria-1.2/#dfn-assistive-technology) as if the value true had been provided.** If the attribute is not present or its value is an empty string or undefined, the default value of false applies and the [aria-current](https://www.w3.org/TR/wai-aria-1.2/#aria-current) [state](https://www.w3.org/TR/wai-aria-1.2/#dfn-state) MUST NOT be exposed by user agents or assistive technologies.

So technically any string is allowable and coalesces to `true`. You could argue these proptypes (plus the typings from React) are incorrect, but I don't think this presents much risk to have specific strings instead of allowing any string. If we get user feedback that some use case is missed, we can roll back this change very easily.

**Review by tay1orjones — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by tw15egan — APPROVED** [review]
