### PR TITLE
fix(components): add support for dart-sass

### LINKED ISSUE #3163: Add support for dart-sass
With angular 8, the angular cli is moving to `sass` and away from `node-sass` (justification: https://github.com/angular/angular-cli/issues/14497).

Browsing issues here, it seems like a number of other projects are also moving away from `node-sass`, which creates friction when bootstrapping a project.

The differences between `sass` and `node-sass` should be minimal, so I'll attempt to add support for `sass` in a PR.

### PR DESCRIPTION
**Pull request by cal-smith**
Closes #3163

dart-sass is the primary implementation of sass - effectively deprecating node-sass ([more on that here](https://sass-lang.com/dart-sass)). Angular and a number of other projects are switching over to dart-sass because of this.

This has a bunch of changes around variable declarations (global variables must now be declared at the global scope - `!global` no longer declares new variables) and a couple changes around `&` (`&` can't be used at the top level, it must be within or preceded by another selector)

At the moment this also changes the build pipeline to use dart-sass as well as Fibers (for better concurrency), but I can revert that if we'd prefer to stick with node-sass for the time being.

### CODE REVIEW

File: packages/components/gulpfile.js [hunk 1]
```diff
@@ -10,6 +10,9 @@ const sass = require('gulp-sass');
 const postcss = require('gulp-postcss');
 const autoprefixer = require('autoprefixer');
 const deduper = require('postcss-discard-duplicates');
+const Fiber = require('fibers');
+
+sass.compiler = require('sass');
```
Comment (cal-smith) [inline packages/components/gulpfile.js]: totally can revert this set of changes :+1:

File: packages/components/src/components/button/_button.scss [hunk 2]
```diff
@@ -213,7 +213,7 @@
     padding: $button-padding-sm;
   }
 
-  &.#{$prefix}--btn--field {
+  .#{$prefix}--btn--field {
```
Comment (cal-smith) [inline packages/components/src/components/button/_button.scss]: `--btn--field` is used elsewhere without `&` so from what I can see it's unnecessary anyway.

File: packages/components/src/globals/scss/_feature-flags.scss [hunk 3]
```diff
@@ -37,7 +37,7 @@ $default-feature-flags: (
 /// @access private
 /// @type Bool
 /// @group feature-flags
-$did-warn-diverged-feature-flags: false !default !global;
+$did-warn-diverged-feature-flags: false !default;
```
Comment (cal-smith) [inline packages/components/src/globals/scss/_feature-flags.scss:40]: `$did-warn-diverged-feature-flags` is declared at the global scope, so `!global` is redundant

File: packages/components/src/globals/scss/_theme-tokens.scss [hunk 4]
```diff
@@ -10,6 +10,338 @@
 @import 'spacing';
 @import './vendor/@carbon/elements/scss/themes/themes';
 
+/// forward declaration of variables (requried with sass 2.0.0)
```
Comment (cal-smith) [inline packages/components/src/globals/scss/_theme-tokens.scss]: The variables declared in the mixin attempt to assign and create global variables ... this isn't allowed in sass 2.0.0, so I've moved the declarations here (but left the same assigns in the mixin) ... I'm not sure if they need to be contained within a mixin, and what that would get us.

**Comment by joshblack** [comment]
Thanks for doing this @cal-smith! 👋 When we chatted with the Sass team earlier this year, they recommending moving over to dart so am definitely interested. It did seem like some of the bigger changes were around global variables so am curious what the repercussions are across the project 👀

**Comment by cal-smith** [comment]
> It did seem like some of the bigger changes were around global variables so am curious what the repercussions are across the project 

For sure ... I did a bit of a naive change over, since I'm not intimately familiar with what that part of the theme system is doing ... doing a quick check everything seemed to be in place.

I know there are a couple other sass projects beyond `/components`, I could flip the switch on those as well. `/components` was just the one we've had the most requests for.

File: packages/components/gulpfile.js (hunk 1 above)
Comment (asudoh) [reply packages/components/gulpfile.js]: Thank you for leaving a note here @cal-smith! Would you be able to add an option to [`cloptions`](https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/components/gulpfile.js#L69-L92) and assign `sass.compiler` if such option is enabled? (Note: Please make sure the short version doesn't collide with one for Gulp itself)

File: packages/components/src/components/button/_button.scss (hunk 2 above)
Comment (asudoh) [reply packages/components/src/components/button/_button.scss]: @emyarod Would you agree?

File: packages/components/src/globals/scss/_feature-flags.scss (hunk 3 above)
Comment (asudoh) [reply packages/components/src/globals/scss/_feature-flags.scss:40]: This is for:

```scss
.foo {
  @import 'carbon-components/scss/globals/scss/styles';
}
```

Given this is a flag to avoid extraneous warnings, the change is good, though.

File: packages/components/src/globals/scss/_theme-tokens.scss (hunk 4 above)
Comment (asudoh) [reply packages/components/src/globals/scss/_theme-tokens.scss]: @cal-smith Given I can see that the original logic for `import-once` stuff, may I ask if Sass 2.0 adoption is imminent in your roadmap? Another reason I wanted to ask this question is that `@carbon/themes` also uses this pattern.

File: packages/components/gulpfile.js [hunk 5]
```diff
@@ -338,6 +341,7 @@ const buildStyles = prod => {
       .pipe(
         sass({
           outputStyle: prod ? 'compressed' : 'expanded',
+          fiber: Fiber,
```
Comment (asudoh) [inline packages/components/gulpfile.js]: IIUC this is for `dart-sass`, is it correct?

**Review by asudoh — COMMENTED** [review]
Thank you so much for jumping in @cal-smith!

File: packages/components/gulpfile.js (hunk 5 above)
Comment (cal-smith) [reply packages/components/gulpfile.js]: Yep ... without `fiber` the compile time is significantly slower when using the async compiler.

**Comment by cal-smith** [comment]
Looks like my test fixes broke the tests 😕 I'll look at it tomorrow ... it runs fine locally so I'm wondering if my local env is just messed up.

File: packages/components/gulpfile.js (hunk 1 above)
Comment (cal-smith) [reply packages/components/gulpfile.js]: Sure 👍 should I default it to `node-sass` or `sass`?

**Comment by joshblack** [comment]
One note just to leave on this PR, we do use `node-sass` for our sass renderer in tests: https://github.com/carbon-design-system/carbon/blob/master/packages/test-utils/scss.js#L67 don't know if that will cause any issues, but might be worth looking at that too 👀 (or we could support multiple renderers, I guess?)

File: packages/components/src/globals/scss/_theme-tokens.scss (hunk 4 above)
Comment (cal-smith) [reply packages/components/src/globals/scss/_theme-tokens.scss]: If I understand the [description here](https://sass-lang.com/documentation/variables#shadowing) and implications of this change correctly, this particular change _should_ be backwards compatible ... for variables I'm not sure the `import-once` logic applies ...

When I was changing this around I initial had all the variables `null`ed out ... somewhat suprisingly this broke several things (since the variables they were using had no value) ... I can dig more into that and see _why_ exactly it was breaking (I believe it was in the typography file)

**Comment by cal-smith** [comment]
Ahh that's probably part of my build issues ... I'll add back `node-sass` for now, until we can do a full `sass` upgrade

**Comment by cal-smith** [comment]
The best option would probably be to swap everything out for `sass` ... that may be something worth scoping for the next iteration

File: packages/components/src/components/button/_button.scss (hunk 2 above)
Comment (emyarod) [reply packages/components/src/components/button/_button.scss]: looks like it was introduced in https://github.com/carbon-design-system/carbon/pull/2719/

I've tested without `&` and it seems unnecessary

**Comment by cal-smith** [comment]
Tests are running successfully now ... just working on the changes @asudoh requested 👍

**Comment by cal-smith** [comment]
(probably be in by next Wednesday ... these holidays and vacations were timed poorly haha)

File: packages/components/gulpfile.js (hunk 1 above)
Comment (asudoh) [reply packages/components/gulpfile.js]: Let's default to `node-sass` for now. It's just about the balance between existing applications using `node-sass` vs. new/modified applications using Dart Sass, though, and we'd flip the switch in next major release.

File: packages/components/src/globals/scss/_theme-tokens.scss (hunk 4 above)
Comment (asudoh) [reply packages/components/src/globals/scss/_theme-tokens.scss]: Good point, probably making compile time slower and possible variable overrides. Given neither of them seems substantial, would you want to just flatten contents in `_theme-tokens.scss`?

File: packages/components/gulpfile.js (hunk 1 above)
Comment (cal-smith) [reply packages/components/gulpfile.js]: Sure, makes sense :+1:

File: packages/components/src/globals/scss/_theme-tokens.scss (hunk 4 above)
Comment (cal-smith) [reply packages/components/src/globals/scss/_theme-tokens.scss]: Sure 👍

**Comment by cal-smith** [comment]
updated 🙌

**Comment by joshblack** [comment]
@cal-smith would you be interested at all in adding tests to verify that our sass can be compiled by both node-sass and dart? I bet we could make `packages/test-utils/scss` pluggable when it comes to renderers

**Comment by cal-smith** [comment]
That's a great idea ... let me dig into that a little bit 🤔

**Comment by cal-smith** [comment]
So, `yarn jest` doesn't do anything for me ... it boots up and then doesn't output anything ... as far as I can tell it's not actually _doing_ anything. I see it running on circleci (Though it still has no output) ... is this right? Am I missing something?

**Comment by cal-smith** [comment]
Okay! So, still doesn't run locally, but I got it to blow up on circleci ... I guess that's progress 😆

**Comment by cal-smith** [comment]
Adding `--no-watchman` sorted out my jest issues ... for whatever reason my system has issues with some of these advanced filesystem watches/crawlers.

**Comment by cal-smith** [comment]
adding node to the jest file extensions fixed the first one of my issues: https://github.com/facebook/jest/issues/353

Now I'm wrestling with jest telling me that `render` isn't a function.

**Comment by cal-smith** [comment]
I'm going to have to think on this a little longer ... I got the tests running in general, but then I hit https://github.com/sass/dart-sass/issues/585 - which breaks at least a few tests fairly badly.

**Comment by cal-smith** [comment]
So potential strategy here - since we're running a given test suite against both dart and node sass, we can just toggle out the parts of the tests that are simply impossible in dart sass.

One interesting note - dart-sass seems to require a `@return` from a function (node-sass was more liberal in this regard) ... functionally `@return null` is the same as not returning a value (as far as I can see), with the exception that it doesn't populate the `error` object (since it doesn't throw an error)

File: package.json [hunk 6]
```diff
@@ -23,7 +23,7 @@
     "lint": "eslint packages",
     "lint:styles": "stylelint '**/*.{css,scss}' --config ./packages/stylelint-config-elements",
     "sync": "carbon-cli sync",
-    "test": "cross-env BABEL_ENV=test jest",
+    "test": "cross-env BABEL_ENV=test jest --no-watchman",
```
Comment (cal-smith) [inline package.json]: Changed this for me ... I'll swap it back to no args 👍

File: package.json [hunk 7]
```diff
@@ -130,7 +130,8 @@
     ],
     "moduleFileExtensions": [
       "js",
-      "json"
+      "json",
+      "node"
```
Comment (cal-smith) [inline package.json:134]: Needed this to load `fibers` ... more on that later

File: packages/colors/__tests__/scss-test.js [hunk 8]
```diff
@@ -9,50 +9,74 @@
 
 'use strict';
 
-const { createSassRenderer, types } = require('@carbon/test-utils/scss');
```
Comment (cal-smith) [inline packages/colors/__tests__/scss-test.js]: `types` is now returned from `createSassRenderer` (to try and ensure we don't mix and match dart and node sass)

File: packages/colors/__tests__/scss-test.js [hunk 9]
```diff
@@ -9,50 +9,74 @@
...
+const { createSassRenderer } = require('@carbon/test-utils/scss');
 
-const render = createSassRenderer(__dirname);
+const tests = useDartSass => {
```
Comment (cal-smith) [inline packages/colors/__tests__/scss-test.js]: All the style tests are now wrapped in a `tests` function that takes a `useDartSass` boolean, this way we can control how the tests are run (right now everything is run twice)

File: packages/colors/__tests__/scss-test.js [hunk 10]
```diff
@@ -9,50 +9,74 @@
...
+  const { renderer: render, types } = createSassRenderer(
+    __dirname,
+    '',
+    useDartSass
+  );
 
-describe('colors.scss', () => {
-  it('should emit no side-effects if mixins are included', async () => {
-    const { calls } = await render(`
+  let compiler = ' in node-sass';
```
Comment (cal-smith) [inline packages/colors/__tests__/scss-test.js]: This is just a convenience, it allows us to differentiate which run is node-sass and which is dart-sass.

File: packages/colors/__tests__/scss-test.js [hunk 11]
```diff
@@ -9,50 +9,74 @@
...
+
+  describe(`colors.scss${compiler}`, () => {
+    it('should emit no side-effects if mixins are included', async () => {
+      const { calls } = await render(`
 @import '../scss/mixins';
 
 $test: test(mixin-exists(carbon--colors));
 $test: test(global-variable-exists(carbon--blue-50));
+
+// dart-sass test to show that mixin hiding _does work_
```
Comment (cal-smith) [inline packages/colors/__tests__/scss-test.js]: There's a lot of weirdness here ... wrapping globals in a mixin _does_ work in dart-sass, but it seems like there's a bug somewhere that results in the global being defined ... either way, the global hiding behavior will likely need to change for sass 2.0, so that's something to keep in mind.

File: packages/themes/__tests__/themes-test.js [hunk 12]
```diff
@@ -102,9 +103,13 @@ $t: test($interactive-01);
...
+        const colors = calls.map(call => convert(call[0], useDartSass));
+        expect(colors[0]).toEqual(colors[2]);
+        expect(colors[1]).toBe('#ffffff');
+      });
     });
   });
-});
+};
+
+tests(false);
```
Comment (asudoh) [inline packages/themes/__tests__/themes-test.js]: What is this for...?

File: packages/components/src/globals/grid/__tests__/grid-test.js [hunk 13]
```diff
@@ -104,75 +114,87 @@ Object {
...
+        expect(output.warn).toHaveBeenCalledTimes((await isClassic()) ? 1 : 2);
 
-    // This should fail because `breakpoint('unknown')` does not return a
-    // value
-    expect(error).toBeDefined();
-  });
+        // skipping this for now, since functions should @return _something_
+        // This should fail because `breakpoint('unknown')` does not return a
+        // value
+        // expect(error).toBeDefined();
```
Comment (asudoh) [inline packages/components/src/globals/grid/__tests__/grid-test.js]: Did you mean to skip this for `dart-sass` only?

**Review by asudoh — COMMENTED** [review]
LGTM basically, just a couple - Thanks @cal-smith!

File: packages/components/src/globals/scss/__tests__/css--font-face-test.js [hunk 14]
```diff
@@ -9,56 +9,66 @@
...
-    );
-    expect(result.css.toString()).toEqual(
-      expect.stringContaining(`font-family: 'IBM Helvetica'`)
-    );
-  });
+      expect(result.css.toString()).toEqual(
+        expect.stringContaining('@font-face')
+      );
+      expect(result.css.toString()).toEqual(
+        expect.stringMatching(/font-family: ['"]IBM Helvetica['"]/)
```
Comment (cal-smith) [inline packages/components/src/globals/scss/__tests__/css--font-face-test.js]: dart-sass seems to prefer using double quotes `"`, so I just changed this to match either - generally it'll behave the same as `stringContaining`

**Review by cal-smith — COMMENTED** [review]
There's a bunch to go over so ...

First things first, I ended up running a full yarn update as part of my testing, so that's where all the offline mirror change come from ... I can undo that though :+1:

File: packages/colors/__tests__/scss-test.js (hunk 11 above)
Comment (asudoh) [reply packages/colors/__tests__/scss-test.js]: Great that you brought this up @cal-smith - Let me better understand what you are saying here...:

```scss
$var-foo: blue !global;

@mixin foo {
  $var-foo: green !global;
}

@include foo;

.foo {
  color: $var-foo;
}
```

Did above test case close to what you brought up? If so, what did you expect for `color` in `.foo`? If above test case is irrelevant my apologies and want to hear more details.

Thanks!

Comment (cal-smith) [reply packages/colors/__tests__/scss-test.js]: The original test case seems to be testing variable hiding ... so

```scss
// var.scss
@mixin foo {
  $var-foo: green !global;
}
```

```scss
// import.scss
@import 'var';

global-variable-exists(var-foo) // false in node-sass, true in dart-sass
```

`node-sass` returns false (what we expect) but `dart-sass` returns true - *however* if I set up a test case like this:

```scss
@mixin foo {
  $var-foo: green !global;
}

global-variable-exists(var-foo)
```

`dart-sass` correctly returns false.

So, _in general_ the behaviour works, there just seems to be something (potentially a bug) that results in dart-sass not hiding variables from imported files.

In either case, `!global` will stop creating global variables from a local scope with sass@2 so this isn't something we can expect to work going forwards.

File: packages/components/src/globals/grid/__tests__/grid-test.js (hunk 13 above)
Comment (cal-smith) [reply packages/components/src/globals/grid/__tests__/grid-test.js]: _probably_, let me check

Comment (cal-smith) [reply packages/components/src/globals/grid/__tests__/grid-test.js]: So, the issue here is that `dart-sass` is far more strict about `@returns` from functions - they _need_ to return _something_.

So, I can either `@return null` and keep the same behavior (the caller will error), or, I can `@error` and have the function throw itself.

File: packages/components/src/globals/grid/__tests__/grid-test.js [hunk 15]
```diff
@@ -105,7 +105,7 @@ Object {
     });
 
     it('should support the breakpoint function', async () => {
-      const { calls, error, output } = await renderClassic(`
+      const { calls, /* error, */ output } = await renderClassic(`
```
Comment (asudoh) [inline packages/components/src/globals/grid/__tests__/grid-test.js]: Given this change makes `output` refer to the 2nd arg (error), did you want to prefix `error` with `_`, assuming the change is for avoiding linter error?

File: packages/components/src/globals/grid/__tests__/grid-test.js (hunk 13 above)
Comment (asudoh) [reply packages/components/src/globals/grid/__tests__/grid-test.js]: Cool, thank you for finding this out! I think `@return null` makes sense.

File: packages/colors/__tests__/scss-test.js (hunk 11 above)
Comment (asudoh) [reply packages/colors/__tests__/scss-test.js]: I see, one question to understand what you said correctly - Do you think `dart-sass` defines a global variable in below code as soon as the mix-in is defined, even though it has _never called_?

```scss
@mixin foo {
  $var-foo: green !global;
}
```

Comment (cal-smith) [reply packages/colors/__tests__/scss-test.js]: _Assuming it's an import from another file_ yes, that seems to be the case. `dart-sass` seems to define any globals when the file is imported. If the mixin is in the same file it waits until it's called.

For our purposes we may as well work with the assumption that, under dart-sass, all globals will be defined up front - though they may not actually have values.

File: packages/components/src/globals/grid/__tests__/grid-test.js (hunk 15 above)
Comment (cal-smith) [reply packages/components/src/globals/grid/__tests__/grid-test.js]: sure 👍

File: packages/components/src/globals/grid/__tests__/grid-test.js (hunk 13 above)
Comment (cal-smith) [reply packages/components/src/globals/grid/__tests__/grid-test.js]: okay cool, I'll see if there's any others that need updating

File: packages/colors/__tests__/scss-test.js (hunk 11 above)
Comment (asudoh) [reply packages/colors/__tests__/scss-test.js]: OK created:

`_mixin.scss`

```scss
@mixin foo() {
  $var-foo: green !global;
}
```

`index.scss`:

```scss
@import "mixin";

@debug "$var-foo: #{$var-foo}";
@debug "type-of($var-foo): #{type-of($var-foo)}";
```

Where `sass index.scss` yielded below, whereas `node-sass` threw:

```
index.scss:3 Debug: $var-foo: 
index.scss:4 Debug: type-of($var-foo): null
```

Does above match your finding?

Comment (cal-smith) [reply packages/colors/__tests__/scss-test.js]: Yeah that matches what I've been seeing

File: packages/components/src/globals/grid/__tests__/grid-test.js (hunk 15 above)
Comment (cal-smith) [reply packages/components/src/globals/grid/__tests__/grid-test.js]: I just removed it, since there's nothing that uses it anymore in that test

File: packages/colors/__tests__/scss-test.js (hunk 11 above)
Comment (asudoh) [reply packages/colors/__tests__/scss-test.js]: Thanks @cal-smith! Would it make sense to add such example code to the comment here, so people clearly know the difference in behavior between `dart-sass` vs. `node-sass`?

Comment (cal-smith) [reply packages/colors/__tests__/scss-test.js]: Sure 👍

**Comment by cal-smith** [comment]
Okay! Ready for another review 🎉

File: packages/components/src/globals/grid/__tests__/grid-test.js [hunk 16]
```diff
@@ -9,68 +9,86 @@
...
-    expect(result.css.toString()).toMatchSnapshot();
-  });
+      expect(result.css.toString()).toMatchSnapshot();
+    });
 
-  it('should export a 12 column grid by default', async () => {
-    const { result } = await render(`
+    it('should export a 12 column grid by default', async () => {
+      const { result } = await render(`
+$feature-flags: (grid: true);
```
Comment (asudoh) [inline packages/components/src/globals/grid/__tests__/grid-test.js]: Just wanted to double-check if this change is intentional.

**Review by asudoh — COMMENTED** [review]
Thank you for the update @cal-smith! Just one question.

File: packages/components/src/globals/grid/__tests__/grid-test.js (hunk 16 above)
Comment (cal-smith) [reply packages/components/src/globals/grid/__tests__/grid-test.js]: Ah I must have missed that when I was resolving some conflicts ... fixed!

**Comment by asudoh** [comment]
Cool thank you for another update @cal-smith! Is this still WIP or ready for final review?

**Comment by cal-smith** [comment]
This is ready for final review @asudoh 👍 I can't change the labels otherwise I'd remove the WIP one 😅

File: packages/test-utils/scss.js [hunk 17]
```diff
@@ -8,18 +8,32 @@
 'use strict';
 
 const fs = require('fs');
-const { render, types } = require('node-sass');
+const { render: nodeRender, types: nodeTypes } = require('node-sass');
+const { render: dartRender, types: dartTypes } = require('sass');
+// TODO figure out how to use fibers with jest
+// const Fiber = require('fibers');
```
Comment (joshblack) [inline packages/test-utils/scss.js]: Did you figure this out with the module extensions stuff that you left a note for above?

**Review by joshblack — CHANGES_REQUESTED** [review]
Wanted to chat a bit about the options in the scss test util, other stuff looks great 🎉 

With respect to the helper, instead of conditionally using dart sass should we design it so that it is pluggable with any sass compiler?

File: packages/test-utils/scss.js (hunk 17 above)
Comment (cal-smith) [reply packages/test-utils/scss.js]: I haven't unfortunately ... I _think_ it's related to the babel generator transforms, but I belive other parts of jest rely on regenerator-runtime so I don't think I can remove it ... that said, build times don't seem to be an issue, so we should be fine without fibers (for now)

**Comment by cal-smith** [comment]
> With respect to the helper, instead of conditionally using dart sass should we design it so that it is pluggable with any sass compiler?

We could ... I have a few worries around ensuring we have the right types available for `convert` and friends (since a hypothetical third sass compiler may not export those). I can experiment a bit more with it, with a potential API looking like:

```javascript
const sass = require("sass");
const { sassTestUtil } = require('@carbon/test-utils/scss');
const { createSassRenderer } = sassTestUtil(sass);
```

naming TBD, but something along those lines would allow us to dynamically create sass renderers

**Comment by joshblack** [comment]
@cal-smith I would hate for you to have to revisit this stuff given that the sass changes seem great, would we want to move the testing-utils related stuff to a separate issue/PR just so we can get the sass changes in?

**Comment by cal-smith** [comment]
Sure ... I should be able to pick apart the js changes from the scss changes, and we can continue the conversation in another PR

**Comment by cal-smith** [comment]
Okay, pulled out the test refactoring, so we should be good with just the scss changes now :+1:

File: packages/components/src/components/notification/_mixins.scss [hunk 18]
```diff
@@ -20,6 +20,17 @@
   }
 }
 
+/// @access private
```
Comment (asudoh) [inline packages/components/src/components/notification/_mixins.scss]: Is this change here intentional...?

**Review by asudoh — COMMENTED** [review]
Thank you for another update @cal-smith!

File: packages/components/src/components/notification/_mixins.scss (hunk 18 above)
Comment (cal-smith) [reply packages/components/src/components/notification/_mixins.scss]: That seems to be an artifact of extracting the changes I wanted ... I'll sort that out

**Review by joshblack — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @cal-smith for all the updates!
