### PR TITLE
fix(tag): use refs to handle component access

### LINKED ISSUE #16570: [Bug]: Tag components use query selector with id value without protection
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.58.0

### React version

v18.2.0

### Description

The following PR https://github.com/carbon-design-system/carbon/pull/16437 introduces the use of a querySelector call in the tag components which uses the id directly. If the id value contains anything that isn't a valid query then it breaks. It should use a ref to access the instance of the Tag DOM node.

Also the helper function `isEllipsisActive` accesses a element prop directly without validation and this causes an error if the element isn't a valid DOM node. 

### Reproduction/example

https://stackblitz.com/edit/github-ejg4ae?file=src%2FApp.jsx

### Steps to reproduce

open browser console and see errors

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Kilian-Collender**
Closes https://github.com/carbon-design-system/carbon/issues/16570

When using the querySelector it is easily broken if the id has reserved characters also the isEllipsisActive helper had no protection for a non element. So now using refs to access the DOM element and the helper has been extracted for reuse and includes extra protection.

#### Changelog

**New**

- {{new thing}}

**Changed**

- Update how the tag components reference themselves

**Removed**

- {{removed thing}}

#### Testing / Reviewing

- Follow the example in the original bug to test that the original issue does not take place.

N.B. There was no testing in place around the recent changes that were added, it is strongly advised that we need tests here both unit and E2E.

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
Thanks again for the quick fix!

**Comment by tay1orjones** [comment]
Hey real quick before we merge this I'm going to correct the deprecation notices

**Review by alisonjoseph — APPROVED** [review]
Thanks for the fix!

**Comment by guidari** [comment]
Thanks for that! I added a `forwardRef` to Tag, so the ref can use in the variants. If the CI pass I think we are good to merge it!

File: packages/react/src/components/Tag/isEllipsisActive.ts [hunk 1]
```diff
@@ -0,0 +1,14 @@
+/**
+ * Copyright IBM Corp. 2024
+ *
+ * This source code is licensed under the Apache-2.0 license found in the
+ * LICENSE file in the root directory of this source tree.
+ */
+
+export const isEllipsisActive = (element: any) => {
+  if (element) {
+    console.log('element offste', element?.offsetWidth < element?.scrollWidth);
```
Comment (Kilian-Collender) [inline packages/react/src/components/Tag/isEllipsisActive.ts]: console.log here

File: packages/react/src/components/Tag/Tag.tsx [hunk 2]
```diff
@@ -172,9 +179,9 @@ const Tag = <T extends React.ElementType>({
   }
 
   if (filter) {
-    const ComponentTag = BaseComponent ?? 'div';
+    const ComponentTag = (BaseComponent as React.ElementType) ?? 'div';
     return (
-      <ComponentTag className={tagClasses} id={tagId} {...other}>
+      <ComponentTag ref={tagRef} className={tagClasses} id={tagId} {...other}>
```
Comment (Kilian-Collender) [inline packages/react/src/components/Tag/Tag.tsx]: should this not be ref too now?

Comment (guidari) [reply packages/react/src/components/Tag/Tag.tsx]: Actually we can remove the ref from this one. The `filter` prop should be replace with the new variant `Dissmisible Tag` so we don't have to add the new functionality to the old `filter` tag.

Comment (Kilian-Collender) [reply packages/react/src/components/Tag/Tag.tsx]: but isn't the `Dismissible Tag` experimental? so you still need it there until it is fully deprecated

Comment (guidari) [reply packages/react/src/components/Tag/Tag.tsx]: I see your point. It is something I will take to the team to talk about it. Since we have implemented in the `Dissmisible Tag` it would be quick to implement on the old filter prop.
But for now the spec we have is only in the new Intereactive Tag.

**Review by guidari — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]
