### PR TITLE
fix(ui-shell): change the way to generate unique ID

### LINKED ISSUE #4288: Got some security issues after scaned by AppScan on Cloud
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
We used ASoC to scan open source libs we are packaging in our product, some security issues reported by ASoC.
main issues reported:
- Insecure Use of setAttribute
图片
- Insecure HTTP Communication
图片
- Query Insecure Manipulation of Child Node
图片
- Insecure random number
图片

> Is this issue related to a specific component?
No.
> What did you expect to happen? What happened instead? What would you like to
> see changed?
No security issue reported by ASoC because we package carbon in our product.
> What browser are you working in?
N/A
> What version of the Carbon Design System are you using?
10.6
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Service Management Unite
## Steps to reproduce the issue
1. Login ASoC: https://cloud.appscan.com
2. Upload source code
3. Scan
4. Download report

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

### PR DESCRIPTION
**Pull request by asudoh**
Closes #4288.

#### Changelog

**Changed**

- Unique ID generation logic in vanilla UI shell code from `Math.random()` to sequence number to address the presumable concern with security.

#### Testing / Reviewing

Testing should make sure our vanilla product switcher is not broken.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
this only resolves the insecure usage of `Math.random` report right? are we reopening the ticket to address the other issues? on a side note I get stuck in a redirect loop after logging into ASoC to see the original issues

File: packages/components/src/components/ui-shell/product-switcher.js [hunk 1]
```diff
@@ -80,9 +82,7 @@ export default class ProductSwitcher extends NavigationMenuPanel {
     );
     const launcher = event.delegateTarget;
     if (!launcher.id) {
-      launcher.id = `__carbon-product-switcher-launcher-${Math.random()
-        .toString(36)
-        .substr(2)}`;
+      launcher.id = `__carbon-product-switcher-launcher-${seq++}`;
```
Comment (elizabethsjudd) [inline packages/components/src/components/ui-shell/product-switcher.js:85]: FYI, ids must start with a letter in order to be valid HTML.  If this is an id that get's added to the HTML I would suggest removing the underscores.

Comment (joshblack) [reply packages/components/src/components/ui-shell/product-switcher.js:85]: Is it more-so that it was a requirement in HTML4? And they suggest doing it for backwards compat

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

> Note: Using characters except ASCII letters, digits, '_', '-' and '.' may cause compatibility problems, as they weren't allowed in HTML 4. Though this restriction has been lifted in HTML5, an ID should start with a letter for compatibility.

**Comment by asudoh** [comment]
@emyarod Updated the original issue; Seems that none of the reports actually affect their app. The random ID one (this PR) is just for pre-caution.

**Review by emyarod — APPROVED** [review]
aside from the note about valid HTML IDs looks good to me, product switcher is functioning as expected

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! Thank you for clarifying on the original issue @asudoh !

File: packages/components/src/components/ui-shell/product-switcher.js (hunk 1 above)
Comment (asudoh) [reply packages/components/src/components/ui-shell/product-switcher.js:85]: Given the point seems for older browsers probably we'd go for it as-is for now.
