### PR TITLE
fix: multiselect was giving error while selecting value for first time

### LINKED ISSUE #15758: [Bug]: Multiselect drop down throwing browser console error while selecting the value first time
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

v1.49.0

### React version

v18.2.0

### Description

Multiselect dropdown throwing browser console error while selecting the value the first time
Error Details:
`App.jsx:13 Warning: Cannot update a component (`App`) while rendering a different component (`MultiSelect`). To locate the bad setState() call inside `MultiSelect`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at https://githubbs1zsv-faiz--5173--a9c8a5a3.local-credentialless.webcontainer.io/node_modules/.vite/deps/@carbon_react.js?v=703ae265:97328:16
    at div
    at App (https://githubbs1zsv-faiz--5173--a9c8a5a3.local-credentialless.webcontainer.io/src/App.jsx:22:49)`

Screenshot: 
image

I have reproduced this issue here
https://stackblitz.com/edit/github-bs1zsv?file=src%2Findex.scss,src%2FApp.jsx&preset=node=

### Reproduction/example

https://stackblitz.com/edit/github-bs1zsv?file=src%2Findex.scss,src%2FApp.jsx&preset=node=

### Steps to reproduce

1. Open URL:https://stackblitz.com/edit/github-bs1zsv?file=src%2Findex.scss,src%2FApp.jsx&preset=node=
2. Open the console tab in the developer tool
3. Select the value from the multi-select dropdown
4. When we select the 1st value, throw console error "Bad setState inside the Multiselect"

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

I am using React carbon component

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by preetibansalui**
Closes #15758 

Multiselect was giving console error while selecting first time in controlled state
#### Changelog

**Changed**

wrap onChangeHandlerControlled function in queueMicrotask.
**Removed**

#### Testing / Reviewing
1. Go to Storybbok > Multiselect > Test Story
2. Select any item. Check the console error.
3. There should be no console error related to` Cannot update a component () while rendering a different component (MultiSelect)`

Note: I will remove the Test story before merge.

### CODE REVIEW

File: packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js [hunk 1]
```diff
@@ -817,6 +817,18 @@ describe('MultiSelect', () => {
...
+        .spyOn(console, 'error')
+        .mockImplementation(() => {});
+      render(<ControlledMultiselect />);
+      const dropdownNode = screen.getByRole('combobox');
+      await userEvent.click(dropdownNode);
+      await userEvent.click(screen.getAllByRole('option')[0]);
+
+      expect(errorSpy).not.toHaveBeenCalled();
+      errorSpy.mockRestore();
+    });
```
Comment (kennylam) [inline packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js]: I'm not sure this is really necessary, since none of the variations should throw a console error at all. Unless there is something specific to check for, that, when missing, would cause an error.

Comment (preetibansalui) [reply packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js]: I tried running the test again after reverting my changes in` Selection.tsx`, it throws the same error that my changes were intended to fix. 
image

Comment (kennylam) [reply packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js]: Hm, everything still passes for me after removing your new test (and reverting the `id` changes in [here](https://github.com/carbon-design-system/carbon/pull/19257/files#diff-3bb0559ed2d41136cbfb29d1ca36b894ddb44ee10827a60e393f79b0a950ff93R961-R962) and [here](https://github.com/carbon-design-system/carbon/pull/19257/files#diff-3bb0559ed2d41136cbfb29d1ca36b894ddb44ee10827a60e393f79b0a950ff93R979)).

**Review by 2nikhiltom — APPROVED** [review]
queueMicrotask works well for this specific use case, While alternatives like useEffect or flushSync could work, this seems more efficient here
A small comment explaining the rationale would be helpful for future reference

**Comment by preetibansalui** [comment]
@tay1orjones , Adding you as a reviewer here, it's the same issue we were discussing last time with Kenny about using `useEffect` in the `useSelection` hook of Multiselect.

**Review by Gururajj77 — APPROVED** [review]

**Review by tay1orjones — COMMENTED** [review]
Anytime we step outside of react's scheduling I think it warrants code comments explaining why

**Comment by preetibansalui** [comment]
> Anytime we step outside of react's scheduling I think it warrants code comments explaining why

Thanks Taylor, Added comment and used setTimeout instead of queueMicrotask.

**Review by tay1orjones — APPROVED** [review]
