### PR TITLE
fix(TableExpandHeader): fix requiredIfGivenPropExists call

### LINKED ISSUE #5904: [TableExpandHeader] eroneous propType errors
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Related to this this pull request I believe https://github.com/carbon-design-system/carbon/pull/5682/files
I'm seeing errors for props:
`ariaLabel`
`isExpanded`
`onExpand`

Whether I pass the props or not, it seems this are being set by the library already
`ariaLabel` is set as: "Collapse all rows" for example, yet the error persists.

> Is this issue related to a specific component?

TableExpandHeader

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The prop type error shouldn't exist I don't think.
Not sure exactly how this code is supposed to work https://github.com/carbon-design-system/carbon/blob/8fdf8be184dc305e94e83fe6980ebc79ffe878de/packages/react/src/prop-types/requiredIfGivenPropExists.js#L17
but it seems it's not actually checking for the existence of the prop it's supposedly checking, just the dependency prop.

> What browser are you working in?

`Brave 1.8, Chromium 81`

> What version of the Carbon Design System are you using?

```json
"carbon-components": "^10.11.1",
"carbon-components-react": "^7.11.1"
```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

New custom small business application

## Steps to reproduce the issue

1. Step one
Use DataTable and TableExpandHeader

2. Step two
Pass required props or not, error results either way.

## Test case
https://codesandbox.io/s/bold-keller-ehewx?file=/src/index.js

- Screenshots or code

Showing console errors

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5904

Background: If `enableExpando` exists, three more props are marked as required. If that prop is not added, they are not required.

Before, our function call was always returning an error if `enableExpando` was provided because it was matching on the first `if` statement. To fix this, I added a check before the error that checks to see if the prop, `props[propName]`, is required (aria-label, for example) if `enableExpando`, or `props[name]` is there. 

#### Changelog

**Changed**

- Rearranged `requiredIfGivenPropExists` function to check if the prop exists

#### Testing / Reviewing

Check out `with-expansion.js` under `DataTable/stories`, and change `TableExpandHeader` to the following.

```jsx
<TableExpandHeader
   enableExpando={true}
   ariaLabel="testing"
   isExpanded={false}
   onExpand={() => {}}
/>
```

Ensure there are no console warnings. Now try removing all the props, but leave `enableExpando={true}`. You should see 3 console warnings.

### CODE REVIEW

File: packages/react/src/prop-types/requiredIfGivenPropExists.js [hunk 1]
```diff
@@ -14,11 +14,13 @@
  */
 export default function requiredIfGivenPropExists(name, propType) {
   return function check(props, propName, componentName, ...rest) {
+    if (props[name] && props[propName]) {
```
Comment (asudoh) [inline packages/react/src/prop-types/requiredIfGivenPropExists.js]: Thank you for jumping in @tw15egan! From my reading of the code `propType()` doesn't run in the condition of `props[name] && !props[propName]`, where it should. Probably we can simply apply the following patch to the original logic?

```javascript
diff --git a/packages/react/src/prop-types/requiredIfGivenPropExists.js b/packages/react/src/prop-types/requiredIfGivenPropExists.js
index 355481920..7c0ab9ec2 100644
--- a/packages/react/src/prop-types/requiredIfGivenPropExists.js
+++ b/packages/react/src/prop-types/requiredIfGivenPropExists.js
@@ -14,7 +14,7 @@
  */
 export default function requiredIfGivenPropExists(name, propType) {
   return function check(props, propName, componentName, ...rest) {
-    if (__DEV__ && props[name]) {
+    if (__DEV__ && props[name] != null && props[propName] == null) {
       return new Error(
         `You must provide a value for \`${propName}\` in \`${componentName}\` if \`${name}\` exists.`
       );
```

Comment (tw15egan) [reply packages/react/src/prop-types/requiredIfGivenPropExists.js]: Ah, you're right, good catch. Updating now! 💪

Comment (tw15egan) [reply packages/react/src/prop-types/requiredIfGivenPropExists.js]: @asudoh I've updated it to `props[name] == true` instead of `props[name] != null`. 

The reasoning is that I'm not sure if people are toggling this feature like so 

`enableExpando={shouldExpand ? true : false}`

 In this case, `enableExpando` is never null and caused errors each time. Maybe an edge-case, but figured it would make sense to only evaluate it if it is true.

Comment (asudoh) [reply packages/react/src/prop-types/requiredIfGivenPropExists.js]: Good point @tw15egan! - Given the presumable nature of the custom prop-check, would we want to rename it to `requiredIfGivenPropIsTruthy()`?

**Review by dakahn — APPROVED** [review]

File: packages/react/src/prop-types/requiredIfGivenPropExists.js (hunk 1 above)
Comment (tw15egan) [reply packages/react/src/prop-types/requiredIfGivenPropExists.js]: @asudoh updated 👍

**Review by asudoh — APPROVED** [review]
LGTM :+1: - Thanks @tw15egan for the update!

**Review by aledavila — APPROVED** [review]
