### PR TITLE
fix(slider): fix duplicate max value on final step

### LINKED ISSUE #20471: [Bug]: Slider component showing max value twice in slider
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.84.0

### React version

v18.3.0

### Description

In the Slider component, when the step is a decimal value, the max value is shown twice in the slider

https://github.com/user-attachments/assets/ce206f45-74cc-43a5-9a37-605caf6379fd

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-slider--default&args=max:1;step:0.1

### Steps to reproduce

Using the slider component, set the max to 1 and step to 0.1

### Suggested Severity

None

### Application/PAL

Elyra CommonProperties

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Pradhicsha-MR-IBM**
Closes #20471

Fixing the slider component showing max value twice in slider

### Changelog

**New**

- NA

**Changed**

- fixed the logic where the max value is shown twice.

**Removed**

- NA

#### Testing / Reviewing

{{ Add steps or a checklist for how reviewers can verify this PR works or not }}

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] ~Updated documentation and storybook examples~
- [ ] ~Wrote passing tests that cover this change~
- [ ] ~Addressed any impact on accessibility (a11y)~
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by Pradhicsha-MR-IBM** [comment]
I have read the DCO document and I hereby sign the DCO.

File: packages/react/src/components/Slider/Slider.tsx [hunk 1]
```diff
@@ -1007,10 +1007,10 @@ export const Slider = (props: SliderProps) => {
     leftPercent: number;
   }) => {
     const { step = 1, min, max } = props;
-    const numSteps =
-      Math.floor((max - min) / step) + ((max - min) % step === 0 ? 1 : 2);
+    const numSteps = Math.floor((max - min) / step) + 1;
     /** Index of the step that corresponds to `leftPercent`. */
     const stepIndex = Math.round(leftPercent * (numSteps - 1));
+    // const discreteValue = min + step * stepIndex;
```
Comment (tay1orjones) [inline packages/react/src/components/Slider/Slider.tsx]:
```suggestion
```

**Review by tay1orjones — CHANGES_REQUESTED** [review]

**Review by tay1orjones — APPROVED** [review]
LGTM, the `1` is no longer repeated as described in the issue 👍 

https://github.com/user-attachments/assets/ab884c94-0132-48b1-8dac-954547b7536b

**Review by kennylam — APPROVED** [review]
