### PR TITLE
fix(DatePicker): remove decorative svg as a click target

### LINKED ISSUE #8865: DatePicker type 'range' - On second input ‘calendar icon’ click updates the date in the first input field.
BUG  - 
1. I am on @carbon/ibm-security version 1.41.0
2. I found an issue with date range picker component i.e `<DatePicker datePickerType="range">`

Description -
 - This issue is specific to second input field calendar icon click only.
 - Also this issue is reproducible on carbon documentation link too ( https://react.carbondesignsystem.com/?path=/story/components-datepicker--range ).
 - When I click on second input field's ‘calendar icon’ it updates the date in the first input field.
 - BUT when I click inside input field and select the date then it updates the date as expected inside input fields that I clicked.

```
<DatePicker datePickerType="range">
      <DatePickerInput
        id="date-picker-input-id-start"
        placeholder="mm/dd/yyyy"
        labelText="Start date"
      />
      <DatePickerInput
        id="date-picker-input-id-finish"
        placeholder="mm/dd/yyyy"
        labelText="End date"
      />
    </DatePicker>
```

Please refer attached screenshots for the reference.
image

Actual implementation screenshots,
image

Expected behavior -
 - When I click on the second input calendar icon, it should update the date in second field not first field

Actual behavior - 
 - On clicking second input calendar icon, it updates the date in first field.
 - It is incorrect.

Steps for reproducing -
(TRY it in both Chrome and Firefox)
https://react.carbondesignsystem.com/?path=/story/components-datepicker--range

Browsers
 - Not browser specific

Optional information
- None

### LINKED ISSUE #9815: [a11y]: Date picker - unable to use keybord after opening calendar
### Package

carbon-components

### Browser

Chrome, Firefox

### Operating System

Windows

### Package version

10.42.0

### Automated testing tool and ruleset

manual

### Assistive technology

_No response_

### Description

When user clicks on calendar icon in date picker it;s impossible to pick date with arrows on keyboard.
When calendar is opened by clicking on input field keyboard select works fine.

Opened by icon clicked:
image

Opened by input cliecked:
image

### WCAG 2.1 Violation

_No response_

### CodeSandbox example

https://codesandbox.io/s/withered-rain-q2olg

### Steps to reproduce

Click on calendar icon in date picker.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by dakahn**
Closes #8865 
Closes #9815

The small decorative calendars were click targets. This was causing weird issue with the second calendar opening and setting the first input. Seems to me they should just not receive pointer events at all which seems to address the problem. 

#### Testing / Reviewing

- click the first input and select a date
- observe the first input populate with correct date
- click the second input and select a date
- observe the second input populate with correct date

🏄🏾

### CODE REVIEW

**Comment by tay1orjones** [comment]
@dakahn I just made two updates to this:
1. Within DatePicker, remove usages of the `openCalendar` prop that has been removed
2. Mirror the style changes you made in `packages/styles` to `packages/components`

The storybook now shows the intended functionality; clicking the calendar icon is technically clicking/focusing the input, which opens the calendar.

File: packages/react/__tests__/__snapshots__/PublicAPI-test.js.snap [hunk 1]
```diff
@@ -2525,9 +2525,6 @@ Map {
       "onClick": Object {
         "type": "func",
       },
-      "openCalendar": Object {
-        "type": "func",
-      },
```
Comment (tay1orjones) [inline packages/react/__tests__/__snapshots__/PublicAPI-test.js.snap:2530]: I don't think we can remove this without a major. We'll have to deprecate it instead.

File: packages/react/src/components/DatePickerInput/DatePickerInput.js [hunk 2]
```diff
@@ -218,9 +212,8 @@ export default class DatePickerInput extends Component {
       return (
         <Calendar16
           className={`${prefix}--date-picker__icon`}
-          aria-label={iconDescription}
-          onClick={openCalendar}
-          role="img">
+          role="img"
+          aria-hidden="true">
```
Comment (tay1orjones) [inline packages/react/src/components/DatePickerInput/DatePickerInput.js]: Do we still need to still call `openCalendar ` on click, so it's not a breaking change in functionality? 

It's no longer being used in `DatePicker` to actually open the calendar but maybe it's possible someone is relying on this function being called when the calendar is clicked vs the input?

**Review by tay1orjones — CHANGES_REQUESTED** [review]
A couple considerations for avoiding breaking changes.

File: packages/react/src/components/DatePickerInput/DatePickerInput.js (hunk 2 above)
Comment (dakahn) [reply packages/react/src/components/DatePickerInput/DatePickerInput.js]: makes sense to leave it on while the prop is being deprecated 👍🏾

Comment (tay1orjones) [reply packages/react/src/components/DatePickerInput/DatePickerInput.js]: I think we can still remove DatePicker from calling it though. The `openCalendar` function is never called when the icon is clicked since it now has pointer-events none

https://github.com/carbon-design-system/carbon/blob/e8c23254039993e2fcaae9b558f3ae55df7839b9/packages/react/src/components/DatePicker/DatePicker.js#L532-L536

**Comment by tay1orjones** [comment]
Tests were failing because the DatePicker was still using the deprecated `openCalendar` prop, triggering an unexpected `console.warn`. I pushed an update to remove it from DatePicker. `openCalendar` isn't actually called anymore anyway now that the icon has `pointer-events: none`.

**Review by tay1orjones — APPROVED** [review]

**Comment by tay1orjones** [comment]
@joshblack could you share more on how to get the autocomplete list to pop? I can't repro in chrome, firefox, or safari. 

I'm not sure how/why these changes would impact the browser's autocomplete. We could place `autocomplete="off"` on the DatePickerInput in storybook.

**Comment by joshblack** [comment]
@tay1orjones I think it's because before we were never interacting with the input, whereas now we are in order to trigger the appearance of the date picker.

As to how to get the autocomplete, great question lol. I have no idea how it's picking up dates in this situation

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! I also wasn't able to recreate the autocomplete @joshblack was experiencing either but auto complete can be fickle. Reminds me of this old [issue](https://github.com/carbon-design-system/carbon/issues/8993), solving it isn't super clear cut and I don't personally think it has to prevent this PR from being merged in
