### PR TITLE
fix: Select component on hover shows invalid title/tooltip

### LINKED ISSUE #15752: [Bug]: Select component on hover shows invalid title/tooltip
### Package

carbon-components-react

### Browser

_No response_

### Package version

v8.41.2

### React version

v18.2.0

### Description

https://react.carbondesignsystem.com/?path=/docs/components-select--overview
When we hover to dropdown first time on default selected value (without changing option) hover title is not showing.
After changing value it show value on hover.

Expected: text should show on hover as title. value can be number or any unique key

Example:
```
<Select
  id={`select-2`}
  labelText="Select an option"
  helperText="Optional helper text">
  <SelectItem value="option-1" text="Option 1" />
  <SelectItem value="option-2" text="Option 2" />
  <SelectItem value="option-3" text="Option 3" />
</Select>
```

On hover it should show Option 1, Option 2, Option 3 but it is showing option-1, option-2, option-3. (after changing option from dropdown)

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-select--overview

### Steps to reproduce

* hover on default selected value. see we do not have any hover title
* Change select dropdown value and again over on selected
* It will show value title not text.

Screenshot 2024-02-12 at 5 23 08 PM

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Bhas-kar**
Closes https://github.com/carbon-design-system/carbon/issues/15752, https://github.com/carbon-design-system/carbon/issues/18769

Fixed the invalid title/no title in Select component on hovering

#### Changelog

**New**

- The default title for the component was not being set correctly, hence used `useState` to set the title by the default or the `selectedItem` value. onChange updates these title values.

**Changed**

To address the issue, the fix implements the following logic.
- `Prioritised Default Value`: The code now first attempts to find a child option whose value matches the defaultValue prop. If found, this option's value is used as the default title.
- `Fallback to Selected/First Option`: If no matching defaultValue is found, it falls back to using the value which is already selected, essentially the first in the valueSet, as the default title. This ensures that a title is always set.

**Removed**

- None

#### Testing / Reviewing

- Hover on Select component, it should show the selected Option as tooltip

- If there's no option selected, tooltip should not show

### CODE REVIEW

**Comment by Bhas-kar** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by Bhas-kar** [comment]
recheck

**Comment by Bhas-kar** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by Bhas-kar** [comment]
recheck

**Comment by Bhas-kar** [comment]
Hi @2nikhiltom ,
I have fixed the issue now and the build is successful 
image
image

**Comment by tay1orjones** [comment]
Just a heads up that the DCO is failing because some of the commits weren't made with the username and email that matches your github profile, so the DCO sees this as a different "person" that hasn't signed the DCO. 

We can override it and merge but something to know for next time.

File: packages/react/src/components/Select/Select.tsx [hunk 1]
```diff
@@ -169,9 +167,27 @@ const Select = React.forwardRef(function Select(
...
+    React.isValidElement(child)
+  );
+
+  // Initialize the title with the `text` prop
+  const [title, setTitle] = useState(
+    (React.isValidElement(defaultOption) && defaultOption.props?.text) ||
+      (React.isValidElement(firstOptionInSet) &&
+        firstOptionInSet.props?.text) ||
+      ''
+  );
```
Comment (tay1orjones) [inline packages/react/src/components/Select/Select.tsx]: Reducing the duplication and simplifying the logic a bit:

```suggestion
  // Convert children to an array of valid elements once
  const validChildren = React.Children.toArray(children).filter(React.isValidElement);
  // Find the default option based on the specified defaultValue
  const defaultOption = validChildren.find(
    (child) => child.props?.value === other?.defaultValue
  );
  // Use the default option's text if available; otherwise, fallback to the first option's text
  const initialTitle = defaultOption?.props?.text || validChildren[0]?.props?.text || '';
  
  const [title, setTitle] = useState(initialTitle);
```

What do you think?

**Comment by Bhas-kar** [comment]
Hey @tay1orjones ,
I have added the suggested code with few changes to validate the React child element too.
requesting to re-review.
thanks

File: packages/react/src/components/Select/Select.tsx [hunk 2]
```diff
@@ -169,9 +167,18 @@ const Select = React.forwardRef(function Select(
...
   const selectInstanceId = useId();
 
+  // Convert children to an array of valid elements once
+  const validChildren = React.Children.toArray(children).filter(React.isValidElement);
+  // Find the default option based on the specified defaultValue
+  const defaultOption = validChildren.find(
+    (child) => child.props?.value === other?.defaultValue
+  );
+  // Use the default option's text if available; otherwise, fallback to the first option's text
+  const initialTitle = defaultOption?.props?.text || validChildren[0]?.props?.text || '';
```
Comment (2nikhiltom) [inline packages/react/src/components/Select/Select.tsx]: The TypeScript error Property 'text' does not exist on type '{}' is occurring because TypeScript doesn't recognize the text property on the props of child elements. 

```suggestion
 // Define an interface for the expected props
interface SelectItemProps {
  value: any;
  text: string;
}

// Use type narrowing
const validChildren = React.Children.toArray(children)
  .filter((child): child is React.ReactElement<SelectItemProps> => 
    React.isValidElement<SelectItemProps>(child));

// Now TypeScript knows the shape of each child's props
const defaultOption = validChildren.find(
  (child) => child.props.value === other?.defaultValue
);
/ Use the default option's text if available; otherwise, fallback to the first option's text
  const initialTitle =
    defaultOption?.props?.text || validChildren[0]?.props?.text || '';
```

What are your views ?

Comment (Bhas-kar) [reply packages/react/src/components/Select/Select.tsx]: included this with minor changes

Comment (Bhas-kar) [reply packages/react/src/components/Select/Select.tsx]: the code has been changed to validate the child element and build error got resolved

Comment (Bhas-kar) [reply packages/react/src/components/Select/Select.tsx]: UPDATE: addressed the said issue, pushed the suggested change.

**Review by 2nikhiltom — APPROVED** [review]
Looks great! 🎉 .Thanks for the prompt follow-up.

**Review by tay1orjones — APPROVED** [review]
