### PR TITLE
fix(tile): change expandable tile to button

### LINKED ISSUE #5557: [React component Tile - Expandable] It's impossible to expand or collapse the tile by focusing the chevron and hitting space / enter
## Environment

> Operating system 

Windows 10

> Browser 

Chrome/FF

## Detailed description

> What version of the Carbon Design System are you using? 

    "@carbon/grid": "^10.3.0",
    "@carbon/icons-react": "^10.6.0",
    "@carbon/type": "^10.2.0",
    "carbon-components": "^10.9.1",
    "carbon-components-react": "^7.9.1",
    "carbon-icons": "^7.0.7",

> What did you expect to happen?

When selecting the chevron using the keyboard I can expand/collapse the tile. And the icon is also outlined on focus.

> What happened instead? 

It's not working and the icon is not outlined on focus.

## Steps to reproduce the issue

1. Open official playground https://react.carbondesignsystem.com/?path=/story/tile--expandable
2. Use tab key to select the chevron in the tile
3. Hit Enter key or Space bar.
4. The tile is not keeping the expand or collapse state

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #5557 

This PR adds a FF specific override for the border and focus it was supplying to the Chevron in ExpandableTile.  

#### Testing / Reviewing

Go to the ExpandableTile example in Storybook on Firefox and make sure that the Chevron does not receive focus.

### CODE REVIEW

**Comment by abbeyhrt** [comment]
Since the chevron is a button, it is still receiving focus. Going to try and figure out a different pattern to address this problem since this isn't the right solution.

**Review by asudoh — DISMISSED** [review]
LGTM 👍 - Thanks @abbeyhrt!

**Comment by tw15egan** [comment]
Wondering why we need the icon to be wrapped in a button anyways 🤔Since the expansion is always triggered by clicking the tile itself, it seems like it may be unnecessary markup. Wonder if we can just switch it to a div, and move the `aria-expanded` to the container div? Since that is what is receiving focus anyways. The SVG seems to be decorative.

File: packages/react/src/components/Tile/Tile.js [hunk 1]
```diff
@@ -542,15 +542,17 @@ export class ExpandableTile extends Component {
...
           this.tile = tile;
         }}
         style={tileStyle}
         className={classes}
+        aria-expanded={isExpanded}
+        title={isExpanded ? tileExpandedIconText : tileCollapsedIconText}
         {...other}
         onClick={this.handleClick}
-        onKeyPress={this.handleKeyDown}
+        // onKeyPress={this.handleKeyDown}
```
Comment (asudoh) [inline packages/react/src/components/Tile/Tile.js]: Did you mean to remove this line, or keep it? Or is this PR still WIP...?

Comment (abbeyhrt) [reply packages/react/src/components/Tile/Tile.js]: This is still a WIP but since I changed the outer `div` to a button, `handleKeydown` is no longer necessary since handleClick will be triggered for keydown events. Definitely meant to remove it completely though! Not just comment it out, my bad!

**Comment by abbeyhrt** [comment]
@tw15egan agreed! I'm thinking of going that route! Unfortunately, it seems like screenreaders don't read the expanded state unless it's on `button` or `a` tag. I'm messing around with changing the outer `div` to a `button` to remedy this but there is a little weirdness there as well.

File: packages/react/src/components/Tile/Tile-test.js [hunk 2]
```diff
@@ -284,23 +284,20 @@ describe('Tile', () => {
       expect(wrapper.state().expanded).toEqual(false);
     });
 
-    it('displays the default tooltip for the button depending on state', () => {
+    fit('displays the default tooltip for the button depending on state', () => {
```
Comment (asudoh) [inline packages/react/src/components/Tile/Tile-test.js]: Did you want to revert this line?

**Comment by aagonzales** [comment]
The chevron is not receiving focus but the tile also isn't getting the focus border either. Is that intended?

**Comment by abbeyhrt** [comment]
@aagonzales definitely not intentional! Where are you seeing this? I wasn't able to reproduce it

**Comment by aagonzales** [comment]
oh that's weird I just checked it again and now its there. I swear I didn't see it earlier. Oh well seems to be correct now 😆

**Review by aagonzales — APPROVED** [review]

File: packages/components/docs/sass.md [hunk 3]
```diff
@@ -22861,6 +22861,14 @@ Tile styles
     }
   }
 
+  .#{$prefix}--tile--expandable {
+    width: inherit;
```
Comment (asudoh) [inline packages/components/docs/sass.md:22868]: Honestly I think there is not many use cases for `width: inherit`. So may I ask what this is for?

Comment (abbeyhrt) [reply packages/components/docs/sass.md:22868]: I just wanted it to get the width that was already defined in `bx--tile`, but I see that doing `width: 100%` gets the same result so I'll change it to that!

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @abbeyhrt!

**Review by dakahn — APPROVED** [review]
