### PR TITLE
fix(multiselect): replace checkbox with visually identical element

### LINKED ISSUE #4008: AVT 1 - React MultiSelect default has DAP violations
Environment
macOS Mojave version 10.14.5
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
Carbon v10 - React
DAP IBM Accessibility July 2019 Ruleset

Detailed Description
Go to the React MultiSelect w/initial selected item
Run DAP with the drop-down menu expanded and the following issues are found (see screenshot):
Screen Shot 2019-09-16 at 3 54 39 PM

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/4008

After reading Josh's comment, this replaces the use of a checkbox entirely and uses a visually identical element to visually indicate change. 

#### Changelog

**Changed**
- Replaces `Checkbox` inside of `MultiSelect` and uses an element that toggles the checkbox styles based on `isChecked`

#### Testing / Reviewing

Open the `MultiSelect` component, expand the `MultiSelect`, then run DAP and ensure there are no longer any violations. There will be 1 violation due to the nature of the Storybook. 

Also, ensure new element styles match old styles

Screen Shot 2020-01-14 at 2 15 34 PM

### CODE REVIEW

**Review by joshblack — CHANGES_REQUESTED** [review]
Hey @tw15egan! 👋 We were actually taking a look at this today in the morning 👀 When looking at the DAP violation, it seemed like instead we need to remove our usage of checkbox and instead provide something that visually is identical but without the underlying checkbox `<input>`

Deque has a demo with their custom multiselect icon over in: https://dequelabs.github.io/combobo/demo/ that we were referencing. 

The whole reason a checkbox itself isn't necessary is that `aria-selected` will indicate whether an item is selected for a screen reader user and the visual representation of the selection will be enough for the keyboard user as they don't need tab stops created from the checkboxes.

**Comment by tw15egan** [comment]
So something like this? We get the check functionality but don't actually use the `Checkbox` 

Screen Shot 2020-01-14 at 4 00 06 PM


```jsx
<div
    className="bx--checkbox-label"
    data-contained-checkbox-state={isChecked}
    id={`${itemProps.id}__checkbox`}>
    {itemText}
 </div>
```

**Comment by tw15egan** [comment]
@joshblack updated to use a new element instead of a `Checkbox`

**Comment by joshblack** [comment]
@tw15egan sorry for the delay! Yeah, I think that'd be perfect but will bump @dakahn just to confirm 👍

**Comment by asudoh** [comment]
@dakahn Could you review @tw15egan's latest code? Thanks!

File: packages/react/src/components/MultiSelect/MultiSelect.js [hunk 1]
```diff
@@ -379,17 +378,21 @@ export default class MultiSelect extends React.Component {
...
-                              name={itemText}
-                              checked={isChecked}
-                              disabled={disabled}
-                              readOnly={true}
-                              tabIndex="-1"
-                              labelText={itemText}
-                            />
+                            <div
+                              role="group"
+                              aria-label={`${itemProps.id}__checkbox`}
```
Comment (joshblack) [inline packages/react/src/components/MultiSelect/MultiSelect.js]: We should be able to remove these groups, right? And then the item itself should be getting `aria-selected` from Downshift, right?

**Review by joshblack — CHANGES_REQUESTED** [review]

File: packages/react/src/components/MultiSelect/MultiSelect.js (hunk 1 above)
Comment (tw15egan) [reply packages/react/src/components/MultiSelect/MultiSelect.js]: I can try removing it and see if DAP complains

Comment (dakahn) [reply packages/react/src/components/MultiSelect/MultiSelect.js]: removing it doesn't cause any DAP errors in my testing here

**Review by dakahn — APPROVED** [review]
Did a pass with VoiceOver and NVDA on Windows 10 and macOS. Controls work as expected and reads quite well everywhere but Firefox, but it seems like that's an existing bug that no ones noticed yet unrelated to this PR in particular. 🤦‍♂ 

DAP errors gone -- that's awesome. If we decided to remove `role=group` as well I can recheck real quick.

File: packages/react/src/components/MultiSelect/MultiSelect.js (hunk 1 above)
Comment (tw15egan) [reply packages/react/src/components/MultiSelect/MultiSelect.js]: Seems like `aria-selected` is not being passed down via downshift. If I add it, it complains that `aria-selected` can't be used on a `div`. Using `aria-checked` seems to cause problems as well.

**Comment by tw15egan** [comment]
Alright made some modifications as I went through it with voiceover on my mac. Still not sure how to alert that an option has been selected/checked.  DAP errors should still be resolved

**Review by dakahn — CHANGES_REQUESTED** [review]
quick run through with NVDA on Windows 10 in Chrome and Edge and it looks like in Chrome I can no longer access the options menu and in Edge I can, but there is no focus or indication :hurtrealbad:

**Comment by tw15egan** [comment]
Would that be due to adding the `role` and `aria-selected`? Would it be better to just remove them?

**Comment by dakahn** [comment]
lemme check VO real quick

**Comment by dakahn** [comment]
It's working with VoiceOver in Safari and Chrome, but now the option menu is no longer working on Windows 10 in Chrome 😕

In Edge it works, but there's no indications or where in the menu you are (focus states) -- you can just see the menu scrolling as the options are read. Something in the last round of changes.

**Comment by asudoh** [comment]
CC @carmacleod just in case she has some insights on using native checkbox for multi select dropdown's selection.

**Comment by carmacleod** [comment]
@asudoh 
> using native checkbox for multi select dropdown's selection.

A quick test of DAP and Windows Chrome/FF/CrEdge with NVDA/JAWS, and Mac Safari with VO, on the [checkbox list in Example 2 on this page](http://ebay.github.io/mindpatterns/input/checkbox/index.html) seems ok. Of course, that's just a very quick test. Checkboxes in the example are native, with opacity 0 and svg image.

I realize that the example listbox is not in a dropdown, but hopefully that won't change things? Make sure you use css visibility: hidden on the dropdown to completely hide it when it isn't showing (i.e. don't use html hidden or css display: none because the animation may not be smooth, and don't use opacity 0 on the dropdown or position it offscreen because that doesn't really hide it from keyboard or screen readers).

Note when using the new Chromium-based-Edge with screen readers, it helps a lot to [turn off UIA](https://twitter.com/stevefaulkner/status/1218108274861576192).

Hope this is helpful!

File: packages/react/src/components/MultiSelect/MultiSelect.js (hunk 1 above)
Comment (joshblack) [reply packages/react/src/components/MultiSelect/MultiSelect.js]: I believe `aria-selected` needs to be on the node with `role="option"` IIRC. Let me know if not 🤔

**Comment by asudoh** [comment]
@carmacleod Thank you for your insights! @tw15egan Does the guidance from @carmacleod make sense? Thanks!

**Comment by joshblack** [comment]
We specifically hit the fieldset violation from DAP when using checkboxes which is what the removal of native checkboxes is for. The specific rule that is flagged is: https://aat.w3ibm.mybluemix.net/token/1899dd76-e350-4eef-aaea-8d7f41a398f6/807c38b0-4c39-41db-9d71-72230dbc0eb5/archives/2019SeptDeploy//doc/w3/help/en-US/idhi_accessibility_check_g1029.html

Ultimately, in a listbox we do not require native checkboxes to indicate selection status as this is done through `aria-selected="true"` on the item that has `role="option"`. The reference for this is WAI ARIA's listbox design pattern: https://www.w3.org/TR/wai-aria-practices/#listbox_roles_states_props specifically:

> * All selected options have aria-selected set to true.
> * All options that are not selected have aria-selected set to false.

**Comment by carmacleod** [comment]
> We specifically hit the fieldset violation from DAP when using checkboxes

fieldset?! Wild. DAP shouldn't be flagging that for checkboxes in a listbox or table.
(If you wanted to go back to native, you could open a DAP issue - it would be semantically weird and inconsistent to require a fieldset inside a listbox).

> in a listbox we do not require native checkboxes to indicate selection status as this is done through aria-selected="true" on the item that has role="option". 

Yep - that is a totally fine solution, too! :)

**Comment by tw15egan** [comment]
@carmacleod Ok, awesome! Good to know this is a valid solution as well. 

@joshblack added in `aria-selected` and changed it to `role="option"`. Let me know if you want any other changes.

@dakahn Let me know what further voiceover work we want to include in this PR, or if we should open a sperate issue for that.

**Comment by carmacleod** [comment]
Make sure you have `aria-multiselectable="true"` on the element with `role="listbox"`.  :)

File: packages/react/src/components/ListBox/ListBoxMenu.js [hunk 2]
```diff
@@ -23,6 +23,7 @@ const ListBoxMenu = ({ children, id, ...rest }) => (
     id={`${id}__menu`}
     className={`${prefix}--list-box__menu`}
     role="listbox"
+    aria-multiselectable="true"
```
Comment (joshblack) [inline packages/react/src/components/ListBox/ListBoxMenu.js]: Would this be specified in `MultiSelect` JS on `ListBox.Menu` since `ListBoxMenu` is shared between the different dropdown variants?

File: packages/react/src/components/MultiSelect/MultiSelect.js [hunk 3]
```diff
@@ -378,19 +377,22 @@ export default class MultiSelect extends React.Component {
                           <ListBox.MenuItem
                             key={itemProps.id}
                             isActive={isChecked}
+                            role="option"
+                            aria-selected={isChecked}
+                            tabIndex={-1}
                             isHighlighted={highlightedIndex === index}
                             title={itemText}
+                            aria-label={itemText}
```
Comment (joshblack) [inline packages/react/src/components/MultiSelect/MultiSelect.js]: What is the `aria-label` needed for here? 👀

File: packages/react/src/components/ListBox/ListBoxMenu.js (hunk 2 above)
Comment (tw15egan) [reply packages/react/src/components/ListBox/ListBoxMenu.js]: Fixed

File: packages/react/src/components/MultiSelect/MultiSelect.js (hunk 3 above)
Comment (tw15egan) [reply packages/react/src/components/MultiSelect/MultiSelect.js]: Removed

**Comment by asudoh** [comment]
@joshblack @dakahn Any further comments?

Update 1/24/2020: Pinged them offline.

**Review by joshblack — APPROVED** [review]
Looks great! 🎉

**Review by dakahn — APPROVED** [review]
