### PR TITLE
fix: increase test coverage for ToggleTip

### LINKED ISSUE #17498: Increase `Toggletip` unit test coverage

### PR DESCRIPTION
**Pull request by 2nikhiltom**
Closes https://github.com/carbon-design-system/carbon/issues/17498

This PR increases test coverage got ToggleTip 

#### Changelog

Added new test cases

#### Testing / Reviewing

Test coverage should increase
Verify that test makes sense

### CODE REVIEW

File: packages/react/src/components/Toggletip/__tests__/Toggletip-test.js [hunk 1]
```diff
@@ -202,5 +202,245 @@ describe('Toggletip', () => {
...
+      it('should render custom component with onClick handler', () => {
+        render(
+          <Toggletip>
+            <ToggletipButton as={CustomButton}>Click me</ToggletipButton>
+          </Toggletip>
+        );
+
+        const button = screen.getByTestId('custom-button');
+        expect(button).toBeInTheDocument();
+        fireEvent.click(button);
```
Comment (ariellalgilmore) [inline packages/react/src/components/Toggletip/__tests__/Toggletip-test.js]: is it possible to use userEvent instead of fireEvent?

File: packages/react/src/components/Toggletip/__tests__/Toggletip-test.js [hunk 2]
```diff
@@ -202,5 +202,245 @@ describe('Toggletip', () => {
...
+              <ToggletipButton>Toggle</ToggletipButton>
+              <ToggletipContent>Content</ToggletipContent>
+            </Toggletip>
+          </>
+        );
+
+        const toggleButton = screen.getByText('Toggle');
+        const externalButton = screen.getByTestId('external-button');
+
+        fireEvent.blur(toggleButton, {
```
Comment (ariellalgilmore) [inline packages/react/src/components/Toggletip/__tests__/Toggletip-test.js]: same as here

File: packages/react/src/components/Toggletip/__tests__/Toggletip-test.js [hunk 3]
```diff
@@ -202,5 +202,245 @@ describe('Toggletip', () => {
...
+            <ToggletipContent>
+              <button>Action</button>
+            </ToggletipContent>
+          </Toggletip>
+        );
+
+        expect(container.firstChild).toHaveClass(`${prefix}--toggletip--open`);
+        const toggletipWrapper = container.firstChild;
+
+        fireEvent.blur(toggletipWrapper, {
```
Comment (ariellalgilmore) [inline packages/react/src/components/Toggletip/__tests__/Toggletip-test.js:433]: same here

**Review by ariellalgilmore — COMMENTED** [review]
just some placs using fireevent where I think we can use userEvent, but otherwise looks good!

File: packages/react/src/components/Toggletip/__tests__/Toggletip-test.js (hunk 3 above)
Comment (2nikhiltom) [reply packages/react/src/components/Toggletip/__tests__/Toggletip-test.js:433]: Hey Ari , I replaced fireEvent with userEvent on other places
for this test case I used fireEvent instead of userEvent here to explicitly test blur behavior with a `null` relatedTarget. Thoughts ?

Comment (ariellalgilmore) [reply packages/react/src/components/Toggletip/__tests__/Toggletip-test.js:433]: ah yup! looks good!

**Review by ariellalgilmore — APPROVED** [review]

**Review by Gururajj77 — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me!
