### PR TITLE
fix(number-input): prevent value change via arrow keys in readOnly mode

### LINKED ISSUE #21885: [Bug]: NumberInput allows to update value in read only mode with arrow keys
### Package

@carbon/react

### Browser

Chrome

### Package version

1.103.0

### React version

_No response_

### Description

as per the comment https://github.com/carbon-design-system/carbon/pull/21681#discussion_r2965223668

when `type="text"` and `readOnly`. the number input allows for updates with arrow keys when focused.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-numberinput--with-type-of-text&args=readOnly:!true

### Steps to reproduce

https://react.carbondesignsystem.com/?path=/story/components-numberinput--with-type-of-text&args=readOnly:!true

visit this story with `type="text"` and `readOnly`

focus the input and press up or down arrow

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

carbon

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by jadamski02**
Closes https://github.com/carbon-design-system/carbon/issues/21885

Fix NumberInput to prevent arrow key value changes in readOnly mode

### Changelog

**New**

-  New test "should not allow arrow key changes when readOnly with type='text'" validates the fix

**Changed**

Fixed arrow key behavior to respect readOnly prop when `type="text"`. Arrow keys (up/down) no longer change the input value when the component is in read-only mode, ensuring consistency with the stepper button behavior.

#### Testing / Reviewing

Manual Testing:

1. Visit the NumberInput Storybook story with `type="text"`:
2. Navigate to NumberInput -> With Type Of Text
3. Enable the readOnly control in Storybook
4. Focus the input field
5. Press ArrowUp and ArrowDown keys
6. Verify the value does NOT change
7. Disable readOnly control
8. Press arrow keys again
9. Verify the value DOES change

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by adamalston — COMMENTED** [review]
Hi, none of the checklist items in https://github.com/carbon-design-system/carbon/pull/21907#issue-4164914019 have been marked as completed.

File: packages/react/src/components/NumberInput/__tests__/NumberInput-test.js [hunk 1]
```diff
@@ -827,6 +832,28 @@ describe('NumberInput', () => {
...
+
+    const input = screen.getByLabelText('test-label');
+    expect(input).toHaveValue('50');
+
+    await userEvent.click(input);
+    await userEvent.keyboard('{ArrowUp}');
+    expect(input).toHaveValue('50'); // Should not change
+
+    await userEvent.keyboard('{ArrowDown}');
+    expect(input).toHaveValue('50'); // Should not change
```
Comment (adamalston) [inline packages/react/src/components/NumberInput/__tests__/NumberInput-test.js]: I'm not sure these comments add value, given the test title and assertions. This test seems to be a case where the code is self-explanatory.

```suggestion
    expect(input).toHaveValue('50');

    await userEvent.keyboard('{ArrowDown}');
    expect(input).toHaveValue('50');
```

**Comment by jadamski02** [comment]
@adamalston thanks, done.

**Review by adamalston — APPROVED** [review]

**Review by maradwan26 — APPROVED** [review]
LGTM
