### PR TITLE
fix(cds-multi-select): sorting behaviours, new properties `sortItems`, `compareItems`

### LINKED ISSUE #22016: [Bug]: `cds-multi-select` selection-feedback = 'top' / 'top-after-reopen' does not re-sort items on deselection
### Package

@carbon/web-components

### Browser

Chrome, Safari, Firefox, Edge

### Package version

2.27.2

## What did you see?

When using `cds-multi-select` with a sequential list of items (e.g., hours 00-23 or minutes 00-59), the component reorders the DOM elements after user interaction. Specifically:

1. **Initial State**: Dropdown displays items in correct order (00, 01, 02, ... 21, 22, 23)
2. **After Selection**: User selects items near the end of the list (e.g., 22 and 23)
3. **After Deselection**: User clicks the X to deselect these values
4. **Observed Behavior**: When reopening the dropdown, items 22 and 23 now appear at the **top** of the list instead of their original position at the bottom
5. **Result**: The dropdown order becomes (22, 23, 00, 01, 02, ... 21), breaking the sequential ordering

This behavior persists - the selected items remain at the top even after deselection, making it confusing for users to find and select items in their expected positions.

## What did you expect to see?

The `cds-multi-select` component should **maintain the original order** of items in the dropdown at all times, regardless of which items are selected or deselected. The DOM structure should remain stable and match the order in which `cds-multi-select-item` elements are defined in the markup.

**Expected behavior:**
- Items should always appear in their original order (00-23 for hours, 00-59 for minutes)
- Selecting or deselecting items should not reorder the dropdown
- The visual presentation should remain consistent across all user interactions

## Impact

- **User Experience**: Users become confused when dropdown order changes unexpectedly
- **Usability**: Difficult to find and select additional items when order keeps changing
- **Data Integrity**: Sequential data (time, dates, numbers) loses its logical ordering
- **Accessibility**: Screen readers may announce items in unexpected order
- **Development Overhead**: Requires workarounds like trackBy functions, array recreation, and component re-rendering

## Use Case

This issue is particularly problematic in **time selection interfaces** where maintaining numerical order is critical:
- **Hours dropdown**: Must display 00-23 in sequential order
- **Minutes dropdown**: Must display 00-59 in sequential order
- **Scheduler interfaces**: Where users need to select multiple time slots

## Technical Details

The `cds-multi-select` web component appears to manipulate the DOM order of child `cds-multi-select-item` elements, moving selected items to the top. This happens at the Shadow DOM level, bypassing Angular's change detection and making it difficult to prevent without recreating the entire component.

## Suggested Enhancement

The component should respect the original DOM order of `cds-multi-select-item` elements as defined in the template. Item positioning should be determined solely by markup order, not by selection state. If visual indication of selected items is needed, it should be achieved through styling (highlighting, checkmarks) rather than DOM reordering.

**This issue is being tracked internally as** https://ibm-middleware.atlassian.net/browse/BOC-38538

### Screenshots

Selected the hours as 22 and 23
Image

Now remove the selected hours
Image

Now when we reopen the multi-select dropdown, Final order becomes: 22, 23, 00, 01, 02, ... 21. The sequential ordering is permanently broken until page reload
Image

### Prerequisites
- Carbon Design System with `cds-multi-select` component
- A multi-select dropdown with sequential numeric items (e.g., hours 00-23)

### Reproduction Steps

1. **Create a cds-multi-select component** with sequential items:
   ```html
   <cds-multi-select label="Hours (in UTC)">
     <cds-multi-select-item value="00">00</cds-multi-select-item>
     <cds-multi-select-item value="01">01</cds-multi-select-item>
     <cds-multi-select-item value="02">02</cds-multi-select-item>
     ...
     <cds-multi-select-item value="21">21</cds-multi-select-item>
     <cds-multi-select-item value="22">22</cds-multi-select-item>
     <cds-multi-select-item value="23">23</cds-multi-select-item>
   </cds-multi-select>
   ```
or

```html
   <cds-multi-select 
    label="Select Hours" 
    value="{{selectedValue}}" 
    size="md"
    (cds-multi-select-selected)="handleChange($event)">
    <cds-multi-select-item 
        *ngFor="let hour of hours"
        [value]="hour.value">
        {{hour.label}}
    </cds-multi-select-item>
</cds-multi-select>
```

2. **Open the dropdown** and verify items are displayed in correct order (00-23)

3. **Scroll to the bottom** of the dropdown list

4. **Select items near the end** of the list (e.g., select "22" and "23")

5. **Close the dropdown** (click outside or press Escape)

6. **Reopen the dropdown** and observe the order

7. **Click the X button** on the selected values to deselect them

8. **Reopen the dropdown again**

### Expected Result
- Items should remain in their original sequential order: 00, 01, 02, ... 21, 22, 23
- The order should not change regardless of selection/deselection

### Actual Result
- After step 6: Items 22 and 23 appear at the **top** of the dropdown
- After step 8: Items 22 and 23 **remain at the top** even after deselection
- Final order becomes: 22, 23, 00, 01, 02, ... 21
- The sequential ordering is permanently broken until page reload

### Additional Notes
- This issue occurs with any items selected from the dropdown, but is most noticeable with items at the end of the list
- The problem persists across multiple open/close cycles
- The DOM elements themselves are being reordered, not just visually repositioned
- This behavior makes it difficult for users to find items in their expected positions

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by maradwan26**
Closes #22016

Fixes an issue with `cds-multi-select` where items were not getting sorted on de-selection. This was due to the `compareItems` function implicitly returning `undefined`. Adds new properties `sortItems` and `compareItems` that allow for sorting customization.

### Changelog

**New**

- Added `sortItems` and `compareItems` properties
- Added `With Custom Sorting` story
- Added tests to cover this change
- Added docs to cover this change

**Changed**

- Fixed the default `compareItems` function by returning `itemA.localeCompare(itemB, locale, { numeric: true });` instead of nothing
- Changed the default `sortItems` function to sort by the item text instead of value

> [!NOTE]
> The new fixed sorting behaviour could affect users that were relying on the legacy behaviour (no sorting, just DOM order).
> These PR should be well highlighted in the release changelog when this PR gets merged to ensure visibility for affected users.

#### Testing / Reviewing

- Go to MultiSelect stories
- Select and deselect an item
- The item should go back its original position
- Go to With Custom Sorting story
- Selected items should move to the bottom of the list
- Check new docs for typos/grammar/clarity
    - Please let me know if you think this should be documented some place else, too, to increase visibility

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [X] Reviewed every line of the diff
- [X] Updated documentation and storybook examples
- [X] Wrote passing tests that cover this change
- [X] Addressed any impact on accessibility (a11y)
- [X] Tested for cross-browser consistency
- [X] Validated that this code is ready for review and status checks should pass

### CODE REVIEW

**Review by heloiselui — APPROVED** [review]
LGTM! Do we need to add an ADR for this, or is Storybook enough?

File: packages/web-components/src/components/multi-select/multi-select.ts [hunk 1]
```diff
@@ -679,14 +679,34 @@ class CDSMultiSelect extends CDSDropdown {
     });
   }
 
-  protected compareItems = (itemA, itemB, { locale }) => {
-    itemA.localeCompare(itemB, locale, { numeric: true });
+  protected defaultCompareItems = (
+    itemA: string,
+    itemB: string,
+    { locale }
```
Comment (adamalston) [inline packages/web-components/src/components/multi-select/multi-select.ts]: Types were added for `itemA` and `itemB`, but not for `locale`. Was there a reason for that?

File: packages/web-components/src/components/multi-select/multi-select.mdx [hunk 2]
```diff
@@ -51,6 +52,108 @@ selectable items to a subset.
...
+## Custom sorting
+
+The `cds-multi-select` component provides two properties to customize how items
+are sorted:
+
+### `sortItems` property
+
+The `sortItems` property allows you to override the default sorting behavior. By
+default, items are sorted alphabetically and selected items get moved to the top
+of the list.
```
Comment (adamalston) [inline packages/web-components/src/components/multi-select/multi-select.mdx]: This description appears to overstate the current behavior. With `selection-feedback="fixed"`, `compareItems` never runs because `sortItems` is only invoked under the `top` and `top-after-reopen` conditions in `shouldUpdate`. Should the docs be narrowed to those supported modes, or should the new sorting API also be wired up for `fixed`?

File: packages/web-components/src/components/multi-select/multi-select.ts [hunk 3]
```diff
@@ -679,14 +679,34 @@ class CDSMultiSelect extends CDSDropdown {
...
 
-  protected sortItems = (
+  /**
+   * Provide a custom function that is used to determine the ordering of
+   * options. The compare function should return a number whose sign indicates
+   * the relative order of the two elements: negative if a is less than b,
+   * positive if a is greater than b, and zero if they are equal. See 'sortItems'
+   * for more control.
+   *
+   * (itemA: string, itemB: string, { locale: string }) => number
```
Comment (adamalston) [inline packages/web-components/src/components/multi-select/multi-select.ts]: This code is invalid because the third parameter is missing either a parameter name or a properly typed destructuring pattern. I suggest updating it to one of the following:

```suggestion
   * (itemA: string, itemB: string, options: { locale: string }) => number
```

```suggestion
   * (itemA: string, itemB: string, { locale }: { locale: string }) => number
```

File: packages/web-components/src/components/multi-select/multi-select.ts [hunk 4]
```diff
@@ -714,6 +734,34 @@ class CDSMultiSelect extends CDSDropdown {
...
+  /**
+   * Provide a method that sorts all options in the control. Overriding this
+   * prop means that you also have to handle the sort logic for selected versus
+   * un-selected items. If you just want to control ordering, consider the
+   * `compareItems` prop instead.
+   *
+   * sortItems :
+   * (menuItems: NodeList, {
+   *   values: string[],
+   *   compareItems: (itemA: string, itemB: string, { locale: string }) => number,
```
Comment (adamalston) [inline packages/web-components/src/components/multi-select/multi-select.ts]: Same as earlier, this code is invalid.

File: packages/web-components/src/components/multi-select/multi-select.ts
Comment (adamalston) [inline packages/web-components/src/components/multi-select/multi-select.ts:1]: I noticed several `changedProperties.has` calls, but I don’t see any checks for `changedProperties.has('compareItems')`, `changedProperties.has('sortItems')`, or `changedProperties.has('locale')`. Should those checks and the corresponding handling be added as well?

File: packages/web-components/src/components/multi-select/multi-select.ts [hunk 5]
```diff
@@ -703,8 +723,8 @@ class CDSMultiSelect extends CDSDropdown {
       }
 
       return compareItems(
-        (itemA as HTMLInputElement).value,
-        (itemB as HTMLInputElement).value,
+        (itemA as HTMLElement).innerText.trim(),
+        (itemB as HTMLElement).innerText.trim(),
```
Comment (adamalston) [inline packages/web-components/src/components/multi-select/multi-select.ts]: I don’t think the type assertions are necessary. There are be type safe ways to get the items' text.

File: packages/web-components/src/components/multi-select/multi-select.ts (hunk 1 above)
Comment (maradwan26) [reply packages/web-components/src/components/multi-select/multi-select.ts]: Fixed ✅

File: packages/web-components/src/components/multi-select/multi-select.mdx (hunk 2 above)
Comment (maradwan26) [reply packages/web-components/src/components/multi-select/multi-select.mdx]: I've narrowed down this paragraph to be more specific to `top` and `top-after-reopen`

File: packages/web-components/src/components/multi-select/multi-select.ts (hunk 3 above)
Comment (maradwan26) [reply packages/web-components/src/components/multi-select/multi-select.ts]: Thanks for pointing this out. I've updated it to `{ locale }: { locale: string }` in the two instances in this file and also in one example that was in the `.mdx`

File: packages/web-components/src/components/multi-select/multi-select.ts
Comment (maradwan26) [reply packages/web-components/src/components/multi-select/multi-select.ts:1]: Added checks for `locale`, `compareItems`, and `sortItems` as sorting triggers in `shouldUpdate()` alongside the original checks for `value`, `open` and `selectionFeedback`.

File: packages/web-components/src/components/multi-select/multi-select.ts (hunk 5 above)
Comment (maradwan26) [reply packages/web-components/src/components/multi-select/multi-select.ts]: Yeah good point, Node already has a `textContent` property that can be used instead. I've updated this https://github.com/carbon-design-system/carbon/pull/22090/changes/57cbca6aa446b3dbd34a192e5a5d6a2529fda5cf

**Comment by tay1orjones** [comment]
> Do we need to add an ADR for this, or is Storybook enough?

Totally up to you. The [ADR guidance](https://github.com/carbon-design-system/carbon/blame/e8153093a0673f7da2feb381eb6ab07074f47e2e/docs/decisions/README.md#L11) is intentionally ambiguous describing ADRs as things that are "architecturally significant"

This doesn't feel significant to me personally, but if you think it would help future devs to have additional context and detail not captured in this PR, an ADR could make sense.

**Review by tay1orjones — APPROVED** [review]

File: packages/web-components/src/components/multi-select/multi-select.mdx [hunk 6]
```diff
@@ -51,6 +52,114 @@ selectable items to a subset.
...
+        if (hasItemA && !hasItemB) {
+          return 1;
+        }
+        if (hasItemB && !hasItemA) {
+          return -1;
+        }
+
+        return compareItems(
+          (itemA as HTMLElement).innerText.trim(),
+          (itemB as HTMLElement).innerText.trim(),
```
Comment (adamalston) [inline packages/web-components/src/components/multi-select/multi-select.mdx:103]: The type assertions aren't necessary, similar to https://github.com/carbon-design-system/carbon/pull/22090#discussion_r3144332511.

File: packages/web-components/src/components/multi-select/multi-select.stories.ts [hunk 7]
```diff
@@ -1048,6 +1048,102 @@ export const WithToggletipLabel = {
...
+        if (hasItemA && !hasItemB) {
+          return 1;
+        }
+        if (hasItemB && !hasItemA) {
+          return -1;
+        }
+
+        return compareItems(
+          (itemA as HTMLElement).innerText.trim(),
+          (itemB as HTMLElement).innerText.trim(),
```
Comment (adamalston) [inline packages/web-components/src/components/multi-select/multi-select.stories.ts:1111]: The type assertions aren't necessary, similar to https://github.com/carbon-design-system/carbon/pull/22090#discussion_r3144332511.

**Review by adamalston — COMMENTED** [review]
I realize this pull request has already been merged. I’m submitting this review anyway since I think there's still some cleanup that should be done in a future pull request.

File: packages/web-components/src/components/multi-select/multi-select.mdx (hunk 6 above)
Comment (maradwan26) [reply packages/web-components/src/components/multi-select/multi-select.mdx:103]: https://github.com/carbon-design-system/carbon/pull/22146
