### PR TITLE
fix(react): update tablist to check if tab current is defined

### LINKED ISSUE #11379: [Bug]: TabList component causes app crash
### Package

@carbon/react

### Browser

Safari

### Package version

1.2.0

### React version

_No response_

### Description

When using TabList component the app crashes.  Taking the code example from the carbon site and just rendering it causes the crash as well.  Taking out TabList fixes it; but Tabs need it to work properly.

```
      <Tabs>
        <TabList aria-label="List of tabs" contained={true}>
          <Tab>Tab Label 1</Tab>
          <Tab>Tab Label 2</Tab>
          <Tab>Tab Label 5</Tab>
        </TabList>
        <TabPanels>
          <TabPanel>Tab Panel 1</TabPanel>
          <TabPanel>Tab Panel 2</TabPanel>
        </TabPanels>
      </Tabs>
```

Error:
```
TypeError: tab.current.getBoundingClientRect is not a function. (In 'tab.current.getBoundingClientRect()', 'tab.current.getBoundingClientRect' is undefined)
(anonymous function) — Tabs.js:255
```

### CodeSandbox example

CODE SANDBOX IS NOT WORKING WITH CARBON 11

### Steps to reproduce

Crashes on app load.

Issue started with Carbon 11 migration.
re

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #11379 

Checks for `tab.current` before using it. 

### Testing 

Check and see that Tabs works as expected

### CODE REVIEW

**Comment by joshblack** [comment]
@abbeyhrt do you know of a good way to re-create the issue from https://github.com/carbon-design-system/carbon/issues/11379 to verify that it's fixed?

**Review by dabrad26 — APPROVED** [review]

File: packages/react/src/components/Tabs/next/Tabs.js [hunk 1]
```diff
@@ -132,14 +132,22 @@ function TabList({
...
   });
 
+  console.group('TabList#render');
+  console.log({
+    activeIndex,
+    selectedIndex,
+    scrollLeft,
+  });
+  console.groupEnd();
+
```
Comment (tay1orjones) [inline packages/react/src/components/Tabs/next/Tabs.js]: This is causing tests to fail

```suggestion
```

**Review by tay1orjones — APPROVED** [review]
Looks good other than the test ci failing due to the console.logs

**Review by joshblack — APPROVED** [review]
