### PR TITLE
fix(Slider): onRelease not always firing (#2695)

### LINKED ISSUE #2695: Slider: `onRelease` sometimes doesn't fire
## Detailed description

When changing the slider value, the `onRelease` event doesn't fire sometimes. This happens inconsistently, but usually every 20 or so attempts. I can reproduce this by starting at any position on the slider (0-100%), dragging, and finally releasing at any other point on the slider, but it seems to happen more often when I release at 0%. 

My expectation is that every time I release the handle, `onRelease` is fired and should be the last event to be fired (after all the `onChange`s that occurs during the drag).

__Component version:__ carbon-components-react@6.107.0 and the version currently running on Carbon Storybook

__Browser:__ Chrome 74.0.3729.108 (Official Build) (64-bit)

## Steps to reproduce the issue

1. In the slider component in Storybook http://react.carbondesignsystem.com/?selectedKind=Slider&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
2. Drag the handle from anywhere on the slider (eg. 50%) to a different position (eg. 0%)
3. Release the handle

## Additional information
Video reproducing the problem in Storybook
[carbonslider_onrelease.mp4.zip](https://github.com/carbon-design-system/carbon-components-react/files/3170831/carbonslider_onrelease.mp4.zip)

Would it be possible to get a fix for v9 urgently as we need to meet our timeline for May?

### PR DESCRIPTION
**Pull request by jharvey10**
Closes #2695 

This PR makes a few updates/fixes to the Slider component and also addresses some unit test failures on Windows.

#### Changelog

**New**

- You can now click anywhere on the Slider track to begin dragging. I believe this to be an improvement over the previous behavior (when clicking/dragging on the track, the thumb would only update once you released the mouse).
Old:
old1
New:
new1

**Changed**

- Fixes a bug with the Slider where fast dragging/release could sometimes neglect to fire the `onRelease` event.
Old:
old2
New:
new2

- Fixed some issues with running the unit test suite on Windows.
  -  Fixed 2 issues relating to forward-slash vs back-slash in paths.
  - There are still 3 outstanding test failures in `packages/upgrade/src/migrations/carbon-icons-react/10.3.0/__tests__/update-icon-import-path-test.js` because the test fixtures used in these tests contain `\n` line endings and the `jscodeshift` `transform()` operation (on Windows) appears to be generating output with `\r\n` line endings.
    - My recommendation would be to ignore these tests on Windows, but I haven't implemented anything to that effect.
  - I noticed that many of the unit tests weren't running on Windows because of the way the `testMatch` micromatch expressions were written in `package.json` (see: facebook/jest#7914)

#### Testing / Reviewing

The above GIFs should give a good indication of how to test this functionality in the react storybook.

### CODE REVIEW

**Review by aagonzales — APPROVED** [review]
Looks good from a visual standpoint

**Comment by abbeyhrt** [comment]
Thanks for taking the time to contribute! Any thoughts on this, @joshblack?

File: packages/react/src/components/Slider/Slider.js [hunk 1]
```diff
@@ -176,41 +209,56 @@ export default class Slider extends PureComponent {
...
+        left,
+        value: newValue,
+        needsOnChange: true,
+      };
+    };
+
+    const setStateCallback = () => {
+      this.handleDragComplete();
+
+      requestAnimationFrame(() => {
```
Comment (joshblack) [inline packages/react/src/components/Slider/Slider.js]: Seems like the call to rAF is moved from enqueuing the state update to now calling `props.onChange`, was there any particular reason for this change? Super curious 👀

File: packages/react/src/components/Slider/Slider.js [hunk 2]
```diff
@@ -17,6 +17,38 @@ const defaultFormatLabel = (value, label) => {
   return typeof label === 'function' ? label(value) : `${value}${label}`;
 };
 
+/**
+ * Types of events used to indicate that the slider's value should get recalculated.
+ */
+const CALC_VALUE_EVENT_TYPES = Object.freeze([
```
Comment (asudoh) [inline packages/react/src/components/Slider/Slider.js]: Nitpick - Probably a `Set`?

File: packages/react/src/components/Slider/Slider.js (hunk 1 above)
Comment (jharvey10) [reply packages/react/src/components/Slider/Slider.js]: I did this primarily because the way rAF was being used was the cause of the bug, but also because it was hard to determine exactly why rAF was being used. I ran under the assumption that it was being used to rate limit the number of `onChange` and `onRelease` callbacks that are fired, since when we chatted on Webex, I believe you indicated that this type of rAF usage wasn't a common paradigm across components.

I got a message earlier from @asudoh indicating that the reason for this rAF usage was in fact to throttle the number of mousemove events that are considered for state updates, but in spite of this intent, I don't believe this is actually the way the component was behaving. Since pretty much every mousemove event ultimately resulted in a call to rAF, these events were simply being queued for batch execution at the next animation frame; none of them would actually be discarded from consideration altogether. In theory, the net number of state updates would be the same, except in the old implementation, the `setState` calls would be slightly delayed until the next animation frame picked them up for execution. This delayed state update is what causes the bug, since a mouseup event could actually fire and complete before the next animation frame had a chance to update the state in the proper way to cause the `onRelease` callback to fire.

so I guess my question is:

What is the Carbon-wide paradigm here? Are callbacks and events typically rate limited? If so, are there typical ways in which components accomplish this?

Comment (asudoh) [reply packages/react/src/components/Slider/Slider.js]: Thank you for your thoughts @jdharvey-ibm! Basically, we use `lodash.debounce` or `lodash.throttle` whenever handling every event does not make sense; One of the cases is stale event, e.g. if we have two events to open timer-based tooltip in a short amount of time, the earlier one is stale (given the timer should be based on the latter). Another is many same events (e.g. `mousemove` or `resize`) in short amount of time, especially if the event handler involves heavy operation, which is the case of `<Slider>` (more below).

The current `<Slider>` code cancels running the logic of moving the thumb if one for earlier event is pending, which means an optimization similar to throttling:
https://github.com/carbon-design-system/carbon/blob/v10.9.0/packages/react/src/components/Slider/Slider.js#L169-L171

The direct cause of the problem is that running `onRelease()` callback is canceled if the operation of moving the thumb is canceled, even though calling `onRelease()` is _not_ considered heavy. That said, moving `handleDrag()` to before that line at least ensures that `onRelease()` is called. Wondering it's something you want to try instead of doing some refactoring.

An indirect cause of the problem that such throttling logic is written in a way that may confuse people who try to jump in and maintain the code that the logic is for managing "dragging state" instead. That caused the one who introduced `onRelease()` to put his code into a wrong place. That said, in future, I think we need to put part of `mousemove` handler code (only the logic calculating the position) into `lodash.throttle` callback rather than maintaining our own logic of throttling.

Comment (jharvey10) [reply packages/react/src/components/Slider/Slider.js]: Unfortunately making that particular change you suggest (I did indeed try that earlier on) regresses the deterministic behavior of the order in which the events are fired. Since `onChange` is still fired within the rAF call, it becomes possible to have `onRelease` called *before* `onChange`. If that is acceptable, then we can go with that instead, but I feel like it's kind of weird to change that behavior.

If the long-term goal is to convert this to use `_.throttle`, then I could probably take a stab at that over the next week or two, but I'd like your feedback on that before going off in that direction.

Comment (asudoh) [reply packages/react/src/components/Slider/Slider.js]: `onChange`/`onRelease` order is a great point. A quick fix may be enqueueing `onRelease` call instead of calling it directly at https://github.com/carbon-design-system/carbon/blob/v10.9.0/packages/react/src/components/Slider/Slider.js#L347.

And you are right that the long-term goal is converting the code to use `_.throttle`.

**Comment by jharvey10** [comment]
This PR is not yet ready for merging, but I am pushing it for two reasons. 1) so I can work on it on my other machine :) and 2) to potentially give you guys an early look at it for review purposes. I need to update the unit tests and also go through the code again to make sure everything looks okay.

File: packages/react/src/components/Slider/Slider.js [hunk 3]
```diff
@@ -143,221 +177,255 @@ export default class Slider extends PureComponent {
...
-    newValue = value;
+    // Set needsOnRelease flag so event fires on next update
+    this.setState({ needsOnRelease: true });
+  };
 
-    if (evt) {
-      const { type } = evt;
+  /**
+   * Handles a "drag" event by recalculating the value/thumb and setting state
+   * accordingly. This function throttles "drag" events to be processed at most
```
Comment (jdharvey-ibm) [inline packages/react/src/components/Slider/Slider.js]: should be "at least"

File: packages/react/src/components/Slider/Slider.js [hunk 4]
```diff
@@ -143,221 +177,255 @@ export default class Slider extends PureComponent {
...
+      const { value, left } = this.calcValue({ clientX: evt.clientX });
+      this.setState({ value, left });
+    },
+    EVENT_THROTTLE,
+    { leading: true, trailing: false }
+  );
+
+  /**
+   * Handles a `keydown` event by recalculating the value/thumb and setting
+   * state accordingly. This function throttles "drag" events to be processed at
```
Comment (jharvey10) [inline packages/react/src/components/Slider/Slider.js]: should say "keydown" instead of "drag"

File: packages/react/src/components/Slider/Slider.js [hunk 5]
```diff
@@ -143,221 +177,255 @@ export default class Slider extends PureComponent {
...
-      {
-        holding: false,
-      },
-      this.updatePosition
-    );
+    // Avoid calling calcValue for invaid numbers, but still update the state
+    if (Number.isNaN(targetValue)) {
+      this.setState({ value: evt.target.value });
+    } else {
+      targetValue = Math.clamp(targetValue, this.props.min, this.props.max);
```
Comment (asudoh) [inline packages/react/src/components/Slider/Slider.js]: Chrome-only `Math` API: https://developer.mozilla.org/en-US/docs/Web/CSS/clamp, we should replace with something else.

File: packages/react/src/components/Slider/Slider.js [hunk 6]
```diff
@@ -143,221 +177,255 @@ export default class Slider extends PureComponent {
...
 
-  handleMouseEnd = () => {
-    this.setState(
-      {
-        holding: false,
-      },
-      this.updatePosition
-    );
+    // Avoid calling calcValue for invaid numbers, but still update the state
+    if (Number.isNaN(targetValue)) {
```
Comment (asudoh) [inline packages/react/src/components/Slider/Slider.js]: IE11 doesn't support `Number.isNaN()`. We tend to use legacy/global `isNaN()` for now.

**Review by asudoh — COMMENTED** [review]
@jdharvey-ibm The new code looks great basically, and thank you for the updated code. Just a couple of things:

* Seems that the new code has usage of browser APIs that don't have IE11, etc. support. Please check e.g. MDN for those.
* Though dragging requires throttling, I don't think arrow keys requires throttling. (We rather want to capture every gesture of increment/decrement in this case)

Looking forward to seeing the finished code!

File: packages/react/src/components/Slider/Slider.js (hunk 5 above)
Comment (jharvey10) [reply packages/react/src/components/Slider/Slider.js]: Done!

File: packages/react/src/components/Slider/Slider.js (hunk 6 above)
Comment (jharvey10) [reply packages/react/src/components/Slider/Slider.js]: Done!

**Review by aagonzales — APPROVED** [review]

**Comment by asudoh** [comment]
@jdharvey-ibm Let us know when you are ready for re-review - Thanks!

**Comment by jharvey10** [comment]
Oops! Sorry, though I'd already hit the "request re-review" button for everyone, but I'm not sure if that worked. It's all set for re-review! No further commits planned at this time. I re-requested a review from @aagonzales, and it looks like she already re-approved the changes from a visual perspective (thanks!).

**Comment by asudoh** [comment]
Thank you for clarifying @jdharvey-ibm - The automatic way in GH of requesting re-review does not tend to tell what change has been done and how reviewers should act on. That's why I asked for the latest state. Sorry if it was confusing.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jdharvey-ibm for finishing up the work!

**Comment by jharvey10** [comment]
👍 Thanks for the feedback and guidance along the way!

**Comment by abbeyhrt** [comment]
@joshblack not sure if you want to take a second look but the PR is ready for it! 👍

File: packages/react/src/components/Slider/Slider.js [hunk 7]
```diff
@@ -17,6 +19,31 @@ const defaultFormatLabel = (value, label) => {
...
+
+/**
+ * Event types that trigger a "drag" to stop.
+ */
+const DRAG_STOP_EVENT_TYPES = new Set(['mouseup', 'touchend', 'touchcancel']);
+
+/**
+ * Constants used during keydown event processing.
+ */
+const ARROW_KEYS = Object.freeze({
```
Comment (joshblack) [inline packages/react/src/components/Slider/Slider.js]: We have `matches` and `match` in our keyboard module to help out with keyboard events 👀 

https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/internal/keyboard/match.js#L15-L32

**Review by joshblack — CHANGES_REQUESTED** [review]
Looks amazing! 🎉 Just a quick comment to help out with keyboard stuff 👀

File: packages/react/src/components/Slider/Slider.js (hunk 7 above)
Comment (jharvey10) [reply packages/react/src/components/Slider/Slider.js]: Done!

**Review by joshblack — APPROVED** [review]
🔥
