### PR TITLE
fix: update welcome page content and styles in storybook

### LINKED ISSUE #18891: welcome.scss does not pass stylelint checks
https://github.com/carbon-design-system/carbon/blob/f574ad0e46ed2f7d84ba50c8561bd9cb20ffa1b3/packages/react/.storybook/Welcome/welcome.scss

```sh
❯ yarn stylelint --report-needless-disables --report-invalid-scope-disables --allow-empty-input packages/react/.storybook/Welcome/welcome.scss

packages/react/.storybook/Welcome/welcome.scss
  11:3  ✖  Unexpected "top" property. Use "inset-block-start".          csstools/use-logical
  12:3  ✖  Unexpected "left" property. Use "inset-inline-start".        csstools/use-logical
  13:3  ✖  Unexpected "width" property. Use "inline-size".              csstools/use-logical
  14:3  ✖  Unexpected "height" property. Use "block-size".              csstools/use-logical
  31:3  ✖  Unexpected "margin-top" property. Use "margin-block-start".  csstools/use-logical
  36:3  ✖  Unexpected "margin-top" property. Use "margin-block-start".  csstools/use-logical
```

### PR DESCRIPTION
**Pull request by adamalston**
Closes https://github.com/carbon-design-system/carbon/issues/18891

Updated welcome page content and styles in Storybook.

### Changelog

**Changed**

- Updated welcome page content and styles in Storybook.

**Removed**

- Removed dead code.

#### Testing / Reviewing

Compare http://localhost:3000/?path=/docs/getting-started-welcome--welcome to https://react.carbondesignsystem.com/?path=/docs/getting-started-welcome--welcome.

I left a `TODO` with a question that hopefully someone can answer.

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [ ] ~Wrote passing tests that cover this change~
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/react/.storybook/Welcome/Welcome.js [hunk 1]
```diff
@@ -15,22 +14,20 @@ import { Stack } from '../../src/components/Stack';
...
         <Link
           href="https://carbondesignsystem.com/"
           className="welcome__link"
           renderIcon={ArrowRight}>
           Website
         </Link>
         <Link
+          // TODO: Should the `href` be `PackageInfo.repository.url` instead?
+          // The current value links to the package's directory, not the
+          // repository. The link's text says "GitHub repo".
```
Comment (annawen1) [inline packages/react/.storybook/Welcome/Welcome.js]: I think it should link to the current value (package directory) as this storybook is specific to the react package

Comment (adamalston) [reply packages/react/.storybook/Welcome/Welcome.js]: Do you think I should modify the text in the link or leave it unchanged?

Comment (annawen1) [reply packages/react/.storybook/Welcome/Welcome.js]: I personally think it's ok to leave it unchanged

Comment (annawen1) [inline packages/react/.storybook/Welcome/Welcome.js]:
```suggestion
```

**Review by annawen1 — APPROVED** [review]

**Review by kennylam — APPROVED** [review]
