### PR TITLE
fix(ui-shell): display names for HeaderMenu & SideNavMenu forwardRefs

### LINKED ISSUE #4679: [UIShell] HeaderMenu and SideNavMenu forwardsRefs have no displayName & are Anonymous
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The `HeaderMenu` and `SideNavMenu` subcomponents of the `UIShell` are forwardRefs and do not have display names set. Therefore, in the React browser plugin, they show up as `Anonymous` --

Screen Shot 2019-11-14 at 10 33 47 AM
Screen Shot 2019-11-14 at 10 34 16 AM

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4679

Adds display names to 2 forwardRef components so that they aren't anonymous.

Easiest way to check on this is view the deployment with the React browser plugin, and specifically inspect these components.

EDIT: note this also helps other forwardRefs that are descendants of these components, like icons, so that their display names will now show up as well.

EDIT 2: I also went ahead and added display names to the story to help with the story source, so that prop tables + source for `SideNav`-related stories shows the component name instead of "Unknown" or "[object Object]"

#### Changelog

**Added**

- added display names to `SideNav`-related stories to prevent "Unknown" or "[object Object]" in story source

**Changed**

- add display names to `HeaderMenu` and `SideNavMenu`

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Comment by asudoh** [comment]
@jendowns Could you please updae the snapshot? Thanks!

File: packages/react/src/components/UIShell/HeaderMenu.js [hunk 1]
```diff
@@ -219,6 +219,8 @@ class HeaderMenu extends React.Component {
   };
 }
 
-export default React.forwardRef((props, ref) => {
-  return <HeaderMenu {...props} focusRef={ref} />;
-});
+export default (() => {
```
Comment (joshblack) [inline packages/react/src/components/UIShell/HeaderMenu.js]: Is there anyway we could switch the pattern here to:

```jsx
const Component = React.forwardRef((props, ref) => {
  //
});

Component.displayName;
export default Component;
```

Just want to avoid adding IIFE blocks to exports

**Review by joshblack — CHANGES_REQUESTED** [review]

**Review by abbeyhrt — APPROVED** [review]
Looks good to me!! 🎉

**Comment by jendowns** [comment]
@asudoh I have updated the snapshots, and @joshblack I have updated the export pattern per your feedback. Thank you both!

File: packages/react/src/components/UIShell/HeaderMenu.js [hunk 2]
```diff
@@ -221,6 +221,9 @@ class HeaderMenu extends React.Component {
   };
 }
 
-export default React.forwardRef((props, ref) => {
+const Component = React.forwardRef((props, ref) => {
```
Comment (joshblack) [inline packages/react/src/components/UIShell/HeaderMenu.js]: While verbose, would something like this make? Just thinking out loud. `Component` can conflict with `React.Component` if folks pull it off the import so would hate to run into that.

```suggestion
const HeaderMenuForwardRef = React.forwardRef((props, ref) => {
```

**Comment by jendowns** [comment]
Thank you @joshblack! That's a really good point 😅 I just pushed an update that fixes the exports.

**Review by joshblack — APPROVED** [review]
