### PR TITLE
fix: dynamic classes only now functional

### LINKED ISSUE #4779: dynamic classes only added to icons when static classes used
Ensure dynamic classes work when icon in @carbon/icons-vue is not given a static class.

## What package(s) are you using?

- [x] @carbon/icons-vue
 
## Detailed description

> Describe in detail the issue you're having.
It was not possible to specify only dynamic classes to @carbon/icons-vue

> Is this issue related to a specific component?
All icons generated by @carbon-icons/vue

> What did you expect to happen? What happened instead? What would you like to
> see changed?
To be able to specify dynamic classes only

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.7

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
@caronb/vue

## Steps to reproduce the issue

PR with test to follow.

### PR DESCRIPTION
**Pull request by lee-chase**
Closes #4779

Add the ability to use dynamic classes only in @carbon/icons-vue

#### Changelog

m packages/icons-vue/tasks/__tests__/createIconComponent-test.js
m packages/icons-vue/tasks/createIconComponent.js

#### Testing / Reviewing

Without this I am unable to progress the use of carbon prefix for classes in some @carbon/vue components.

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @lee-chase!

File: packages/icons-vue/tasks/createIconComponent.js [hunk 1]
```diff
@@ -55,6 +55,7 @@ export default {
       };
     }
     if (data.class) {
+      svgData.class = svgData.class || {}; // may be no static class
```
Comment (emyarod) [inline packages/icons-vue/tasks/createIconComponent.js:58]: just wondering could the default value for `svgData.class` be an empty object as well? on L48:

```js
const svgData = {
  attrs,
  on: listeners,
  class: {},
};
```

**Review by emyarod — APPROVED** [review]
looks good to me

File: packages/icons-vue/tasks/createIconComponent.js (hunk 1 above)
Comment (lee-chase) [reply packages/icons-vue/tasks/createIconComponent.js:58]: I don't think it will do any harm, I was just trying to make the minimal impact change.

**Comment by lee-chase** [comment]
Hey @asudoh @emyarod any chance this could make it into the next release? It is preventing me replacing 'bx' prefixes on classes with the carbon setting in @carbon/vue
