### PR TITLE
fix: combobox focus input

### LINKED ISSUE #9776: [a11y]: focus not visible when clicking on combobox toggle
### Package

carbon-components-react

### Browser

Chrome

### Operating System

MacOS

### Package version

v10.44.2

### Automated testing tool and ruleset

none

### Assistive technology

_No response_

## Current
When clicking with a mouse on the combobox toggle, there is no visual indication of focus.
Kapture 2021-09-30 at 12 13 18

## Expected
The input should receive a visual focus when clicking the toggle. This was the behaviour in a prior version of Carbon (10.17 and likely later versions)

Kapture 2021-09-30 at 12 15 35

### WCAG 2.1 Violation

Success Criterion 2.4.7: Focus Visible

### CodeSandbox example

https://codesandbox.io/s/cranky-mestorf-nevdm

### Steps to reproduce

Click on the chevron/toggle with a mouse to expand the listbox.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #9776 

Adds input focus when opening and collapsing menu

- [x] Make sure when toggling the up/down arrow the input receives focus

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]

File: packages/react/src/components/ComboBox/ComboBox.js [hunk 1]
```diff
@@ -303,11 +306,7 @@ const ComboBox = React.forwardRef((props, ref) => {
         });
 
         const handleFocus = (evt) => {
-          if (evt.target.type === 'button') {
-            setIsFocused(false);
-          } else {
-            setIsFocused(evt.type === 'focus' ? true : false);
-          }
+          setIsFocused(evt.type === 'focus' ? true : false);
```
Comment (francinelucca) [inline packages/react/src/components/ComboBox/ComboBox.js]: is the ternary necessary here? 🤔
```suggestion
          setIsFocused(evt.type === 'focus');
```

**Review by francinelucca — CHANGES_REQUESTED** [review]
Looks good! one minor code suggestion

**Review by francinelucca — APPROVED** [review]
🚀
