### PR TITLE
fix(search): switch search role from datatable to search, add labeledby

### LINKED ISSUE #4665: TableToolbarSearch does not add aria-label for accessibility
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The TableToobarSearch within the DataTable does not add/provide with an aria label. This is causing accessbility violations in our accessbility tool. Currently the work around is add an aria label attribute once the DataTable component is mounted and there doesn't seem to be any other way.

## Steps to reproduce the issue
1. Inspect the Search bar element
2. Under the <div class='bx--toolbar-action..> no aria-labels are displayed

> Please create a reduced test case in CodeSandbox
>
 - React:
https://codesandbox.io/embed/affectionate-elbakyan-f0rsj?fontsize=14

## Additional information

- Screenshots or code
Screen Shot 2019-11-12 at 3 13 57 PM

- Current work around by setting the attributes inside ComponentDidMount
Screen Shot 2019-11-12 at 3 36 02 PM

### LINKED ISSUE #5289: Cannot add 'aria-label' attribute to TableToolbarSearch.js component
## What package(s) are you using?

- [x] `carbon-components-react`

Detailed description

> Describe in detail the issue you're having.
The 'search' region in the TableToolbarSearch.js region does not have an 'aria-label' attribute, and it is not possible to add one.

> Is this issue related to a specific component?
TableToolbarSearch.js

Steps to reproduce the issue

See the role="search" region on Carbon storybook:
https://react.carbondesignsystem.com/?path=/story/datatable--with-toolbar

Screenshot shows the storybook with the relevant div highlighted:
Screenshot 2020-02-06 at 16 42 32

Screenshot shows 'role="search"' region in TableToolbarSearch in carbon-design-system/carbon:
Screenshot 2020-02-06 at 16 43 08

- Notes

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #5289 
Closes: #4665

This PR removes `role="search"` from TableToolbarSearch and adds it to the outer div of the search component and adds an `id` to the label so that the search is labeled by `labelText` and can be made unique to each Search bar if there are multiple on a page, for example if someone has a search component for the page and one inside a data table. 

#### Changelog

**New**

- `id` for Search `label` 
- search role on Search component

**Changed**

- updated snapshots 

**Removed**

- search role from TableToolbarSearch

#### Testing / Reviewing

Inspect the Search component in or outside of a data table and check that `aria-labelledby` with a unique id is being applied to the div with `role="search"` .

### CODE REVIEW

File: packages/react/src/components/Search/Search.js [hunk 1]
```diff
@@ -162,9 +162,12 @@ export default class Search extends Component {
     const CloseIconX = size === 'xl' ? Close20 : Close16;
 
     return (
-      <div className={searchClasses}>
+      <div
+        role="search"
```
Comment (joshblack) [inline packages/react/src/components/Search/Search.js]: Should this always be on the `<Search>` component? I'm just not sure what the impact is 🤔 

It seems like `role="search"` is treated as a landmark and if folks are using this frequently it might clutter the list of regions on the page if we default here versus over in `TableToolbarSearch` we should have ideally one version of itself on thepage.

File: packages/react/src/components/Search/Search.js [hunk 2]
```diff
@@ -162,9 +162,12 @@ export default class Search extends Component {
...
+        aria-labelledby={id + '-search'}
+        className={searchClasses}>
         <Search16 className={`${prefix}--search-magnifier`} />
-        <label htmlFor={id} className={`${prefix}--label`}>
+        <label id={id + '-search'} htmlFor={id} className={`${prefix}--label`}>
```
Comment (joshblack) [inline packages/react/src/components/Search/Search.js]: Maybe it'd help out to create a variable like `const searchId = `${id}-search`;` and use it in both spots? Just so updates to one location are mirrored in the other location.

File: packages/react/src/components/Search/Search.js (hunk 1 above)
Comment (abbeyhrt) [reply packages/react/src/components/Search/Search.js]: From what I read, it seems like even if there are multiple searches on a page, each one still should be a landmark with a unique label of what it is for (data table, the whole site, etc). Since we didn't make the input type "search", the Search component isn't a landmark right now and probably should be without users needing to add it.

File: packages/react/src/components/Search/Search.js (hunk 2 above)
Comment (abbeyhrt) [reply packages/react/src/components/Search/Search.js]: Good idea! I'll add it!

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @abbeyhrt!

**Review by joshblack — APPROVED** [review]
