### PR TITLE
fix(dropdown): add id to label for titleText elements

### LINKED ISSUE #19101: [a11y]: The 'id' "downshift-:r2:-label" specified for the ARIA property 'aria-labelledby' value is not valid
### Package

@carbon/react

### Browser

Chrome

### Operating System

MacOS

### Package version

v1.40.0

### React version

_No response_

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker - Latest Deployment

### Assistive technology

_No response_

### Description

The 'id' "downshift-:r2:-label" specified for the ARIA property 'aria-labelledby' value is not valid.

FYI: I have found that if we are using the Tooltip/ ToggleTip component inside the Dropdown, it causes a violation.

Image

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://stackblitz.com/edit/github-jdzenu?file=src%2FApp.jsx

### Steps to reproduce

https://stackblitz.com/edit/github-jdzenu?file=src%2FApp.jsx

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by annawen1**
Closes #19101 

When we pass in an element to the `titleText` prop, the `id` and `for` attributes provided by downshift don't get applied to the `label` element which results in a violation with the IBM Equal Access Accessibility Checker

example:
`The 'id' "downshift-:r2:-label" specified for the ARIA property 'aria-labelledby' value is not valid.`

This PR adds only `id` to the `label` element when the `titleText` is an element which allows for [interactive labels to still work](https://github.com/carbon-design-system/carbon/pull/18643)

#### Changelog

**Changed**

- change tests to check for `for` attribute instead of `id`
- in `Dropdown` and `Multiselect`, add `id` to `labelProps` when `titleText` is an HTMLElement

#### Testing / Reviewing

Go to `With Toggletip Label` stories in `Dropdown` and `Multiselect` and check that you are still able to open and interact with the Toggletip component in the labels

Run the Accessibility Checker to confirm the violation mentioned above doesn't appear

### CODE REVIEW

**Comment by annawen1** [comment]
Hi @adamalston can you review this PR and double check it doesn't undo the fix you had made to address https://github.com/carbon-design-system/carbon/issues/16987?

File: packages/react/src/components/Dropdown/__tests__/Dropdown-test.js [hunk 1]
```diff
@@ -472,6 +472,6 @@ describe('Test useEffect ', () => {
 
     const label = screen.getByText('Dropdown Title').closest('label');
 
-    expect(label).not.toHaveAttribute('id');
+    expect(label).not.toHaveAttribute('for');
```
Comment (adamalston) [inline packages/react/src/components/Dropdown/__tests__/Dropdown-test.js]: I notice that we're checking for the element not to have a `for` attribute. However, I don't see any other testing that an element should have that attribute in this file. So when should and element have it and when should it not? And should both be tested? I probably should've considered these things more in https://github.com/carbon-design-system/carbon/issues/16987.

Suggestion to replace the last two tests in this file with the following code or something similar to check all attributes. Note that I've also changed the test titles given the component updates.

```js
it('should add certain label props when `titleText` is a string', () => {
  render(<Dropdown {...mockProps} titleText="Dropdown Title" />);

  const label = screen.getByText('Dropdown Title').closest('label');
  const attributes = Array.from(label.attributes).reduce(
    (acc, { name, value }) => ({ ...acc, [name]: value }),
    {}
  );

  expect(attributes).toEqual({
    class: 'cds--label',
    for: 'downshift-:r2d:-toggle-button',
    id: 'downshift-:r2d:-label',
  });
});

it('should add certain label props when `titleText` is an element', () => {
  render(<Dropdown {...mockProps} titleText={<span>Dropdown Title</span>} />);

  const label = screen.getByText('Dropdown Title').closest('label');
  const attributes = Array.from(label.attributes).reduce(
    (acc, { name, value }) => ({ ...acc, [name]: value }),
    {}
  );

  expect(attributes).toEqual({
    class: 'cds--label',
    id: 'downshift-:r2g:-label',
  });
});
```

File: packages/react/src/components/Dropdown/Dropdown.tsx [hunk 2]
```diff
@@ -608,7 +608,9 @@ const Dropdown = React.forwardRef(
       return React.isValidElement(element) ? element : null;
     }, [slug, decorator]);
 
-    const labelProps = !isValidElement(titleText) ? getLabelProps() : null;
+    const labelProps = !isValidElement(titleText)
+      ? getLabelProps()
+      : { id: getLabelProps().id };
```
Comment (adamalston) [inline packages/react/src/components/Dropdown/Dropdown.tsx]:
```suggestion
    const allLabelProps = getLabelProps();
    const labelProps = isValidElement(titleText)
      ? { id: allLabelProps.id }
      : allLabelProps;
```

**Review by adamalston — COMMENTED** [review]
I checked the stories and the tests I added in https://github.com/carbon-design-system/carbon/issues/16987. They all still appear to be working correctly.

Separately, it seems like a good bit of code is shared between `Dropdown` and `MultiSelect`. Should some of that code be abstracted? When thinking about the future of these components, do we run the risk of someone updating something in one of them and forgetting to put that same update in the other? Nothing that needs to change in this PR if at all, just curious to hear your thoughts and others.

File: packages/react/src/components/Dropdown/__tests__/Dropdown-test.js (hunk 1 above)
Comment (annawen1) [reply packages/react/src/components/Dropdown/__tests__/Dropdown-test.js]: Good point, I'll do the same for MultiSelect as well

**Comment by annawen1** [comment]
> I checked the stories and the tests I added in #16987. They all still appear to be working correctly.
> 
> Separately, it seems like a good bit of code is shared between `Dropdown` and `MultiSelect`. Should some of that code be abstracted? When thinking about the future of these components, do we run the risk of someone updating something in one of them and forgetting to put that same update in the other? Nothing that needs to change in this PR if at all, just curious to hear your thoughts and others.

Yeah that makes sense to me to abstract those common parts!

**Review by adamalston — APPROVED** [review]

**Review by 2nikhiltom — APPROVED** [review]

**Review by kennylam — APPROVED** [review]

**Comment by CCCCChloe** [comment]
Hi I verified v11.81.0 but seeing the accessibility issue is still there. Could you check this code piece to see if there is any changes need to made? https://stackblitz.com/edit/github-7bh8iprp?file=src%2FApp.jsx

Screenshot 2025-04-30 at 10 59 56 AM
