### PR TITLE
fix(toggletip): close on outside click in Safari

### LINKED ISSUE #19244: [Bug]: Toggletip in a Modal not closing when click outside in Safari
### Package

@carbon/react

### Browser

Safari

### Package version

1.81.0

### React version

17.0.1

### Description

**Current**

After opening, the `Toggletip` is not closing when clicking outside

**Expected**

`Toggletip` should close when clicked outside

### Reproduction/example

https://stackblitz.com/edit/cviamf2v?file=src%2FApp.jsx

### Steps to reproduce

1. Open https://stackblitz.com/edit/cviamf2v?file=src%2FApp.jsx in Safari
2. Click the `Launch modal` button
3. Click the `Toggletip` trigger button (`i` button) to open
4. Then click outside, ie, in the body of the Modal to close the toggle tip

https://github.com/user-attachments/assets/2c520465-d222-44a0-aa06-a69124b0ceea

### Suggested Severity

None

### Application/PAL

Carbon for IBM Products

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by heloiselui**
Closes #19244 

Fix Toggletip not closing on outside click in Safari

### Changelog

**New**
- Added a temporary Storybook story (`OutsideClickTest`) to reproduce and verify the Safari issue.  
> [!WARNING]  
> This story must be removed before merging.

**Changed**
- Updated `Toggletip` to listen for `pointerdown` (or `mousedown` fallback) in the capture phase.  
- This ensures outside clicks are detected even when `Modal` calls `stopPropagation()`, fixing Safari behavior.  
- Replaced `useWindowEvent('click')` with `useEffect` + `addEventListener` for more robust handling.

**Removed**
- ~None.~

#### Testing / Reviewing

Please, test in Safari

1. Go to `React Deploy Preview` > `Toggletip` > `OutsideClickTest`  
2. Launch the Modal and open the Toggletip.  
3. Click anywhere in the Modal body (outside the Toggletip).  
   - The Toggletip should close as expected.  

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [X] Reviewed every line of the diff
- ~[ ] Updated documentation and storybook examples~
- ~[ ] Wrote passing tests that cover this change~
- ~[ ] Addressed any impact on accessibility (a11y)~
- [X] Tested for cross-browser consistency
- [X] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by Gururajj77 — APPROVED** [review]

File: packages/react/src/components/Toggletip/index.tsx [hunk 1]
```diff
@@ -173,11 +174,31 @@ export function Toggletip<E extends ElementType = 'span'>({
...
+    const targetDocument = ref.current.ownerDocument || document;
+    const eventType: 'pointerdown' | 'mousedown' =
+      'PointerEvent' in window ? 'pointerdown' : 'mousedown';
+
+    const handleOutsideClick = (event: MouseEvent | PointerEvent) => {
+      const node = event.target as Node | null;
+      if (node && !ref.current!.contains(node)) {
+        setOpen(false);
+      }
+    };
```
Comment (kennylam) [inline packages/react/src/components/Toggletip/index.tsx]:
```suggestion
  useEffect(() => {
    if (!ref.current) return;

    const targetDocument = ref.current.ownerDocument || document;
    const eventType: 'pointerdown' | 'mousedown' =
      'PointerEvent' in window ? 'pointerdown' : 'mousedown';

    const handleOutsideClick = (event: MouseEvent | PointerEvent) => {
      const node = event.target as Node | null;
      if (open && node && !ref.current!.contains(node)) {
        setOpen(false);
      }
    };
```

Really small thing - it seems like this event handler would get removed and re-added every time `open` changes. Can we just let the handler check `open`?

Comment (heloiselui) [reply packages/react/src/components/Toggletip/index.tsx]: Good point, thanks @kennylam! I updated it to check open inside the handler instead.

**Review by kennylam — APPROVED** [review]
LGTM!
