### PR TITLE
fix: The type of the onInputValueChange function in FilterableMultiSelect was misused.

### LINKED ISSUE #21662: [Bug]: FilterableMultiSelect onInputValueChange typed incorrectly
### Package

@carbon/react

### Browser

Chrome

### Package version

v11.102.0

### React version

v19

### Description

The type of the onInputValueChange function in FilterableMultiSelect is incorrect or misused.

https://github.com/carbon-design-system/carbon/blob/1c7d80ab174dc05e258f57dc5e45481323b4d870/packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx#L246

https://github.com/carbon-design-system/carbon/blob/1c7d80ab174dc05e258f57dc5e45481323b4d870/packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx#L737-L743

### Reproduction/example

https://stackblitz.com/edit/github-vegkbisa?file=src%2FApp.tsx&preset=node=

### Steps to reproduce

The typescript checker should underline the onInputValueChange with a string as a parameter as incorrect

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by riddhybansal**
Closes #21662 

The type of the onInputValueChange function in FilterableMultiSelect was misused.

### Changelog

**Changed**

- Instead of sending just a string a whole object is send as expected by onInputChange

#### Testing / Reviewing

All tests should pass

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] ~Updated documentation and storybook examples~
- [ ] ~Wrote passing tests that cover this change~
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by heloiselui — APPROVED** [review]
LGTM! Just need to check the tests.

File: packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx [hunk 1]
```diff
@@ -736,7 +736,7 @@ export const FilterableMultiSelect = forwardRef(function FilterableMultiSelect<
         };
       case InputChange:
         if (onInputValueChange) {
-          onInputValueChange(changes.inputValue);
+          onInputValueChange(changes);
```
Comment (adamalston) [inline packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx:733]: Should `FluidMultiSelect` be updated? That component still types `onInputValueChange` as `(inputValue: string) => void`, so passing the full `changes` object here will give existing consumers an object instead of the string they currently expect.

https://github.com/carbon-design-system/carbon/blob/186fdad7c7cb8ed7113cfcc461f94b637ab17c4f/packages/react/src/components/FluidMultiSelect/FluidMultiSelect.tsx#L109-L113

https://github.com/carbon-design-system/carbon/blob/186fdad7c7cb8ed7113cfcc461f94b637ab17c4f/packages/react/src/components/FluidMultiSelect/FluidMultiSelect.tsx#L172-L179

File: packages/react/src/components/MultiSelect/__tests__/FilterableMultiSelect-test.js
Comment (adamalston) [inline packages/react/src/components/MultiSelect/__tests__/FilterableMultiSelect-test.js:1]: I don't see any `FluidMultiSelect` coverage in this file via `isFilterable`. Should coverage for `FilterableMultiSelect` when `isFilterable` is enabled be added as part of this change?

The new assertion only covers `FilterableMultiSelect`, so it doesn't catch the callback payload mismatch that the filterable fluid wrapper now exposes.

File: packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx (hunk 1 above)
Comment (riddhybansal) [reply packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx:733]: isFilterable is deprecated in favor of FluidFilterableMultiSelect, so I dont think any changes needed there. The relevant component is FluidFilterableMultiSelect, which already has the correct Downshift type.

File: packages/react/src/components/MultiSelect/__tests__/FilterableMultiSelect-test.js
Comment (riddhybansal) [reply packages/react/src/components/MultiSelect/__tests__/FilterableMultiSelect-test.js:1]: Since FluidFilterableMultiSelect is just a thin wrapper that passes all props straight through to FilterableMultiSelect, the onInputValueChange behavior is already fully covered by the FilterableMultiSelect tests

File: packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx (hunk 1 above)
Comment (adamalston) [reply packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx:733]: I'm not sure I understand. Could you clarify whether it is intended to modify the behavior related to the deprecated `FluidMultiSelect` `isFilterable` prop?

I added the test below, and it fails on this branch because `onInputValueChange` receives the Downshift state object instead of the expected string value.

```diff
diff --git a/packages/react/src/components/FluidMultiSelect/__tests__/FluidMultiSelect-test.js b/packages/react/src/components/FluidMultiSelect/__tests__/FluidMultiSelect-test.js
index efe715a88b..f2c89a1edc 100644
--- a/packages/react/src/components/FluidMultiSelect/__tests__/FluidMultiSelect-test.js
+++ b/packages/react/src/components/FluidMultiSelect/__tests__/FluidMultiSelect-test.js
@@ -6,7 +6,8 @@
  */
 
 import React from 'react';
-import { render } from '@testing-library/react';
+import { act, render, screen } from '@testing-library/react';
+import userEvent from '@testing-library/user-event';
 import { generateItems, generateGenericItem } from '../../ListBox/test-helpers';
 import FluidMultiSelect from '../FluidMultiSelect';
 
@@ -18,4 +19,27 @@ describe('FluidMultiSelect', () => {
     );
     expect(container.firstChild).toHaveClass(`cds--list-box__wrapper--fluid`);
   });
+
+  it('should pass a string to `onInputValueChange` when `isFilterable` is enabled', async () => {
+    const items = generateItems(4, generateGenericItem);
+    const onInputValueChange = jest.fn();
+
+    render(
+      <FluidMultiSelect
+        id="test"
+        isFilterable
+        label="Field"
+        titleText="Field"
+        items={items}
+        onInputValueChange={onInputValueChange}
+      />
+    );
+
+    await act(async () => {});
+    await userEvent.click(screen.getByRole('combobox'));
+    await userEvent.type(screen.getByRole('combobox'), 'test');
+
+    expect(onInputValueChange).toHaveBeenCalledTimes(4);
+    expect(onInputValueChange).toHaveBeenLastCalledWith('test');
+  });
 });
```

Failure:

```txt
Expected: "test"
Received
        3: {"highlightedIndex": -1, "inputValue": "tes", "isOpen": true, "selectedItem": null}
->     4: {"highlightedIndex": -1, "inputValue": "test", "isOpen": true, "selectedItem": null}
```

I then reverted the code changes:

```sh
git checkout main packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx
```

After running the same test again, it passed. This suggests that the pull request changes the behavior of what `FluidMultiSelect` forwards through `onInputValueChange`. It also indicates that the `FluidMultiSelect` type for `onInputValueChange` (`(inputValue: string) => void`) no longer matches the behavior of the current implementation.

**Review by sunny-kukkar-ibm — APPROVED** [review]

File: packages/react/src/components/FluidMultiSelect/FluidMultiSelect.tsx [hunk 2]
```diff
@@ -110,7 +110,7 @@ export interface FluidMultiSelectProps<ItemType>
    * **Filterable variant only** - `onInputValueChange` is a utility for this controlled component to communicate to
    * the currently typed input.
    */
-  onInputValueChange?: (inputValue: string) => void;
+  onInputValueChange?: UseComboboxProps<ItemType>['onInputValueChange'];
```
Comment (adamalston) [inline packages/react/src/components/FluidMultiSelect/FluidMultiSelect.tsx:113]: Regarding https://github.com/carbon-design-system/carbon/commit/366a9b11ef7a41beec218a5e299e6ba001a7009f, although `isFilterable` is deprecated, should a test be added to guard against the breakage noted in https://github.com/carbon-design-system/carbon/pull/21720#discussion_r2905251289? I'm not sure how likely it is that this issue will recur before `isFilterable` is ultimately removed, but it has already occurred once, and the lack of coverage meant it wasn't caught early.

**Review by adamalston — APPROVED** [review]
