### PR TITLE
fix(IconTab): added disabled prop to IconTabProps

### LINKED ISSUE #20261: IconTabProps is missing the 'disabled' property
### Package

@carbon/react

### Browser

Chrome

### Package version

1.85.0

### React version

19.0.0

### Description

The documentation for Tabs → [Icon Tabs Only](https://react.carbondesignsystem.com/?path=/docs/components-tabs--overview#icon-tabs-only) shows usage of the disabled prop on <IconTab>.

Example from Docs:

`  <IconTab
      disabled
      label="Analyze"
    >`

However, when using this in my Next.js project, the compiler reports:
`Property 'disabled' does not exist on type 'IntrinsicAttributes & IconTabProps & RefAttributes<HTMLDivElement>'`

This means the disabled prop is not currently typed in IconTabProps, even though the docs (and runtime behavior) suggest it is supported.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-tabs--overview#icon-tabs-only

### Steps to reproduce

- Install @carbon/react@1.85.0

- Import IconTab from @carbon/react

- Try to use <IconTab disabled label="...">...</IconTab>
 
- Observe TypeScript error.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Vignesh-Loganathan-IBM-1**
Closes #20261

Added the disabled prop to the IconTabProps

### Changelog

**New**

- Added disabled prop to the IconTabProps

#### Testing / Reviewing

- [ ] In a typescript component use disabled in IconTab Component.

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by Vignesh-Loganathan-IBM-1** [comment]
I have read the DCO document and I hereby sign the DCO.

File: packages/react/src/components/Tabs/Tabs.tsx [hunk 1]
```diff
@@ -1574,6 +1579,7 @@ const IconTab = React.forwardRef<HTMLDivElement, IconTabProps>(function IconTab(
     enterDelayMs,
     leaveDelayMs,
     label,
+    disabled = false,
```
Comment (adamalston) [inline packages/react/src/components/Tabs/Tabs.tsx]: I have two questions:

1. Why does the prop need a default value?
2. Why does the prop need to be destructured here instead of being passed to `Tab` via the `rest` parameter?

The issue is a type issue. I don't think it requires a code change within the component.

File: packages/react/src/components/Tabs/Tabs.tsx [hunk 2]
```diff
@@ -1545,6 +1545,11 @@ export interface IconTabProps extends DivAttributes {
    */
   defaultOpen?: boolean;
 
+  /**
+   *  Specify whether your Tab is disabled.
```
Comment (adamalston) [inline packages/react/src/components/Tabs/Tabs.tsx]: Should this comment be updated to refer to `IconTab` instead of `Tab`?

**Review by adamalston — COMMENTED** [review]
Is there an existing test that has a `disabled` `IconTab`?

File: packages/react/src/components/Tabs/Tabs.tsx (hunk 2 above)
Comment (Vignesh-Loganathan-IBM-1) [reply packages/react/src/components/Tabs/Tabs.tsx]: updated

File: packages/react/src/components/Tabs/Tabs.tsx (hunk 1 above)
Comment (Vignesh-Loganathan-IBM-1) [reply packages/react/src/components/Tabs/Tabs.tsx]: @adamalston  got it . Reverted the changes and updated the PR

**Review by heloiselui — APPROVED** [review]
LGTM, thanks for your help!

File: packages/react/src/components/Tabs/Tabs.tsx (hunk 2 above)
Comment (adamalston) [reply packages/react/src/components/Tabs/Tabs.tsx]: Was the correct comment updated in https://github.com/carbon-design-system/carbon/commit/33ef48f2caff09c8c11dd8e993e5dfa23bed81c1? I'm looking at https://github.com/carbon-design-system/carbon/pull/20306/files and it doesn't appear so.

Comment (Vignesh-Loganathan-IBM-1) [reply packages/react/src/components/Tabs/Tabs.tsx]: sorry @adamalston . previously updated the other comment . now its updated correctly.

**Review by Gururajj77 — APPROVED** [review]

**Review by riddhybansal — APPROVED** [review]
