### PR TITLE
fix(DatePicker): fix calendar dropdown position

### LINKED ISSUE #4818: DatePicker calendar using appendTo prop is badly positioned if ancestor has padding
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

We had an issue where the calendar popup of the DatePicker did not scroll when the input box scrolled.  This is fixed by supplying the appendTo prop and setting it's positioning of that appendTo element to relative.  

However, if there is any padding or margins on ancestors of that appendTo element, the calendar popup does not render in the right place.  If you comment out the padding, it's fine.

Also, if the DatePicker is rendered in a portal, clicking the calendar icon does not work at all.  When I try in my local environment, I get an error about cal not being defined.  In the Code Sandbox, it just silently fails.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
   "carbon-components": "^10.7.0",
    "carbon-components-react": "^7.7.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
OpenPages

## Steps to reproduce the issue
https://codesandbox.io/s/codesandbox-fyj49

### PR DESCRIPTION
**Pull request by asudoh**
This change introduces a Flatpickr plugin that ensures that the calendar dropdown is put in the correct floating position even if the floating menu container is changed via `appendTo` and the floating menu container has significant offset from `<body>`.

Fixes #4818.

#### Changelog

**New**

- A Flatpickr plugin that ensures that the calendar dropdown is put in the correct floating position even if the floating menu container is changed via `appendTo` and the floating menu container has significant offset from `<body>`.

#### Testing / Reviewing

Testing should make sure `<DatePicker>` is not broken.

### CODE REVIEW

File: packages/react/src/components/DatePicker/plugins/appendToPlugin.js [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+      ) {
+        throw new Error(
+          'Floating menu container must not have `position:static`.'
+        );
+      }
+      // `2` for negative mergin on calendar dropdown
+      calendarContainer.style.top = `${refBottom - containerTop + 2}px`;
+      calendarContainer.style.left = `${refLeft - containerLeft}px`;
+    });
+  };
```
Comment (abbeyhrt) [inline packages/react/src/components/DatePicker/plugins/appendToPlugin.js:50]: Hi @asudoh! I haven't worked much with positioning via javascript, could you explain what's going on here so I can learn a bit more about it? Thank you!

**Review by abbeyhrt — APPROVED** [review]
This looks good to me! Thanks for taking the time to explain what's going on @asudoh !

**Review by emyarod — APPROVED** [review]
looks good to me, tested against the original sandbox and the calendar now positions properly with React portals
