### PR TITLE
fix(CheckboxGroup): propagate props to Checkbox children

### LINKED ISSUE #20260: [Bug]: A `readOnly` `Checkbox` can be checked and unchecked
### Package

@carbon/react

### Browser

_No response_

### Package version

v1.84.0

### React version

_No response_

### Description

Users can check and uncheck a `readOnly` `Checkbox`.

https://github.com/user-attachments/assets/21658f51-2649-4228-9d1b-3e2c0290699d

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-checkbox--default&args=readOnly:!true

### Steps to reproduce

1. Go to the reproduction.
2. Select a `Checkbox` and observe the visual change indicating that it has been selected.

### Suggested Severity

None

### Application/PAL

DataPower

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by adamalston**
Closes https://github.com/carbon-design-system/carbon/issues/20260

Propagated `CheckboxGroup` props to `Checkbox` children.

### Changelog

**New**

- Propagated `CheckboxGroup` props to `Checkbox` children.

#### Testing / Reviewing

It crossed my mind that I shouldn't have to hardcode the three properties that need to be propagated, since those properties may change in the future. However, I'm not sure there is a dynamic way to gather the properties that do and don't need to be propagated.

```sh
yarn test packages/react
```

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/react/src/components/CheckboxGroup/CheckboxGroup.tsx [hunk 1]
```diff
@@ -89,6 +96,44 @@ const CheckboxGroup: React.FC<CheckboxGroupProps> = ({
...
+      ) {
+        childProps.readOnly = readOnly;
+      }
+
+      if (
+        typeof warn !== 'undefined' &&
+        typeof child.props.warn === 'undefined'
+      ) {
+        childProps.warn = warn;
+      }
```
Comment (Gururajj77) [inline packages/react/src/components/CheckboxGroup/CheckboxGroup.tsx]: Everything looks good, just a small improvement here




```suggestion
    const childProps = Object.assign(
  {},
  typeof invalid !== 'undefined' && typeof child.props.invalid === 'undefined' && { invalid },
  typeof readOnly !== 'undefined' && typeof child.props.readOnly === 'undefined' && { readOnly },
  typeof warn !== 'undefined' && typeof child.props.warn === 'undefined' && { warn }
);
```

**Review by Gururajj77 — CHANGES_REQUESTED** [review]

File: packages/react/src/components/CheckboxGroup/CheckboxGroup.tsx (hunk 1 above)
Comment (adamalston) [reply packages/react/src/components/CheckboxGroup/CheckboxGroup.tsx]: > just a small improvement here

I don't see how that suggestion is an improvement. That code would result in a type error and has worse performance characteristics. I'm willing to update the implementation to be more concise, but I'd prefer a different approach than the one suggested.

**Review by Gururajj77 — APPROVED** [review]
Looks good now, thanks.

**Review by tay1orjones — APPROVED** [review]
Hardcoded's fine imo 👍 LGTM
