### PR TITLE
fix(project): build issues on windows

### LINKED ISSUE #4809: Windows Support
### Summary
This enhancement improves support for development of the project on the windows operating system.

### Justification
Fixes build & development issues related to the windows OS, making for an easier means of entry into the code base for other contributors down the line.

### Desired UX and success metrics
- Easier means to entry on the project on the Windows OS
- Fixes build issues on windows

### "Must have" functionality
- Consistent build output on the windows OS and any other Operating System.

### Specific timeline issues / requests
ASAP

### PR DESCRIPTION
**Pull request by sichangi**
Closes #4809

Fixes build errors on running the ``build`` script on the windows operating system

#### Changelog

**New**

- The react & vanilla icon builder checks the current operating system and handles path related operations accordingly
- The same applies to the bundlers ``inline`` command
- As well as the ``elements`` package build task
- Clearer logging during builds

**Changed**

- The react & vanilla icon builder script now generates icon variable names that start with a number, which throws an error while bundling, with an underscore on windows but retains initial behavior on other operating systems.

#### Testing / Reviewing
- Should work as expected on any other previously functional operating system
- Should generate similarly functioning outputs for react & vanilla icons

### CODE REVIEW

**Comment by sichangi** [comment]
Something that I may need an opinion on is the the fix I made where the icon bundlers throw on parsing variables that start with a number e.g ``32Q...``. 
I figured that the generated react icon files were exporting the icons by default ( ``export default ...`` ), I could add an underscore to the beginning of the variable name.
Am not so sure if this is fine for the vanilla output, hence the need for a second opinion.

File: packages/elements/tasks/build.js [hunk 1]
```diff
@@ -40,7 +41,7 @@ async function build() {
   const paths = klaw(BUNDLE_DIR, {
     nodir: true,
     filter(item) {
-      const paths = item.path.split('/');
+      const paths = item.path.split(isWin ? '\\' : '/');
```
Comment (joshblack) [inline packages/elements/tasks/build.js]: Would it make sense for us to use [`path.sep`](https://nodejs.org/api/path.html#path_path_sep)?

File: packages/icon-build-helpers/src/builders/react/builder.js [hunk 2]
```diff
@@ -52,9 +54,13 @@ async function builder(meta, { cwd }) {
     },
   ];
 
-  const modules = meta.map(icon =>
-    createIconComponent(icon.moduleName, icon.descriptor)
-  );
+  const modules = meta.map(icon => {
+    let name = icon.moduleName;
+    if (isWin && name.match(/^\d/)) {
+      name = '_' + icon.moduleName;
```
Comment (joshblack) [inline packages/icon-build-helpers/src/builders/react/builder.js]: Is it the case that filenames can't start with numbers? 👀

File: packages/icon-build-helpers/src/builders/react/builder.js [hunk 3]
```diff
@@ -114,16 +122,20 @@ export { Icon };
...
         // and minus 1 for the filename as it does not count as a directory jump
-        length: outputOptions.file.split('/').length - 2,
+        length: outputOptions.file.split(isWin ? '\\' : '/').length - 2,
       })
         .fill('..')
         .join('/');
 
+      let name = moduleName;
+      if (isWin && name.match(/^\d/)) {
+        name = '_' + moduleName;
```
Comment (joshblack) [inline packages/icon-build-helpers/src/builders/react/builder.js]: I believe the `moduleName` should already be sanitized as identifiers in JS also cannot start with a number similar to what I think the Windows requirement is above 👍

File: packages/bundler/src/commands/inline.js [hunk 4]
```diff
@@ -123,20 +126,21 @@ async function inlineSassDependencies(
 function findSassModule(packageName, cwd) {
   let currentDirectory = cwd;
 
-  while (currentDirectory !== '/') {
-    const nodeModulesFolder = path.join(currentDirectory, 'node_modules');
+  if (
```
Comment (joshblack) [inline packages/bundler/src/commands/inline.js]: Seems like we lost the recursive nature of this block, any particular reason?

Separately, what are the best practices for handling per-drive directory naming conventions? 🤔

File: packages/bundler/src/commands/inline.js [hunk 5]
```diff
@@ -50,14 +54,15 @@ async function inlineSassDependencies(
...
+      const modules = await findSassModule(dependency, cwd);
+      if (modules) {
+        const [scssFolder] = modules;
         const dependencyOutputFolder = path.join(vendorFolder, dependency);
 
         await fs.copy(scssFolder, dependencyOutputFolder);
 
         return [dependency, dependencyOutputFolder];
-      }
+      } else return false;
```
Comment (joshblack) [inline packages/bundler/src/commands/inline.js]: Quick style-nit, if we return early in the `if` block then we don't need `else` and can just return false in the same block 👍

**Review by joshblack — CHANGES_REQUESTED** [review]

File: packages/icon-build-helpers/src/builders/react/builder.js (hunk 2 above)
Comment (sichangi) [reply packages/icon-build-helpers/src/builders/react/builder.js]: It's more of variable names can't start with numbers, yet how you build the names involves concatenating folder names, some of which start with numbers

File: packages/elements/tasks/build.js (hunk 1 above)
Comment (sichangi) [reply packages/elements/tasks/build.js]: Coool, 😅,  yes it would.
Learning something new everyday 👍

File: packages/icon-build-helpers/src/builders/react/builder.js (hunk 3 above)
Comment (sichangi) [reply packages/icon-build-helpers/src/builders/react/builder.js]: Hmm... That does make sense, although that section did stall the build process,
Lemme look more into it.

File: packages/bundler/src/commands/inline.js (hunk 4 above)
Comment (sichangi) [reply packages/bundler/src/commands/inline.js]: On loosing the recursion, that's my bad, I've had another look into the logic & it seems I misunderstood it.

On the windows per-drive directory naming, I found that they start with any letter followed by the ``://`` or ``:\`` in nodes case, hence the check for that with a regular exp.

**Comment by joshblack** [comment]
Bump @dakahn if you have a sec to help with reviewing this!

File: packages/icon-build-helpers/src/builders/react/builder.js (hunk 3 above)
Comment (sichangi) [reply packages/icon-build-helpers/src/builders/react/builder.js]: You're right, the logic that should be sanitizing this actually was missing names with a prefix that starts with a number.
Glad I looked at ti with fresh eyes  👌

**Review by dakahn — APPROVED** [review]
seems good to me from my end 👍

File: packages/bundler/src/commands/inline.js [hunk 6]
```diff
@@ -113,7 +114,9 @@ async function inlineSassDependencies(
         files: file.path,
         from: REPLACE_REGEX,
         to(_, match) {
-          return `@import '${relativeImportPath}/${match}`;
+          return `@import '${
```
Comment (joshblack) [inline packages/bundler/src/commands/inline.js:117]: Would it help if we used `path.join` here and have the `path` module handle this resolution for us? 👀

File: packages/bundler/src/commands/inline.js [hunk 7]
```diff
@@ -123,20 +126,25 @@ async function inlineSassDependencies(
 function findSassModule(packageName, cwd) {
   let currentDirectory = cwd;
 
-  while (currentDirectory !== '/') {
+  const isNotRoot = () =>
+    isWin
+      ? !/^[a-zA-Z]:(\/\/|\\)$/.test(currentDirectory)
+      : currentDirectory !== '/';
+
+  while (isNotRoot()) {
```
Comment (joshblack) [inline packages/bundler/src/commands/inline.js]: Would the terminal case here be something like:

```js
while (currentDirectory !== path.dirname(currentDirectory)) {
  // ...
}
```

Basically just trying to say as long as moving up doesn't result in the same directory (root) 🤔

**Review by joshblack — COMMENTED** [review]
Thanks so much for sticking with this! Really appreciate it 🙏 Just had a couple of questions to see if we can reduce the number of times we rely on a windows-specific check 👀

File: packages/bundler/src/commands/inline.js (hunk 6 above)
Comment (sichangi) [reply packages/bundler/src/commands/inline.js:117]: So I tried using the ``path.join`` function, but it seems to not resolve the separators as expected as shown in the second image below

Using PathA

Using PathB

File: packages/bundler/src/commands/inline.js (hunk 7 above)
Comment (sichangi) [reply packages/bundler/src/commands/inline.js]: Pretty smart way of checking that, will implement it this way 👍

File: packages/bundler/src/commands/inline.js (hunk 6 above)
Comment (sichangi) [reply packages/bundler/src/commands/inline.js:117]: Am not sure if using ``path.normalize`` may help, but lemme try that as well

Comment (sichangi) [reply packages/bundler/src/commands/inline.js:117]: Nope, changes nothing, I still have to do an os check

**Review by joshblack — APPROVED** [review]
