### PR TITLE
fix(overflow-menu): support flip mode in experimental

### LINKED ISSUE #1481: Experimental overflow flip mode not functioning
## Detailed description

> Describe in detail the issue you're having.

It appears that adding the `OverflowMenu.options.classMenuFlip` class to the experimental overflow menu `ul` does not change the position of the expanded menu

> Is this issue related to a specific component?

OverflowMenu

> What did you expect to happen? What happened instead? What would you like to see changed?

adding the correct class for flip mode should alter the position if the overflow menu

> What browser are you working in?

Chrome 70+, Firefox 65+

> What version of the Carbon Design System are you using?

latest `master`

## Steps to reproduce the issue

1. fork latest `master` branch
2. start dev environment
3. navigate to experimental overflow menu demo
4. open second overflow menu example

the first and second overflow menu examples should not be identical, since the second example has the flip mode class applied

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #1481.

#### Changelog

**New**

- Add 3rd argument to `objOffset`/`objOffsetFlip` callbacks, which is, the trigger button
- Logic to support flip mode in experimental

#### Testing / Reviewing

Testing should make sure overflow menu, especially in experimental mode, is not broken.

### CODE REVIEW

File: src/components/overflow-menu/overflow-menu.js [hunk 1]
```diff
@@ -63,17 +64,21 @@ export const getMenuOffset = (menuBody, direction) => {
   }
 
   if (componentsX) {
+    const flip = menuBody.classList.contains(`${settings.prefix}--overflow-menu--flip`);
```
Comment (emyarod) [inline src/components/overflow-menu/overflow-menu.js]: is this class identical to `this.options.classMenuFlip`?

**Review by emyarod — APPROVED** [review]

File: src/components/overflow-menu/overflow-menu.js (hunk 1 above)
Comment (asudoh) [reply src/components/overflow-menu/overflow-menu.js]: Great catch @emyarod! - Fixed.

**Review by marijohannessen — APPROVED** [review]
Looks great!
