### PR TITLE
fix(CodeSnippet): a11y tabstop + attributes

### LINKED ISSUE #10527: [a11y]: add required tab stop to multiline Codesnippet textbox
multiline codesnippet has an inaccessible scrollable text box. this text box should be able to receive focus and have a tab stop

### PR DESCRIPTION
**Pull request by jsehull**
Closes #10527

**The following changes are only for the `Singleline` and `Multiline` snippets, but do not include `Inline`.

Primary fix: add tab stop for `Multiline` `CodeSnippet`
I also added a few more `aria` attributes as requested in #10527 comments.
___

I would like confirmation on `aria-multiline`. Documentation suggests that without it, screen readers assume it is a single line. Obviously it's now `readonly` so they won't edit, but I thought it may help inform users that they can/should scroll since it is not one line. 

Thoughts on keeping/not?

#### Changelog

**New**

- add tabstop to `Multiline` snippets
- add `role='textbox'` to multi (single currently has)
- add `aria-readonly` to single/multi (users cannot interact with the "textarea")
- add `aria-multiline` for multi (single will never have)

**Changed**

- n/a

**Removed**

- n/a

#### Testing / Reviewing

Visit Storybook > `CodeSnippet` to compare `aria` changes for Single and Multi line snippets. Check for the following:
1. Multiline tab stop is working (tab selects + allows keyboard scrolling)
2. Single/Multi both show a `role` of 'textbox'
3. Single/Multi have are `aria-readonly`
4. Multi now has `aria-multiline` added

Multiline example:
image

### CODE REVIEW

**Comment by tw15egan** [comment]
Looks great. Can we adjust the `focus` styles so that it aligns with Carbon?

`_code-snippet.scss:L197`
```scss
.#{$prefix}--snippet--multi .#{$prefix}--snippet-container:focus {
    @include focus-outline('outline');
    outline-offset: 0;
}
```

File: packages/react/src/components/CodeSnippet/CodeSnippet.js [hunk 1]
```diff
@@ -226,10 +226,14 @@ function CodeSnippet({
     <div {...rest} className={codeSnippetClasses}>
       <div
         ref={codeContainerRef}
-        role={type === 'single' ? 'textbox' : null}
-        tabIndex={type === 'single' && !disabled ? 0 : null}
+        role={type === 'single' || type === 'multi' ? 'textbox' : null}
+        tabIndex={
+          type === 'single' || (type === 'multi' && !disabled) ? 0 : null
```
Comment (francinelucca) [inline packages/react/src/components/CodeSnippet/CodeSnippet.js]: should this be the following instead? looks like the original condition for `single` is changing
```suggestion
          (type === 'single' || type === 'multi') && !disabled ? 0 : null
```

Comment (jsehull) [reply packages/react/src/components/CodeSnippet/CodeSnippet.js]: It must have auto formatted it. I think if we use your suggestion it _won't_ next time. I'll work on getting that added!

**Review by francinelucca — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
