### PR TITLE
fix(sketch): add undefined exception handler in icon generate script

### LINKED ISSUE #5582: Sketch icon `generate` script cannot handle icon range subsets
## What package(s) are you using?

`@carbon/sketch`

## Detailed description

> Describe in detail the issue you're having.

when trying to generate a subset of icons for an icon page, the command will fail with the message `An error occured, please check the development logs`

the development log shows

```sh
$ skpm log -f
    at __skpm_run@[native code] (/)
'[Carbon Elements] commands/icons/generate: Done in 30ms'
TypeError: undefined is not an object (evaluating 'symbol.createNewInstance')
    at _loop (/Users/username/carbon/packages/sketch/carbon-elements.sketchplugin/Contents/Sketch/commands_index.js:16228:38)
    at /Users/username/carbon/packages/sketch/carbon-elements.sketchplugin/Contents/Sketch/commands_index.js:16242:22
    at command (/Users/username/carbon/packages/sketch/carbon-elements.sketchplugin/Contents/Sketch/commands_index.js:16093:7)
    at generate (/Users/username/carbon/packages/sketch/carbon-elements.sketchplugin/Contents/Sketch/commands_index.js:16144:59)
    at __skpm_run (/Users/username/carbon/packages/sketch/carbon-elements.sketchplugin/Contents/Sketch/commands_index.js:17968:19)
    at __skpm_run@[native code] (/)
'[Carbon Elements] commands/icons/generate: Done in 40ms'
```

## Steps to reproduce the issue

1. modify `carbon/packages/sketch/src/commands/icons/shared.js` to only deal with a subset of icons (either modify the `start` and `end` variables to be a subset of the full icons list or directly change the slice size in `symbolsToSync`)
2. `yarn build`
3. sync and generate the icons in Sketch

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5582

This PR avoid pushing `undefined` as a Layer object to Sketch in the icon page generation script and adds an npm script for viewing the development log

#### Changelog

**New**

- `log` npm script for viewing the development log

**Changed**

- `undefined` exception handler in icons/generate script

#### Testing / Reviewing

1. modify `carbon/packages/sketch/src/commands/icons/shared.js` to only deal with a subset of icons (either modify the `start` and `end` variables to be a subset of the full icons list or directly change the slice size in `symbolsToSync`)
2. `yarn build`
3. sync and generate the icons in Sketch

### CODE REVIEW

File: packages/sketch/src/commands/icons/generate.js [hunk 1]
```diff
@@ -68,18 +68,19 @@ export function generate() {
             const [_type, _category, _subcategory, name, size] = parts;
             return name === icon && size === '32';
           });
-          const instance = symbol.createNewInstance();
-          instance.frame.offset(ICON_X_OFFSET, ICON_Y_OFFSET);
+          const instance = symbol?.createNewInstance();
```
Comment (joshblack) [inline packages/sketch/src/commands/icons/generate.js]: Oh wild, I think we might want to fail if the symbol doesn't exist. Maybe something like:

```js
if (!symbol) {
  throw new Error(`Unable to find symbol for icon ${icon}`);
}
```

**Review by joshblack — CHANGES_REQUESTED** [review]

**Review by joshblack — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!
