### PR TITLE
fix(accordion): prevent setting title by default

### LINKED ISSUE #6235: AccordionItem uses `title` as string, but listed as type 'node'
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Recent changes to `AccordionItem` have started to use the `title` prop as a string value. However, it's listed as type `node`. Leads to DOM like this:

```html
<button aria-controls="accordion-item-1" aria-expanded="false"
  class="bx--accordion__heading" title="[object Object]" type="button">
```

## Steps to reproduce the issue

```javascript
const titleNode = (
  <div>This is a title</div>
);
return (
  <AccordionItem title={titleNode}>content</AccordionItem>
);
```

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/6235

We were setting the `title` attribute on `AccordionItem` headings by default, and taking the value from the `title` prop. The `title` prop has a type of `node`. which rendered incorrectly. Secondly, the `AccordionItem` heading wraps, so a `title` is unnecessary. 

Also of note, we should rename this prop to something besides `title` in `v11`, as this can be confused with the actual HTML title property. 

#### Changelog

**Removed**

- removed `title` attribute being auto-populated from the heading text
- no longer used `iconDescription` 

#### Testing / Reviewing

Verify `AccordionItem` renders correctly

### CODE REVIEW

**Review by dakahn — APPROVED** [review]

File: packages/react/src/components/Accordion/AccordionItem.js [hunk 1]
```diff
@@ -20,7 +20,6 @@ const defaultRenderExpando = (props) => <button {...props} />;
 function AccordionItem({
   children,
   className: customClassName,
-  iconDescription,
```
Comment (joshblack) [inline packages/react/src/components/Accordion/AccordionItem.js:23]: Should we keep it here so that it doesn't accidentally get added to wherever `...rest` is applied? 👀

File: packages/react/src/components/Accordion/AccordionItem.js [hunk 2]
```diff
@@ -78,7 +77,6 @@ function AccordionItem({
         className={`${prefix}--accordion__heading`}
         onClick={onClick}
         onKeyDown={onKeyDown}
-        title={title || iconDescription}
```
Comment (joshblack) [inline packages/react/src/components/Accordion/AccordionItem.js:81]: Where is `title` being set instead? Or is it just no longer available for this component?

**Review by joshblack — CHANGES_REQUESTED** [review]

File: packages/react/src/components/Accordion/AccordionItem.js (hunk 2 above)
Comment (tw15egan) [reply packages/react/src/components/Accordion/AccordionItem.js:81]: the HTML attribute `title` isn't being set anymore (since the title wraps anyways), but `title` in this component refers to the text that shows up on the accordion item header. It's rendered [here](https://github.com/carbon-design-system/carbon/pull/6236/files#diff-9994d046a59710de8aa5c73ee2b8ff72R83)

Flagged this as a prop that should be renamed for V11.

**Review by joshblack — APPROVED** [review]
