### PR TITLE
fix(makeDraggable): drag improvement

### LINKED ISSUE #9067: Update makeDraggable util in Core Carbon
Drag positioning was previously implemented using left/top, which does not work correctly for elements that already rely on transform for positioning.

Analysis showed that dragging works as expected for Bubble. However, in the case of Popover, dragging above the trigger is not possible because Popover already applies its own transform logic.

To address this, drag positioning needs to be updated to use transform: translate() instead. This ensures compatibility with elements that rely on transform-based positioning and improves support for web components.

### PR DESCRIPTION
**Pull request by anamikaanu96**
Closes [9067](https://github.com/carbon-design-system/ibm-products/issues/9067) ibm-products

Switched drag positioning from left/top to transform: translate() so it works correctly with elements that already use transform-based positioning and ensures compatibility with web components.

### Changelog

**Changed**

- packages/utilities/src/makeDraggable/makeDraggable.ts
- packages/utilities/src/makeDraggable/makeDraggable-test.js

#### Testing / Reviewing

Popover - https://carbon-for-ibm-products.netlify.app/?path=/story/utilities-makedraggable--draggable-popover
Bubble   - https://carbon-for-ibm-products.netlify.app/?path=/story/preview-onboarding-coachmark--floating
cds-popover - https://ibm-products-web-components.carbondesignsystem.com/?path=/story/components-coachmark--floating

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/utilities/src/makeDraggable/makeDraggable.ts [hunk 1]
```diff
@@ -87,16 +94,20 @@ export const makeDraggable = ({
...
       case 'ArrowUp':
-        el.style.top = `${el.offsetTop - distance}px`;
+        currentY -= distance;
+        el.style.transform = `translate(${currentX}px, ${currentY}px)`;
         break;
       case 'ArrowDown':
-        el.style.top = `${el.offsetTop + distance}px`;
+        currentY += distance;
+        el.style.transform = `translate(${currentX}px, ${currentY}px)`;
         break;
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable.ts:169]: This function now assigns `el.style.transform = translate(...)` during keyboard and mouse movement. Setting `el.style.transform` this way overwrites any existing `transform` on the element (e.g., `scale`, `rotate`, or existing `translate`). Is this change intentional? It seems like it could break styles for any consumers.

This comment applies elsewhere too.

File: packages/utilities/src/makeDraggable/makeDraggable-test.js [hunk 2]
```diff
@@ -171,14 +174,13 @@ describe('makeDraggable', () => {
...
+    const transformAfterMove = el.style.transform;
+    expect(transformAfterMove).toBe('translate(50px, 70px)');
 
     fireEvent.mouseUp(handle);
 
     fireEvent.mouseMove(document, { clientX: 100, clientY: 120 });
 
-    expect(el.style.left).toBe('50px');
-    expect(el.style.top).toBe('70px');
+    expect(transformAfterMove).toBe('translate(50px, 70px)');
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable-test.js]: This assertion checks `transformAfterMove` (a cached string) instead of `el.style.transform` after the second `mousemove`. Does that mean this test can still pass even if dragging incorrectly continues after `mouseup`? Should `el.style.transform` be asserted directly here?

File: packages/utilities/src/makeDraggable/makeDraggable-test.js [hunk 3]
```diff
@@ -33,6 +31,23 @@ function createDraggableElement(options = {}) {
...
+            .map(parseFloat);
+          this.m41 = values[4];
+          this.m42 = values[5];
+        } else {
+          this.m41 = 0;
+          this.m42 = 0;
+        }
+      }
+    };
+  });
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable-test.js:86]: I see that `global.DOMMatrix` is stubbed here, but I don't see it being restored anywhere. Should it be restored to avoid affecting other tests?

File: packages/utilities/src/makeDraggable/makeDraggable-test.js
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable-test.js:1]: Could you add a test for an element that already has a non-`translate` `transform` before dragging starts? That should protect the `transform` behavior.

File: packages/utilities/src/makeDraggable/makeDraggable.ts (hunk 1 above)
Comment (anamikaanu96) [reply packages/utilities/src/makeDraggable/makeDraggable.ts:169]: Good catch!
Thanks for pointing this out. I’ve updated the implementation to address this.

File: packages/utilities/src/makeDraggable/makeDraggable.ts [hunk 4]
```diff
@@ -57,6 +57,33 @@ export const makeDraggable = ({
...
+      /translate(3d|X|Y)?\([^)]+\)\s*/g,
+      ''
+    );
+    return withoutTranslate.trim();
+  };
+
+  // Helper function to apply transform with preserved other transforms
+  const applyTransform = (x: number, y: number) => {
+    const translatePart = `translate(${x}px, ${y}px)`;
+    el.style.transform = otherTransforms
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable.ts]: This functionality appears to only preserve inline `transform`s, dropping class and CSS based `transform`s on first drag because writing inline `transform` overrides computed styles. Should computed non-`translate` `transform`s be preserved as well?

This comment applies elsewhere too.

File: packages/utilities/src/makeDraggable/makeDraggable.ts [hunk 5]
```diff
@@ -57,6 +57,33 @@ export const makeDraggable = ({
...
+      ? `${translatePart} ${otherTransforms}`
+      : translatePart;
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable.ts]: Unless I'm misunderstanding, this functionality preserves only inline transforms. Class and CSS based transforms are dropped on first drag because setting inline transform overrides computed styles. Should non-translate transforms from computed styles be preserved too?

```css
.scaled { transform: scale(1.2) rotate(10deg); }
```

```ts
el.className = 'scaled';
makeDraggable({ el, dragHandle: handle });
// The first drag writes inline transform: translate(...).
// As a result, the class based scale and rotate no longer apply.
```

File: packages/utilities/src/makeDraggable/makeDraggable.ts [hunk 6]
```diff
@@ -57,6 +57,33 @@ export const makeDraggable = ({
   let currentY = 0;
   let initialMouseX = 0;
   let initialMouseY = 0;
+  let otherTransforms = '';
+
+  // Initialize current position from computed style
+  const initialStyle = window.getComputedStyle(el);
+  const initialMatrix = new DOMMatrix(initialStyle.transform);
+  currentX = initialMatrix.m41;
+  currentY = initialMatrix.m42;
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable.ts]: These values appear to be captured at init and then updated only by this function. If the element is repositioned externally between drags, would internal state drift and cause a jump on drag start? Should there be a re-sync from the computed transform at drag start?

```ts
makeDraggable({ el, dragHandle: handle });
// External reposition.
el.style.transform = 'translate(300px, 0px)';
// The next drag starts with stale internal currentX and currentY values, which may cause it to jump.
```

File: packages/utilities/src/makeDraggable/makeDraggable.ts [hunk 7]
```diff
@@ -57,6 +57,33 @@ export const makeDraggable = ({
...
+  const extractOtherTransforms = (transformString: string): string => {
+    if (!transformString || transformString === 'none') {
+      return '';
+    }
+    const withoutTranslate = transformString.replace(
+      /translate(3d|X|Y)?\([^)]+\)\s*/g,
+      ''
+    );
+    return withoutTranslate.trim();
+  };
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable.ts]: I see that translate is stripped here but not `matrix` (and maybe `matrix3d` too?). If an existing inline matrix includes translation, dragging will add a `translate` on top which could double apply movement. Is that expected, or am I missing something? Like if an element already has `matrix(...)`, is it going to also get a `translate(...)`?

File: packages/utilities/src/makeDraggable/makeDraggable.ts [hunk 8]
```diff
@@ -57,6 +57,33 @@ export const makeDraggable = ({
...
+
+  // Helper function to apply transform with preserved other transforms
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable.ts]: Should this comment be a JSDoc comment?

File: packages/utilities/src/makeDraggable/makeDraggable.ts (hunk 5 above)
Comment (anamikaanu96) [reply packages/utilities/src/makeDraggable/makeDraggable.ts]: Thanks for spotting that! 🙌 I was testing it in Storybook using inline styles, so I completely missed this behaviour.

File: packages/utilities/src/makeDraggable/makeDraggable.ts (hunk 6 above)
Comment (anamikaanu96) [reply packages/utilities/src/makeDraggable/makeDraggable.ts]: I've fixed this by adding re-sync calls at drag start.

File: packages/utilities/src/makeDraggable/makeDraggable.ts (hunk 7 above)
Comment (anamikaanu96) [reply packages/utilities/src/makeDraggable/makeDraggable.ts]: I've addressed this by using matrix multiplication.

File: packages/utilities/src/makeDraggable/makeDraggable.ts (hunk 8 above)
Comment (anamikaanu96) [reply packages/utilities/src/makeDraggable/makeDraggable.ts]: added as a simple inline comment, but now I cleaned up the unnecessary ones and converted the remaining comments into proper JSDoc comments.

File: packages/utilities/src/makeDraggable/makeDraggable-test.js [hunk 9]
```diff
@@ -171,14 +213,34 @@ describe('makeDraggable', () => {
...
+    // After mouseup, the transform should remain unchanged
+    expect(el.style.transform).toBe('translate(50px, 70px)');
+  });
+
+  it('should preserve existing non-translate transforms during drag', () => {
+    const { el, handle } = createDraggableElement();
+
+    // Set an initial transform with scale and rotate (as matrix)
+    // matrix(a, b, c, d, e, f) where scale(1.5) rotate(45deg) =
+    // matrix(1.06066, 1.06066, -1.06066, 1.06066, 0, 0)
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable-test.js]:
```suggestion
    // Start with a matrix that represents a 45deg rotation with 1.5 scaling.
    // matrix(a, b, c, d, e, f), where e and f are translation, so `0, 0` means
    // no offset. Dragging should preserve the existing rotation and scale terms
    // and only update translation.
```

File: packages/utilities/src/makeDraggable/makeDraggable-test.js [hunk 10]
```diff
@@ -171,14 +213,34 @@ describe('makeDraggable', () => {
...
+    el.style.transform = 'matrix(1.06066, 1.06066, -1.06066, 1.06066, 0, 0)';
+
+    // Start dragging
+    fireEvent.mouseDown(handle, { clientX: 0, clientY: 0 });
+    fireEvent.mouseMove(document, { clientX: 50, clientY: 30 });
+
+    // The transform should preserve the base matrix (a,b,c,d) and add translation (e,f)
+    // Expected: matrix(1.06066, 1.06066, -1.06066, 1.06066, 50, 30)
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable-test.js]:
```suggestion
    // The drag should preserve the existing rotation and scale terms and append
    // the drag offset.
```

File: packages/utilities/src/makeDraggable/makeDraggable.ts [hunk 11]
```diff
@@ -158,7 +238,18 @@ export const makeDraggable = ({
...
   };
+
+  /**
+   * Re-initialize the draggable position from the element's current computed transform.
+   * Call this if the element has been repositioned externally (e.g., via CSS animation,
+   * class changes, or other scripts) to prevent position jumps on the next drag.
+   */
+  const init = () => {
+    syncTransformState();
+  };
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable.ts:249]: The comment says this function should recover from external repositioning via class changes, but after the first drag this code has already written an inline `style.transform`, which overrides normal class based transforms. In that state `syncTransformState` will keep seeing the inline matrix. It appears that the recovery path does not actually work for class changes.

File: packages/utilities/src/makeDraggable/makeDraggable.ts [hunk 12]
```diff
@@ -53,8 +53,72 @@ export const makeDraggable = ({
...
+      baseMatrix = null;
+    } else {
+      baseMatrix = new DOMMatrix([
+        matrix.a,
+        matrix.b,
+        matrix.c,
+        matrix.d,
+        0,
+        0,
+      ]);
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable.ts:101]: What should happen if the existing transform uses 3D terms? Does rebuilding the matrix from only `a`, `b`, `c` and `d` plus zeroed translation flatten the transform to 2D on the first drag?

File: packages/utilities/src/makeDraggable/makeDraggable.ts [hunk 13]
```diff
@@ -53,8 +53,72 @@ export const makeDraggable = ({
...
+      const translationMatrix = new DOMMatrix();
+      translationMatrix.m41 = x;
+      translationMatrix.m42 = y;
+
+      const combined = translationMatrix.multiply(baseMatrix);
+      el.style.transform = combined.toString();
+    } else {
+      el.style.transform = `translate(${x}px, ${y}px)`;
+    }
+  };
```
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable.ts:121]: The implementation now moves elements using `style.transform`, so `style.left`, `style.top`, `offsetLeft`, and `offsetTop` no longer reflect the dropped position. Is that okay? I'm mainly asking because a consumer of this utility might read the element's position in a `dragend` handler. I'm not sure whether this change could be considered a breaking change, or whether it matters. Maybe Carbon for IBM Products is the only expected consumer of it?

File: packages/utilities/src/makeDraggable/makeDraggable-test.js
Comment (adamalston) [inline packages/utilities/src/makeDraggable/makeDraggable-test.js:1]: I see that assertions have been updated in every test. Does that suggest consumers of this utility might have their implementations break when they update it? Maybe a breaking change is what you were alluding to in https://github.com/carbon-design-system/ibm-products/issues/9067#issue-4011572190?

**Review by amal-k-joy — APPROVED** [review]

**Comment by anamikaanu96** [comment]
Hey @adamalston, thanks for the detailed review! I’ve addressed most of the feedback, and a few of the “nice-to-have” points are still pending.

Currently, Carbon for IBM Products is the primary consumer of this utility, and we’re using it specifically within the Coachmark component. At the same time, we intend for this utility to be available for use by other adopters as well.
Given that these changes are required for the products library, I suggest we go ahead and merge this PR for now. We can open a follow-up issue to address the remaining items. It would also be great if you’d like to contribute to those improvements.

**Comment by adamalston** [comment]
Hi @anamikaanu96, the comments from my latest review have all been marked as resolved, so I just want to make sure I'm understanding correctly.

When you mention that a few of the "nice-to-have" points are still pending, are those items outside the review comments, or follow-ups beyond what was discussed here? I'm just trying to reconcile that with everything currently being marked as resolved. Should any of the review comments be marked as unresolved?

**Comment by anamikaanu96** [comment]
> Hi @anamikaanu96, the comments from my latest review have all been marked as resolved, so I just want to make sure I'm understanding correctly.
> 
> When you mention that a few of the "nice-to-have" points are still pending, are those items outside the review comments, or follow-ups beyond what was discussed here? I'm just trying to reconcile that with everything currently being marked as resolved. Should any of the review comments be marked as unresolved?

My bad, I have unresolved those comments which are not addressed.

**Comment by adamalston** [comment]
> Currently, Carbon for IBM Products is the primary consumer of this utility, and we’re using it specifically within the Coachmark component. At the same time, we intend for this utility to be available for use by other adopters as well.
> Given that these changes are required for the products library, I suggest we go ahead and merge this PR for now. We can open a follow-up issue to address the remaining items. It would also be great if you’d like to contribute to those improvements.

If someone from the Carbon team can confirm that they support this approach, or are comfortable with introducing a breaking change and addressing it afterward, I'm fine moving forward and approving this pull request.

File: packages/utilities/src/makeDraggable/makeDraggable.ts (hunk 11 above)
Comment (amal-k-joy) [reply packages/utilities/src/makeDraggable/makeDraggable.ts:249]: Hi @adamalston ,
Why would adopter wants to apply class based transforms as well when makeDraggable works using transform property?

File: packages/utilities/src/makeDraggable/makeDraggable.ts (hunk 12 above)
Comment (amal-k-joy) [reply packages/utilities/src/makeDraggable/makeDraggable.ts:101]: @adamalston , do you think 3d transform would be relevant for draggable container when the draggable happens in 2d ?

File: packages/utilities/src/makeDraggable/makeDraggable.ts (hunk 11 above)
Comment (adamalston) [reply packages/utilities/src/makeDraggable/makeDraggable.ts:249]: The issue is less that consumers should do it and more that this pull request documents it as a supported case. The `init` JSDoc comment explicitly calls out recovery from CSS animations, class changes, and other external repositioning. After the first drag, `makeDraggable` has already written an inline `style.transform`, so later class based transforms lose in the cascade and `getComputedStyle(el).transform` still reflects the inline matrix. In other words, the documented recovery path for class changes does not work once the element has been dragged.

If the intended contract is that `makeDraggable` fully owns `transform` after initialization, that is fine, but then I think the `init` comment and recovery claim should be narrowed to match that behavior.

It doesn't make sense to document something that's unsupported. It's misleading and may cause confusion.

File: packages/utilities/src/makeDraggable/makeDraggable.ts (hunk 12 above)
Comment (adamalston) [reply packages/utilities/src/makeDraggable/makeDraggable.ts:101]: Yes.

The drag delta is 2D, but the element can still start with a 3D transform. `DOMMatrix` can parse `matrix3d(...)`, but this code rebuilds `baseMatrix` from only `a`, `b`, `c`, and `d`, which drops the remaining 3D and perspective terms. That means the first drag can change the element's rendering even though the user only moved it in `x` and `y`.

If 3D transforms are intentionally out of scope, I think the code should either document that limitation or guard against it explicitly instead of silently flattening the transform on first drag. An explicit guard would be more consistent with the defensive checks used elsewhere in the codebase for unsupported inputs or states.

Examples of guards:

- https://github.com/carbon-design-system/carbon/blob/b06b381d14e33f2a8264b8fc39a7a7e71a2813a7/packages/utilities/src/overflowHandler/overflowHandler.ts#L165-L174
- https://github.com/carbon-design-system/carbon/blob/b06b381d14e33f2a8264b8fc39a7a7e71a2813a7/packages/web-components/src/components/data-table/table-header-cell.ts#L107-L113

Comment (tay1orjones) [reply packages/utilities/src/makeDraggable/makeDraggable.ts:101]: 3D transforms feel out of scope to me, at least for now. Agree adding a guard would be a good stopgap

**Comment by tay1orjones** [comment]
@adamalston `@carbon/utilities` and `@carbon/utilties-react` are in prerelease `0.x` versioning state for now and not subject to semver. This is intentional as these are primarily utilities for use in other carbon libraries rather than downstream consumers (atleast for now)

**Review by tay1orjones — APPROVED** [review]

**Review by adamalston — APPROVED** [review]
