### PR TITLE
fix(checkbox): Disabled checkbox fix, update checkbox demo html

### LINKED ISSUE #667: Support disabled state for label > input variant of Checkbox
This issue is to make sure that we're supporting the disabled state for the `label > input` variant of the checkbox in carbon components 😄

### PR DESCRIPTION
**Pull request by alisonjoseph**
## Overview

Resolves #667 

### Added

support for disabled checkboxes for `label > input` checkbox 

### Changed

Updated demo html file, update javascript to support disabled checkboxes nested inside the label.

## Testing / Reviewing

Make sure checkboxes are working

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

File: src/components/checkbox/checkbox.js [hunk 1]
```diff
@@ -96,6 +101,23 @@ class Checkbox extends mixin(createComponent, initComponentBySearch, handles) {
     }
   }
 
+  setDisabled(value) {
+    if (value === undefined || disabledTypes[value] === undefined) {
```
Comment (asudoh) [inline src/components/checkbox/checkbox.js]: Great that you added sanity check here! And good attempt to use a table, which works for limited set of accepted values in general. I’m guessing that we are accepting only boolean values? Do we want to accept `'true'` and `'false'` as strings?

**Review by asudoh — COMMENTED** [review]
Thanks @alisonjoseph for making this fix! LGTM in general, just one comment.

File: src/components/checkbox/checkbox.js (hunk 1 above)
Comment (alisonjoseph) [reply src/components/checkbox/checkbox.js]: I updated the code to use a boolean value for `setDisabled`, you're right that makes more sense. I also found a bug with the indeterminate checkbox when I was testing and fixed that on line `115`.

File: src/components/checkbox/checkbox.js [hunk 2]
```diff
@@ -96,15 +96,31 @@ class Checkbox extends mixin(createComponent, initComponentBySearch, handles) {
...
   }
 
+  setDisabled(value) {
+    if (value === undefined) {
+      throw new TypeError('setDisabled expects a boolean value of true or false');
+    }
+    if (value === true) {
+      this.element.setAttribute('disabled', true);
+    } else if (value === false) {
+      this.element.removeAttribute('disabled', true);
```
Comment (asudoh) [inline src/components/checkbox/checkbox.js]: IIRC `removeAttribute()` only takes one argument?

File: src/components/checkbox/checkbox.js [hunk 3]
```diff
@@ -96,15 +96,31 @@ class Checkbox extends mixin(createComponent, initComponentBySearch, handles) {
...
+    }
+    const container = this.element.closest('[data-contained-checkbox-disabled]');
+    if (container) {
+      this.element.parentElement.setAttribute('data-contained-checkbox-disabled', value);
```
Comment (asudoh) [inline src/components/checkbox/checkbox.js]: Did we want to change the attribute of the `container` here...?

**Review by asudoh — COMMENTED** [review]
Thanks @alisonjoseph for your quick changes? Almost there - Just a couple tiny things.

File: src/components/checkbox/checkbox.js (hunk 3 above)
Comment (alisonjoseph) [reply src/components/checkbox/checkbox.js]: We need this for the styling for the *(input > label)* variant.

File: src/components/checkbox/checkbox.js (hunk 2 above)
Comment (alisonjoseph) [reply src/components/checkbox/checkbox.js]: Yes, I'll update

File: src/components/checkbox/checkbox.js (hunk 3 above)
Comment (asudoh) [reply src/components/checkbox/checkbox.js]: OK thank you for clarifying!

**Review by asudoh — APPROVED** [review]
Thanks @alisonjoseph for making the changes! LGTM 👍
