### PR TITLE
fix(overflow-menu): return focus to trigger on esc

### LINKED ISSUE #20646: [a11y]: Overflow Menu: focus lost when menu closed using keyboard navigation
### Package

@carbon/web-components

### Browser

Chrome

### Operating System

Windows

### Package version

2.27.1

### React version

_No response_

### Automated testing tool and ruleset

Manual testing

### Assistive technology

_No response_

### Description

When overflow menu is open Esc key should collapse the menu and return focus to the menu button. This doesn't happen, currently the menu collapses and focus is lost. This can be seen on the Overflow menu story book. 

### WCAG 2.1 Violation

_No response_

### Reproduction/example

Esc focus key issue is visible on overflow menu storybook 

### Steps to reproduce

Using keyboard navigate to and open the overflow menu works as expected.

However when pressing the "Escape" key, to leave the overflow menu focus is lost. According to documentation Esc should collapse the menu and return focus to the menu button. This doesn't happen, currently the menu collapses and focus is lost. This can be seen on the Overflow menu story book. 

### Suggested Severity

None

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by divya-281**
Closes #20646

This PR closes issue  #20646 

In web components when overflow menu is opened then closed using esc key, the focus returns to the triggering button

### Changelog

https://github.com/user-attachments/assets/d5e2f90b-b87b-4bfe-9631-09aa5acfb3ee

#### Testing / Reviewing

Open web components story book locally with `npm run storybook` in `carbon/packages/web-components`

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [ ] ~Wrote passing tests that cover this change~
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by Gururajj77 — CHANGES_REQUESTED** [review]
Hey @divya-281 , Everything looks good, could you write some tests covering this use case??

**Review by alisonjoseph — APPROVED** [review]

File: packages/web-components/src/components/overflow-menu/overflow-menu-body.ts [hunk 1]
```diff
@@ -131,23 +171,14 @@ class CDSOverflowMenuBody extends CDSFloatingMenu {
...
         event.preventDefault();
-        this.open = false;
 
-        requestAnimationFrame(() => {
-          const menuTrigger = this.parent as HTMLElement | null;
-          const triggerButton =
-            menuTrigger?.shadowRoot?.querySelector(
-              `button.${prefix}--overflow-menu`
-            ) || menuTrigger?.querySelector(`button.${prefix}--overflow-menu`);
+        const menuTrigger = this.parent as HTMLElement | null;
```
Comment (2nikhiltom) [inline packages/web-components/src/components/overflow-menu/overflow-menu-body.ts:155]: Hey @divya-281 , Seeing a regression here - When menu item is selected via Enter key,  the menu closes but focus is lost

https://github.com/user-attachments/assets/dc67988e-e8c4-4c70-8e8b-692b0904ca00



 I think adding back the focus return logic should fix this
 
```suggestion
          requestAnimationFrame(() => {
        const menuTrigger = this.parent as HTMLElement | null;
    const triggerButton =
      menuTrigger?.shadowRoot?.querySelector(
        `button.${prefix}--overflow-menu`
      ) || menuTrigger?.querySelector(`button.${prefix}--overflow-menu`);

    if (triggerButton) {
      (triggerButton as HTMLElement).focus();
    } else {
      console.warn('Could not find trigger button.');
      (document.body as HTMLElement).focus();
    }
  });
```

**Review by 2nikhiltom — CHANGES_REQUESTED** [review]

File: packages/web-components/src/components/overflow-menu/overflow-menu-body.ts (hunk 1 above)
Comment (divya-281) [reply packages/web-components/src/components/overflow-menu/overflow-menu-body.ts:155]: @2nikhiltom When a user selects one of the items in overflow menu the focus does not return back to the trigger button in [react components](https://react.carbondesignsystem.com/?path=/story/components-overflowmenu--default), which is why I removed this, adding this back makes the focus return to the trigger button after user selects an item. Can you let me know what is the expected behaviour?

Comment (2nikhiltom) [reply packages/web-components/src/components/overflow-menu/overflow-menu-body.ts:155]: Looking at the Dropdown in both [react](https://web-components.carbondesignsystem.com/?path=/story/components-dropdown--default) and [web-components  ](https://web-components.carbondesignsystem.com/?path=/story/components-dropdown--default) I think the focus should go back to the triggering element after the item is selected or the list is closed via ESC key

Comment (divya-281) [reply packages/web-components/src/components/overflow-menu/overflow-menu-body.ts:155]: Thanks for clarifying, I've made the change!

**Comment by divya-281** [comment]
@Gururajj77 @2nikhiltom Could you re-review my PR? 
TIA!

**Comment by 2nikhiltom** [comment]
@divya-281  thanks for the quick follow up, the changes LGTM. it just seems like there is an issue with the test cases, I suspect  adding `await` should fix them 
image

**Comment by divya-281** [comment]
Hey @2nikhiltom Can you please check again?

**Comment by divya-281** [comment]
@2nikhiltom I think tests are failing due to recent changes, as they all passed locally before for me
https://github.com/carbon-design-system/carbon/commit/c1e47b9bec90f1c4e2c678a60bc9b8d577acf321

**Review by Gururajj77 — APPROVED** [review]
LGTM

**Review by 2nikhiltom — APPROVED** [review]
Awesome 🥳 ! thanks for the contribution
