### PR TITLE
fix(multiselect): 5880-multiselect-active-descendent

### LINKED ISSUE #5880: (Multiselect): A button must have "no interactive content descendant"
When a user selects one or more items in our multiselect component they're presented with a button inside of a button in order to clear their selection:
image
Annotation 2020-04-16 163952

Along with creating a host of accessibility errors/adding to potential screen reader and keyboard user confusion and frustration this violates [W3C HTML5 spec 4.10.6](https://www.w3.org/TR/html51/sec-forms.html#the-button-element) which states "there must be no interactive content descendant" for a button element.

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #5880

### CHANGED:

- Fixes MultiSelect active descendant a11y violation by adding a delete `onKeyDown` event handler to the `clear input button`
- Adds visually hidden description `To clear selection, press Delete`

### TESTING:

- [ ] Interact with the MultiSelect component with a browser compatible screen reader (i.e. - VoiceOver test on Safari) 

- [ ] Make sure component is fully interactive with keyboard functionalities and descriptions are detailed enough for all users

### CODE REVIEW

File: packages/react/src/components/MultiSelect/MultiSelect.js [hunk 1]
```diff
@@ -193,6 +193,13 @@ const MultiSelect = React.forwardRef(function MultiSelect(
     }
   }
 
+  const onKeyDown = (e) => {
+    if (e.keyCode === 8 && !disabled) {
```
Comment (tw15egan) [inline packages/react/src/components/MultiSelect/MultiSelect.js]: Should we use the internal `keyboard` function here?

https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Search/Search.js#L153-L157

Comment (jnm2377) [reply packages/react/src/components/MultiSelect/MultiSelect.js]: Thanks for the suggestion @tw15egan Didn't realize we had this :D just updated!

**Review by jnm2377 — APPROVED** [review]

File: packages/react/src/components/MultiSelect/MultiSelect.js [hunk 2]
```diff
@@ -222,13 +230,22 @@ const MultiSelect = React.forwardRef(function MultiSelect(
             className={`${prefix}--list-box__invalid-icon ${prefix}--list-box__invalid-icon--warning`}
           />
         )}
+        {selectedItems.length > 0 && (
+          <span
+            className={`${prefix}--visually-hidden`}
+            id={`clear-button-label${id}`}>
+            To clear selection, press Delete
```
Comment (tay1orjones) [inline packages/react/src/components/MultiSelect/MultiSelect.js]: Should this string be parameterized so it can be translated?

File: packages/react/src/internal/keyboard/keys.js [hunk 3]
```diff
@@ -80,3 +80,9 @@ export const ArrowDown = {
   which: 40,
   keyCode: 40,
 };
+
+export const Delete = {
+  key: 'Delete',
+  which: 8,
+  keyCode: 8,
```
Comment (tay1orjones) [inline packages/react/src/internal/keyboard/keys.js]: Should we specify and handle <kbd>Delete</kbd> vs <kbd>Backspace</kbd>? I think `8` is technically Backspace and `46` is Delete? I don't have an extended keyboard with the numpad to test the Delete key directly, but I it looks like same functionality can be achieved via <kbd>fn</kbd> + <kbd>backspace</kbd> testing on https://keycode.info/.

It's super confusing to me because on a non-numpad mac keyboard they label the key as "delete" 🤦

**Review by tay1orjones — COMMENTED** [review]
So sorry for the delay on this one! Just a couple questions below - let me know if I'm off base.

File: packages/react/src/components/MultiSelect/MultiSelect.js (hunk 2 above)
Comment (jnm2377) [reply packages/react/src/components/MultiSelect/MultiSelect.js]: ah, that's a good point. Hadn't thought of that!

File: packages/react/src/internal/keyboard/keys.js (hunk 3 above)
Comment (jnm2377) [reply packages/react/src/internal/keyboard/keys.js]: Hmm, that's a good point. I also used keycode.info to figure out the code for Delete. I wonder if maybe it would just be better to use a different command for keyboard controls, one that doesn't change with different type of keyboards. @andreancardona @tay1orjones I don't have an extended keyboard to test it out either.

cc:  @dakahn @vpicone  do either of y'all have an extended keyboard to test this out?

**Review by dakahn — CHANGES_REQUESTED** [review]
_Testing with NVDA in Firefox and JAWS 2020 in Chrome on Windows 10_ 

- [x] If the input has selected options the ability to clear them with <kbd>del</kbd> is not described in either reader when the input receives focus, only the number of selected items are read along with the title/label like  "multiselect title, 5, multiselect label menu"

**Review by tay1orjones — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by dakahn — APPROVED** [review]
Great work -- thanks for doing this
