### PR TITLE
fix(side-nav-menu-item): pass on target prop

### LINKED ISSUE #19367: [Bug]: Side nav links cannot open in a new tab
### Package

@carbon/web-components

### Browser

Chrome

### Package version

2.28.0

### React version

_No response_

### Description

The href on "cds-side-nav-menu-item" gets passed down to the "a" anchor element but other attributes like "target" do not.

Compare the web components code here:

https://github.com/carbon-design-system/carbon/blob/main/packages/web-components/src/components/ui-shell/side-nav-menu-item.ts

with the React version:
https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/UIShell/SideNavMenuItem.tsx

which takes "...rest" from the props, and passes it down to the generated link component.

### Reproduction/example

https://stackblitz.com/edit/github-bhuku7my

### Steps to reproduce

Click on the link - it is not opened in a new tab

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by asfordmatt**
Closes #19367

Parity with React equivalent

### Changelog

**Changed**

- Add optional "target" prop to side-nav-menu-item that is passed down to the link component.

#### Testing / Reviewing

Can be checked via storybook

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by sangeethababu9223 — APPROVED** [review]

File: packages/web-components/src/components/ui-shell/side-nav-menu-item.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@
  */
 
 import { classMap } from 'lit/directives/class-map.js';
-import { LitElement, html } from 'lit';
+import { LitElement, html, nothing } from 'lit';
```
Comment (heloiselui) [inline packages/web-components/src/components/ui-shell/side-nav-menu-item.ts]:
```suggestion
import { ifDefined } from 'lit/directives/if-defined.js';
import { LitElement, html } from 'lit';
```

Comment (heloiselui) [reply packages/web-components/src/components/ui-shell/side-nav-menu-item.ts]: Consider using Lit’s `ifDefined()` for target (like `cds-side-nav-link`) so the target attribute is omitted when not set, instead of risking `target="nothing"` output.

File: packages/web-components/src/components/ui-shell/side-nav-menu-item.ts [hunk 2]
```diff
@@ -35,6 +35,12 @@ class CDSSideNavMenuItem extends FocusMixin(LitElement) {
   @property()
   href = '';
 
+  /**
+   * Link `target`.
+   */
+  @property()
```
Comment (heloiselui) [inline packages/web-components/src/components/ui-shell/side-nav-menu-item.ts]:
```suggestion
  @property({ reflect: true })
```

File: packages/web-components/src/components/ui-shell/side-nav-menu-item.ts [hunk 3]
```diff
@@ -60,13 +66,17 @@ class CDSSideNavMenuItem extends FocusMixin(LitElement) {
...
       [`${prefix}--side-nav__link`]: true,
       [`${prefix}--side-nav__link--current`]: active,
     });
     return html`
-      <a part="link" class="${classes}" href="${href}">
+      <a
+        part="link"
+        class="${classes}"
+        href="${href}"
+        target="${target || nothing}">
```
Comment (heloiselui) [inline packages/web-components/src/components/ui-shell/side-nav-menu-item.ts]:
```suggestion
        target="${ifDefined(target)}">
```

**Review by heloiselui — CHANGES_REQUESTED** [review]
Looks good, just a small suggestion.

File: packages/web-components/src/components/ui-shell/side-nav-menu-item.ts (hunk 1 above)
Comment (asfordmatt) [reply packages/web-components/src/components/ui-shell/side-nav-menu-item.ts]: Lit's "nothing" value does have that same behaviour ("ifDefined" is implementing using it). But I see there is a preference in the codebase for using "ifDefined" so happy to switch over.

**Review by heloiselui — APPROVED** [review]
LGTM, Thanks!! 🚀
