### PR TITLE
fix(table-batch-action): remove default iconDescription, add proptype check, update stories

### LINKED ISSUE #3809: TableBatchAction iconDescription should only be required when there are no children and should default to ''
If an iconDescription is defined, it is read by JAWS in addition to the button's visible label. So an iconDescription should only be provided when there is no visible label. 

image

Additionally, callers must pass iconDescription='' to override the bad default value of 'Add' (the default value should be '')

image

## Environment

Firefox ESR 60.8.0esr
JAWS Version 2019.1906.10 ILM

## Detailed description

carbon-components@10.5.1
carbon-components-react@7.5.1

## Steps to reproduce the issue

https://codesandbox.io/s/tablebatchaction-icondescription-provided-7jk8o
https://codesandbox.io/s/tablebatchaction-icondescription-not-provided-v11z8

### PR DESCRIPTION
**Pull request by jendowns**
Closes #3809 

The 2 big takeaways for me from #3809 are:
1.  if button text is provided, `iconDescription` is not necessary (and shouldn't be present)
2. `iconDescription` should not be "Add" by default because that adds noise for screen readers

Both of these points are very similar to what's been changed with the `Button`'s props recently (https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Button/Button.js#L177) , so I used that component as a guide here.

#### Changelog

**New**

- surface `hasIconOnly` button prop in `TableBatchAction` (referring to same prop in `Button`: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Button/Button.js#L189)

**Changed**

- `iconDescription` is **no longer required**
- change `iconDescription` prop type to add similar warning as the one that already exists in `Button` (https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Button/Button.js#L177)
- update snapshots

**Removed**

- remove default prop value for `iconDescription` (same as in `Button` - https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Button/Button.js#L204)
- in stories, remove `iconDescription` value because button text is already provided in all of those examples

#### Testing / Reviewing

Please note that I am unable to test in JAWS myself (cc @dakahn how should we verify this? thanks for your help!)

### CODE REVIEW

File: packages/react/src/components/DataTable/TableBatchAction.js [hunk 1]
```diff
@@ -14,9 +14,22 @@ const TableBatchAction = props => <Button {...props} />;
 
 TableBatchAction.propTypes = {
   /**
-   * Provide a text description for the icon in the button
+   * Specify if the button is an icon-only button
    */
-  iconDescription: PropTypes.string.isRequired,
+  hasIconOnly: PropTypes.bool,
```
Comment (joshblack) [inline packages/react/src/components/DataTable/TableBatchAction.js:19]: Is `hasIconOnly` being used anywhere?

Comment (jendowns) [reply packages/react/src/components/DataTable/TableBatchAction.js:19]: Oh right, it's not 😅 

I could update the batch actions story to include sample usage of `hasIconOnly` with `iconDescription`? Something like this, maybe for that last button in the batch actions series ("Download"):

```jsx
<TableBatchAction
  hasIconOnly
  renderIcon={Download}
  iconDescription="Download the selected rows"
  onClick={batchActionClick(selectedRows)}
/>
```

Or would you prefer to remove `hasIconOnly` from this?

**Review by joshblack — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!
