### PR TITLE
fix: added aria-label and aria-labelledby support to `PaginationNav`

### LINKED ISSUE #20665: [a11y]: aria-label is hardcoded as 'pagination' for the PaginationNav component
### Package

@carbon/react

### Browser

Chrome

### Operating System

MacOS

### Package version

v1.78.2

### React version

18.3.1

### Automated testing tool and ruleset

e.g. IBM Equal Access Accessibility Checker - 10February2025

### Assistive technology

_No response_

### Description

Currently `aria-label` is hardcoded as 'pagination' for the [PaginationNav](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/PaginationNav/PaginationNav.tsx#L508) component. If we use more than one PaginationNav in the page then it's adding the below accessibility violation

```
"Multiple elements with \"navigation\" role do not have unique labels"
```

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://stackblitz.com/edit/kcijtun1?file=src%2FApp.jsx

### Steps to reproduce

Add more than one PaginationNav component and then scan the page with IBM Accessibility checker chrome extension.

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Gururajj77**
Closes #20665 

the `PaginationNav` component now has the ability to accept `aria-label` and `aria-labelledby`

### Changelog

**New**

- new optional props, `aria-label` and `aria-labelledby` 

**Changed**

- kept the backwards compatibility for `"aria-label"="pagination"`, and introduced a way to use the user-provided a11y values

#### Testing / Reviewing

- open the test pr
- run the accessibility checker
- see that the below error isn't showing up

> [!NOTE]
> Remove the test story before merge

```
"Multiple elements with \"navigation\" role do not have unique labels"
```

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- ~[ ] Updated documentation and storybook examples~
- ~[ ] Wrote passing tests that cover this change~
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/react/src/components/PaginationNav/PaginationNav.tsx [hunk 1]
```diff
@@ -504,8 +511,12 @@ const PaginationNav = React.forwardRef<HTMLElement, PaginationNavProps>(
 
     const startOffset = itemsDisplayedOnPage <= 4 && currentPage > 1 ? 0 : 1;
 
+    const accessibilityLabel = ariaLabelledBy
+      ? { 'aria-labelledby': ariaLabelledBy }
+      : { 'aria-label': ariaLabel ?? 'pagination' };
+
     return (
-      <nav className={classNames} ref={ref} {...rest} aria-label="pagination">
+      <nav className={classNames} ref={ref} {...rest} {...accessibilityLabel}>
```
Comment (tay1orjones) [inline packages/react/src/components/PaginationNav/PaginationNav.tsx]:
```suggestion
      <nav className={classNames} ref={ref} {...rest}>
```

Since the `nav` isn't required to have an accessible name, what if these weren't part of the proptypes/interface and instead just passed through `...rest`?

**Review by tay1orjones — APPROVED** [review]
LGTM but need to remove the test story before merging

File: packages/react/src/components/PaginationNav/PaginationNav.stories.js [hunk 2]
```diff
@@ -29,6 +29,49 @@ export const Default = (args) => {
...
+      </section>
+    </div>
+  );
+};
+
+TwoPaginations.args = {
+  tooltipAlignment: 'center',
+  tooltipPosition: 'bottom',
+};
+
```
Comment (tay1orjones) [inline packages/react/src/components/PaginationNav/PaginationNav.stories.js]:
```suggestion
```

**Review by alisonjoseph — APPROVED** [review]
LGTM
