### PR TITLE
wc: fix(tag): align tooltip logic and a11y with React

### LINKED ISSUE #18517: [Bug]: Allow custom dismiss tooltip label in `DismissibleTag` when ellipsis applied
### The problem

Currently if ellipsis is applied, the hard-coded 'Dismiss' string will be added to the tooltip label.

https://github.com/carbon-design-system/carbon/blob/2f99a479550f3bc52636d65f816cd3ddc3e26207/packages/react/src/components/Tag/DismissibleTag.tsx#L150

https://github.com/carbon-design-system/carbon/blob/2f99a479550f3bc52636d65f816cd3ddc3e26207/packages/react/src/components/Tag/DismissibleTag.tsx#L177-L178

### The solution

Allow the component to receive custom label to be used instead of `dismissLabel` const.

### Examples

_No response_

### Application/PAL

_No response_

### Business priority

Medium Priority = upcoming release but is not pressing

### Available extra resources

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

### Tasks

- [ ] Web Components Implementation
- [ ] React Implementation

### PR DESCRIPTION
**Pull request by heloiselui**
Closes #18517

Fixes the tooltip behavior on `<cds-dismissible-tag>` to match the logic in the React implementation.

> [!NOTE]  
> I created a separate [PR](https://github.com/carbon-design-system/carbon/pull/19106) for React.

#### Changelog

**New**
- Added `dismissTooltipLabel` property

**Changed**
- Updated `dismissActionLabel` logic in `<cds-dismissible-tag>` to show:
  - `Dismiss "Label"` when ellipsis/truncation is applied
  - `Dismiss` when not
- Removed native `title` attribute from close button to avoid tooltip overlap
image

#### Testing / Reviewing
- CI should pass

To test this in Storybook (Deploy Preview):

1. Go to Tag > Dismissible story.
2. Set a long text value (so it's truncated).
3. Hover over the close button (×) and check:
   - The tooltip shows your custom message.
image

### CODE REVIEW

File: packages/web-components/src/components/tag/dismissible-tag.ts [hunk 1]
```diff
@@ -169,13 +171,13 @@ class CDSDismissibleTag extends HostListenerMixin(FocusMixin(CDSTag)) {
           <button
             class="sb-tooltip-trigger"
             role="button"
-            aria-labelledby="content"
+            aria-label="${dismissActionLabel}"
```
Comment (tay1orjones) [inline packages/web-components/src/components/tag/dismissible-tag.ts]: Is aria-label what we typically do here or could this remain `aria-labelledby="content"` since `dismissActionLabel` is rendered in the `#content`?

**Review by tay1orjones — APPROVED** [review]
Just one question

File: packages/web-components/src/components/tag/dismissible-tag.ts (hunk 1 above)
Comment (heloiselui) [reply packages/web-components/src/components/tag/dismissible-tag.ts]: Thanks for pointing that out! I'll use aria-labelledby="content" because the label text is already rendered in #content, and it follows the pattern used in other components as well.

**Review by 2nikhiltom — APPROVED** [review]
