### PR TITLE
fix(modal): resolve focus trap issue

### LINKED ISSUE #20073: [a11y]: focus trap not working in `shift+tab` in modal web component
### Package

@carbon/web-components

### Browser

Chrome

### Operating System

MacOS

### Package version

v2.35.0

### React version

_No response_

### Automated testing tool and ruleset

-

### Assistive technology

_No response_

### Description

Observed two issues related to focus:

https://github.com/user-attachments/assets/ea7be9d4-1d1c-403e-b43f-c3ec4eb7fa7e

1. Initial focus is on the 4th element in the Storybook
2. When pressing `shift+tab`, the focus is lost (see the above screen recording)

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://web-components.carbondesignsystem.com/?path=/story/components-modal--default

### Steps to reproduce

1. Go to the [storybook](https://web-components.carbondesignsystem.com/?path=/story/components-modal--default)
2. Press `Shift+tab` to focus in reverse order

It can be observed that after the first element, it loses the focus from the Modal; instead, it should focus on the last element.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by makafsal**
Closes #20073 

Resolved focus trap issue in `cds-modal` component

### Changelog

**New**

- Implemented tab handling in the `keydown` event

**Removed**

- Removed `blur` event handler and focus-related log

#### Testing / Reviewing

Storybook
Check the focus trap using `Tab` key and `Shift+Tab` key.

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/web-components/src/components/modal/modal.ts [hunk 1]
```diff
@@ -276,6 +200,12 @@ class CDSModal extends HostListenerMixin(LitElement) {
   @property({ attribute: 'container-class' })
   containerClass = '';
 
+  /**
+   * Specify the Modal should disable the focus trap.
+   */
+  @property({ type: Boolean, reflect: true, attribute: 'disable-focus-trap' })
+  disableFocusTrap = false;
```
Comment (ariellalgilmore) [inline packages/web-components/src/components/modal/modal.ts]: I don't see a matching prop in react, so maybe we can remove this?

**Review by ariellalgilmore — COMMENTED** [review]
This is looking good! sorry for the delay, but just one small comment

File: packages/web-components/src/components/modal/modal.ts (hunk 1 above)
Comment (makafsal) [reply packages/web-components/src/components/modal/modal.ts]: Sure.

**Comment by makafsal** [comment]
> This is looking good! sorry for the delay, but just one small comment

I'm back from the SevOne away mission; this comment is resolved. Thank you for reviewing ✌️

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

**Review by riddhybansal — APPROVED** [review]
LGTM 💯
