### PR TITLE
fix(Dropdown): prevent unnecessary duplicate VO readings

### LINKED ISSUE #7707: Voiceover reads dropdown items twice
## Environment

> Operating system

Mac osx 11.1

> Browser

Safari

> Automated testing tool and ruleset

https://www.ibm.com/able/guidelines/ci162/info_and_relationships.html

> Assistive technology used to verify

Mac voice over (command f5), then move focus from one item to the next, items are read twice.

## Detailed description

> What version of the Carbon Design System are you using?

latest

> What did you expect to happen?

voice over read item once

> What happened instead?

Items are read twice

> What WCAG 2.1 checkpoint does the issue violate?

https://www.ibm.com/able/guidelines/ci162/info_and_relationships.html

## Steps to reproduce the issue

1. Go to https://carbon-components-react.netlify.app/?path=/story/dropdown--default
2. On a mac, press command f5
3. Open the dropdown, then using the keyboard, navigate the focus from one item to the next
4. Voice over reads items twice

## Additional information

- Screenshots or code
- Notes
image

### PR DESCRIPTION
**Pull request by emyarod**
Closes #7707

This PR prevents VO from reading listbox items twice except for items whose width exceeds the listbox menu width

#### Changelog

**Changed**

- attach `title` only when menu item option width exceeds listbox menu width
- forward refs in ListBoxMenuItem

#### Testing / Reviewing

Ensure that native HTML tooltips are only added to long listbox menu item options with ellipses

### CODE REVIEW

File: packages/react/src/components/Dropdown/Dropdown.js [hunk 1]
```diff
@@ -172,14 +174,20 @@ const Dropdown = React.forwardRef(function Dropdown(
...
+                menuItemOptionRefs?.current[index]?.current || {};
               return (
                 <ListBox.MenuItem
                   key={itemProps.id}
                   isActive={selectedItem === item}
                   isHighlighted={
                     highlightedIndex === index || selectedItem === item
                   }
-                  title={itemToElement ? item.text : itemToString(item)}
+                  title={(offsetWidth < scrollWidth && title) || undefined}
```
Comment (joshblack) [inline packages/react/src/components/Dropdown/Dropdown.js:187]: Would it make sense to do this check in the menu item component itself? Something like

```js
const ListBoxMenuItem = ({ children, isActive, isHighlighted, title, ...rest }) => {
  const ref = useRef(null);
  const truncated = useTruncated(ref);

  // ...

  return (
    <div {...rest} className={className} title={truncated ? title : undefined}>
      <div
        className={`${prefix}--list-box__menu-item__option`}
        ref={ref}>
        {children}
      </div>
    </div>
  );
};

function useTruncated(ref) {
  const [truncated, setTruncated] = useState(false);

  useLayoutEffect(() => {
    const { offsetWidth, scrollWidth } = ref.current;
    if (offsetWidth < scrollWidth) {
      setTruncated(true);
    } else {
      setTruncated(false);
    }
  });

  return truncated;
}
```

Comment (emyarod) [reply packages/react/src/components/Dropdown/Dropdown.js:187]: I tried this to begin with but Downshift was not playing nice with hooks in the ListBoxMenuItem. Did this approach work in your testing?

Comment (joshblack) [reply packages/react/src/components/Dropdown/Dropdown.js:187]: @emyarod I see what you mean, surprisingly it changes depending on if you are viewing the story in the storybook or in a standalone/full screen view 🤔  (meaning it works when full screen)

Would be good to figure out what's going on with it for the "ideal" setup, I wonder if it's just the way that we're rendering items versus some weird downshift issue. I think reading from a ref in render is one of those [weird forbidden rules ](https://gist.github.com/sebmarkbage/75f0838967cd003cd7f9ab938eb1958f#forbidden)

> Read a property from an object, unless that object was "newly created" or if the property will never change after it is read once.

Since reading the ref can change between renders. Quick example: https://codesandbox.io/s/dazzling-leftpad-ql8b1?file=/src/App.js

Comment (emyarod) [reply packages/react/src/components/Dropdown/Dropdown.js:187]: > it changes depending on if you are viewing the story in the storybook or in a standalone/full screen view 🤔 (meaning it works when full screen)

I wasn't seeing this from my testing and the error was appearing in all views. that's what initially led me to believe that it's Downshift related and also why I began exploring forwarding refs to the listbox menu item

Comment (emyarod) [reply packages/react/src/components/Dropdown/Dropdown.js:187]: do we want to continue exploring our initial idea of using hooks in `ListBoxMenuItem` or should we proceed with something else?

Comment (joshblack) [reply packages/react/src/components/Dropdown/Dropdown.js:187]: @emyarod would be great to figure out what's going on with using hooks in `ListBoxMenuItem` 🤔  I think that'd be ideal for this setup. I wonder if the issue with downshift is a small one or if it really is a broader issue for the library.

Comment (emyarod) [reply packages/react/src/components/Dropdown/Dropdown.js:187]: the problem is we are using hooks in class based components. I have refactored `ComboBox` to a function component but in order to preserve compatibility with MultiSelect and Dropdown I still need to forward the ref with the object ref syntax. I didn't want to refactor those other ListBox components in this PR but I can do so in separate PRs so that we will no longer need to forward refs to `ListBox.MenuItem`

Comment (joshblack) [reply packages/react/src/components/Dropdown/Dropdown.js:187]: @emyarod definitely agreed that hooks don't make sense in class-based components. I think from above what was surprising was that using hooks in one of the components rendered by the class-based component was violating the rules of hooks as we should be able to call/render components that use hooks inside of components that are class-based.

Comment (emyarod) [reply packages/react/src/components/Dropdown/Dropdown.js:187]: gotcha do you have something else in mind to resolve the error? from my testing refactoring the component was the only way I could resolve the issue so I rolled it into this PR

**Comment by emyarod** [comment]
I assume this PR review was held up for #7777 due to the massive merge conflicts

**Review by dakahn — APPROVED** [review]
Getting back to this sorry -- reads reaally well. Also reads great in NVDA and JAWS 2020 on Windows latest with Edge and Firefox

**Review by joshblack — APPROVED** [review]

File: packages/react/src/components/ComboBox/ComboBox.js [hunk 2]
```diff
@@ -65,490 +70,479 @@ const findHighlightedIndex = ({ items, itemToString }, inputValue) => {
...
   };
 
-  handleSelectionClear = () => {
-    if (this.textInput?.current) {
-      this.textInput.current.focus();
+  useEffect(() => {
+    if (onInputChange) {
+      onInputChange(inputValue);
+    }
+  });
```
Comment (TheSharpieOne) [inline packages/react/src/components/ComboBox/ComboBox.js:153]: Without a dependency array, this will trigger the `onInputChange` with _every_ render.

This should only be triggered when the `inputValue` changes
```js
  useEffect(() => {
    if (onInputChange) {
      onInputChange(inputValue);
    }
  }, [inputValue]); // <-- it should have this!
```

Comment (emyarod) [reply packages/react/src/components/ComboBox/ComboBox.js:153]: related #8306 #8308
