### PR TITLE
fix: adds warning for inccorect API usage on datepickerInput

### LINKED ISSUE #19712: [Bug]: DatePickerInput fails to display value under DatePicker range in readOnly mode
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.83.0 and v1.84.0 

### React version

v18.3.1

### Description

With `DatePicker` component in `readOnly` mode and `datePickerType="range"`, the 2nd child `DatePickerInput` component fails to display the value. Instead, it displays the placeholder value.

This bug was first introduced in @carbon/react v1.83.0 and persists in 1.84.0. In older versions 1.82.0 and prior, the bug is not present and everything works correctly.

The 1st screenshot is `readOnly` mode enabled, note the 2nd date field not displaying value. This is the bug.
Image

The 2nd screenshot is with `readOnly` mode disabled, note the 2nd date field displaying value as it should.
Image

### Reproduction/example

n/a

### Steps to reproduce

`npm install @carbon/react v1.83.0` or `npm install @carbon/react v1.84.0`

```
<DatePicker
                      id="startend"
                      datePickerType="range"
                      readOnly={readOnly}
                      disabled={isSubmitted}
                      onChange={(e) => {
                        setStartDate(e[0] && e[0].toLocaleDateString());
                        setEndDate(e[1] && e[1].toLocaleDateString());
                        setStartDateInvalid(false);
                        setEndDateInvalid(false);
                      }}
                    >
                      <DatePickerInput
                        id="startDate"
                        placeholder="mm/dd/yyyy"
                        labelText="Start date"
                        size="md"
                        value={startDate}
                        invalid={startDateInvalid}
                        invalidText="Valid date required."
                      />
                      <DatePickerInput
                        id="endDate"
                        placeholder="mm/dd/yyyy"
                        labelText="End date"
                        size="md"
                        value={endDate}
                        invalid={endDateInvalid}
                        invalidText="Valid date required."
                      />
</DatePicker>
```

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Application/PAL

IBM Redbooks

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by 2nikhiltom**
Closes https://github.com/carbon-design-system/carbon/issues/19712

This PR introduces a one-time console `warning` when the value prop is passed directly to the DatePickerInput component.

Our recent TypeScript migration and stricter prop validation in the DatePicker component exposed an incorrect API usage pattern that was previously "accidentally functional."

`value` is a fundamental HTML input attribute, making it intuitive for developers to try to control DatePickerInput directly. This warning provides immediate, explicit feedback that this is incorrect usage, guiding them to the proper API.

### Changelog

**New**

Adds a `warning` in the console if value is passed to `DatePickerInput`

#### Testing / Reviewing

pull down PR locally (warning is only thrown in non production env )
open "datepicker--read-only-range-bug-reproduction"  story
verify warning is seen once 

- [ ] test story needs to be removed before merging 

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
~- [ ] Addressed any impact on accessibility (a11y)~
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by Gururajj77 — APPROVED** [review]
LGTM🚀

File: packages/react/src/components/DatePickerInput/DatePickerInput.tsx [hunk 1]
```diff
@@ -189,6 +191,18 @@ const DatePickerInput = React.forwardRef(function DatePickerInput(
...
+      warning(
+        false,
+        `The 'value' prop is not supported on the DatePickerInput component. ` +
+          `For DatePicker components with 'datePickerType="range"', please ` +
+          `pass the 'value' prop (as an array of dates) to the parent ` +
+          `DatePicker component instead.`
+      );
+      didWarnAboutDatePickerInputValue = true;
+    }
+  }
```
Comment (tay1orjones) [inline packages/react/src/components/DatePickerInput/DatePickerInput.tsx]:
```suggestion
  if (process.env.NODE_ENV !== 'production' && !didWarnAboutDatePickerInputValue) {
    warning(
      !('value' in rest),
      `The 'value' prop is not supported on the DatePickerInput component. ` +
        `For DatePicker components with 'datePickerType="range"', please ` +
        `pass the 'value' prop (as an array of dates) to the parent ` +
        `DatePicker component instead.`
    );
    didWarnAboutDatePickerInputValue = true;
  }
```

**Review by tay1orjones — APPROVED** [review]
LGTM once the test story is removed

**Review by ariellalgilmore — APPROVED** [review]

File: packages/react/src/components/DatePickerInput/DatePickerInput.tsx (hunk 1 above)
Comment (2nikhiltom) [reply packages/react/src/components/DatePickerInput/DatePickerInput.tsx]: Hey - I suspect this would always set the `didWarnAboutDatePickerInputValue` flag irrespective of the warning being shown or not. I changed it to
```
if (process.env.NODE_ENV !== 'production' && 'value' in rest && !didWarnAboutDatePickerInputValue) {
  warning(
    false,
    `The 'value' prop is not supported on the DatePickerInput component. ` +
      `For DatePicker components with 'datePickerType="range"', please ` +
      `pass the 'value' prop (as an array of dates) to the parent ` +
      `DatePicker component instead.`
  );
  didWarnAboutDatePickerInputValue = true;
}
```
