### PR TITLE
fix(search): fix expand and focus behavior

### LINKED ISSUE #20081: [cds-search]: search bar expands on focus
This is a **parity issue**. In React, the expandable search bar expands on focus. This seems to be the expected behaviour.

React: 

https://github.com/user-attachments/assets/82baf35a-105d-4145-aae5-9809f6e7dca0

But in the `cds-search` web component, it expands on focus.

WC:

https://github.com/user-attachments/assets/b14758ab-a9eb-441e-ba8c-7af44899688c

### PR DESCRIPTION
**Pull request by heloiselui**
Closes #20081

Fixed expand and focus behavior

### Changelog

**New**

- N/A

**Changed**

- Search expands only when clicking the magnifier or pressing Enter/Space
- ESC clears input if it has text, otherwise collapses and focuses the magnifier

**Removed**

- N/A

#### Testing / Reviewing

- Go to `WC Deploy Preview` > `Search` > `Expandable`
- Tab, shoul focus in magnifier button > should expand and focus input  
- Press Enter/Space when collapsed > should expand and focus input  
- Type something, press ESC > input clears but stays focused  
- Leave input empty, press ESC > search collapses and focus returns to magnifier  
 
## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [X] Reviewed every line of the diff
- ~[ ] Updated documentation and storybook examples~
- ~[ ] Wrote passing tests that cover this change~
- ~[ ] Addressed any impact on accessibility (a11y)~
- [X] Tested for cross-browser consistency
- [X] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by maradwan26 — CHANGES_REQUESTED** [review]
The focus ring on the icon doesn't show when tabbing.


I'm suspecting that this may just be a styling issue, because when using VoiceOver I can see that I'm able to focus the icon when clicking tab, its just that there is no user feedback to show that it is focused. Using Esc after opening the search bar to close it correctly shows the focus ring.

_Tab to focus, Enter to open_:

Tabbing doesn't show that the element is being focused with a focus ring, I can still use Enter to open it after, though:

https://github.com/user-attachments/assets/29cf181c-a133-4834-970d-8e8b2a814ec9


How it looks with VoiceOver:

https://github.com/user-attachments/assets/560bb05e-ed70-4010-9fd2-336f60ec2916

**Comment by heloiselui** [comment]
> The focus ring on the icon doesn't show when tabbing.
> 
> I'm suspecting that this may just be a styling issue, because when using VoiceOver I can see that I'm able to focus the icon when clicking tab, its just that there is no user feedback to show that it is focused. Using Esc after opening the search bar to close it correctly shows the focus ring.
> 
@maradwan26 thanks for catching that! I tested it locally and it was working, which I found strange. I tested again on another device and it really wasn’t working. Just fixed it.

**Review by maradwan26 — APPROVED** [review]
Nice! LGTM

File: packages/web-components/src/components/search/search.ts [hunk 1]
```diff
@@ -76,13 +76,73 @@ class CDSSearch extends HostListenerMixin(FocusMixin(FormMixin(LitElement))) {
...
+    const isMagnifierClick = path.some((n: unknown) =>
+      (n as Element)?.classList?.contains(`${prefix}--search-magnifier`)
+    );
+
+    if (isMagnifierClick && this.expandable && !this.expanded) {
       this.setAttribute('expanded', '');
+      // Focus the input after expanding
+      this.shadowRoot!.getElementById('input')?.focus();
+    }
+  }
```
Comment (kennylam) [inline packages/web-components/src/components/search/search.ts]:
```suggestion
    if (isMagnifierClick && this.expandable && !this.expanded) {
      this._expandAndFocus();
    }
  }
  
private _expandAndFocus() {
  this.setAttribute('expanded', '');
  // Focus the input after expanding
  this.shadowRoot?.getElementById('input')?.focus();
}
```

This block, as well as the last `if` in `_handleKeys` do the same thing. They can probably share a function to avoid repetition.

File: packages/web-components/src/components/search/search.ts [hunk 2]
```diff
@@ -76,13 +76,73 @@ class CDSSearch extends HostListenerMixin(FocusMixin(FormMixin(LitElement))) {
...
+
+    if (!this.expandable || this.expanded) {
+      return;
+    }
+
+    // Enter/Space: expand if collapsed
+    if (key === 'Enter' || key === ' ') {
+      event.preventDefault();
+      this.setAttribute('expanded', '');
+      this.shadowRoot!.getElementById('input')?.focus();
```
Comment (kennylam) [inline packages/web-components/src/components/search/search.ts]:
```suggestion
    // Enter/Space: expand if collapsed
    if (key === 'Enter' || key === ' ') {
      event.preventDefault();
      this._expandAndFocus();
```

Same comment as above, to use a shared method for expanding and focusing.

File: packages/web-components/src/components/search/search.ts [hunk 3]
```diff
@@ -119,6 +179,22 @@ class CDSSearch extends HostListenerMixin(FocusMixin(FormMixin(LitElement))) {
...
   }
 
+  /**
+   * Move focus back to the magnifier element.
+   * Adds tabindex="-1" if it is not focusable yet.
+   */
+  private _focusMagnifier() {
+    const magnifier = this.shadowRoot?.querySelector(
+      `.${prefix}--search-magnifier`
+    ) as HTMLElement | null;
```
Comment (kennylam) [inline packages/web-components/src/components/search/search.ts]:
```suggestion
    const magnifier = this.shadowRoot?.querySelector<HTMLElement>(
      `.${prefix}--search-magnifier`
    );
```

`<HTMLElement>` can be used here and you get type checking for free (this will make the type `HTMLElement | null`).

File: packages/web-components/src/components/search/search.ts [hunk 4]
```diff
@@ -76,13 +76,73 @@ class CDSSearch extends HostListenerMixin(FocusMixin(FormMixin(LitElement))) {
...
+    // Esc only works when the input is the active element
+    if (key === 'Escape') {
+      const inputEl = this.shadowRoot?.getElementById(
+        'input'
+      ) as HTMLInputElement | null;
+      if (this.shadowRoot?.activeElement === inputEl) {
+        event.stopPropagation();
+        event.preventDefault();
+
+        if (this.value && this.value.length > 0) {
```
Comment (kennylam) [inline packages/web-components/src/components/search/search.ts]:
```suggestion
        if (this.value?.length) {
```

File: packages/web-components/src/components/search/search.ts [hunk 5]
```diff
@@ -119,6 +179,22 @@ class CDSSearch extends HostListenerMixin(FocusMixin(FormMixin(LitElement))) {
...
+   * Move focus back to the magnifier element.
+   * Adds tabindex="-1" if it is not focusable yet.
+   */
+  private _focusMagnifier() {
+    const magnifier = this.shadowRoot?.querySelector(
+      `.${prefix}--search-magnifier`
+    ) as HTMLElement | null;
+    if (magnifier) {
+      if (!magnifier.hasAttribute('tabindex')) {
+        magnifier.setAttribute('tabindex', '-1');
```
Comment (kennylam) [inline packages/web-components/src/components/search/search.ts]:
```suggestion
        magnifier.tabIndex = -1;
```

Can use the property directly here.

**Review by kennylam — COMMENTED** [review]
Looks good! Just a few suggestions.

**Review by kennylam — APPROVED** [review]
