### PR TITLE
fix(SelectableTile): sync selected prop and state

### LINKED ISSUE #7759: [SelectableTile] Selected state is out of sync when user do shift+click for multi-selection
The last selected item can lose selected state in certain scenario.
Steps to reproduce:
1) Build a view with list of selectable tile
2) Click on one tile and then hold shift to do multi-selection on tiles
3) Hold the shift key and select any tile again
Bug -> if the tile was previously selected, the tile is deselected, even though the `select` props passed in indicate that the tile should persistent selection
holdingShiftToDeselectObjects

Looked into the code base, the issue seems from here:
https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/Tile/Tile.js#L228
https://github.com/carbon-design-system/carbon-components-react/blob/master/src/components/Tile/Tile.js#L239-L247
When user click on the tile, the selected state doesn't respect the selected props value.

## Environment

> Operating system Mac OS

> Browser Chrome

> Automated testing tool and ruleset

> Assistive technology used to verify

## Detailed description

> What version of the Carbon Design System are you using? "carbon-components": "10.17.0", "carbon-components-react": "7.17.0",

> What did you expect to happen? The selected state should respect the selected props value passed in.

> What happened instead? The selected state automatically toggled when user click on the tile

> What WCAG 2.1 checkpoint does the issue violate?

## Steps to reproduce the issue

1. Click on the fourth tile, it should select all the four tiles, but the last tile is toggled as deselected.
> Please create a reduced test case in CodeSandbox
> - React:
>   https://codesandbox.io/s/s-m4yeb

Thanks Bill for helping me put up this codesandbox link. The critical line is at line 76.

## Additional information

- Screenshots or code
Feb-08-2021 15-19-46

- Notes

### PR DESCRIPTION
**Pull request by emyarod**
Closes #7759

This PR keeps the selectable tile's selected state in sync to prevent unexpected selection behavior

#### Changelog

**Changed**

- deprecate `handleClick` and `handleKeyDown` props in favor of standard `onClick` and `onKeyDown` props
- accept value from `selected` prop when provided

#### Testing / Reviewing

ensure the existing tile use cases work as expected together with the added temp example

### CODE REVIEW

File: packages/react/src/components/Tile/Tile.js [hunk 1]
```diff
@@ -181,212 +181,207 @@ export class ClickableTile extends Component {
...
-      }
-    );
+    setIsSelected(!isSelected);
+    clickHandler(evt);
+    onChange(evt);
   };
 
-  handleKeyDown = (evt) => {
+  // TODO: rename to handleKeyDown when handleKeyDown prop is deprecated
+  const handleOnKeyDown = (evt) => {
```
Comment (joshblack) [inline packages/react/src/components/Tile/Tile.js]: One quick style nit: for refactors we should make sure we're following the style guide for components with hooks: [Component](https://github.com/carbon-design-system/carbon/blob/main/docs/style.md#writing-a-component) and [Event Handlers](https://github.com/carbon-design-system/carbon/blob/main/docs/style.md#naming-event-handlers)

**Review by tay1orjones — APPROVED** [review]
Existing and temp stories look good 👍

**Review by joshblack — APPROVED** [review]

**Review by jnm2377 — APPROVED** [review]
