### PR TITLE
fix(Pagination): dont reset page to 1 for pageSizes

### LINKED ISSUE #4217: carbon-components-react Pagination should not reset page number to 1 when itemsPerPage choices change
## What package(s) are you using?
- [x] `carbon-components-react`

## Detailed description
The Pagination component will reset the current `page` to 1 during `getDerivedStateFromProps` if `pageSizesChanged` is true. 

## Steps to reproduce the issue

1. Initialise a Pagination object with pageSizes = [10, 20, 30]
2. change to page 3 (or any page above page 1)
3. render again with a different value for `pageSizes` (see example code)
4. See that page is reset to 1

See behaviour in this sandbox:
https://codesandbox.io/s/codesandbox-i55sv?fontsize=14

## Additional information
I understand that the page number should reset to 1 if the pageSize changes, but not if it's only pageSizes (the array of choices) changes.

### PR DESCRIPTION
**Pull request by stvcisco**
Closes #4217
Page number was resetting to 1 whenever the pageSizes list changed. This was too aggressive since it's not necessary unless the actual pageSize (ie Items-per-page) changes.

#### Changelog
Adjust the pageSIze value if necessary (ie, the new list of pageSizes does not include the current pageSize). Then reset page to 1 only if pageSizeChanged.

#### Testing / Reviewing
Added unit tests for these cases.

### CODE REVIEW

File: packages/react/src/components/Pagination/Pagination.js [hunk 1]
```diff
@@ -154,17 +154,16 @@ export default class Pagination extends Component {
...
     return !pageSizesChanged && !pageChanged && !pageSizeChanged
       ? null
       : {
-          page: pageSizesChanged ? 1 : pageChanged ? page : currentPage,
-          pageSize: pageSizesChanged
-            ? pageSizes[0]
-            : pageSizeChanged
-            ? pageSize
-            : currentPageSize,
+          page: pageSizeChanged ? 1 : pageChanged ? page : currentPage,
```
Comment (emyarod) [inline packages/react/src/components/Pagination/Pagination.js]:
```suggestion
          page: pageSizeChanged && 1 || pageChanged && page || currentPage,
```

just one nitpick about the nested ternary (although I see it's carried over from the existing code). I wonder if that would be slightly more readable and still achieve the same results?

**Review by emyarod — APPROVED** [review]
this looks good to me

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @stvcisco!

**Review by joshblack — APPROVED** [review]
