### PR TITLE
test(useResizeObserver): cleanup tests and add resizing tests

### LINKED ISSUE #19350: [Bug]: `use-resize-observer` does not support React 19
### Package

@carbon/react

### Browser

Chrome

### Package version

1.81.0

### React version

19

### Description

Reported via @ocornec, teams within Cloud noticed build failures after including his AI chat library components from `@carbon/labs`. However, they noticed build failures because of version compatibility issues with `use-resize-observer` since they are using React 19. Even though these are just warnings, it is causing their builds to fail.

`@carbon/ibm-products` has a `useResizeObserver` hook that we use internally, I can add this internally as well to `@carbon/react` and remove `use-resize-observer` as a dependency in `@carbon/react`. This overall sounds like a win-win as it will resolve the warnings/build failures for teams and remove a potentially extraneous dependency.

### Reproduction/example

https://stackblitz.com/edit/q1yb8s5s?file=package.json

### Steps to reproduce

Run `npm install` from stackblitz provided (thanks @ariellalgilmore for putting the stackblitz together!)

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by matthewgallo**
Closes #19350 (Follow up to refactor tests)

The [initial PR](https://github.com/carbon-design-system/carbon/pull/19351) for the `useResizeObserver` included an overly complex testing setup/configuration. I've simplified it a bit with these changes and also included tests for actually resizing, by triggering a resize observer callback. The current tests do not test the actual resize behavior, just that the hook returns the initial (mocked) width and height values.

A lot of the test setup previously was around configuring the mocking. By not mocking the element's width or height, we know those values returned from the hook will always be 0 initially, but by triggering the resize observer callback we can now validate that the returned width and height from the hook are correct.

I also removed a comment about type casting needed for a ref from the old package (`use-resize-observer`) since that is no longer applicable.

### Changelog

**Changed**

- `packages/react/src/components/CodeSnippet/CodeSnippet.tsx`
- `packages/react/src/internal/__tests__/useResizeObserver-test.js`

**Removed**

- `packages/react/src/internal/__mocks__/mockHTMLElement.ts`

#### Testing / Reviewing

Validate by running the updated tests, `npx jest /useResizeObserver`

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] ~Updated documentation and storybook examples~
- [x] Wrote passing tests that cover this change
- [ ] ~Addressed any impact on accessibility (a11y)~
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by Gururajj77 — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me!

File: packages/react/src/components/CodeSnippet/CodeSnippet.tsx [hunk 1]
```diff
@@ -258,8 +258,6 @@ function CodeSnippet({
   }, [type, getCodeRefDimensions]);
 
   useResizeObserver({
-    // Cast the ref until the hook supports React 19
-    // https://github.com/ZeeCoder/use-resize-observer/issues/108
     ref: getCodeRef() as React.RefObject<HTMLElement>,
```
Comment (adamalston) [inline packages/react/src/components/CodeSnippet/CodeSnippet.tsx]: Can the type assertion be deleted if the `ref` type in `useResizeObserver` is updated? It seems like `null` is expected given the `ref.current` condition in that hook.

```diff
diff --git a/packages/react/src/components/CodeSnippet/CodeSnippet.tsx b/packages/react/src/components/CodeSnippet/CodeSnippet.tsx
index 3e26b0b17..db232b6dc 100644
--- a/packages/react/src/components/CodeSnippet/CodeSnippet.tsx
+++ b/packages/react/src/components/CodeSnippet/CodeSnippet.tsx
@@ -258,7 +258,7 @@ function CodeSnippet({
   }, [type, getCodeRefDimensions]);
 
   useResizeObserver({
-    ref: getCodeRef() as React.RefObject<HTMLElement>,
+    ref: getCodeRef(),
     onResize: () => {
       if (codeContentRef?.current && type === 'multi') {
         const { height } = codeContentRef.current.getBoundingClientRect();
diff --git a/packages/react/src/internal/useResizeObserver.ts b/packages/react/src/internal/useResizeObserver.ts
index fa78e751f..f64ca965c 100644
--- a/packages/react/src/internal/useResizeObserver.ts
+++ b/packages/react/src/internal/useResizeObserver.ts
@@ -10,7 +10,7 @@ export const useResizeObserver = ({
   ref,
   onResize,
 }: {
-  ref: RefObject<HTMLElement>;
+  ref: RefObject<HTMLElement | null>;
   onResize?: (rect: DOMRectReadOnly) => void;
 }) => {
   const [width, setWidth] = useState(-1);
```

File: packages/react/src/internal/__tests__/useResizeObserver-test.js [hunk 2]
```diff
@@ -5,96 +5,77 @@
...
+    act(() => {
+      savedObserverCb([{ target: element, contentRect: { width, height } }]);
+    });
+
   it('returns the initial size of the component', () => {
-    render(<TestComponent />);
-    screen.getByText('width: 400, height: 200');
+    render(<ResizeTest />);
+    screen.getByText('width: 0, height: 0');
+  });
```
Comment (adamalston) [inline packages/react/src/internal/__tests__/useResizeObserver-test.js]: Is there supposed to be an assertion in this test?

I see a few instances of `screen.getByText` in this file that are not followed by explicit assertions or otherwise validated.

File: packages/react/src/internal/__tests__/useResizeObserver-test.js [hunk 3]
```diff
@@ -5,96 +5,77 @@
...
+    });
   });
 
   afterEach(() => {
-    mockElement.mockRestore();
-    window.ResizeObserver = ResizeObserver;
+    jest.clearAllMocks();
   });
 
+  // Triggers resize from the saved resize observer callback
```
Comment (adamalston) [inline packages/react/src/internal/__tests__/useResizeObserver-test.js]: This comment should be a JSDoc comment. It's describing a function.

```suggestion
  /** Triggers resize from the saved resize observer callback */
```

File: packages/react/src/internal/__tests__/useResizeObserver-test.js [hunk 4]
```diff
@@ -5,96 +5,77 @@
...
+  const triggerResize = (element, width = defaultSize, height = defaultSize) =>
+    act(() => {
+      savedObserverCb([{ target: element, contentRect: { width, height } }]);
+    });
```
Comment (adamalston) [inline packages/react/src/internal/__tests__/useResizeObserver-test.js]: Is this function supposed to be asynchrouns?

```diff
diff --git a/packages/react/src/internal/__tests__/useResizeObserver-test.js b/packages/react/src/internal/__tests__/useResizeObserver-test.js
index efba9513b..a3449dfa1 100644
--- a/packages/react/src/internal/__tests__/useResizeObserver-test.js
+++ b/packages/react/src/internal/__tests__/useResizeObserver-test.js
@@ -39,8 +39,12 @@ describe('useResizeObserver', () => {
   });
 
   // Triggers resize from the saved resize observer callback
-  const triggerResize = (element, width = defaultSize, height = defaultSize) =>
-    act(() => {
+  const triggerResize = async (
+    element,
+    width = defaultSize,
+    height = defaultSize
+  ) =>
+    await act(async () => {
       savedObserverCb([{ target: element, contentRect: { width, height } }]);
     });
 
@@ -54,27 +58,27 @@ describe('useResizeObserver', () => {
     const element = screen.getByTestId('observed-element');
     screen.getByText('width: 0, height: 0');
 
-    triggerResize(element);
+    await triggerResize(element);
     screen.getByText(`width: ${defaultSize}, height: ${defaultSize}`);
 
-    triggerResize(element, defaultSize * 2, defaultSize * 3);
+    await triggerResize(element, defaultSize * 2, defaultSize * 3);
     screen.getByText(`width: ${defaultSize * 2}, height: ${defaultSize * 3}`);
   });
 
-  it('calls the provided onResize function', () => {
+  it('calls the provided onResize function', async () => {
     const resizeFn = jest.fn();
     render(<ResizeTest onResize={resizeFn} />);
     const element = screen.getByTestId('observed-element');
 
-    triggerResize(element, defaultSize * 2, defaultSize * 3);
+    await triggerResize(element, defaultSize * 2, defaultSize * 3);
     screen.getByText(`width: ${defaultSize * 2}, height: ${defaultSize * 3}`);
     expect(resizeFn).toHaveBeenCalledTimes(1);
 
-    triggerResize(element, defaultSize * 3, defaultSize * 4);
+    await triggerResize(element, defaultSize * 3, defaultSize * 4);
     screen.getByText(`width: ${defaultSize * 3}, height: ${defaultSize * 4}`);
     expect(resizeFn).toHaveBeenCalledTimes(2);
 
-    triggerResize(element, defaultSize, defaultSize);
+    await triggerResize(element, defaultSize, defaultSize);
     screen.getByText(`width: ${defaultSize}, height: ${defaultSize}`);
     expect(resizeFn).toHaveBeenCalledTimes(3);
   });
```

File: packages/react/src/internal/__tests__/useResizeObserver-test.js [hunk 5]
```diff
@@ -5,96 +5,77 @@
...
+
   it('returns the initial size of the component', () => {
-    render(<TestComponent />);
-    screen.getByText('width: 400, height: 200');
+    render(<ResizeTest />);
+    screen.getByText('width: 0, height: 0');
+  });
+
+  it('returns the updated sizes from hook upon resizing', async () => {
```
Comment (adamalston) [inline packages/react/src/internal/__tests__/useResizeObserver-test.js:56]: Why is the callback marked with `async`? Maybe more changes are expected here?

Comment (matthewgallo) [reply packages/react/src/internal/__tests__/useResizeObserver-test.js:56]: Addressed by making `triggerResize` async

File: packages/react/src/internal/__tests__/useResizeObserver-test.js (hunk 4 above)
Comment (matthewgallo) [reply packages/react/src/internal/__tests__/useResizeObserver-test.js]: Addressed via https://github.com/carbon-design-system/carbon/pull/19452/commits/6633de6ef908dc44c4fac5ba21ec94e8a931a83c

File: packages/react/src/internal/__tests__/useResizeObserver-test.js (hunk 3 above)
Comment (matthewgallo) [reply packages/react/src/internal/__tests__/useResizeObserver-test.js]: Addressed via https://github.com/carbon-design-system/carbon/pull/19452/commits/6633de6ef908dc44c4fac5ba21ec94e8a931a83c

File: packages/react/src/internal/__tests__/useResizeObserver-test.js [hunk 6]
```diff
@@ -5,96 +5,91 @@
...
-const TestComponent = () => {
-  const observedElement = useRef(null);
-  const { width, height } = useResizeObserver({ ref: observedElement });
-  const [content, setContent] = useState(-1);
-
-  useEffect(() => {
-    setContent(`width: ${width}, height: ${height}`);
-  }, [height, width]);
 
+const ResizeTest = ({ onResize = null }) => {
```
Comment (adamalston) [inline packages/react/src/internal/__tests__/useResizeObserver-test.js]: Maybe I'm missing something, why does `onResize` need a default value? The tests pass when I delete it.

**Review by adamalston — APPROVED** [review]

File: packages/react/src/internal/__tests__/useResizeObserver-test.js (hunk 6 above)
Comment (matthewgallo) [reply packages/react/src/internal/__tests__/useResizeObserver-test.js]: You're right, it technically doesn't need a default value since it'll just be `undefined` by default. I'll update that as well

**Review by riddhybansal — APPROVED** [review]
