### PR TITLE
fix(modal): prevent bubbling on ESC on inactive

### LINKED ISSUE #2312: Modal traps keydown event for `esc` key for the whole document
## Detailed description
Other elements are not able to add keydown event for the escape key

The keydown event should not add to the document level and stop it from propagating

## Steps to reproduce the issue
Add a event listener for the escape keydown event to any element in the document, and it's not response to the escape key

## Additional information
the line of code doing that 
https://github.com/IBM/carbon-components/blob/master/src/components/modal/modal.js#L139

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #2312.

#### Changelog

**Changed**

- A change to prevent `event.stopPropagation()` from running upon ESC key when modal is not open.

#### Testing / Reviewing

Testing should make sure our modal is not broken.

### CODE REVIEW

**Review by jnm2377 — APPROVED** [review]

File: src/components/modal/modal.js [hunk 1]
```diff
@@ -137,7 +137,8 @@ class Modal extends mixin(createComponent, initComponentByLauncher, eventedShowH
 
     this._handleKeydownListener = this.manage(
       on(this.element.ownerDocument.body, 'keydown', evt => {
-        if (evt.which === 27) {
+        // Avoid running `evt.stopPropagation()` only when modal is shown
+        if (evt.which === 27 && this.shouldStateBeChanged('hidden')) {
```
Comment (emyarod) [inline src/components/modal/modal.js:141]: do we want to use our keyboard event helpers here?

**Review by emyarod — APPROVED** [review]
looks good to me!

File: src/components/modal/modal.js (hunk 1 above)
Comment (asudoh) [reply src/components/modal/modal.js:141]: @emyarod Which helper do you have in mind?

Comment (emyarod) [reply src/components/modal/modal.js:141]: none, I initially thought we had the same helpers as we do in the React repo 😅
