### PR TITLE
fix(DatePicker): date picker month label with "year first" locales

### LINKED ISSUE #21173: [Bug]: Month label in date picker not updating when locale has month after year
### Package

@carbon/react

### Browser

_No response_

### Package version

1.97.0

### React version

_No response_

### Description

With locale that has yeah before month, for example, `lv` or `lt`, when switching between months, month label is not updated.

https://github.com/user-attachments/assets/04001404-d4cc-4089-a209-f31e69cb22f5

### Reproduction/example

https://stackblitz.com/edit/github-hl19uqzb?file=src%2FApp.jsx

### Steps to reproduce

Set DatePicker locale to "lv". Open date picker, select right arrow to go to next month. 

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by fucadzi**
Closes #21173 

Fixes month label update on month change in Date Picker with locales that have years before months (e.g., "lv", "lt").

### Changelog

**Changed**

- fixed inserting month label node inside `flatpickr-current-month` node, not after it.

#### Testing / Reviewing

Set Date Picker locale to "lv" and navigate between months, check if month name changes.

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] ~Updated documentation and storybook examples~
- [ ] ~Wrote passing tests that cover this change~
- [ ] ~Addressed any impact on accessibility (a11y)~
- [ ] ~Tested for cross-browser consistency~
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by fucadzi** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by devadula-nandan — APPROVED** [review]
LGTM, tested and works as expected.

Could u update the contributor file conflict?

found something unrelated to the issue. the locale global control from the storybook toolbar updates to 'ja-JP'
which seems not working as locale prop accepts 'ja' in datepicker
I'm going to update the story to `const locale = useDocumentLang().split('-')[0];` in a separate pr #21401

**Review by emyarod — APPROVED** [review]
looks good to me! just need to resolve the merge conflict

File: packages/react/src/components/DatePicker/DatePicker.tsx [hunk 1]
```diff
@@ -113,7 +113,7 @@ const carbonFlatpickrMonthSelectPlugin = (config) => (fp) => {
         } else {
           fp.yearElements[0]
             .closest(config.selectorFlatpickrMonthYearContainer)
-            .insertAdjacentElement('afterend', monthElement);
+            .insertAdjacentElement('beforeend', monthElement);
```
Comment (adamalston) [inline packages/react/src/components/DatePicker/DatePicker.tsx:113]: Could you add a test for this change? The current locale tests only assert document order, and both `afterend` and `beforeend` satisfy that check, even though only `beforeend` keeps the month label inside `.flatpickr-current-month`.

As is, if someone reverts this change or otherwise introduces a regression, the tests will still pass.

**Review by heloiselui — APPROVED** [review]
