### PR TITLE
fix: added rel prop in switcher item

### LINKED ISSUE #17052: [Bug]: TS error: rel prop does not exist in SwitcherItem type
### Package

@carbon/react

### Browser

Chrome

### Package version

1.62.1

### React version

18.3.1

### Description

Two nearly identical errors were fixed (#15510 and #16294) for this component for two other props, and once again another anchor prop, `rel`, is now flagging as a TypeScript compile-time error (it wasn't in Carbon 1.56). 

image

### Reproduction/example

Any .tsx file that uses the rel attr with SwitcherItem will show this, no working example needed (compile-time issue, not run-time)

### Steps to reproduce

Any .tsx file that uses the rel attr with SwitcherItem will show this, no working example needed (compile-time issue, not run-time)

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Application/PAL

CDD Hub

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by riddhybansal**
Closes #17052 

Added optional 'rel' prop to `BaseSwitcherItemProps`.

**New**
Added rel prop to `BaseSwitcherItemProps`

#### Testing / Reviewing
```tsx
<Switcher aria-label="Switcher Container" expanded={true}>
  <SwitcherItem aria-label="Link 1" href="#" rel="norelerror">
    Link 1
  </SwitcherItem>
</Switcher>
```

Test the usage of `SwitcherItem` with the `rel` prop in a TypeScript environment within a `Switcher` component. Verify that the  TypeScript compiler should not throw error and the component renders without errors and correctly applies the provided `rel` attribute

### CODE REVIEW

File: packages/react/src/components/UIShell/SwitcherItem.tsx [hunk 1]
```diff
@@ -58,6 +58,10 @@ interface BaseSwitcherItemProps {
    * Specify where to open the link.
    */
   target?: HTMLAttributeAnchorTarget;
+  /**
+   * The rel property for the link.
+   */
+  rel?: string;
```
Comment (tay1orjones) [inline packages/react/src/components/UIShell/SwitcherItem.tsx:64]: Is there a specific type off of HTMLAttributes or DOMAttributes or something that we could use here? It's not any string - it's one of a specific set of allowed/expected strings, right?

[MDN's list](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel) is "some of the most important existing keywords" 🤔 very possible this doesn't exist but figured I'd ask

**Review by tay1orjones — APPROVED** [review]
Looks good! Just one question

**Review by alisonjoseph — APPROVED** [review]

File: packages/react/src/components/UIShell/SwitcherItem.tsx (hunk 1 above)
Comment (riddhybansal) [reply packages/react/src/components/UIShell/SwitcherItem.tsx:64]: Yes we cannot add any string there are some specific keywords that can be used . What do you think should I create an interface and made rel at that type ??
