### PR TITLE
fix( radio-tile, selectable-tile): deprecates iconDescription and adds handleOnChange function

### LINKED ISSUE #3474: AVT 2 & 3 - React MultiSelect and Selectable Tile  - can not use the keyboard only to select or deselect a checkbox.
## Environment
Windows 10 
FireFox Quantum 68.0
JAWS 18

macOS 10.15.1
Chrome Version 78.0.3904.108 (Official Build) (64-bit)
VoiceOver

## Description
1. Tab to the MultiSelect Tile
2. Press Space bar to select a Tile, JAWS announces the checkbox but it can not be checked. 
**Expected Result:** User should be able to check 1 or more checkboxes.

Note: keyboard navigation fails with and without the use of a screen reader.

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #3474 

This was done during mob programming with @aledavila and @joshblack.

This PR adds a `handleOnChange` to the SelectableTile so that the tiles are selectable with Jaws and VO. It changes the name of the "Selectable Tile" story to "Radio" since the example uses `RadioTile` and causes confusion with the MultiSelect story that does use the `SelectableTile`. It also deprecates `iconDescription` for `SelectableTile` and `RadioTile`  and removes its implementation. The `CheckmarkFilled` icon is purely for decoration and removing the iconDescription allows it to be ignored by screenreaders. This PR also converts `RadioTile` to a functional component instead of a class. 

#### Changelog

**New**

- `handleOnChange` function for `SelectableTile`

**Changed**

- `RadioTile` to function
- Selectable Tile story changed to Radio Tile story 

**Removed**

- `iconDescription` deprecated for RadioTile and SelectableTile 

#### Testing / Reviewing

Verify that with VO and Jaws that you can check and uncheck all of the selectable tiles and generally check to make sure everything is still working as expected.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

File: packages/react/src/components/Tile/Tile.js [hunk 1]
```diff
@@ -297,10 +306,12 @@ export class SelectableTile extends Component {
       value,
       name,
       title,
+      // eslint-disable-next-line no-unused-vars
```
Comment (asudoh) [inline packages/react/src/components/Tile/Tile.js:309]: Instead of ignoring `no-unused-vars` here, we can safely remove `iconDescription` here?

**Review by asudoh — COMMENTED** [review]
LGTM basically, just one thing - Thanks @abbeyhrt!

**Review by aledavila — APPROVED** [review]
🎉

File: packages/react/src/components/Tile/Tile.js (hunk 1 above)
Comment (abbeyhrt) [reply packages/react/src/components/Tile/Tile.js:309]: I tried that but it seemed to cause this warning to pop up if iconDescription is defined:
Screen Shot 2020-01-08 at 10 34 17 AM
Seems like if folks are still using `iconDescription` the prop will be spread onto `...other` and cause the warning?

Comment (asudoh) [reply packages/react/src/components/Tile/Tile.js:309]: Though this has been merged already - You are right. I don't see it's a problem, though, given it's a React warning that doesn't prevent user applications from working, and they can simply remove `iconDescription` to get rid of the warning.
