### PR TITLE
fix: type fix for onActionButtonClick in Notification component #19986

### LINKED ISSUE #19986: [Bug]: Incorrect type for ActionableNotification `onActionButtonClick` event. In type it is not expecting any arguments. but click event values are there
### Package

@carbon/react

### Browser

_No response_

### Package version

1.69.0

### React version

17

### Description

Incorrect type for ActionableNotification `onActionButtonClick` event. In type it is not expecting any arguments. but click event values are there. 

Both [here](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Notification/Notification.tsx#L1072) and [here](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Notification/Notification.tsx#L111) have click events arguments
But in [type definition ](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Notification/Notification.tsx#L1268) it is not added.

### Reproduction/example

just a type error. 

### Steps to reproduce

Both [here](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Notification/Notification.tsx#L1072) and [here](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Notification/Notification.tsx#L111) have click events arguments
But in [type definition ](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Notification/Notification.tsx#L1268) it is not added.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by sojinantony01**
Closes #19986

 type fix for `onActionButtonClick` in Notification component - #19986 

### Changelog

**New**

- onActionButtonClick argument type added

**Changed**

- onActionButtonClick argument type added

**Removed**

- nill

#### Testing / Reviewing

onClick mouse event is present in onActionButtonClick argument of `ActionableNotification` component

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by sojinantony01** [comment]
@tay1orjones This a small PR fixing typescript errors in a function. please  have alook

**Comment by sojinantony01** [comment]
@riddhybansal @tay1orjones, Small PR. please review this one

File: packages/react/src/components/Notification/Notification.tsx
Comment (adamalston) [inline packages/react/src/components/Notification/Notification.tsx:1]: Should we derive these types from the existing prop types in the source components to keep a single source of truth? That way if `Button` or `NotificationActionButton` ever change in a way TypeScript doesn't approve of, we’ll get a type error.

```diff
diff --git a/packages/react/src/components/Notification/Notification.tsx b/packages/react/src/components/Notification/Notification.tsx
index 84be02932..24b4ead31 100644
--- a/packages/react/src/components/Notification/Notification.tsx
+++ b/packages/react/src/components/Notification/Notification.tsx
@@ -14,6 +14,7 @@ import React, {
   useEffect,
   useRef,
   useState,
+  type ComponentProps,
 } from 'react';
 import { deprecate } from '../../prop-types/deprecate';
 import cx from 'classnames';
@@ -89,7 +90,7 @@ export interface NotificationActionButtonProps extends ButtonProps<'button'> {
   /**
    * Optionally specify a click handler for the notification action button.
    */
-  onClick?(event: MouseEvent): void;
+  onClick?: ComponentProps<typeof Button>['onClick'];
 }
 
 export function NotificationActionButton({
@@ -881,7 +882,9 @@ export interface ActionableNotificationProps
   /**
    * Provide a function that is called when the action is clicked
    */
-  onActionButtonClick?(event: MouseEvent): void;
+  onActionButtonClick?: ComponentProps<
+    typeof NotificationActionButton
+  >['onClick'];
 
   /**
    * Provide a function that is called when menu is closed.
@@ -1283,7 +1286,9 @@ export interface CalloutProps extends HTMLAttributes<HTMLDivElement> {
   /**
    * Provide a function that is called when the action is clicked
    */
-  onActionButtonClick?(event: MouseEvent): void;
+  onActionButtonClick?: ComponentProps<
+    typeof NotificationActionButton
+  >['onClick'];
 
   /**
    * Provide a description for "status" icon that can be read by screen readers
```

File: packages/react/src/components/Notification/__tests__/Notification-test.js [hunk 1]
```diff
@@ -397,6 +397,8 @@ describe('Callout', () => {
     });
     await userEvent.click(closeButton);
     expect(onActionButtonClick).toHaveBeenCalledTimes(1);
+    expect(onActionButtonClick).toHaveBeenCalledWith(expect.any(Object));
+    expect(onActionButtonClick.mock.calls[0][0].type).toBe('click');
```
Comment (adamalston) [inline packages/react/src/components/Notification/__tests__/Notification-test.js]: These three assertions can be reduced to a single assertion:

```js
expect(onActionButtonClick.mock.calls).toEqual([
  [expect.objectContaining({ type: 'click' })],
]);
```

However, I think the `toHaveBeenCalledTimes` check should be kept for consistency with the other tests. With that, the final two assertions can be consolidated to improve accuracy, avoiding `expect.any(Object)`:

```suggestion
    expect(onActionButtonClick).toHaveBeenCalledTimes(1);
    expect(onActionButtonClick.mock.calls).toEqual([
      [expect.objectContaining({ type: 'click' })],
    ]);
```

File: packages/react/src/components/Notification/Notification.tsx
Comment (sojinantony01) [reply packages/react/src/components/Notification/Notification.tsx:1]: That looks really good. Thanks @adamalston 
Updated

File: packages/react/src/components/Notification/__tests__/Notification-test.js (hunk 1 above)
Comment (sojinantony01) [reply packages/react/src/components/Notification/__tests__/Notification-test.js]: Sure. Updated

**Review by adamalston — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]
Thank you!

**Review by kennylam — APPROVED** [review]
