### PR TITLE
fix(React): remove deprecated v11 props

### LINKED ISSUE #8418: Remove deprecated code from React package
Part of #8410 

This is an issue to track the effort to remove deprecated code from the React codebase

- Remove props that have been marked as deprecated
- Remove deprecated components
- Remove any code noted for removal for next major release

### LINKED ISSUE #11082: [Bug]: incorrect prop types provided by getToolbarProps for v11
### Package

@carbon/react

### Browser

Chrome

### Package version

0.17.0

### React version

17.0.2

### Description

The render function `getToolbarProps()` from `DataTable` is providing incorrect prop types for v11. The function is defined at 
https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/DataTable/DataTable.js#L385 and is returning a size of `small` but for v11 the prop is expecting `sm` https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/DataTable/TableToolbar.js#L43

### CodeSandbox example

n/a

### Steps to reproduce

Use a datatable with a toolbar

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by dakahn**
Closes https://github.com/carbon-design-system/carbon/issues/11082

Remove deprecated in v11 props from the following files:

partially closes #8418 

- [x] `Accordion/Accordion.Skeleton.js`
- [x] `Accordion/AccordionItem.js`
- [x] `Button/Button.js`
- [x] `Checkbox/Checkbox.js`
- [x] `ContentSwitcher/ContentSwitcher.js`
- [x] `DataTable/Table.js`
- [x] `DataTable/TableExpandHeader.js`
- [x] `DataTable/TableToolbarSearch.js`
- [ ] `DatePickerInput/DatePickerInput.js`
- [x] `DatePickerInput/next/DatePickerInput.js`
- [x] `Dropdown/Dropdown.js`
- [x] `Dropdown/Dropdown.Skeleton.js`
- [x] `InlineLoading/InlineLoading.js`
- [ ] `Modal/Modal.js`
- [x] `Modal/next/Modal.js`

### CODE REVIEW

**Comment by dakahn** [comment]
Didn't touch datepickerinput and modal (designated that above) because as per the instructions they had corresponding /next files 👍🏾

File: packages/react/src/components/DatePickerInput/next/DatePickerInput.js [hunk 1]
```diff
@@ -68,7 +67,7 @@ const DatePickerInput = React.forwardRef(function DatePickerInput(props, ref) {
     [`${prefix}--date-picker--nolabel`]: !labelText,
   });
 
-  const { openCalendar, iconDescription, ...other } = { ...rest };
+  const { ...other } = { ...rest };
```
Comment (joshblack) [inline packages/react/src/components/DatePickerInput/next/DatePickerInput.js]: I think this can just be `rest` now? The assignment pattern looks so funny now lol. Definitely an odd one when quickly getting rid of deprecated code

**Review by joshblack — APPROVED** [review]
Looking good, just left a refactor note

**Comment by joshblack** [comment]
@dakahn @tay1orjones one thing I noticed is that the VRT for button changed. Is this the correct change for the size prop updates?

File: packages/react/src/components/DatePickerInput/next/DatePickerInput.js (hunk 1 above)
Comment (dakahn) [reply packages/react/src/components/DatePickerInput/next/DatePickerInput.js]: lol! my bad. made a mental todo to refactor that as ...rest in the render.

File: packages/react/src/components/Accordion/AccordionItem.js [hunk 2]
```diff
@@ -141,15 +126,6 @@ AccordionItem.propTypes = {
    */
   open: PropTypes.bool,
 
-  /**
-   * The callback function to render the expand button.
-   * Can be a React component class.
-   */
-  renderExpando: deprecate(
```
Comment (jnm2377) [inline packages/react/src/components/Accordion/AccordionItem.js]: I thought this was one of the props that we deprecated as part of v11? I recall Ale and Scott working on this, I think.

File: packages/react/src/components/Checkbox/Checkbox.js [hunk 3]
```diff
@@ -127,14 +117,6 @@ Checkbox.propTypes = {
    * Specify a title for the <label> node for the Checkbox
    */
   title: PropTypes.string,
-
-  /**
-   * The CSS class name to be placed on the wrapping element
-   */
-  wrapperClassName: deprecate(
```
Comment (jnm2377) [inline packages/react/src/components/Checkbox/Checkbox.js:134]: If we deprecated this for v11, should it stay until v12?

File: packages/react/src/components/DataTable/TableExpandHeader.js [hunk 4]
```diff
@@ -57,23 +55,12 @@ TableExpandHeader.propTypes = {
...
+  ariaLabel: requiredIfGivenPropIsTruthy('enableToggle', PropTypes.string),
 
   children: PropTypes.node,
 
   className: PropTypes.string,
 
-  /**
-   * The enableExpando prop is being replaced by enableToggle
-   */
-  enableExpando: deprecate(
```
Comment (jnm2377) [inline packages/react/src/components/DataTable/TableExpandHeader.js]: I think this was also deprecated as part of v11 changes. https://github.com/carbon-design-system/carbon/issues/10317

**Comment by tay1orjones** [comment]
@joshblack @dakahn my guess is that the vrt test needs to be updated to use the correct/new `size` prop values

File: packages/react/src/components/Accordion/AccordionItem.js (hunk 2 above)
Comment (dakahn) [reply packages/react/src/components/Accordion/AccordionItem.js]: Good catch. I'll roll these back.

**Review by tay1orjones — APPROVED** [review]
