### PR TITLE
fix(popover): keep popover open when selecting a date from datepicker

### LINKED ISSUE #21690: Popover getting closed while selecting a date from DatePicker
In the recent versions, when I use a DatePicker inside a Popover, the popover closes whenever I click to select a date. It seems that onRequestClose is being triggered on date selection.

[Stackblitz reproduction](https://stackblitz.com/edit/bcmgxmqs?file=src%2FApp.jsx)

### PR DESCRIPTION
**Pull request by nehaaprasad**
Closes #21690

Fix `Popover` so selecting a date from a `DatePicker` rendered in `document.body` does not trigger `onRequestClose` when that calendar belongs to an input inside the popover.

### Changelog

**New**

- Added regression tests for DatePicker calendar interactions inside `Popover`, including click and focusout behavior.

**Changed**

- Updated `Popover` close logic to ignore outside click/focus transitions when the target is a `.flatpickr-calendar` associated with an input inside the current popover.
- Kept normal close behavior for calendars not associated with inputs inside this popover.
- Improved typing/narrowing around `_flatpickr` lookup in Popover internals.

**Removed**

- ~None~

#### Testing / Reviewing

[ ] Open Popover with DatePicker inside
[ ] Open calendar and select a date
[ ] Confirm Popover stays open
[ ] Confirm Popover still closes on outside click
[ ] Run Popover tests and ensure they pass

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- ~[ ] Updated documentation and storybook examples~
- [X] Wrote passing tests that cover this change
- ~[ ] Addressed any impact on accessibility (a11y)~
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/react/src/components/Popover/index.tsx [hunk 1]
```diff
@@ -200,6 +200,19 @@ export const Popover: PopoverComponent & {
...
   const lastClickWasInsidePopoverContent = useRef(false);
 
+  const isTargetInDatePickerInsidePopover = (target: Node | null) => {
+    if (!target || !popover.current) return false;
+    const calendar =
+      target instanceof Element && target.closest?.('.flatpickr-calendar');
+    if (!calendar) return false;
+    const inputs = popover.current.querySelectorAll('input');
+    for (const input of inputs) {
+      const fp = (input as HTMLInputElement & { _flatpickr?: { calendarContainer: Element } })._flatpickr;
```
Comment (adamalston) [inline packages/react/src/components/Popover/index.tsx]: I don't think the type assertion is necesary. `input` and `calendar` are typed. You should be able to use comparisons between the two to check whether the calendar container is the calendar.

File: packages/react/src/components/Popover/index.tsx [hunk 2]
```diff
@@ -200,6 +200,19 @@ export const Popover: PopoverComponent & {
     useFeatureFlag('enable-v12-dynamic-floating-styles') || autoAlign;
   const lastClickWasInsidePopoverContent = useRef(false);
 
+  const isTargetInDatePickerInsidePopover = (target: Node | null) => {
+    if (!target || !popover.current) return false;
```
Comment (adamalston) [inline packages/react/src/components/Popover/index.tsx]: I don't see any call sites passing `null` to this function. Is there a case where `target` can be `null` in this function's usage? If not:

1. Could the parameter type be narrowed to `Node`?
2. Could the `!target` check be deleted?

File: packages/react/src/components/Popover/__tests__/Popover-test.js [hunk 3]
```diff
@@ -436,4 +436,37 @@ describe('Popover', () => {
...
+    Object.defineProperty(input, '_flatpickr', {
+      value: { calendarContainer: calendar },
+      configurable: true,
+    });
+
+    await userEvent.click(calendar.querySelector('.flatpickr-day'));
+
+    expect(onRequestClose).not.toHaveBeenCalled();
+
+    document.body.removeChild(calendar);
```
Comment (adamalston) [inline packages/react/src/components/Popover/__tests__/Popover-test.js]: If the test fails before this cleanup step, will the calendar element stay on `document.body`? If so, should that change to avoid impacting other tests?

File: packages/react/src/components/Popover/__tests__/Popover-test.js
Comment (adamalston) [inline packages/react/src/components/Popover/__tests__/Popover-test.js:1]: A couple of follow-ups on coverage:

1. The exception is now in both the `click` and `focusout` paths, but I only see a `click` test. Could the `focusout` case be covered as well?
2. Could a negative case be added to verify that the popover still closes when clicking a `.flatpickr-calendar` that is not associated with an input inside this popover?

**Comment by nehaaprasad** [comment]
@adamalston i have updated it, please check it out!

**Comment by adamalston** [comment]
https://github.com/carbon-design-system/carbon/pull/21874#issuecomment-4103788884

**Review by sangeethababu9223 — COMMENTED** [review]
Hey @nehaaprasad ,
Please update the PR description to match the standard PR template.
Also ci check for format is failing, you could solve it by running `yarn format` in local and pushing the changes to the PR.

**Comment by heloiselui** [comment]
Hey @sangeethababu9223, @devadula-nandan and @adamalston , when you have a moment, could you take a look at this PR? I’ve updated the remaining items.

File: packages/react/src/components/Popover/index.tsx [hunk 4]
```diff
@@ -200,6 +200,27 @@ export const Popover: PopoverComponent & {
     useFeatureFlag('enable-v12-dynamic-floating-styles') || autoAlign;
   const lastClickWasInsidePopoverContent = useRef(false);
 
+  const isTargetInDatePickerInsidePopover = (target: Node) => {
+    if (!popover.current) return false;
+    const calendar =
+      target instanceof Element && target.closest?.('.flatpickr-calendar');
```
Comment (adamalston) [inline packages/react/src/components/Popover/index.tsx]: What's the optional chaining operator for?

File: packages/react/src/components/Popover/index.tsx [hunk 5]
```diff
@@ -200,6 +200,27 @@ export const Popover: PopoverComponent & {
...
+        fp &&
+        typeof fp === 'object' &&
+        'calendarContainer' in fp &&
+        fp.calendarContainer === calendar
+      ) {
+        return true;
+      }
+    }
+    return false;
+  };
```
Comment (adamalston) [inline packages/react/src/components/Popover/index.tsx:225]: I've been wondering whether there's a more robust, cross-component approach, such as shared refs or a stable marker, that would avoid relying on `_flatpickr`. Have you explored any alternatives? I'm a bit concerned about the use of `closest`.

If not, no worries.

File: packages/react/src/components/Popover/index.tsx (hunk 4 above)
Comment (heloiselui) [reply packages/react/src/components/Popover/index.tsx]: Not necessary, just updated.

File: packages/react/src/components/Popover/index.tsx (hunk 5 above)
Comment (heloiselui) [reply packages/react/src/components/Popover/index.tsx:225]: I think it’s worth exploring this more. I added a TODO for us to look for a better solution.

**Review by adamalston — APPROVED** [review]

**Review by devadula-nandan — APPROVED** [review]
