### PR TITLE
fix(ProgressIndicator): prevent `current` from overriding `invalid`

### LINKED ISSUE #3558: Progress Indicator current overrides invalid
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The `ProgressIndicator` component overrides the `invalid` prop on a step if that step is at `currentIndex`. This means there is no good way to display a failed/invalid step once that index is reached (without using `progressStep` outside of the `progressIndicator` component and controlling each step manually).

> Is this issue related to a specific component?

The `ProgressIndicator` component, specifically its control of `ProgressStep` children.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected there to be an indication of a step being invalid even if that step is current, similar to how a step can be disabled even if it is current. I think ideally the icon of the step would be changed to invalid if that property is true, regardless of `current`. The indicator bar above the step could stay highlighted, possibly in red instead of blue, to reinforce that the step is indeed current.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

In development I use `carbon-components-react 7.2` and `carbon-components 10.2`, but demonstrate the same functionality as described above in a codesandbox with the current 7.4 and 10.4 versions.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

An internal IBM team/product, no pressing release dates.

## Steps to reproduce the issue

1. Create a `ProgressIndicator` with at least 2 `ProgressStep` children
2. Set `currentIndex={1}` on the indicator
3. Set `invalid` on the second (index 1) step
4. Note that there is no indication the step is invalid as the `current` prop set by `currentIndex` overrides it visually

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/carbon-components-react-liw7c

## Additional information/Notes

It might be worth talking about allowing developers to fully control each step by setting complete, invalid, current, and disabled themselves. This can currently be done by using `ProgressStep`s without a `ProgressIndicator` parent (as the `complete` prop set by a dev is ignored if in an indicator parent) but at the cost of losing or manually replicating the styles provided by the indicator.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3558

This PR modifies the SVG icon selection logic to display the correct icon based on progress step state. If the step is disabled, the disabled icon will be used, and if the step is invalid, the invalid icon will be used. Otherwise, the current, complete, and incomplete icons will be used depending on the progress step state

#### Testing / Reviewing

Ensure the correct icon is displayed for each progress step state

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
LGTM 👍

**Review by dakahn — APPROVED** [review]
Nice!

File: packages/react/src/components/ProgressIndicator/ProgressIndicator.js [hunk 1]
```diff
@@ -43,36 +43,36 @@ export const ProgressStep = ({ ...props }) => {
...
-  const completeSvg = complete && (
-    <CheckmarkOutline16 aria-label={description} role="img">
-      <title>{description}</title>
-    </CheckmarkOutline16>
-  );
-  const incompleteSvg = (() => {
-    if (complete) {
-      return null;
-    }
+  const SVGIcon = () => {
```
Comment (asudoh) [inline packages/react/src/components/ProgressIndicator/ProgressIndicator.js]: Given you made this React component, would you want to remove closure ref dependency? e.g. Making `invalid`/`description`, etc. React props for this component.

**Review by asudoh — COMMENTED** [review]
Nice change @emyarod!

File: packages/react/src/components/ProgressIndicator/ProgressIndicator.js [hunk 2]
```diff
@@ -43,36 +43,36 @@ export const ProgressStep = ({ ...props }) => {
...
     if (invalid) {
       return (
         <Warning16 className={`${prefix}--progress__warning`}>
           <title>{description}</title>
         </Warning16>
       );
     }
+    if (current) {
+      return (
+        <svg>
```
Comment (joshblack) [inline packages/react/src/components/ProgressIndicator/ProgressIndicator.js:52]: Where's this SVG asset coming from?

File: packages/react/src/components/ProgressIndicator/ProgressIndicator.js [hunk 3]
```diff
@@ -43,36 +43,36 @@ export const ProgressStep = ({ ...props }) => {
...
+          <path d="M 7, 7 m -7, 0 a 7,7 0 1,0 14,0 a 7,7 0 1,0 -14,0" />
+          <title>{description}</title>
+        </svg>
+      );
+    }
+    if (complete) {
+      return (
+        <CheckmarkOutline16 aria-label={description} role="img">
```
Comment (joshblack) [inline packages/react/src/components/ProgressIndicator/ProgressIndicator.js]: Do we need `aria-label` and `title` present?

**Review by joshblack — DISMISSED** [review]
Left some comments/questions! Also +1 to the closure comment from @asudoh

File: packages/react/src/components/ProgressIndicator/ProgressIndicator.js (hunk 3 above)
Comment (emyarod) [reply packages/react/src/components/ProgressIndicator/ProgressIndicator.js]: this is carried over from the existing code, probably before carbon-icons was fleshed out

File: packages/react/src/components/ProgressIndicator/ProgressIndicator.js (hunk 2 above)
Comment (emyarod) [reply packages/react/src/components/ProgressIndicator/ProgressIndicator.js:52]: this is carried over from the existing code

File: packages/react/src/components/ProgressIndicator/ProgressIndicator.js (hunk 3 above)
Comment (emyarod) [reply packages/react/src/components/ProgressIndicator/ProgressIndicator.js]: there's a check for `title` in our test suite so not sure if we want to remove that test as well https://github.com/emyarod/carbon/commit/c59c31609db18eeb55ddd004786aba016dd2a150#diff-583a08c2cda913c3c66233d6428595f3R72-R76

**Review by jeanservaas — APPROVED** [review]
LGTM

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

File: packages/react/src/components/ProgressIndicator/ProgressIndicator.js (hunk 2 above)
Comment (joshblack) [reply packages/react/src/components/ProgressIndicator/ProgressIndicator.js:52]: @emyarod is this to say that we're unable to address this in this PR?

Comment (emyarod) [reply packages/react/src/components/ProgressIndicator/ProgressIndicator.js:52]: @joshblack this is to say unless there is an existing icon we can substitute here the net new icon design work can be done separately from this PR

Comment (joshblack) [reply packages/react/src/components/ProgressIndicator/ProgressIndicator.js:52]: @emyarod totally fair! Just was curious where it came from and if we could substitute it with an official one.

@laurenmrice do you know if the icon for the "current" step of progress indicator is one from our library or is it cool if it's a custom one here?

**Comment by joshblack** [comment]
Should we have waited for Lauren to respond in: https://github.com/carbon-design-system/carbon/pull/3640#discussion_r311628070 ?

**Comment by asudoh** [comment]
My apologies, the comments were kind hidden in history pile. If you have any remaining comments in this kind of case, great if you can state it in the main history so we can track the latest. Thanks!

File: packages/react/src/components/ProgressIndicator/ProgressIndicator.js (hunk 2 above)
Comment (laurenmrice) [reply packages/react/src/components/ProgressIndicator/ProgressIndicator.js:52]: @joshblack sorry for late response, current step icon used to use the radio-button--filled-16 but i don't think this exists anymore in our new icon library, it will have to be custom. It should use `interactive-04` token.

Comment (emyarod) [reply packages/react/src/components/ProgressIndicator/ProgressIndicator.js:52]: @laurenmrice just checking, is radio-button--filled the same as radio-button--checked? I don't see a radio-button--filled in the list of icons

Comment (laurenmrice) [reply packages/react/src/components/ProgressIndicator/ProgressIndicator.js:52]: @emyarod no the filled we used to have was a solid colored circle. It no longer exists in our current library so it will need to be custom
