### PR TITLE
fix: indeterminate state recalculation logic fixed for select all

### LINKED ISSUE #19066: [Bug]: MultiSelect "select all" does not respond to changes in `items`
### Package

@carbon/react

### Browser

Chrome

### Package version

11.79.0

### React version

19

### Description

When using the isSelectAll feature of multiselect, if `items` changes, the select all option is not updated to reflect the new status of selection.

### Reproduction/example

https://stackblitz.com/edit/github-of49kbjd?file=src%2FApp.jsx

### Steps to reproduce

1. Open the multiselect and click the `All roles` option
2. Click the button to add two new items to the list
3. Open the MultiSelect and you can see the issue - `All roles` is still selected, but not all items are selected. The two new ones are in there, unselected.

In this situation I would expect the `All roles` option to change to the indeterminate state with the `-`. This way we're not automatically selecting items as they're added to the list without the user knowing. They'd need to go into the MultiSelect again and re-choose `All roles`.

#### Workaround

Consumers can't get around this by using "fully controlled" `selectedItems` because that isn't supported with the select all feature.

They might be able to work around this by setting `initialSelectedItems` and then resetting the component by placing a `key` prop and changing the value when items are added to the list. ...maybe 🤔 - I didn't confirm this, but even if it works it's incredibly cumbersome.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Gururajj77**
Closes #19066

Enhanced the recalculation logic to determine the indeterminate state. 

#### Changelog

**New**

- test case to make sure this functionality doesn't break in the future.

**Changed**

The improved isIndeterminate logic precisely identifies when a "Select All" checkbox should appear partially selected by comparing:

- Is this the "Select All" checkbox? (item['isSelectAll'])
- Are any regular items selected? (selectedItems.some(selected => !selected.isSelectAll))
- Are some but not all selectable items chosen

#### Testing / Reviewing

- in the deploy preview, go to the test story "Select All With Dynamic Items"
- Open the dropdown
- Click on "All roles", which selects all the items which are eligible for selection.
- Close the dropdown and open it, note that the checkbox associated with "All roles" is having a "Tick" (☑️).
- There is button with the name "Add 2 items to the list", which adds 2 new items to the items list.
- Open the dropdown, verify the checkbox associated with "All roles" is having the Indeterminate state icon (⁻), showing that the list is partially selected.
- once reviewed by 2 devs, delete this story before merging.

### CODE REVIEW

**Review by heloiselui — APPROVED** [review]
Looks awesome! 🚀

File: packages/react/src/components/MultiSelect/MultiSelect.tsx [hunk 1]
```diff
@@ -822,9 +822,15 @@ const MultiSelect = React.forwardRef(
...
                   item['isSelectAll'] &&
-                  !isChecked;
+                  selectedItems.some(
+                    (selected: any) => !selected.isSelectAll
+                  ) &&
+                  selectedItems.filter((selected: any) => !selected.isSelectAll)
+                    .length <
+                    filteredItems.filter(
+                      (item: any) => !item.isSelectAll && !item.disabled
+                    ).length;
```
Comment (adamalston) [inline packages/react/src/components/MultiSelect/MultiSelect.tsx]: Performance suggestion to move any logic that doesn’t depend on the `map` iteration outside of it, so it doesn’t get re-evaluated each time.

**Review by heloiselui — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Comment by alisonjoseph** [comment]
Ready to merge once test story is removed @Gururajj77
