### PR TITLE
fix(select): use title prop for tooltip instead of first SelectItem

### LINKED ISSUE #20582: [Bug]: <Select> uses first <SelectItem> value as tooltip instead of respecting title prop Description
### Package

@carbon/react

### Browser

Chrome

### Package version

last

### React version

_No response_

### Description

When rendering a Carbon `<Select>`, the browser tooltip on the native `<select>` element shows the value of the first `<SelectItem>` instead of the selected or even the title prop passed to `<Select>`.

**Expected behavior**

If a initial value is set, it should be displaying the value of the selected item as tooltip.
If a title prop is provided, it should be forwarded to the native `<Select>` element and used as the tooltip.

**Actual behavior**

The tooltip shows the initial option’s value (first `<SelectItem>`) rather than the intended title or initial value.

### Reproduction/example

https://stackblitz.com/edit/github-vfphhms5?file=src%2FApp.tsx

### Steps to reproduce

Render the component the link above.

Hover over the component.

Tooltip shows "Monday" (the first option) instead of "Tooltip test".
Tooltip shows "Monday" (the first option) instead of "Tuesday" (selected value - supposed value when removing the title)

Setting value 2 as initial value -> initial tooltip shows "Monday" instead of "Tuesday"

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Vignesh-Loganathan-IBM-1**
Closes #20582

Fixed Select component to properly handle value prop for tooltips, ensuring correct display of selected option text when using controlled components and  use title prop for tooltip instead of first SelectItem

### Changelog

**Changed**

Tooltip now correctly uses the `title` prop when provided, or falls back to the selected item's label. Previously, the tooltip incorrectly defaulted to the first `SelectItem` value regardless of selection or props. This fix improves accessibility and user experience when using the component in controlled mode.

#### Testing / Reviewing

- [x] Rendered the Select component with value and title props; verified tooltip shows the title or selected value correctly and no longer shows the first SelectItem value.
 
## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by Vignesh-Loganathan-IBM-1** [comment]
I have read the DCO document and I hereby sign the DCO.

File: packages/react/src/components/Select/Select.tsx [hunk 1]
```diff
@@ -471,3 +476,5 @@ Select.propTypes = {
 };
 
 export default Select;
+
+// Made with Bob
```
Comment (tay1orjones) [inline packages/react/src/components/Select/Select.tsx]:
```suggestion
```

**Review by tay1orjones — CHANGES_REQUESTED** [review]

**Review by tay1orjones — APPROVED** [review]
LGTM

**Review by maradwan26 — APPROVED** [review]
LGTM
