### PR TITLE
fix(ui-shell): improve header global action a11y

### LINKED ISSUE #19374: [a11y]: UI Shell right panel does not close on loss of focus
Continuation of #19289, for the web-components version. 

Refer the above issue for more clarity.

### PR DESCRIPTION
**Pull request by heloiselui**
Closes #19374  

Continuation of #19289, that improves the behavior of `header-global-action` so the right panel now closes when focus is lost, and can also be toggled using Enter or Space. It also brings it in line with how the React version works.

### Changelog

**New**

- Added support for toggling the panel using `Enter` and `Space` keys.
- Added `focusout` and `document.click` handlers to close the panel when focus is lost or the user clicks outside.

**Changed**

- Used `@HostListener` for `keydown` to match the keyboard interaction.
- Used `ownerDocument` instead of `document` to make sure the panel is found even inside Shadow DOM. 

#### Testing / Reviewing

- Go to `Web Components Deploy Preview` > `Header w/ Actions and Right Panel`.
- Click or press `**Enter or Space**` on the `**Notifications**` button:
  - It should open the right panel.
  - Press `**Enter or Space**` again to close it.
- Click or tab away from the button/panel:
  - The panel should close automatically.

I used this as reference:
- https://lit.dev/docs/components/shadow-dom/
- https://web.dev/articles/shadowdom-v1
- https://developer.mozilla.org/en-US/docs/Web/API/Node/ownerDocument

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff  
- ~[N/A] Updated documentation and storybook examples~
- ~[N/A] Wrote passing tests that cover this change~
- [x] Addressed any impact on accessibility (a11y)  
- [x] Tested for cross-browser consistency  
- [x] Validated that this code is ready for review and status checks should pass  

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by Gururajj77 — APPROVED** [review]
Looks good

**Review by maradwan26 — APPROVED** [review]
LGTM !

File: packages/web-components/src/components/ui-shell/header-global-action.ts [hunk 1]
```diff
@@ -85,6 +121,16 @@ class CDSHeaderGlobalAction extends CDSButton {
...
   }
 
+  @HostListener('keydown', { capture: true })
+  // @ts-ignore
+  private _handleKeyDown(event: KeyboardEvent) {
+    const { key } = event;
+    if (key === 'Enter' || key === ' ') {
+      event.preventDefault();
+      this._handleClick(event);
+    }
```
Comment (ariellalgilmore) [inline packages/web-components/src/components/ui-shell/header-global-action.ts:137]: I think we also need to check for "Esc" and make sure it closes then

**Review by ariellalgilmore — COMMENTED** [review]
looks good!! just one small comment

**Review by ariellalgilmore — APPROVED** [review]

**Review by riddhybansal — APPROVED** [review]
