### PR TITLE
fix(overflowmenu): added typing to align prop

### LINKED ISSUE #18957: [Bug]: The `OverflowMenu` `align` prop isn't typed
### Package

@carbon/react

### Browser

_No response_

### Package version

1.79.0

### React version

_No response_

### Description

The `OverflowMenu` `align` prop isn't typed even though it's used the code in https://react.carbondesignsystem.com/?path=/docs/components-overflowmenu--overview#customizing-the-tooltip.

### Reproduction/example

https://stackblitz.com/edit/github-zwvqaxgz?file=src%2FApp.tsx

### Steps to reproduce

See type error in reproduction.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

DataPower

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by jose-biescas**
Closes #18957 

Adds a type to the `align` prop in `OverflowMenu`

#### Changelog

**New**

- Added `align` property

#### Testing / Reviewing

Go to the `Default` storybook for `OverflowMenu` and the `align` property can be controlled via a dropdown with allowed prop values

### CODE REVIEW

**Comment by jose-biescas** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by jose-biescas** [comment]
recheck

File: packages/react/src/components/OverflowMenu/OverflowMenu.tsx [hunk 1]
```diff
@@ -120,7 +121,59 @@ export const getMenuOffset: MenuOffset = (
...
+    'right-bottom': 'right-end',
+    'right-top': 'right-start',
+  };
+  return mapping[deprecatedValue];
+};
+
+type IconProps = {
+  className?: string;
+  'aria-label'?: string;
+};
```
Comment (adamalston) [inline packages/react/src/components/OverflowMenu/OverflowMenu.tsx]: What's this `type` for?

Comment (tay1orjones) [inline packages/react/src/components/OverflowMenu/OverflowMenu.tsx]: Is this needed?
```suggestion
```

File: packages/react/src/components/OverflowMenu/OverflowMenu.stories.js [hunk 2]
```diff
@@ -51,6 +51,18 @@ Default.args = {
...
+  align: {
+    options: [
+      'top',
+      'top-left',
+      'top-right',
+      'bottom',
+      'bottom-left',
+      'bottom-right',
+      'left',
+      'right',
```
Comment (tay1orjones) [inline packages/react/src/components/OverflowMenu/OverflowMenu.stories.js]: I think these could be just the "new" values instead of the old to encourage use of the new ones.

File: packages/react/src/components/OverflowMenu/OverflowMenu.tsx [hunk 3]
```diff
@@ -120,7 +121,59 @@ export const getMenuOffset: MenuOffset = (
...
+  | 'bottom-start'
+  | 'bottom-end'
+  | 'left-end'
+  | 'left-start'
+  | 'right-end'
+  | 'right-start';
+
+export type OverflowMenuAlignment =
+  | DeprecatedOverflowMenuAlignment
+  | NewOverflowMenuAlignment;
```
Comment (adamalston) [inline packages/react/src/components/OverflowMenu/OverflowMenu.tsx]: Suggestion to delete these types. You could use `PopoverAlignment` since this `align` prop is just being passed to `IconButton` which passes it to `Tooltip` which passes it to `Popover`.

For reference, I've consolidated all of this functionality in https://github.com/carbon-design-system/carbon/pull/19081 but until that goes in, I think things here could be simplified.

File: packages/react/src/components/OverflowMenu/OverflowMenu.tsx [hunk 4]
```diff
@@ -120,7 +121,59 @@ export const getMenuOffset: MenuOffset = (
...
+    'top-right': 'top-end',
+    'bottom-left': 'bottom-start',
+    'bottom-right': 'bottom-end',
+    'left-bottom': 'left-end',
+    'left-top': 'left-start',
+    'right-bottom': 'right-end',
+    'right-top': 'right-start',
+  };
+  return mapping[deprecatedValue];
+};
```
Comment (adamalston) [inline packages/react/src/components/OverflowMenu/OverflowMenu.tsx:139]: As with the other comment, suggestion to simplify here by exporting `propMappingFunction` from `packages/react/src/components/Popover/index.tsx` and using it in this file instead of create another function.

Again, all of this logic will be consolidated pending https://github.com/carbon-design-system/carbon/pull/19081.

**Review by tay1orjones — CHANGES_REQUESTED** [review]
A couple comments but otherwise looks good to me. Thanks for taking this on!

---

Having `align` alongside `direction` and `flipped` is probably going to lead to some confusion. Prop/type comments help though since they explicitly mention "tooltip". The new OverflowMenu implementation calls it `tooltipAlignment` to avoid this confusion.

This being the old implementation though I don't think it's necessary to try and get a new `tooltipAlignment` to work alongside the existing `align` that some might be using. Plus it would add another layer of complexity having to iron out the types for all that. 

I just want to make note of this, there's no action for you to take here.

File: packages/react/src/components/OverflowMenu/OverflowMenu.tsx (hunk 4 above)
Comment (jose-biescas) [reply packages/react/src/components/OverflowMenu/OverflowMenu.tsx:139]: Would you want me to wait until #19081 gets merged, so I can export the function from `mapPopoverAlign.ts`? Instead of exporting `propMappingFunction`, since it will be changing.

Comment (adamalston) [reply packages/react/src/components/OverflowMenu/OverflowMenu.tsx:139]: I don't think you have to wait necessarily. I guess another thing you could do instead of making these changes is to add a `TODO` like the following in the code:

```tsx
// TODO: Replace this code when align mapping is consolidated.
// https://github.com/carbon-design-system/carbon/pull/19081
```

That `TODO` will just let me know to go and update this code later.

File: packages/react/src/components/OverflowMenu/OverflowMenu.tsx (hunk 1 above)
Comment (jose-biescas) [reply packages/react/src/components/OverflowMenu/OverflowMenu.tsx]: The `type` has been removed

File: packages/react/src/components/OverflowMenu/OverflowMenu.tsx (hunk 3 above)
Comment (jose-biescas) [reply packages/react/src/components/OverflowMenu/OverflowMenu.tsx]: Using `PopoverAlignment` as the type for `align` prop

File: packages/react/src/components/OverflowMenu/OverflowMenu.tsx (hunk 4 above)
Comment (jose-biescas) [reply packages/react/src/components/OverflowMenu/OverflowMenu.tsx:139]: Added the TODO

File: packages/react/src/components/OverflowMenu/OverflowMenu.stories.js (hunk 2 above)
Comment (jose-biescas) [reply packages/react/src/components/OverflowMenu/OverflowMenu.stories.js]: Updated the list to the latest options

**Review by tay1orjones — APPROVED** [review]

**Comment by jose-biescas** [comment]
@tay1orjones Apologies for that, not sure what happened. Will make sure future commits are also verified/signed. Thank you!

**Review by kennylam — APPROVED** [review]

**Review by 2nikhiltom — APPROVED** [review]
