### PR TITLE
fix(OverflowMenu): ignore disabled items during keyboard navigation

### LINKED ISSUE #6126: OverflowMenu handling of arrow keys with disabled menu items
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When an OverflowMenu which contains a disabled OverflowMenuItem, then the arrow keys stop navigating passed the disabled item.

> Is this issue related to a specific component?

OverflowMenu

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The arrow keys should goto the next/prior enabled OverflowMenuItem

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.12.x

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cognos PA Workspace

## Steps to reproduce the issue

1. Create an OverflowMenu with 3 OverflowMenuItems with the first item have primaryFocus property and second item have disabled property
2. Press down arrow, notice focus does not move

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6126

This PR fixes overflow menu keyboard navigation so that the component does not attempt to focus on disabled menu items

#### Testing / Reviewing

Confirm that keyboard navigation ignores disabled menu items and works as expected

### CODE REVIEW

**Review by dakahn — APPROVED** [review]

File: packages/react/src/components/OverflowMenu/OverflowMenu.js [hunk 1]
```diff
@@ -392,6 +411,7 @@ class OverflowMenu extends Component {
    */
   _handlePlace = menuBody => {
     if (menuBody) {
+      console.log('ayuayayya');
```
Comment (asudoh) [inline packages/react/src/components/OverflowMenu/OverflowMenu.js]:
```suggestion
```

**Review by asudoh — COMMENTED** [review]
LGTM basically - Thanks @emyarod!

**Review by asudoh — APPROVED** [review]
