### PR TITLE
fix(ui-shel): fix header panel function

### LINKED ISSUE #2964: [UIShell/HeaderPanel] forwardRef error since update to CC-React 7.3.0
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

I've just upgraded to Carbon Components 10.3.0 and Carbon Components React 7.3.0.

Since the upgrade I get the following console error in Chrome:

```
  | console.<computed> | @ | index.js:1449
-- | -- | -- | --
  | warningWithoutStack | @ | react.development.js:190
  | forwardRef | @ | react.development.js:1439
  | ../../carbon-components-react/es/index.js | @ | HeaderPanel.js:66
  | __webpack_require__ | @ | bootstrap:723
  | fn | @ | bootstrap:100
  | (anonymous) | @ | Header.js:16
  | ../../../src/components/frame/SiteNavigation.js | @ | SiteNavigation.js:37
  | __webpack_require__ | @ | bootstrap:723
  | fn | @ | bootstrap:100
  | (anonymous) | @ | Footer.js:28
  | ../../../src/components/frame/Header.js | @ | Header.js:16
  | __webpack_require__ | @ | bootstrap:723
  | fn | @ | bootstrap:100
  | (anonymous) | @ | Markdown.js:12
  | ../../../src/containers/Page.js | @ | Page.js:13
  | __webpack_require__ | @ | bootstrap:723
  | fn | @ | bootstrap:100
  | (anonymous) | @ | index.js:28
  | ../../../src/pages/404.js | @ | 404.js:14
  | __webpack_require__ | @ | bootstrap:723
  | fn | @ | bootstrap:100
  | (anonymous) | @ | react-static-browser-plugins.js:5
  | ../../../artifacts/react-static-templates.js | @ | react-static-templates.js:39
  | __webpack_require__ | @ | bootstrap:723
  | fn | @ | bootstrap:100
  | (anonymous) | @ | bootstrapTemplates.js:4
  | ../lib/bootstrapTemplates.js | @ | bootstrapTemplates.js:21
  | __webpack_require__ | @ | bootstrap:723
  | fn | @ | bootstrap:100
  | 0 | @ | index.js:7
  | __webpack_require__ | @ | bootstrap:723
  | (anonymous) | @ | bootstrap:790
  | (anonymous) | @ | bootstrap:790
```

It seems to be a problem with the `UIShell/HeaderPanel` component.
I don't use `UIShell` in my project.

## Steps to reproduce the issue

1. Upgrade to CC 10.3.0 and CCR 7.3.0
2. Use `Button`, `OverflowMenu` and `OverflowMenuItem`

### PR DESCRIPTION
**Pull request by aledavila**
Closes #2964 

#### Changelog

**Changed**

- changed header panel to function component

#### Testing / Reviewing

check to see if ui shell is not broken

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

File: packages/react/src/components/UIShell/HeaderPanel.js [hunk 1]
```diff
@@ -13,15 +13,14 @@ import { AriaLabelPropType } from '../../prop-types/AriaPropTypes';
...
-const HeaderPanel = React.forwardRef(function HeaderPanel(props) {
-  const {
-    'aria-label': ariaLabel,
-    'aria-labelledby': ariaLabelledBy,
-    children,
-    className: customClassName,
-    expanded,
-  } = props;
-
+const HeaderPanel = ({
```
Comment (asudoh) [inline packages/react/src/components/UIShell/HeaderPanel.js:16]: Any reason we stopped do-ing `forwardRef()` here? I didn't think `forwardRef()` itself caused #2964?
