### PR TITLE
fix(pagination): call onchange on page size change

### LINKED ISSUE #21661: [Bug]: preview_Pagination: onChange is not triggered when changing page size
### Package

@carbon/react

### Browser

Chrome

### Package version

1.100.0

### React version

18

### Description

With the preview_Pagination component, `onChange` event is not triggered when changing page size.
With the stable Pagination component, it is triggered as expected.

We have to use the preview_Pagination component for performance reason, since it allows us to use a page number input for large number of pages.

Looking at the preview_Pagination component code, it doesn't triggered the `onChange` event: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Pagination/experimental/Pagination.js#L84

The stable Pagination component resets page to 1 and triggers the event: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Pagination/Pagination.tsx#L295

### Reproduction/example

https://stackblitz.com/edit/github-kae1gsku?file=src%2FApp.jsx

### Steps to reproduce

- Import and use the `preview_Pagination` component.
- Add `onChange` event handler.
- Notice `onChange` event is not triggered when changing page size.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

IBM Envizi

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #21661

Update experimental pagination to call onChange and reset the current page to page 1 when the page size changes. This matches how the non-experimental pagination works. 

### Changelog

**New**

- Add experimental pagination test file

**Changed**

- Update experimental pagination to call onChange and reset to page 1 when page size changes

#### Testing / Reviewing

- Visit the story, go to the second page, change the page size, validate onChange was called and page resets to page 1

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
~- [ ] Addressed any impact on accessibility (a11y)~
~- [ ] Tested for cross-browser consistency~
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/react/src/components/Pagination/experimental/Pagination.js [hunk 1]
```diff
@@ -81,9 +81,14 @@ function Pagination({
...
               inline
-              onChange={(event) =>
-                setCurrentPageSize(Number(event.target.value))
-              }
+              onChange={(event) => {
+                const pageSize = Number(event.target.value);
+                setCurrentPageSize(pageSize);
+
+                if (onChange) {
+                  onChange({ page: currentPage, pageSize });
```
Comment (yinglejia) [inline packages/react/src/components/Pagination/experimental/Pagination.js]: Can we reset page to 1 when the page size changes? This is the behavior of the stable Pagination component, and makes it easier for callers. For example, if the page size changes from 20 to 50, the current page might no longer be a valid page. Of course, in theory the caller should be able to detect and fix the current page.

https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Pagination/Pagination.tsx#L299

Comment (adamalston) [reply packages/react/src/components/Pagination/experimental/Pagination.js]: > the current page might no longer be a valid page.

I have open pull requests that address `Pagination` issues:

- https://github.com/carbon-design-system/carbon/pull/21292
- https://github.com/carbon-design-system/carbon/pull/21480

I think the issue you're referring to is addressed in https://github.com/carbon-design-system/carbon/pull/21292.

Comment (yinglejia) [reply packages/react/src/components/Pagination/experimental/Pagination.js]: Thanks @adamalston. This PR and my comment pertain to the preview/experimental pagination, not the non-experimental pagination. Of course it is always a good idea to keep both in sync.

Comment (tay1orjones) [reply packages/react/src/components/Pagination/experimental/Pagination.js]: Done 👍 thanks for the feedback

**Review by yinglejia — APPROVED** [review]
Thanks!

**Review by devadula-nandan — APPROVED** [review]
LGTM

**Review by heloiselui — APPROVED** [review]
LGTM
