### PR TITLE
fix(tooltip): backwards compatibility

### LINKED ISSUE #19472: [Bug]: `aria-labelledby` attributes no longer added to underlying `IconButton`s
### Package

@carbon/react

### Browser

_No response_

### Package version

v11.83.0

### React version

_No response_

### Description

Prior to https://github.com/carbon-design-system/carbon/pull/19308, `aria-labelledby` attributes were added to `HeaderGlobalAction` components. These attributes connected the underlying `IconButton` to the `Popover` via an `id`. Now, `aria-labelledby` is no longer being added.

For example, before https://github.com/carbon-design-system/carbon/pull/19308, the element with `aria-label="Search"` in https://react.carbondesignsystem.com/?path=/story/components-ui-shell-header--header-w-actions-and-right-panel also had an `aria-labelledby` attribute. That's no longer the case.

Is this change expected? The only reason I ask is that typically, there are `id` references connecting `Popover` elements to their corresponding triggers. Now, the `Popover` that appears when hovering over the **Search** action in the header has an `id` that doesn't correspond to any other element.

I also see this change in the **Close** buttons that are added to `Modal`s.

At first, I wasn't sure if this change was expected. Then, I noticed that these attributes were still being added to standalone `IconButton`s that I am using in my app. Perhaps the `IconButton` usage in `HeaderGlobalAction`, `Modal`, and other components needs to be updated?

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-ui-shell-header--header-w-actions-and-right-panel

### Steps to reproduce

See description.

### Suggested Severity

None

### Application/PAL

DataPower

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by heloiselui**
Closes #19472

simplify tooltip ARIA logic while keeping backwards compatibility

### Changelog

**New**

- n/a

**Changed**

- refactored how `aria-labelledby` and `aria-describedby` are set in the Tooltip component
- refactored unit test for this case

**Removed**

- removed nested ternary conditions and unnecessary checks for `aria-label`

#### Testing / Reviewing
CI should pass
Go to `React Deploy Preview` > `UI Shell `> `Header w/ Actions and Right Panel `and test the `Search button`. Use `DevTools` to inspect the `Search button` and verify the ARIA attributes in each of the test scenarios.

I've documented eight scenarios in a markdown file. You can either open that directly or refer to the `>Testing scenarios` section where the tests are listed. Feel free to review and replicate them if you think is needed.

[Tests_PR_19472.md](https://github.com/user-attachments/files/21243584/Tests_PR_19472.md)

<details close>
<summary>Testing scenarios</summary>

### Scenario 1 - aria-label only

**Attributes Passed:**

- aria-label: ✅ ("Search")
- aria-labelledby: ❌
- aria-describedby: ❌

#### Before to #19308

- aria-label: ✅
- aria-labelledby: ⚠️ (id)
- aria-describedby: ❌

```html
<button
  aria-label="Search"
  aria-labelledby="tooltip-«rl»"
  type="button"
></button>
```

#### After to #19308

- aria-label: ✅
- aria-labelledby: ❌
- aria-describedby: ❌

```html
<button aria-label="Search" type="button"></button>
```

#### Proposed solution

- aria-label: ✅
- aria-labelledby: ⚠️ (id)
- aria-describedby: ❌

```html
<button
  aria-label="Search"
  aria-labelledby="tooltip-«rl»"
  type="button"
></button>
```

---

### Scenario 2 - aria-label + aria-labelledby

**Attributes Passed:**

- aria-label: ✅ ("Search")
- aria-labelledby: ✅ ("Search Test 1")
- aria-describedby: ❌

#### Before to #19308

- aria-label: ✅
- aria-labelledby: ⚠️ (id, but custom not applied)
- aria-describedby: ❌

```html
<button
  aria-label="Search"
  aria-labelledby="tooltip-«rl»"
  type="button"
></button>
```

#### After to #19308

- aria-label: ✅
- aria-labelledby: ❌
- aria-describedby: ❌

```html
<button aria-label="Search" type="button"></button>
```

#### Proposed solution

- aria-label: ✅
- aria-labelledby: ✅
- aria-describedby: ❌

```html
<button
  aria-label="Search"
  aria-labelledby="Search Test 1"
  type="button"
></button>
```

---

### Scenario 3 - aria-label + aria-describedby

**Attributes Passed:**

- aria-label: ✅ ("Search")
- aria-labelledby: ❌
- aria-describedby: ✅ ("Search Test 2")

#### Prior to #19308

- aria-label: ✅
- aria-labelledby: ⚠️ (id)
- aria-describedby: ✅

```html
<button
  aria-describedby="Search Test 2"
  aria-label="Search"
  aria-labelledby="tooltip-«rl»"
  type="button"
></button>
```

#### After to #19308

- aria-label: ✅
- aria-labelledby: ❌
- aria-describedby: ✅

```html
<button
  aria-describedby="Search Test 2"
  aria-label="Search"
  type="button"
></button>
```

#### Proposed solution

- aria-label: ✅
- aria-labelledby: ⚠️ (id)
- aria-describedby: ✅

```html
<button
  aria-describedby="Search Test 2"
  aria-label="Search"
  aria-labelledby="tooltip-«r35»"
  type="button"
></button>
```

---

### Scenario 4 - aria-label + aria-labelledby + aria-describedby

**Attributes Passed:**

- aria-label: ✅ ("Search")
- aria-labelledby: ✅ ("Search Test 1")
- aria-describedby: ✅ ("Search Test 2")

#### Prior to #19308

- aria-label: ✅
- aria-labelledby: ⚠️ (id, but custom not applied)
- aria-describedby: ✅

```html
<button
  aria-describedby="Search Test 2"
  aria-label="Search"
  aria-labelledby="tooltip-«rl»"
  type="button"
></button>
```

#### After to #19308

- aria-label: ✅
- aria-labelledby: ❌
- aria-describedby: ✅

```html
<button
  aria-describedby="Search Test 2"
  aria-label="Search"
  type="button"
></button>
```

#### Proposed solution

- aria-label: ✅
- aria-labelledby: ✅
- aria-describedby: ✅

```html
<button
  aria-describedby="Search Test 2"
  aria-label="Search"
  aria-labelledby="Search Test 1"
  type="button"
></button>
```

---

### Scenario 5 - aria-labelledby + aria-describedby

**Attributes Passed:**

- aria-label: ❌
- aria-labelledby: ✅ ("Search Test 1")
- aria-describedby: ✅ ("Search Test 2")

#### Before to #19308

- aria-label: ❌
- aria-labelledby: ✅
- aria-describedby: ⚠️ (id, but custom not applied)

```html
<button
  aria-describedby="tooltip-«rl»"
  aria-labelledby="Search Test 1"
  type="button"
></button>
```

#### After to #19308

- aria-label: ❌
- aria-labelledby: ❌
- aria-describedby: ✅

```html
<button aria-describedby="Search Test 2" type="button"></button>
```

#### Proposed solution

- aria-label: ❌
- aria-labelledby: ✅
- aria-describedby: ✅

```html
<button
  aria-describedby="Search Test 2"
  aria-labelledby="Search Test 1"
  type="button"
></button>
```

---

### Scenario 6 - only aria-labelledby

**Attributes Passed:**

- aria-label: ❌
- aria-labelledby: ✅ ("Search Test 1")
- aria-describedby: ❌

#### Before to #19308

- aria-label: ❌
- aria-labelledby: ✅ (custom)
- aria-describedby: ⚠️ (id)

```html
<button
  aria-labelledby="Search Test 1"
  aria-describedby="tooltip-«r1t»"
  type="button"
></button>
```

#### After to #19308

- aria-label: ❌
- aria-labelledby: ❌
- aria-describedby: ❌

```html
<button type="button"></button>
```

#### Proposed solution

- aria-label: ❌
- aria-labelledby: ✅
- aria-describedby: ⚠️ (id)

```html
<button
  aria-labelledby="Search Test 1"
  aria-describedby="tooltip-«r9d»"
  type="button"
></button>
```

---

### Scenario 7 - only aria-describedby

**Attributes Passed:**

- aria-label: ❌
- aria-labelledby: ❌
- aria-describedby: ✅ ("Search Test 2")

#### Before to #19308

- aria-label: ❌
- aria-labelledby: ❌
- aria-describedby: ⚠️ (id, but custom not applied)

```html
<button aria-describedby="tooltip-«rl»" type="button"></button>
```

#### After to #19308

- aria-label: ❌
- aria-labelledby: ❌
- aria-describedby: ✅

```html
<button aria-describedby="Search Test 2" type="button"></button>
```

#### Proposed solution

- aria-label: ❌
- aria-labelledby: ❌
- aria-describedby: ✅

```html
<button aria-describedby="Search Test 2" type="button"></button>
```

---

### Scenario 8 - no attributes

**Attributes Passed:**

- aria-label: ❌
- aria-labelledby: ❌
- aria-describedby: ❌

#### Before to #19308

- aria-label: ❌
- aria-labelledby: ❌
- aria-describedby: ⚠️ (id)

```html
<button aria-describedby="tooltip-«rl»" type="button"></button>
```

#### After to #19308

- aria-label: ❌
- aria-labelledby: ❌
- aria-describedby: ⚠️ (id)

```html
<button aria-describedby="tooltip-«rl»" type="button"></button>
```

#### Proposed solution

- aria-label: ❌
- aria-labelledby: ❌
- aria-describedby: ⚠️ (id)

```html
<button aria-describedby="tooltip-«rbt»" type="button"></button>
```
</details>

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [X] Reviewed every line of the diff
- ~[] Updated documentation and storybook examples~
- [X] Wrote passing tests that cover this change
- [X] Addressed any impact on accessibility (a11y)
- ~[] Tested for cross-browser consistency~
- [X] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/react/src/components/Tooltip/Tooltip.tsx [hunk 1]
```diff
@@ -151,19 +148,8 @@ const Tooltip: TooltipComponent = React.forwardRef(
     const hasAriaLabel =
       typeof ariaLabel === 'string' ? ariaLabel.trim() !== '' : false;
 
-    // An `aria-label` takes precedence over `aria-describedby`, but when it's
-    // needed and the user doesn't specify one, the fallback `id` is used.
-    const labelledBy = hasAriaLabel
```
Comment (tay1orjones) [inline packages/react/src/components/Tooltip/Tooltip.tsx:156]: Does this mean we can remove `hasAriaLabel`? Or do we need to use this in coordination with `hasLabel`?

**Review by tay1orjones — CHANGES_REQUESTED** [review]

File: packages/react/src/components/Tooltip/Tooltip.tsx (hunk 1 above)
Comment (heloiselui) [reply packages/react/src/components/Tooltip/Tooltip.tsx:156]: Good catch, I just removed it, thank you.

**Review by 2nikhiltom — APPROVED** [review]
Tested all scenarios - fixes the regressions while improving custom attribute handling LGTM

**Review by kennylam — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]
