### PR TITLE
fix: carousel accessibility enhancements

### LINKED ISSUE #21680: Carousel utility: Add ARIA attributes and accessibility features
The carousel utility (packages/utilities/src/carousel) currently lacks essential accessibility features such as aria-hidden, aria-live, and proper ARIA roles.

### PR DESCRIPTION
**Pull request by davidmenendez**
Closes #21680 

adds accessibility enhancements to the carousel utility

### Changelog

**New**

- adds live region to announce slide changes
- adds `aria-hidden` to hidden slides

#### Testing / Reviewing

Manual testing

Additional context for changes: https://www.w3.org/WAI/tutorials/carousels/

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [ ] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [ ] Wrote passing tests that cover this change
- [ ] Addressed any impact on accessibility (a11y)
- [ ] Tested for cross-browser consistency
- [ ] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by davidmenendez** [comment]
currently working on adding unit tests, but wanted to get feedback while that was still in progress 👍

File: packages/utilities/src/carousel/carousel.ts [hunk 1]
```diff
@@ -51,6 +51,32 @@ export const initCarousel = (
     refs[index] = ref;
   };
 
+  const getLiveRegion = (): HTMLDivElement | null =>
+    document.querySelector(`.${prefix}__live-region`);
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel.ts]: Should this function be scoped to `carouselContainer` instead of `document`? What if multiple carousels are mounted?

File: packages/utilities/src/carousel/carousel.ts [hunk 2]
```diff
@@ -51,6 +51,32 @@ export const initCarousel = (
...
+    const div = getLiveRegion();
+    if (div) {
+      div.textContent = `Item ${idx} of ${getCarouselItems().length}`;
+    }
+  };
+
+  const createLiveRegion = () => {
+    if (getLiveRegion()) {
+      return;
+    }
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel.ts]: Similar to the other comment, should this function check only within `carouselContainer` before exiting early? If any live region exists in `document`, this instance may never create its own `aria-live` element inside its container, which seems like it could break something.

File: packages/utilities/src/carousel/carousel.ts [hunk 3]
```diff
@@ -51,6 +51,32 @@ export const initCarousel = (
     refs[index] = ref;
   };
 
+  const getLiveRegion = (): HTMLDivElement | null =>
+    document.querySelector(`.${prefix}__live-region`);
+
+  const getWrapper = (): HTMLDivElement | null =>
+    carouselContainer.querySelector(`.${prefix}__itemsWrapper`);
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel.ts]: The return types can be inferred.


```suggestion
  const getLiveRegion = () => document.querySelector(`.${prefix}__live-region`);

  const getWrapper = () =>
    carouselContainer.querySelector(`.${prefix}__itemsWrapper`);
```

File: packages/utilities/src/carousel/carousel.ts [hunk 4]
```diff
@@ -410,18 +446,17 @@ export const initCarousel = (
    * const carouselItems = getCarouselItems(carouselContainer);
    * console.log(carouselItems); // Logs the carousel items as HTMLElements
    */
-  const getCarouselItems = (container: HTMLElement): HTMLElement[] => {
+  const getCarouselItems = (): HTMLElement[] => {
+    const container = getWrapper() as HTMLElement;
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel.ts]: The type assertion doesn't appear to be correct. `getWrapper` can return `null`. I suggest deleting the type assertion and updating the code to be type safe.


```suggestion
    const container = getWrapper();
```

I opened https://github.com/carbon-design-system/carbon/pull/21618 to address several type issues in this file, so I'm trying to prevent any new ones from being added.

File: packages/utilities/src/carousel/carousel.ts [hunk 5]
```diff
@@ -198,6 +225,12 @@ export const initCarousel = (
     if (!isBeingRecycledIn && isBeingRecycledOut) {
       viewItem.classList.add(`${prefix}__view-recycle-out`);
     }
+
+    if (isActive) {
+      viewItem.removeAttribute('aria-hidden');
+    } else {
+      viewItem.setAttribute('aria-hidden', 'true');
```
Comment (amal-k-joy) [inline packages/utilities/src/carousel/carousel.ts:253]: Can we add inert as well to the viewItem, which will block the complete keyboard navigation.
 if (!isActive) {
      viewItem.setAttribute('aria-hidden', 'true');
      viewItem.setAttribute('inert', '');
    } else {
      viewItem.removeAttribute('aria-hidden');
      viewItem.removeAttribute('inert');
    }

**Review by amal-k-joy — COMMENTED** [review]
LGTM, added 1 minor comment.

**Comment by davidmenendez** [comment]
changes made and testing added

File: packages/utilities/src/carousel/carousel.ts [hunk 6]
```diff
@@ -438,17 +444,18 @@ export const initCarousel = (
    * If the container has a 'slot' element, it fetches all elements assigned to that slot.
    * Otherwise, it fetches all direct children of the container.
    *
-   * @param {HTMLElement} container - The container element from which to extract carousel items.
-   * @returns {HTMLElement[]} An array of HTMLElements representing the carousel items.
+   * @returns {HTMLElement[] | undefined} An array of HTMLElements representing the carousel items or nothing if a container is not found.
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel.ts]: The types are redundant.

```suggestion
   * @returns An array of HTMLElements representing the carousel items or nothing if a container is not found.
```

File: packages/utilities/src/carousel/carousel.ts [hunk 7]
```diff
@@ -438,17 +444,18 @@ export const initCarousel = (
...
    * @example
-   * const carouselContainer = document.querySelector('.carousel-container');
-   * const carouselItems = getCarouselItems(carouselContainer);
+   * const carouselItems = getCarouselItems();
    * console.log(carouselItems); // Logs the carousel items as HTMLElements
    */
-  const getCarouselItems = (): HTMLElement[] => {
-    const container = getWrapper() as HTMLElement;
-    const slot = container.querySelector('slot') as HTMLSlotElement | null;
+  const getCarouselItems = (): HTMLElement[] | undefined => {
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel.ts]: The types can be inferred.

```suggestion
  const getCarouselItems = () => {
```

File: packages/utilities/src/carousel/carousel.ts [hunk 8]
```diff
@@ -51,25 +51,49 @@ export const initCarousel = (
...
+  const createLiveRegion = () => {
+    if (getLiveRegion()) {
+      return;
+    }
+
+    const div = document.createElement('div');
+    div.setAttribute('aria-live', 'polite');
+    div.setAttribute('aria-atomic', 'true');
+    div.setAttribute('class', `${prefix}__live-region`);
+    div.innerText = `Item 1 of ${getCarouselItems()?.length}`;
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel.ts]: 1. Do empty carousels initialize the live region as 'Item 1 of 0'?
2. Should `textContent` be used instead of `innerText`? `textContent` is used elsewhere.

File: packages/utilities/src/carousel/carousel.ts [hunk 9]
```diff
@@ -163,6 +187,7 @@ export const initCarousel = (
 
   const transitionComplete = (ref: HTMLElement) => {
     handleTransitionEnd(ref);
+    updateLiveRegion(viewIndexStack[0] + 1);
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel.ts]: `updateLiveRegion` is triggered on transition completion (`transitionend` and `animationend`) and in `reset`. For `next`, `prev`, and `goToIndex`, if completion events don't fire, it seems the visible slide can change while the live region still announces the previous item. Should live region updates also happen when `viewIndexStack` changes (e.g., in `transitionToViewIndex` and `navigatePrev`), with transition complete updates kept as a fallback?

```diff
diff --git a/packages/utilities/src/carousel/carousel.ts b/packages/utilities/src/carousel/carousel.ts
index 3a75bed423..0a8502f546 100644
--- a/packages/utilities/src/carousel/carousel.ts
+++ b/packages/utilities/src/carousel/carousel.ts
@@ -64,6 +64,10 @@ export const initCarousel = (
     }
   };
 
+  const syncLiveRegionWithActiveView = () => {
+    updateLiveRegion(viewIndexStack[0] + 1);
+  };
+
   const createLiveRegion = () => {
     if (getLiveRegion()) {
       return;
@@ -181,13 +185,14 @@ export const initCarousel = (
     if (viewIndexStack[0] !== sanitizedIndex) {
       handleTransitionStart();
       viewIndexStack = [sanitizedIndex, ...viewIndexStack];
+      syncLiveRegionWithActiveView();
       performAnimation(false);
     }
   };
 
   const transitionComplete = (ref: HTMLElement) => {
     handleTransitionEnd(ref);
-    updateLiveRegion(viewIndexStack[0] + 1);
+    syncLiveRegionWithActiveView();
   };
   /**
    * Attaches class names to an HTMLElement based on given conditions.
@@ -376,6 +381,7 @@ export const initCarousel = (
     if (viewIndexStack.length - 1 >= 1) {
       handleTransitionStart();
       viewIndexStack = viewIndexStack.slice(1);
+      syncLiveRegionWithActiveView();
       performAnimation(false);
     }
   };
@@ -420,7 +426,7 @@ export const initCarousel = (
     previousViewIndexStack = [0];
     viewIndexStack = [0];
     performAnimation(false);
-    updateLiveRegion(1);
+    syncLiveRegionWithActiveView();
   };
 
   /**
```

File: packages/utilities/src/carousel/carousel.ts (hunk 8 above)
Comment (davidmenendez) [reply packages/utilities/src/carousel/carousel.ts]: that's a good point. i'll include a check for when there are no children 👍

File: packages/utilities/src/carousel/carousel.ts (hunk 9 above)
Comment (davidmenendez) [reply packages/utilities/src/carousel/carousel.ts]: that's way better. i was having trouble syncing that up, so thank you for that explanation!

**Comment by davidmenendez** [comment]
@adamalston thank you for that super helpful feedback. changes made 👍

File: packages/utilities/src/carousel/carousel-test.js [hunk 10]
```diff
@@ -38,6 +38,31 @@ describe('initCarousel', () => {
...
+    const children = [...wrapper.children];
+    children.forEach((child, idx) => {
+      if (idx === 0) {
+        expect(child.getAttribute('aria-hidden')).toBe(null);
+        expect(child.getAttribute('inert')).toBe(null);
+      } else {
+        expect(child.getAttribute('aria-hidden')).toBeTruthy();
+        expect(child.getAttribute('inert')).toBe('');
+      }
+    });
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel-test.js:63]: Does anything here require creating a copy of `wrapper.children`, rather than using the original value directly?

File: packages/utilities/src/carousel/carousel-test.js [hunk 11]
```diff
@@ -38,6 +38,31 @@ describe('initCarousel', () => {
...
+    initCarousel(container, {
+      onViewChangeStart: mockOnViewChangeStart,
+      onViewChangeEnd: mockOnViewChangeEnd,
+    });
+
+    const liveRegion = container.querySelector('.carousel__live-region');
+    expect(liveRegion).toBeTruthy();
+    expect(liveRegion.getAttribute('aria-live')).toBe('polite');
+    expect(liveRegion.getAttribute('aria-atomic')).toBeTruthy();
+    expect(liveRegion.innerText).toBe('Item 1 of 3');
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel-test.js]:
```suggestion
    expect(liveRegion.textContent).toBe('Item 1 of 3');
```

File: packages/utilities/src/carousel/carousel-test.js [hunk 12]
```diff
@@ -38,6 +38,31 @@ describe('initCarousel', () => {
...
+  test('initializes carousel with correct a11y attributes', () => {
+    initCarousel(container, {
+      onViewChangeStart: mockOnViewChangeStart,
+      onViewChangeEnd: mockOnViewChangeEnd,
+    });
+
+    const liveRegion = container.querySelector('.carousel__live-region');
+    expect(liveRegion).toBeTruthy();
+    expect(liveRegion.getAttribute('aria-live')).toBe('polite');
+    expect(liveRegion.getAttribute('aria-atomic')).toBeTruthy();
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel-test.js]: I suggest replacing `toBeTruthy` with a more specific assertion.

File: packages/utilities/src/carousel/carousel-test.js
Comment (adamalston) [inline packages/utilities/src/carousel/carousel-test.js:1]: Should tests be added for any of the following functionality? I don’t see existing coverage, though it's possible you don't consider some of these cases as valuable to test.

- Live region sync behavior added in https://github.com/carbon-design-system/carbon/commit/150d0fdfd0baee2f3206bce7737468b1a46335ad.
- Out of range navigation, like `goToIndex(-1)` and `goToIndex(999)`, to ensure values are clamped and the correct item is announced.
- State transitions, not just the initial state. `aria-hidden` and `inert` should update correctly between active and inactive items after navigation.
- Reinitialization behavior, which should ensure that calling `initCarousel` again does not create duplicate live region elements.
- Empty carousel behavior, ensuring there are no crashes or invalid announcement text.

**Review by adamalston — COMMENTED** [review]
The code looks good.

File: packages/utilities/src/carousel/carousel-test.js (hunk 10 above)
Comment (davidmenendez) [reply packages/utilities/src/carousel/carousel-test.js:63]: i originally wrote it just using `wrapper.children.item(0...1...2)` but i thought this might be more scalable. i have no problem going back to that though 👍

**Comment by davidmenendez** [comment]
additional testing has been added to address more usecases and increase coverage 👍

**Review by amal-k-joy — APPROVED** [review]
Cool work. 🎉

File: packages/utilities/src/carousel/carousel-test.js [hunk 13]
```diff
@@ -38,6 +38,47 @@ describe('initCarousel', () => {
...
   });
 
+  test('initializes carousel with correct a11y attributes', () => {
+    initCarousel(container, {
+      onViewChangeStart: mockOnViewChangeStart,
+      onViewChangeEnd: mockOnViewChangeEnd,
+    });
+
+    const liveRegion = container.querySelector('.carousel__live-region');
+    expect(liveRegion).toBeTruthy();
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel-test.js]: https://github.com/carbon-design-system/carbon/pull/21701#discussion_r2887114180

**Review by adamalston — APPROVED** [review]

**Comment by davidmenendez** [comment]
final testing adjustments made based on feedback. ready for final review @carbon-design-system/monorepo-reviewers

**Comment by heloiselui** [comment]
Looks good, just some conflicts that need to be resolved.

**Comment by davidmenendez** [comment]
@heloiselui conflicts resolved 👍

File: packages/utilities/src/carousel/carousel.ts [hunk 14]
```diff
@@ -51,24 +51,55 @@ export const initCarousel = (
...
+    carouselContainer.appendChild(div);
+  };
+
   /**
    * Wraps all child elements of a given container into a new div with the specified class.
    * If an element with the specified class already exists as a child of the container, the function does nothing.
    *
-   * @param container - The container element to wrap child elements of.
-   * @param wrapperClass - The class name to apply to the new wrapper div.
+   * @returns {void}
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel.ts]: This type can be inferred.

```suggestion
```

File: packages/utilities/scss/carousel/_carousel.scss [hunk 15]
```diff
@@ -81,8 +81,33 @@ $animateTime: $duration-moderate-02 !default;
...
+    clip: rect(0 0 0 0);
+    -webkit-clip-path: inset(50%);
+    clip-path: inset(50%);
+    inline-size: 1px;
+    white-space: nowrap;
+  }
+
+  .#{$prefix}__view {
+    visibility: hidden;
+  }
```
Comment (adamalston) [inline packages/utilities/scss/carousel/_carousel.scss:103]: When `prev` runs, the outgoing slide only keeps `${prefix}__view` plus `${prefix}__view-recycle-out`, so would the `visibility: hidden` here prevent the `active-to-out` animation from rendering?

File: packages/utilities/scss/carousel/_carousel.scss [hunk 16]
```diff
@@ -81,8 +81,33 @@ $animateTime: $duration-moderate-02 !default;
   }
 }
 
+@mixin a11yStyles {
```
Comment (adamalston) [inline packages/utilities/scss/carousel/_carousel.scss:84]: Should `a11yStyles` emit `:host(.carousel__view*)` selectors too, the way `viewBase` does, so the documented `:host { @include carousel.viewStyles; }` usage gets the same visibility behavior as the class based path?

File: packages/utilities/src/carousel/carousel.ts [hunk 17]
```diff
@@ -51,24 +51,55 @@ export const initCarousel = (
...
+  const getLiveRegion = () =>
+    carouselContainer.querySelector<HTMLElement>(`.${prefix}__live-region`);
+
+  const getWrapper = () =>
+    carouselContainer.querySelector<HTMLElement>(`.${prefix}__itemsWrapper`);
+
+  const updateLiveRegion = (idx: number) => {
+    const div = getLiveRegion();
+    if (div) {
+      div.textContent = `Item ${idx} of ${getCarouselItems()?.length}`;
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel.ts]: Should this message support localization?

**Review by adamalston — COMMENTED** [review]
I have a few more questions following the merge. After that, everything should hopefully be good to go.

File: packages/utilities/src/carousel/carousel.ts (hunk 17 above)
Comment (davidmenendez) [reply packages/utilities/src/carousel/carousel.ts]: I initially considered this but wasn’t sure how to handle it in this context since the component is handling setting the dynamic values. I guess as a fallback we can allow the user to provide their own custom string with a callback that provides the child length and current index. Something like `customString=({ length, index }) => ‘slide ${index} of ${length} slides’` 🤔

Comment (adamalston) [reply packages/utilities/src/carousel/carousel.ts]: Several components support translation like `Pagination` and `DataTable`.

It's also documented in a few places:
- https://github.com/carbon-design-system/carbon/blob/0e157ff49c73026f3ff98a471447973705d5e851/docs/style.md#translating-a-component
- https://github.com/carbon-design-system/carbon/blob/0e157ff49c73026f3ff98a471447973705d5e851/packages/react/docs/g11n.md
- https://github.com/carbon-design-system/carbon/blob/0e157ff49c73026f3ff98a471447973705d5e851/packages/web-components/src/coding-conventions.md#globalization

Comment (davidmenendez) [reply packages/utilities/src/carousel/carousel.ts]: ahh perfect! i assumed something like this had been figured out here already. i just hadn't had a chance to look yet haha. thank you!

**Review by heloiselui — APPROVED** [review]

File: packages/utilities/scss/carousel/_carousel.scss (hunk 15 above)
Comment (davidmenendez) [reply packages/utilities/scss/carousel/_carousel.scss:103]: i verified that this is occurring. thank you. will resolve!

**Comment by davidmenendez** [comment]
@adamalston request changes made;

* translation functionality implemented
* fixed the visibility behavior you mentioned by fixing a bug where the recycle in class wasn't being applied and the animation values were off because of it
* included host in styles

to make testing and development easier i created a storybook example. i added this story under the accordion web component for local development. i'll share the code here

```
// accordion.stories.ts
import { initCarousel } from '../../../../utilities/src/carousel/carousel';
import {
  InitCarousel,
  TranslationKey,
} from '../../../../utilities/src/carousel/types';
import styles from './story.scss?lit';
...
export const CarouselExample = {
  render: () => {
    let carousel: InitCarousel;
    document.addEventListener('DOMContentLoaded', () => {
      const container = document.getElementById('myCarousel');
      const config = {
        translateWithId: (messageId: TranslationKey) => {
          const dict = {
            'carbon.carousel.item': 'custom item',
            'carbon.carousel.of': 'custom of',
          };
          return dict[messageId];
        },
      };
      carousel = initCarousel(container, config);
    });
    const nextHandler = () => {
      carousel?.next();
    };
    const prevHandler = () => {
      carousel?.prev();
    };
    const lastHandler = () => {
      carousel?.goToIndex(2);
    };
    return html`
      <style>
        ${styles}
      </style>
      <div id="myCarousel">
        <div>Slide 1</div>
        <div>Slide 2</div>
        <div>Slide 3</div>
      </div>
      <button @click="${prevHandler}">prev</button>
      <button @click="${nextHandler}">next</button>
      <button @click="${lastHandler}">last</button>
    `;
  },
};
```

```
// story.scss
@use '@carbon/utilities/scss/carousel' as carousel;

:host {
  @include carousel.carousel;
}

```

File: packages/utilities/src/carousel/carousel.ts [hunk 18]
```diff
@@ -60,7 +75,7 @@ export const initCarousel = (
   const updateLiveRegion = (idx: number) => {
     const div = getLiveRegion();
     if (div) {
-      div.textContent = `Item ${idx} of ${getCarouselItems()?.length}`;
+      div.textContent = `${t('carbon.carousel.item')} ${idx} ${t('carbon.carousel.of')} ${getCarouselItems()?.length}`;
```
Comment (adamalston) [inline packages/utilities/src/carousel/carousel.ts:78]: This string composition appears to be English specific. In other locales, the order may not follow the pattern `Item {current} of {total}`, so translating each piece separately could result in output that is grammatically incorrect or confusing. Instead, this string should be defined as a single translatable message with interpolation for `current` and `total`.

I also suggest abstracting the logic that generates this string so it can be reused, rather than repeating the composition wherever it is needed.

**Review by adamalston — APPROVED** [review]
I think these changes are good if you want to address the translation comment in a follow-up.

File: packages/utilities/src/carousel/carousel.ts (hunk 18 above)
Comment (davidmenendez) [reply packages/utilities/src/carousel/carousel.ts:78]: good points. yeah i'll do it in a follow up. thank you so much for your great reviews!!

**Comment by davidmenendez** [comment]
@heloiselui ready to be merged 👍
