### PR TITLE
fix(time-picker): announce invalid/warn state message

### LINKED ISSUE #19596: [a11y]: Timepicker:  Screen reader should announce the identified error informtion which appears on the screen when user input some invalid data.
### Package

@carbon/react

### Browser

_No response_

### Operating System

_No response_

### Package version

@carbon/react@1.84.0

### React version

_No response_

### Automated testing tool and ruleset

JAWS

### Assistive technology

JAWS

### Description

Issue description: Identified error information is not read by the screen reader. When user navigated on to the edit field and input some invalid information. Screen reader reamins silent.

Recommended fix: Screen reader should announce the identified error informtion which appears on the screen when user input some invalid data. For ex: Screen reader should announce as 'Invalid time format'.
Note: Screen reader should provided identified error information when user renavigated on to the error field.

### WCAG 2.1 Violation

_No response_

### Reproduction/example

It can be reproduced on https://cloud.ibm.com/infrastructure/statusHistory
Click the filter icon

Image

### Steps to reproduce

Click filter icon

### Suggested Severity

None

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by heloiselui**
Closes #19596

Fixed `TimePicker` a11y so invalid and warning messages are announced by screen readers.

### Changelog

**New**

- ~None~

**Changed**

- Updated `TimePicker` accessibility wiring so `aria-describedby` points to the `invalid` text when invalid is true and `warning` text when warning is true
- Preserved any consumer-provided `aria-describedby` values by merging them with the generated validation message ID
- Added `aria-invalid="true"` when `TimePicker` is invalid
- Added tests for `TimePicker` invalid/warning, and merged `aria-describedby` behavior

**Removed**

- ~None~

#### Testing / Reviewing

- Go to `React Deploy Preview` > `TimePicker` > `Default`
- Turn on a screen reader, such as `VoiceOver` or `JAWS`
- Set `invalid to true` or `warning to true` and `provide invalidText` or `provide warningText`, for example `This is test message`
- Focus or re-navigate to the TimePicker input
- Confirm the screen reader announces the invalid or warn message

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [X] Reviewed every line of the diff
- ~[ ] Updated documentation and storybook examples~
- [X] Wrote passing tests that cover this change
- [X] Addressed any impact on accessibility (a11y)
- ~[ ] Tested for cross-browser consistency~
- [X] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/react/src/components/TimePicker/TimePicker.tsx [hunk 1]
```diff
@@ -290,6 +296,8 @@ const TimePicker = frFn((props, ref) => {
             value={value}
             {...rest}
             {...readOnlyProps}
+            aria-describedby={describedBy}
+            aria-invalid={normalizedProps.invalid ? true : undefined}
```
Comment (adamalston) [inline packages/react/src/components/TimePicker/TimePicker.tsx]: Before this change, a consumer provided `aria-describedby` value flowed through `...rest` in every state. Now, `invalid` and `warning` replace that value with only `normalizedProps.invalidId` or `normalizedProps.warnId`, which causes any existing helper or hint relationship to disappear once validation is shown. Should the generated validation ID be appended to the existing `aria-describedby` value instead of overwriting it so both descriptions remain available?

Comment (tay1orjones) [reply packages/react/src/components/TimePicker/TimePicker.tsx]: I don't think the generated validation ID needs to be appended because the user wouldn't have a way to get that and use it as an `id` on another element, right?

We could pass through the user value as is though. `aria-describedby` accepts a space-separated list of element `id`s. Would mean that the `describedBy` earlier in the file could be something like this

```js
const describedBy = [
  normalizedProps.invalid
    ? normalizedProps.invalidId
    : normalizedProps.warn
      ? normalizedProps.warnId
      : null,
  ariaDescribedBy,
]
  .filter(Boolean)
  .join(' ');
```

**Review by tay1orjones — APPROVED** [review]

**Review by adamalston — APPROVED** [review]
