### PR TITLE
fix: arrow breaking in AILabel popover

### LINKED ISSUE #17965: [Bug]: Arrow looks breaking in the AI explainability popover
### Package

@carbon/react

### Browser

_No response_

### Package version

11.69.0

### React version

_No response_

### Description

Arrow looks breaking in the AI explainability popover in case of align values like 'bottom-left', 'bottom-right', 'top-right', 'top-left' etc. Also this is for AILabel icon size is 'mini', 'xs' or '2xs'. 

To resolve the issue, we are planning to add a cross-axis offset of 24px in case of above conditions only.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-ailabel--default

### Steps to reproduce

Image

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by preetibansalui**
Closes #17965 

Arrow looks breaking in the AI explainability popover in case of small icons.

#### Changelog

added alignmentAxis in offset for popover.

**Changed**

passing a prop from AILabel to Toggletip component in case of 'XS', '2xs' or 'mini' icon.

#### Testing / Reviewing

1. Go to Storybook > AILabel > Default
2. hover on AI Label, the popover should not looks breaking.

### CODE REVIEW

**Review by aagonzales — COMMENTED** [review]
The caret looks like its 1px too low.
image

**Comment by preetibansalui** [comment]
> The caret looks like its 1px too low. image

Thanks Anna for noticing this. It was caused by recent renaming of slug to ai-label, which is fixed now.

**Review by aagonzales — APPROVED** [review]
Looks good to me!

**Review by guidari — APPROVED** [review]
LGTM! 🚀

**Review by ariellalgilmore — APPROVED** [review]
LGTM!

File: packages/react/src/components/Popover/index.tsx [hunk 1]
```diff
@@ -172,6 +172,7 @@ export const Popover: PopoverComponent = React.forwardRef(
       highContrast = false,
       onRequestClose,
       open,
+      alignmentAxisOffset,
```
Comment (tay1orjones) [inline packages/react/src/components/Popover/index.tsx:175]: Does this produce an proptypes or ts error/warning because it's not defined in proptypes or the interface?

File: packages/react/src/components/Popover/index.tsx [hunk 2]
```diff
@@ -257,7 +260,14 @@ export const Popover: PopoverComponent = React.forwardRef(
 
             // Middleware order matters, arrow should be last
             middleware: [
-              offset(!isTabTip ? popoverDimensions?.current?.offset : 0),
+              offset(
+                !isTabTip
+                  ? {
+                      alignmentAxis: alignmentAxisOffset,
+                      mainAxis: popoverDimensions?.current?.offset,
```
Comment (tay1orjones) [inline packages/react/src/components/Popover/index.tsx:267]: This isn't something blocking this PR and doesn't need changed, but one concern I just mentioned a comment on https://github.com/carbon-design-system/carbon/issues/17003#issuecomment-2514805003 is that as we add more of these config values, they bloat the interface/api of these components. Especially when we haven't identified a use case from a consumer for this, it's just something we need internally for our use w/ AILabel.

The mainAxis offset is already pulled from a custom property instead of a prop value. Doing this for other values as well might be one way to scale these types of config values without having to have a prop for each one. Could be used in tandem w/ however we end up providing a way for consumers to config floating-ui from anywhere in their react tree.

File: packages/react/src/components/Popover/index.tsx (hunk 1 above)
Comment (preetibansalui) [reply packages/react/src/components/Popover/index.tsx:175]: Hi Taylor, As discussed, its not giving any warning.

File: packages/react/src/components/Popover/index.tsx (hunk 2 above)
Comment (preetibansalui) [reply packages/react/src/components/Popover/index.tsx:267]: I understood your point, I added a prop here instead of some calculations so that it could be changed to different cases as well which might come in future as we have now for AILabel.

**Review by tay1orjones — APPROVED** [review]
