### PR TITLE
fix: let decorator accept any component instead of ailabel

### LINKED ISSUE #20494: [Bug]: decorator prop currently only accepts and renders AILabel component
### Package

@carbon/react

### Browser

_No response_

### Package version

1.90.0

### React version

_No response_

### Description

The `decorator` prop in most of the components is not rendering `custom` React elements, such as `Toggletip`
this behavior is a regression caused by a recent change that explicitly checks for and only renders the AILabel component in this [PR](https://github.com/carbon-design-system/carbon/pull/18971/files)

### Reproduction/example

https://stackblitz.com/edit/qaw8crdy?file=src%2FApp.jsx

### Steps to reproduce

pass a custom element to `decorator` prop and confirm it is not rendered 

```
<RadioButtonGroup
      legendText="Radio Button group"
      name="radio-button-default-group"
      decorator={
        <Toggletip autoAlign>
          <ToggletipButton label={'test'}>
            <span>i</span>
          </ToggletipButton>
          <ToggletipContent>{'test'}</ToggletipContent>
        </Toggletip>
      }
    >
```
workaround [example](https://stackblitz.com/edit/qaw8crdy-xwyjru8s?file=src%2FApp.jsx,package.json)  

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Gururajj77**
Closes #20494

decorator prop accepts any component now, instead of only `AILabel`

> [!NOTE]  
> remove the test story before merging
### Changelog

**Changed**

- modified the normaliser to accept the passed component as it is, if it's not an `AILabel`
```
const normalizedDecorator = candidateIsAILabel
    ? cloneElement(candidate, { size: 'mini', kind: 'default' })
    : candidate;
```

#### Testing / Reviewing

- the test story in the RadioButton component, shows how the `ToggleTip` shows up after this change.

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Updated documentation and storybook examples
- ~[ ] Wrote passing tests that cover this change~
- [x] Addressed any impact on accessibility (a11y)
- ~[ ] Tested for cross-browser consistency~
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

File: packages/react/src/components/NumberInput/NumberInput.tsx [hunk 1]
```diff
@@ -611,14 +613,18 @@ const NumberInput = React.forwardRef<HTMLInputElement, NumberInputProps>(
     // AILabel always size `mini`
     const candidate = slug ?? decorator;
     const candidateIsAILabel = isComponentElement(candidate, AILabel);
-    const normalizedDecorator = candidateIsAILabel
+    const normalizedDecorator: ReactNode = candidateIsAILabel
```
Comment (adamalston) [inline packages/react/src/components/NumberInput/NumberInput.tsx]: This type is not required elsewhere. Why is it needed here?

```suggestion
    const normalizedDecorator = candidateIsAILabel
```

File: packages/react/src/components/NumberInput/NumberInput.tsx [hunk 2]
```diff
@@ -611,14 +613,18 @@ const NumberInput = React.forwardRef<HTMLInputElement, NumberInputProps>(
...
     let isRevertActive: AILabelProps['revertActive'];
-    if (normalizedDecorator?.type === AILabel) {
-      isRevertActive = normalizedDecorator.props.revertActive;
+    if (
+      isValidElement(normalizedDecorator) &&
+      normalizedDecorator.type === AILabel
+    ) {
+      const asAILabel = normalizedDecorator as ReactElement<AILabelProps>;
+      isRevertActive = asAILabel.props.revertActive;
     }
```
Comment (adamalston) [inline packages/react/src/components/NumberInput/NumberInput.tsx]: All of these types can be inferred by using `isComponentElement` or another type-safe implementation.

```tsx
const isRevertActive = isComponentElement(normalizedDecorator, AILabel)
  ? normalizedDecorator.props.revertActive
  : undefined;
```

However, since we already determined earlier in the file whether `candidate` is an `AILabel`, why do we need to perform this check again?

File: packages/react/src/components/NumberInput/NumberInput.tsx [hunk 3]
```diff
@@ -10,6 +10,8 @@ import cx from 'classnames';
 import PropTypes from 'prop-types';
 import React, {
   cloneElement,
+  isValidElement,
+  ReactElement,
```
Comment (adamalston) [inline packages/react/src/components/NumberInput/NumberInput.tsx]:
```suggestion
  type ReactElement,
```

File: packages/react/src/components/NumberInput/NumberInput.tsx (hunk 2 above)
Comment (Gururajj77) [reply packages/react/src/components/NumberInput/NumberInput.tsx]: have made the changes as needed

File: packages/react/src/components/NumberInput/NumberInput.tsx [hunk 4]
```diff
@@ -611,15 +611,14 @@ const NumberInput = React.forwardRef<HTMLInputElement, NumberInputProps>(
...
       ? cloneElement(candidate, { size: 'mini' })
-      : null;
+      : candidate;
 
     // Need to update the internal value when the revert button is clicked
-    let isRevertActive: AILabelProps['revertActive'];
-    if (normalizedDecorator?.type === AILabel) {
-      isRevertActive = normalizedDecorator.props.revertActive;
-    }
+    const isRevertActive = isComponentElement(normalizedDecorator, AILabel)
```
Comment (adamalston) [inline packages/react/src/components/NumberInput/NumberInput.tsx:711]: https://github.com/carbon-design-system/carbon/pull/20525#discussion_r2352576057:

> [S]ince we already determined earlier in the file whether `candidate` is an `AILabel`, why do we need to perform this check again?

File: packages/react/src/components/NumberInput/NumberInput.tsx (hunk 1 above)
Comment (adamalston) [reply packages/react/src/components/NumberInput/NumberInput.tsx]: I don't see an answer to the question. Is the type required, or can it be removed?

File: packages/react/src/components/NumberInput/NumberInput.tsx (hunk 4 above)
Comment (Gururajj77) [reply packages/react/src/components/NumberInput/NumberInput.tsx:711]: This can be removed.

**Review by maradwan26 — APPROVED** [review]
LGTM

**Review by tay1orjones — APPROVED** [review]

**Comment by maradwan26** [comment]
@Gururajj77 
Test story just needs to be removed to merge

File: packages/react/src/components/NumberInput/NumberInput.tsx (hunk 4 above)
Comment (adamalston) [reply packages/react/src/components/NumberInput/NumberInput.tsx:711]: I don't see a removal. Was these supposed to be a change here?
