### PR TITLE
fix(ProgressIndicator): remove `role` attribute from checkmark svg

### LINKED ISSUE #4243: AVT 1 - Progress Indicator has DAP violations
## Environment
macOS Mojave version 10.14.6
Chrome Version Version 77.0.3865.90
Carbon v10 - React
DAP IBM Accessibility 1.8.0.0 Sept 2019 Ruleset

## Detailed Description
Go to the React Progress Indicator (Default) Component
Run DAP and the following violations are present (see screenshot):
Screen Shot 2019-10-07 at 1 16 07 PM

Note: Interactive Progress Indicator Component does not have the contrast issue since there are no disabled steps. Any disabled step should include aria-disabled="true".

### PR DESCRIPTION
**Pull request by emyarod**
Closes #4243

This PR removes the `role` attribute from completed progress steps and adds the `aria-disabled` attribute to disabled progress steps

#### Testing / Reviewing

Ensure the reported DAP violations are no longer present in the progress indicator component

### CODE REVIEW

File: packages/react/src/components/ProgressIndicator/ProgressIndicator.js [hunk 1]
```diff
@@ -43,35 +43,42 @@ export const ProgressStep = ({ ...props }) => {
...
+        <svg {...rest}>
           <path d="M 7, 7 m -7, 0 a 7,7 0 1,0 14,0 a 7,7 0 1,0 -14,0" />
           <title>{description}</title>
         </svg>
       );
     }
     if (complete) {
       return (
-        <CheckmarkOutline16 role="img">
+        <CheckmarkOutline16 role="img" {...rest}>
```
Comment (abbeyhrt) [inline packages/react/src/components/ProgressIndicator/ProgressIndicator.js]: Since the icons are aria-hidden by default, i believe, instead of adding `{...rest}` it might be better to remove `role="img"` and the `aria-label` added to SVGIcon. Since `label` is used twice, VO reads it twice and no longer reads the description. This change also removes the DAP violation.

**Review by abbeyhrt — CHANGES_REQUESTED** [review]

File: packages/react/src/components/ProgressIndicator/ProgressIndicator.js (hunk 1 above)
Comment (emyarod) [reply packages/react/src/components/ProgressIndicator/ProgressIndicator.js]: removed the `role` attribute and reverted aria-label changes

**Review by abbeyhrt — APPROVED** [review]
Looks great! 🎉

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!
