### PR TITLE
fix: added readonly states for fluid components

### LINKED ISSUE #16939: [FluidComponents]: missing readOnly state
- [ ] FluidTextArea
- [ ] FluidTextInput
- [ ] FluidDropdown
- [ ] ... check others

### PR DESCRIPTION
**Pull request by riddhybansal**
Closes #16939 

Added readonly states to fluid components

#### Changelog

**New**

- Added readonly states to fluid components. For FluidMultiselect , FluidDropdown, and FluidCombobox it got added automatically while converting into typescript because of their extending interfaces. If you cant see readonly state for fluid dropdown , it might be because this [PR](https://github.com/carbon-design-system/carbon/pull/17562) is not merged, but you can verify it in the deploy preview.

#### Testing / Reviewing

Test readonly state for fluid components.

### CODE REVIEW

**Review by preetibansalui — CHANGES_REQUESTED** [review]
Hey Riddhi, Thanks for the changes. It looks like still on some components readonly is not working. I found few of them like: 
1. FluidDatePicker
2. FluidTimePicker

can you please check.

**Comment by riddhybansal** [comment]
> Hey Riddhi, Thanks for the changes. It looks like still on some components readonly is not working. I found few of them like:
> 
> 1. FluidDatePicker
> 2. FluidTimePicker
> 
> can you please check.

Hey Preeti, its fixed !! Thanks for pointing out!!

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
Looks like readOnly is missing from the playground story for FluidDropdown.

There is also something weird happening on hover with FluidTimePicker

https://github.com/user-attachments/assets/d8fce7c5-2b55-417c-9106-377c9706911b

**Review by guidari — APPROVED** [review]
LGTM! 🚀
The FluidMultiselect has a bug that is gonna be fixed on this [PR](https://github.com/carbon-design-system/carbon/pull/17944)

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Comment by alisonjoseph** [comment]
@thyhmdo this is ready for a visual review

**Review by 2nikhiltom — APPROVED** [review]

**Comment by thyhmdo** [comment]
Looks good! If it's not too much trouble, can we also fix this description for Combobox? 

To "Whether or not the component is read-only" – This seems to be consistent with other Fluid component's read-only description, 

image

File: packages/react/src/components/FluidTimePicker/FluidTimePicker.tsx [hunk 1]
```diff
@@ -96,15 +101,26 @@ const FluidTimePicker = React.forwardRef<
...
               });
             })
-          : children}
+          : readOnly
+            ? React.Children.toArray(children).map((child) => {
+                return React.cloneElement(child as React.ReactElement, {
+                  readOnly: true,
+                });
+              })
+            : children}
```
Comment (emyarod) [inline packages/react/src/components/FluidTimePicker/FluidTimePicker.tsx]: it might be worth extracting this to a function now (like how we render `errorText`). what do you think? for example like:

```tsx
const childrenWithProps = () => {
  if (!disabled && !readOnly) {
    return children;
  }
  return React.Children.toArray(children).map((child) =>
    React.cloneElement(child as React.ReactElement, {
      disabled: disabled || undefined,
      readOnly: disabled || undefined,
    })
  );
};
```
or
```tsx
const childrenWithProps = () => {
  if (disabled) {
    return React.Children.toArray(children).map((child) =>
      React.cloneElement(child as React.ReactElement, {
        disabled: true,
      })
    );
  }
  if (readOnly) {
    return React.Children.toArray(children).map((child) =>
      React.cloneElement(child as React.ReactElement, {
        readOnly: true,
      })
    );
  }
  return children;
};
```

**Review by preetibansalui — APPROVED** [review]
Thanks for the changes. LGTM

**Review by thyhmdo — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by tay1orjones — APPROVED** [review]
