### PR TITLE
fix(structured-list): remove unused prop

### LINKED ISSUE #5590: [StructuredListWrapper] - border prop does nothing
- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The `StructuredListWrapper` has a `border` prop which does nothing. This may have been a selector used in v9 that was removed in v10. 

Screen Shot 2020-03-10 at 3 43 57 PM

You can see in the [React component](https://github.com/carbon-design-system/carbon/blob/b8187fa97f3ec72998859f7d480d53d1af5053f2/packages/react/src/components/StructuredList/StructuredList.js#L60-L63) that this prop is supposed to apply a css selector:
```js
    const classes = classNames(`${prefix}--structured-list`, className, {
      [`${prefix}--structured-list--border`]: border,
      [`${prefix}--structured-list--selection`]: selection,
    });
```

But, if you look at the [styles for it](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/structured-list/_structured-list.scss
), the selector doesn't exist. 

It seems like this prop should be deprecated.

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5590

Removes all references to the `border` prop. There were no associated styles with it, and it had no effect on the component. We can put it behind a deprecation flag, but I'm not sure that is necessary since this just seems like an old prop that was part of the original implementation that was never removed when we made the large changes to `v10`

#### Changelog

**Removed**

- All references to `border` in the `StructuredList` component

#### Testing / Reviewing

Ensure the component renders properly

### CODE REVIEW

File: packages/react/src/components/StructuredList/StructuredList.js [hunk 1]
```diff
@@ -25,11 +25,6 @@ export class StructuredListWrapper extends Component {
      */
     className: PropTypes.string,
 
-    /**
-     * Specify whether a border should be added to your StructuredListWrapper
-     */
-    border: PropTypes.bool,
```
Comment (joshblack) [inline packages/react/src/components/StructuredList/StructuredList.js:31]: I think we might need to wrap this in a `deprecate` block as lame as that is otherwise if someone is passing in `border` it might get spread onto `<section>` with `other` accidentally :disappointed: This could cause React to complain about the extra attribute showing up.

Comment (tw15egan) [reply packages/react/src/components/StructuredList/StructuredList.js:31]: 😞

Comment (tw15egan) [reply packages/react/src/components/StructuredList/StructuredList.js:31]: Do we need to keep the rest of the `border` code as well? Or is keeping the prop definition wrapped in a deprecate enough?

Comment (joshblack) [reply packages/react/src/components/StructuredList/StructuredList.js:31]: @tw15egan I doubt we need to keep the class name code. As long as we have:

```js
    const { children, selection, className, ariaLabel, border: _border, ...other } = this.props;
```

I think it'd be fine so it doesn't get caught up in `other`.  The rest of the code can totally be dropped I think (alongside the deprecate bit for the prop type)

Comment (tw15egan) [reply packages/react/src/components/StructuredList/StructuredList.js:31]: Alright I've updated it, let me know if the changes look good 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Review by joshblack — APPROVED** [review]
