### PR TITLE
fix(ComboBox): resolves DAP violations

### LINKED ISSUE #3260: AVT 1 - React Combobox has DAP violations
## Environment
macOS Mojave version 10.14.5
Version 75.0.3770.100 (Official Build) (64-bit)
Carbon v10 - React

Detailed Description
Run DAP on any of the three Combobox examples and the following DAP violations are present:

Screen Shot 2019-07-02 at 2 26 14 PM

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #3260

Resolves DAP violations for ComboBox. 

Current Violations: 
Screen Shot 2019-09-18 at 11 08 58 AM

#### Changelog

**New**

- `tabIndex`, `aria-owns`, `aria-labelledby` on the `input`
- `aria-label` on ListBox 
-  `aria-label` on the Close button svg

**Changed**

- Moved the `aria-label` to the outer container to replicate what accessible combobox examples do, see guidance [here](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html)

#### Testing / Reviewing

- Run DAP on ComboBox, preferably with the dropdown open and something selected because that captures the most violations. 
- Make sure that the only  violations you see are these ones: 

Screen Shot 2019-09-18 at 11 09 38 AM
 those are apparently always there and are a part of storybook 
- check the fixes and make sure they're okay/what should be done. 

*Note*: if you check DAP with the ComboBox closed there will be this violation: 

Screen Shot 2019-09-18 at 11 14 07 AM but this will go away with the ComboBox open as the dropdown list part is what has the id `carbon-combobox-example__menu` and it doesn't exist when the ComboBox is closed

### CODE REVIEW

File: packages/react/src/components/ListBox/ListBoxSelection.js [hunk 1]
```diff
@@ -49,7 +49,7 @@ const ListBoxSelection = ({
       onKeyDown={handleOnKeyDown}
       title={description}>
       {selectionCount}
-      <Close16 role="img" />
+      <Close16 role="img" aria-label="Clear Selection" />
```
Comment (joshblack) [inline packages/react/src/components/ListBox/ListBoxSelection.js]: Should we just place the `aria-label` on the containing `div` and remove `role="img"`?

File: packages/react/src/components/ComboBox/ComboBox.js [hunk 2]
```diff
@@ -310,9 +312,11 @@ export default class ComboBox extends React.Component {
               })}>
               <input
                 className={`${prefix}--text-input`}
-                aria-label={ariaLabel}
+                aria-labelledby="combobox-id-a11y"
```
Comment (joshblack) [inline packages/react/src/components/ComboBox/ComboBox.js]: We should make sure this is computed otherwise if there are two combo boxes on a page they have the same id being generated

**Review by joshblack — CHANGES_REQUESTED** [review]

File: packages/react/src/components/ComboBox/ComboBox.js (hunk 2 above)
Comment (abbeyhrt) [reply packages/react/src/components/ComboBox/ComboBox.js]: That makes sense! I added something to do this, let me know if it doesn't look right!

File: packages/react/src/components/ComboBox/ComboBox.js [hunk 3]
```diff
@@ -310,9 +317,11 @@ export default class ComboBox extends React.Component {
               })}>
               <input
                 className={`${prefix}--text-input`}
-                aria-label={ariaLabel}
+                aria-labelledby={comboBoxA11yId}
```
Comment (joshblack) [inline packages/react/src/components/ComboBox/ComboBox.js:320]: This was surprising to me, my first thought was that `ListBox.Field` would provide the label for the input

Comment (abbeyhrt) [reply packages/react/src/components/ComboBox/ComboBox.js:320]: It seemed like the aria-label should be on the combobox container element which I took to be the ListBox but I might be wrong about that. Would the listBox.Field be considered the container?

**Review by dakahn — APPROVED** [review]
Paired up on this. Thanks @abbeyhrt for the fixes. We tested using VO on OSX in Safari.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @abbeyhrt!

**Comment by abbeyhrt** [comment]
@joshblack I moved the aria label to the ListBox.Field, let me know if this looks good now!

File: packages/react/src/components/ComboBox/ComboBox.js (hunk 3 above)
Comment (joshblack) [reply packages/react/src/components/ComboBox/ComboBox.js:320]: Lol ignore me, I thought `ListBox.Field` had the `<label>` for some reason 🤦‍♂️

**Review by joshblack — APPROVED** [review]
