### PR TITLE
fix(DatePicker): prevent invalid/warn states when disabled/readonly

### LINKED ISSUE #20722: [DatePicker]: Disallow invalid & warn when readonly or disabled

### PR DESCRIPTION
**Pull request by Tiss29**
Fixed DatePicker components in both React and Web Components to not show invalid/warn states when in disabled or readonly state, as users cannot interact with these components in those states.

Closes [#20722](https://github.com/carbon-design-system/carbon/issues/20722)

Fix DatePicker components to not show invalid/warn states when disabled or readonly

### Changelog

**New**

- Added tests in DatePicker-test.js and date-picker_spec.ts to verify invalid/warn states are not shown when disabled or readonly.

**Changed**

- Added disabled prop to DatePicker.tsx and modified child component props to include conditions for invalid/warn states.
- Updated DatePickerInput.tsx to not apply invalid/warn CSS classes when disabled/readonly.
- Modified useNormalizedInputProps.tsx to check for disabled state when setting invalid/warn properties.
- Updated date-picker-input.ts to check for disabled state in normalizedProps.
- Added CSS rules in _date-picker.scss to remove invalid/warn styling for disabled and readonly inputs.
- Added CSS rules in date-picker.scss for web components implementation.

#### Testing / Reviewing

- Access DatePicker on storybook and change the state to "Invalid = true" and "disabled = true". The invalid message should not be shown.
- Repeat above test with "readOnly = true" instead of disabled. The invalid message should not be shown.
- Repeat the two tests above using "warn = true" instead of "invalid = true". The warning message on both scenarios should not be shown.

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [ ] Updated documentation and storybook examples
- [x] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Comment by Tiss29** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by Tiss29** [comment]
recheck

**Comment by Tiss29** [comment]
I have read the DCO document and I hereby sign the DCO.

File: packages/react/src/components/DatePicker/DatePicker.tsx [hunk 1]
```diff
@@ -546,24 +552,24 @@ const DatePicker = React.forwardRef(function DatePicker(
...
       }
       if (index === 1) {
         return React.cloneElement(child, {
           ref: endInputField,
           readOnly,
-          invalid,
-          warn: effectiveWarn,
+          invalid: invalid && !disabled,
+          warn: effectiveWarn && !disabled,
         });
```
Comment (maradwan26) [inline packages/react/src/components/DatePicker/DatePicker.tsx]: The `invalid && !disabled` and ` && !disabled` conditions can likely be omitted here, same with the new disabled prop since its already in DatePickerInput

File: packages/react/src/components/DatePickerInput/DatePickerInput.tsx [hunk 2]
```diff
@@ -210,28 +222,34 @@ const DatePickerInput = React.forwardRef(function DatePickerInput(
...
+      normalizedProps.warn && !disabled && !readOnly,
   });
   const containerClasses = cx(`${prefix}--date-picker-container`, {
     [`${prefix}--date-picker--nolabel`]: !labelText,
-    [`${prefix}--date-picker--fluid--invalid`]: isFluid && invalid,
-    [`${prefix}--date-picker--fluid--warn`]: isFluid && warn,
+    [`${prefix}--date-picker--fluid--invalid`]:
+      isFluid && normalizedProps.invalid && !disabled && !readOnly,
+    [`${prefix}--date-picker--fluid--warn`]:
+      isFluid && normalizedProps.warn && !disabled && !readOnly,
```
Comment (maradwan26) [inline packages/react/src/components/DatePickerInput/DatePickerInput.tsx]: `useNormalizedInputProps` already checks to make sure invalid and warn don't get applied with disabled/readonly, so you shouldn't need to recheck the condition with `!disabled && !readOnly` here

File: packages/styles/scss/components/date-picker/_date-picker.scss [hunk 3]
```diff
@@ -91,6 +91,12 @@
     ~ .#{$prefix}--form-requirement {
     color: $text-primary;
   }
+
+  // Don't show form requirements when disabled or readonly
+  .#{$prefix}--date-picker__input[disabled] ~ .#{$prefix}--form-requirement,
+  .#{$prefix}--date-picker__input[readonly] ~ .#{$prefix}--form-requirement {
+    display: none;
+  }
```
Comment (maradwan26) [inline packages/styles/scss/components/date-picker/_date-picker.scss]: Preventing invalid/warn states to be applied with disabled/readonly should just be in the component file, the styles shouldn't need to be updated

File: packages/web-components/src/components/date-picker/date-picker.scss [hunk 4]
```diff
@@ -77,12 +77,19 @@ $css--plex: true !default;
...
   }
 }
 
+:host(#{$prefix}-date-picker-input[disabled]),
+:host(#{$prefix}-date-picker-input[readonly]) {
+  .#{$prefix}--form-requirement {
+    display: none;
+  }
+}
+
```
Comment (maradwan26) [inline packages/web-components/src/components/date-picker/date-picker.scss]: Preventing invalid/warn states to be applied with disabled/readonly should just be in the component file, the styles shouldn't need to be updated

File: packages/react/src/components/DatePickerInput/DatePickerInput.tsx [hunk 5]
```diff
@@ -173,11 +174,22 @@ const DatePickerInput = React.forwardRef(function DatePickerInput(
...
   const { isFluid } = useContext(FormContext);
   const datePickerInputInstanceId = useId();
+
+  const normalizedProps = useNormalizedInputProps({
+    id,
+    readOnly,
+    disabled,
+    invalid: invalid === true,
+    invalidText,
+    warn: warn === true,
```
Comment (maradwan26) [inline packages/react/src/components/DatePickerInput/DatePickerInput.tsx]:
```suggestion
    invalid,
    invalidText,
    warn,
```
This should be able to work without the conditions

**Review by maradwan26 — CHANGES_REQUESTED** [review]
Thanks for contributing! Just some comments on coding conventions and best practices

**Comment by maradwan26** [comment]
@Tiss29 You'll need to sign the DCO with [both accounts used](https://github.com/carbon-design-system/carbon/pull/20828#issuecomment-3456212707) to pass the DCO check

File: packages/react/src/components/DatePicker/DatePicker.tsx (hunk 1 above)
Comment (Tiss29) [reply packages/react/src/components/DatePicker/DatePicker.tsx]: yes  I have made the changes can you check

File: packages/styles/scss/components/date-picker/_date-picker.scss (hunk 3 above)
Comment (Tiss29) [reply packages/styles/scss/components/date-picker/_date-picker.scss]: yes  I have made the changes can you check

File: packages/react/src/components/DatePickerInput/DatePickerInput.tsx (hunk 5 above)
Comment (Tiss29) [reply packages/react/src/components/DatePickerInput/DatePickerInput.tsx]: yes  I have made the changes can you check

File: packages/react/src/components/DatePickerInput/DatePickerInput.tsx (hunk 2 above)
Comment (Tiss29) [reply packages/react/src/components/DatePickerInput/DatePickerInput.tsx]: yes I have made the changes can you check

**Comment by Tiss29** [comment]
@maradwan26  I have a doubt regarding the requirement to “sign the DOC with both accounts.”
Could you please clarify which accounts specifically need to sign it?

**Comment by maradwan26** [comment]
@Tiss29 The DCO checker says you need to sign it with @Tiss-Joseph because there are commits authored by that account

**Comment by Tiss-Joseph** [comment]
I have read the DCO document and I hereby sign the DCO.

File: packages/react/src/components/DatePicker/DatePicker.tsx [hunk 6]
```diff
@@ -244,6 +244,11 @@ export interface DatePickerProps {
    */
   disable?: DateLimit<DateOption>[];
 
+  /**
+   * Specify whether or not the input should be disabled
+   */
+  disabled?: boolean;
+
```
Comment (maradwan26) [inline packages/react/src/components/DatePicker/DatePicker.tsx]: This `disabled` prop isn't being used in this file. I think it can be removed

File: packages/web-components/tests/spec/date-picker_spec.ts [hunk 7]
```diff
@@ -294,6 +294,124 @@ describe('cds-date-picker', () => {
     });
   });
 
+  describe('Invalid and Warning States with Disabled/ReadOnly', () => {
```
Comment (maradwan26) [inline packages/web-components/tests/spec/date-picker_spec.ts]: Tests should be in `packages/web-components/src/components/date-picker/__tests__/date-picker-test.js`

**Review by maradwan26 — CHANGES_REQUESTED** [review]
- The invalid outline still shows with the disabled and readonly states in Web Components
Screenshot 2025-10-30 at 1 15 29 PM

- There are also still some added styles in this PR that should be removed as this implementation should only be done in the component file.

- Tests are failing for React

File: packages/web-components/tests/spec/date-picker_spec.ts (hunk 7 above)
Comment (Tiss29) [reply packages/web-components/tests/spec/date-picker_spec.ts]: Okay I have created a test file in that path and moved my test to there

File: packages/react/src/components/DatePicker/DatePicker.tsx (hunk 6 above)
Comment (Tiss29) [reply packages/react/src/components/DatePicker/DatePicker.tsx]: sure will remove all the disabled prop

**Comment by Tiss29** [comment]
@maradwan26 Could please check

File: packages/web-components/src/components/date-picker/__tests__/date-picker-test.js [hunk 8]
```diff
@@ -0,0 +1,132 @@
+/**
+ * Copyright IBM Corp. 2019, 2025
+ *
+ * This source code is licensed under the Apache-2.0 license found in the
+ * LICENSE file in the root directory of this source tree.
+ */
+
+import { html, render } from 'lit';
+
+describe('cds-date-picker', () => {
```
Comment (maradwan26) [inline packages/web-components/src/components/date-picker/__tests__/date-picker-test.js:11]: This test file is failing.

It's also missing these imports:
```
import '@carbon/web-components/es/components/date-picker/index.js';
import { fixture, html, expect } from '@open-wc/testing';

```

File: packages/web-components/src/components/date-picker/__tests__/date-picker-test.js [hunk 9]
```diff
@@ -0,0 +1,132 @@
...
+        html`
+          <cds-date-picker-input
+            invalid
+            invalid-text="Invalid date"
+            disabled
+            label-text="Date Input"></cds-date-picker-input>
+        `,
+        document.body
+      );
+      await Promise.resolve();
```
Comment (maradwan26) [inline packages/web-components/src/components/date-picker/__tests__/date-picker-test.js]:
```suggestion
      const el = await fixture(
        html`
          <cds-date-picker-input
            invalid
            invalid-text="Invalid date"
            disabled
            label-text="Date Input"></cds-date-picker-input>`
            );
    await el.updateComplete;
```

`await fixture` should be used instead, and `document.body` may not be necessary.

See other test files for coding conventions/practices:
- [One](https://github.com/carbon-design-system/carbon/blob/main/packages/web-components/src/components/slider/__tests__/slider-test.js)
- [Two](https://github.com/carbon-design-system/carbon/blob/main/packages/web-components/src/components/time-picker/__tests__/time-picker-test.js)
- [Three](https://github.com/carbon-design-system/carbon/blob/main/packages/web-components/src/components/password-input/__tests__/password-input-test.js)

File: packages/web-components/src/components/date-picker/__tests__/date-picker-test.js [hunk 10]
```diff
@@ -0,0 +1,132 @@
...
+        '.cds--date-picker__icon--warn'
+      );
+      expect(warnIcon).toBeFalsy();
+    });
+  });
+
+  afterEach(async () => {
+    await render(undefined, document.body);
+  });
+});
```
Comment (maradwan26) [inline packages/web-components/src/components/date-picker/__tests__/date-picker-test.js]: This might not be needed after changes are made

**Review by maradwan26 — CHANGES_REQUESTED** [review]
Screenshot 2025-11-06 at 12 24 50 PM

Invalid outline shows when disabled/readonly is set to "true" in Web Components

**Comment by Tiss29** [comment]
@maradwan26 in my web component action I couldn't see invalid 
Screenshot 2025-11-06 at 11 36 26 PM
do I need to enable something while running storybook

**Comment by maradwan26** [comment]
@Tiss29 

The control for `invalid` is missing in the story, but you can manually set it via inspect element, then set `disabled` to `true` with the control panel

Screenshot 2025-11-06 at 1 18 00 PM

You can also add the controls in 

[`date-picker/date-picker.stories.ts`](https://github.com/carbon-design-system/carbon/blob/main/packages/web-components/src/components/date-picker/date-picker.stories.ts)

**Comment by Tiss29** [comment]
@maradwan26 Please recheck

**Comment by maradwan26** [comment]
@Tiss29 

Tests are failing for web components.

You can run the tests locally by running `yarn web-test-runner "src/components/date-picker/__tests__/date-picker-test.js"` in `packages/web-components`

**Comment by Tiss29** [comment]
@maradwan26 I fix the test
Screenshot 2025-11-24 at 2 23 14 PM

File: packages/web-components/src/components/date-picker/date-picker.scss [hunk 11]
```diff
@@ -77,12 +77,24 @@ $css--plex: true !default;
     display: none;
   }
 }
-:host(#{$prefix}-date-picker-input[warn]) {
+:host(#{$prefix}-date-picker-input[warn]:not([disabled]):not([readonly])) {
```
Comment (maradwan26) [inline packages/web-components/src/components/date-picker/date-picker.scss]:
```suggestion
:host(#{$prefix}-date-picker-input[warn]:not([invalid])) {
```

The warn-text doesn't render when disabled/readonly are true so this isn't really needed. It would be better to do `:not[(invalid)]` so that this colour does not show on the invalid-text if warn and invalid are both true

File: packages/web-components/src/components/date-picker/date-picker.scss [hunk 12]
```diff
@@ -77,12 +77,24 @@ $css--plex: true !default;
...
+  .#{$prefix}--form-requirement {
+    display: none;
+  }
+
+  .#{$prefix}--date-picker__input--invalid,
+  .#{$prefix}--date-picker__input--warn {
+    border-block-end: 1px solid transparent;
+  }
+}
+
```
Comment (maradwan26) [inline packages/web-components/src/components/date-picker/date-picker.scss]:
```suggestion
```

Same here, this is already accounted for in the component `.ts` file

File: packages/web-components/tests/spec/date-picker_spec.ts [hunk 13]
```diff
@@ -76,7 +76,7 @@ describe('cds-date-picker', () => {
       datePicker = document.body.querySelector('cds-date-picker');
```
Comment (maradwan26) [inline packages/web-components/tests/spec/date-picker_spec.ts:76]: I think you should be good to leave this file unchanged.

**Review by maradwan26 — APPROVED** [review]
LGTM just a couple final suggestions/tweaks!

File: packages/web-components/src/components/date-picker/__tests__/date-picker-test.js [hunk 14]
```diff
@@ -0,0 +1,238 @@
...
+
+      const formRequirement = el.shadowRoot?.querySelector(
+        '.cds--form-requirement'
+      );
+      expect(formRequirement?.textContent?.trim()).to.equal(warnText);
+    });
+  });
+});
+
+// Made with Bob
```
Comment (maradwan26) [inline packages/web-components/src/components/date-picker/__tests__/date-picker-test.js]:
```suggestion
```

File: packages/web-components/src/components/date-picker/date-picker.scss (hunk 12 above)
Comment (Tiss29) [reply packages/web-components/src/components/date-picker/date-picker.scss]: okay I will remove them

File: packages/web-components/tests/spec/date-picker_spec.ts (hunk 13 above)
Comment (Tiss29) [reply packages/web-components/tests/spec/date-picker_spec.ts:76]: okay will revert

**Comment by Tiss29** [comment]
@maradwan26 @alisonjoseph Please check

**Comment by Tiss29** [comment]
@maradwan26 @alisonjoseph Please check

File: packages/web-components/src/components/date-picker/date-picker.scss [hunk 15]
```diff
@@ -77,7 +77,7 @@ $css--plex: true !default;
     display: none;
   }
 }
-:host(#{$prefix}-date-picker-input[warn]) {
+:host(#{$prefix}-date-picker-input[warn]:not([disabled]):not([readonly])) {
```
Comment (maradwan26) [inline packages/web-components/src/components/date-picker/date-picker.scss]:
```suggestion
:host(#{$prefix}-date-picker-input[warn]:not([invalid])) {
```

Seems the change was reverted

**Review by maradwan26 — APPROVED** [review]

**Comment by maradwan26** [comment]
Format ci test is failing, should be able to fix it by just running Prettier on the culprit file: `packages/web-components/src/components/date-picker/__tests__/date-picker-test.js
`

**Review by alisonjoseph — APPROVED** [review]
LGTM! I pushed the small format fix so CI should pass.
