### PR TITLE
fix(dropdown): Disallow invalid & warn when readonly or disabled

### LINKED ISSUE #20723: [Dropdown]: Disallow invalid & warn when readonly or disabled

### PR DESCRIPTION
**Pull request by jvictorfsilva**
Closes #20723

Fix Dropdown showing validation states when disabled or readonly

### Description

Prevents dropdown components (React and Web Components) from displaying invalid/warn states when in disabled or readonly mode, as users cannot interact with non-interactive components to fix validation issues.

### Changelog

**Changed**

**React Component (`Dropdown.tsx`):**
- Added `isInteractive` flag (`!readOnly && !disabled`) to conditionally show validation states
- Introduced derived values `showInvalid` and `showWarning` based on interactivity
- Applied consistently across: CSS classes, ListBox props, validation icons, aria-describedby, and helper text rendering

**Web Components (`dropdown.ts`):**
- Changed `invalid` and `warn` properties from `reflect: true` to `reflect: false`
- Added manual attribute reflection in `updated()` method to control when attributes appear on host element
- Implemented same `isInteractive` logic in `_classes` getter and `render()` method
- Fixed `shouldUpdate()` to properly enable/disable child items when `disabled` property toggles
- Applied validation state logic to: CSS classes, helper text classes, validation icons, and helper message display

#### Testing / Reviewing

**React Component:**
1. Open Dropdown component in Storybook
2. Set `invalid={true}` and `invalidText="Error message"`
3. Verify invalid state is visible (red border, error icon, error text)
4. Set `disabled={true}`
5. Verify invalid state is hidden (no red border, no error icon, helper text shown instead)
6. Set `disabled={false}`
7. Verify invalid state returns
8. Repeat steps 4-7 with `readOnly={true}`
9. Test same flow with `warn` prop

**Web Components:**
1. Create dropdown with `invalid` and `invalid-text="Error message"`
2. Verify invalid state is visible
3. Inspect element - confirm `invalid` attribute exists on `<cds-dropdown>`
4. Set `disabled` attribute
5. Verify invalid state is hidden and `invalid` attribute is removed from host
6. Repeat with `read-only` attribute

**Expected behavior:**
- When `disabled=true` or `readOnly=true`: No validation classes, no validation icons, no validation text, no validation attributes on host element
- When interactive (default): Validation states display normally
- Helper text displays when non-interactive, validation text displays when interactive and invalid/warn

**Previous behavior:**
- Validation states (invalid/warn) were shown even when user couldn't interact with the component
- Created confusing UX where disabled/readonly fields showed errors users couldn't fix

#### Accessibility Impact

**Improved:**
- `aria-describedby` correctly associates helper text instead of validation text when non-interactive
- Validation attributes removed from host element when non-interactive, preventing screen readers from announcing errors on disabled/readonly fields
- Helper text remains available to assistive technologies for disabled/readonly states

## PR Checklist

As the author of this PR, before marking ready for review, confirm you:

- [x] Reviewed every line of the diff
- [x] Wrote passing tests that cover this change
- [x] Addressed any impact on accessibility (a11y)
- [x] Tested for cross-browser consistency
- [x] Validated that this code is ready for review and status checks should pass

More details can be found in the [pull request guide](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/reviewing-pull-requests.md)

### CODE REVIEW

**Review by riddhybansal — CHANGES_REQUESTED** [review]
Hey this looks good 

Small Suggestions for Improvement
Code Consistency

Consider using useNormalizedInputProps in all components rather than creating separate validation logic:

 normalizedProps = useNormalizedInputProps({
  id, disabled, readOnly, invalid, invalidText, warn, warnText,
});

Then reference normalizedProps.invalid and normalizedProps.warn for validation states
Our input controls already use this pattern, which makes future fixes simpler (just update the hook once).

Here is the reference [PR](https://github.com/carbon-design-system/carbon/pull/20808)

**Comment by jvictorfsilva** [comment]
The changes have been applied. Could you please add the Hacktoberfest label? If possible, also include it on pull request #20791

**Review by riddhybansal — CHANGES_REQUESTED** [review]
Hi there, the React implementation works as expected, but I've identified an issue with the web-components version. When a component is in an invalid state and I enable the disabled attribute, the invalid styles correctly disappear. However, when I subsequently remove the disabled attribute while the component remains invalid, the invalid styles fail to reappear as they should.


https://github.com/user-attachments/assets/c8d6a4bc-b3d4-4c52-a35b-d3791cb28445

**Comment by jvictorfsilva** [comment]
I've completed the requested changes. Do you have any estimate on when my other pull request might be reviewed?

File: packages/web-components/src/components/dropdown/__tests__/dropdown-test.js [hunk 1]
```diff
@@ -292,9 +292,6 @@ describe('cds-dropdown', function () {
 
       await el.updateComplete;
 
-      // Should have the ai-label attribute
-      expect(el.hasAttribute('ai-label')).to.be.true;
-
```
Comment (maradwan26) [inline packages/web-components/src/components/dropdown/__tests__/dropdown-test.js:297]: Just wondering was there a reason for removing this?

**Review by maradwan26 — COMMENTED** [review]
Thanks for contributing! Just one small comment, the rest LGTM

File: packages/web-components/src/components/dropdown/__tests__/dropdown-test.js (hunk 1 above)
Comment (jvictorfsilva) [reply packages/web-components/src/components/dropdown/__tests__/dropdown-test.js:297]: Sorry, I removed this part of the code while testing. I’ve pushed a new commit adding it back.

**Review by maradwan26 — APPROVED** [review]
Thx! LGTM

**Review by alisonjoseph — APPROVED** [review]

**Comment by heloiselui** [comment]
@riddhybansal could you approve this PR so we can merge it? I think you requested some changes. Thanks!

**Review by riddhybansal — APPROVED** [review]
