### PR TITLE
fix(modal): focus trap within modal

### LINKED ISSUE #2939: [Modal; Vanilla] Carry React focus trap functionality to Vanilla implementation
Watson Health is using the Vanilla JavaScript of Carbon.  The React version of Modal traps focus within the Modal but the vanilla does not appear to have this functionality.  Due to compliance regulations we need this functionality carried over.

## Environment

> Operating system

Mac

> Browser

Chrome

> Automated testing tool and ruleset

> Assistive technology used to verify

Keyboard

## Detailed description

> What version of the Carbon Design System are you using?

v10.2.0

> What did you expect to happen?

When I'm tabbing within the Modal, focus should remain within the modal and not be able to move to other elements within the page

> What happened instead?

I could tab to elements on the page when the modal is open

> What WCAG 2.1 checkpoint does the issue violate?

https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal

## Steps to reproduce the issue

1. Open a modal
2. tab until you've gone through all of the elements in the modal
3. press tab
4. element outside of modal has focus

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/modal-2vjuw

### PR DESCRIPTION
**Pull request by elizabethsjudd**
Closes #2939

Update modal to trap focus when opened without focusing a "hidden element". Carried over the selectorTabble from [@asudoh's web components work](https://github.com/carbon-design-system/carbon-custom-elements/pull/22/files#diff-7b81c66d6f3e9c4b82c40ee5ecd30e50)

## To Do
- [x] Move focus when the modal closes
- [x] Update tests

#### Changelog

**New**

- added selectorTabbable to global settings object

**Changed**

- set focus on the first selectorTabbable element found within the modal

#### Testing / Reviewing

Test keyboard navigation for each type of modal

### CODE REVIEW

File: packages/components/src/globals/js/settings.js [hunk 1]
```diff
@@ -22,4 +22,23 @@
...
+/**
+ * A selector selecting tabbable nodes.
+ * Borrowed from `carbon-angular`. tabbable === focusable.
+ */
+settings.selectorTabbable = `
+  a[href], area[href], input:not([disabled]):not([tabindex='-1']),
+  button:not([disabled]):not([tabindex='-1']),select:not([disabled]):not([tabindex='-1']),
+  textarea:not([disabled]):not([tabindex='-1']),
+  iframe, object, embed, *[tabindex]:not([tabindex='-1']), *[contenteditable=true],
+  ${settings.prefix}-btn,
```
Comment (asudoh) [inline packages/components/src/globals/js/settings.js]: The tag selectors beginning with `${settings.prefix}` are specific to custom elements codebase and thus vanilla/React won't need it.

File: packages/components/src/components/modal/modal.js [hunk 2]
```diff
@@ -136,6 +136,9 @@ class Modal extends mixin(
         this.options.classBody,
         false
       );
+      // Trying to add in the ability to move the focus back to the trigger or a dev-defined element but I don't know
```
Comment (asudoh) [inline packages/components/src/components/modal/modal.js]: As you can see, the "focus-pop" behavior hasn't been implemented yet. I think the approach will be keep a ref to `this.element.ownerDocument.activeElement` right before we move focus upon opening modal.

**Review by asudoh — COMMENTED** [review]
Great to see you jumping in @elizabethsjudd!

File: packages/components/src/components/modal/modal.js [hunk 3]
```diff
@@ -105,7 +105,7 @@ class Modal extends mixin(
       ) {
         (
           this.element.querySelector(this.options.selectorPrimaryFocus) ||
-          this.element
+          this.element.querySelector(settings.selectorTabbable)
```
Comment (asudoh) [inline packages/components/src/components/modal/modal.js]: Just wondered if we should have an escape hatch for the condition where `this.element.querySelector(settings.selectorTabbable)` yields `null`.

Comment (elizabethsjudd) [reply packages/components/src/components/modal/modal.js]: while I understand the concern for this, there should always be at least one button in a modal and buttons should always be in the `selectorTabbable`. Do we want to put an explicit `button` check incase something is overwritten in `selectorTabbable` incorrectly?

**Comment by elizabethsjudd** [comment]
I could use some help getting Circle CI to pass. I ran `yarn ci-check` successfully locally (which is what added the linting files to the PR).

File: packages/components/src/components/modal/modal.js (hunk 3 above)
Comment (asudoh) [reply packages/components/src/components/modal/modal.js]: I think the escape hatch we need is for the edge case where the condition of "a button should already be there" is not met. If you think it's a very edge case it's fine, because it'll be just focus getting lost.

Comment (elizabethsjudd) [reply packages/components/src/components/modal/modal.js]: I do think that it's a very edge case and there should be something that goes wrong, meaning the focus gets lost, because that means that something isn't implemented correctly. If this happens it means that `selectorTabbable` doesn't have every type of element it should or the Modal doesn't have interactive elements that it should. I do feel like it would be appropriate to throw a console warning, if it comes back null, to inform the developer.  Does Carbon have a standardized way of throwing warnings to developers?

Comment (asudoh) [reply packages/components/src/components/modal/modal.js]: Makes sense - We use [`warning` library](https://www.npmjs.com/package/warning) for this purpose.

**Comment by elizabethsjudd** [comment]
@carbon-design-system/developers prettier and eslint are contradicting each other so I'm unable to commit my latest work to this PR.

prettier wants:
```
warning(
  focusableItem,
  `Modals need to contain a focusable element by either using \`${this.options.selectorPrimaryFocus}\` or settings.selectorTabbable.`
);
```

eslint wants:
```
warning(
  focusableItem,
  `Modals need to contain a focusable element by either using \`${
    this.options.selectorPrimaryFocus
  }\` or settings.selectorTabbable.`
);
```

How do I resolve this so I can commit the work?

**Comment by asudoh** [comment]
@elizabethsjudd Do you want to try `git commit --no-verify`? CI may fail but in this way we can see what problem you are stumbling at.

**Comment by elizabethsjudd** [comment]
@asudoh https://github.com/carbon-design-system/carbon/pull/3456/commits/55a3625516059d72309eda9ae30fed0d79701a3c is the commit I had issues with and had to use `--no-verify`

File: packages/components/src/components/modal/modal.js [hunk 4]
```diff
@@ -104,10 +104,18 @@ class Modal extends mixin(
...
       ) {
         this.previouslyFocusedNode = this.element.ownerDocument.activeElement;
-        (
+        const focusableItem =
           this.element.querySelector(this.options.selectorPrimaryFocus) ||
-          this.element.querySelector(settings.selectorTabbable)
-        ).focus();
+          this.element.querySelector(settings.selectorTabbable);
+        focusableItem.focus();
+        if (__DEV__ && focusableItem === null) {
```
Comment (asudoh) [inline packages/components/src/components/modal/modal.js]: The 1st argument is `warning()` is like C `assert()`. That said, you don't need `focusableItem === null` here.

**Comment by asudoh** [comment]
Thanks @elizabethsjudd - Seems that the CI is passing after syncing to `master`. So I guess you are all set!

File: packages/components/src/components/modal/modal.js [hunk 5]
```diff
@@ -136,6 +145,12 @@ class Modal extends mixin(
         this.options.classBody,
         false
       );
+      if (this.options.selectorFocusOnClose || this.previouslyFocusedNode)
```
Comment (asudoh) [inline packages/components/src/components/modal/modal.js]: Not sure why our ESLint didn't catch this, but we mandate curly braces for every `if()` block.

**Review by asudoh — COMMENTED** [review]
Thank you for the updates @elizabethsjudd! Just one last thing.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @elizabethsjudd for the update!

**Review by dakahn — APPROVED** [review]

**Comment by elizabethsjudd** [comment]
@asudoh @tw15egan The test that is failing is the same one that I was having issues with [here](https://github.com/carbon-design-system/carbon/pull/3456#issuecomment-514634294). [This comment ](https://github.com/carbon-design-system/carbon/pull/3456#issuecomment-514329954)outlines the issue I was having

**Comment by asudoh** [comment]
@elizabethsjudd Would you try splitting the long template string in question to two? Like:

```javascript
`Modals need to contain a focusable element by either using ` +
  `\`${this.options.selectorPrimaryFocus}\` or settings.selectorTabbable.`
```
