### PR TITLE
fix(Tabs): ignore disabled tabs on keyboard navigation

### LINKED ISSUE #1495: Tabs component needs more keyboard behavior for improved accessibility
The [Carbon Tabs component](http://www.carbondesignsystem.com/components/tabs/code) could benefit from adding **Home**, **End**, and **Space** key behavior as listed in the Keyboard Interaction section of the [ARIA Practices Guide for Tabs](http://w3c.github.io/aria-practices/#tabpanel).

Rationale:
- **Space**: Many users expect to be able to use the **Space** key to activate a Tab. They might not think of typing **Enter**. Please support both methods.
- **Home/End**: Since Carbon's Tabs are not "single-tab-stop" (the APG ones are), keyboard users need to type the tab key once per Tab (instead of just once for the whole Tabs component) before they can move past the component. If the **Home** and **End** keys were implemented, then at least there would be a quicker way to bypass the component if there are many Tabs.

### LINKED ISSUE #2880: [Tabs]: Disabled tabs are still clickable and active
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Passing the disabled prop to a tab only impacts the style, the Tabs component will still switch contents when a disabled tab is clicked

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Disabled tabs should have no effect when clicked

## Steps to reproduce the issue

1. Go to [tabs storybook](http://react.carbondesignsystem.com/?selectedKind=Tabs&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel)
2. Under the `knobs` panel of storybook enable the `Disabled` knob
3. Click the tabs, they are still active and change the content of the Tabs component

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2880
Closes #1495 (our tabs are now "single tab stop")

This PR modifies the tab navigation logic to cycle through enabled tabs only rather than blindly looping through the tab list. It also resolves a performance issue when cycling through tabs

#### Testing / Reviewing

cycle through the tab list with the arrow keys and ensure that disabled tabs are ignored

(notice that the focus outline jump occurs at the same time as the font weight change rather than a second later)

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

File: packages/react/src/components/Tabs/Tabs.js [hunk 1]
```diff
@@ -139,35 +146,47 @@ export default class Tabs extends React.Component {
...
+      return -1;
+    }
+    if (match(evt, keys.ArrowRight)) {
+      return 1;
+    }
+    return 0;
+  };
+
+  getNextIndex = (index, direction) => {
+    const enabledTabs = this.getEnabledTabs();
```
Comment (joshblack) [inline packages/react/src/components/Tabs/Tabs.js:160]: Would we want to use this helper at all: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/internal/keyboard/navigation.js#L27

File: packages/react/src/components/Tabs/Tabs.js [hunk 2]
```diff
@@ -116,6 +117,12 @@ export default class Tabs extends React.Component {
     return React.Children.map(this.props.children, tab => tab);
   }
 
+  getEnabledTabs = () =>
+    React.Children.toArray(this.props.children).reduce(
+      (acc, tab, index) => (!tab.props.disabled ? acc.concat(index) : acc),
```
Comment (joshblack) [inline packages/react/src/components/Tabs/Tabs.js:122]: When we're looping through children, do we ever need to do null checks? Wasn't sure about `toArray` but was just remembering some issues with UI Shell where this was coming up.

**Review by joshblack — DISMISSED** [review]

File: packages/react/src/components/Tabs/Tabs.js (hunk 1 above)
Comment (emyarod) [reply packages/react/src/components/Tabs/Tabs.js:160]: that doesn't look like a drop-in replacement for the function I have currently

File: packages/react/src/components/Tabs/Tabs.js (hunk 2 above)
Comment (emyarod) [reply packages/react/src/components/Tabs/Tabs.js:122]: as far as I know `React.Children.toArray` removes nulls

ref https://github.com/facebook/react/blob/master/packages/react/src/__tests__/ReactChildren-test.js#L815

**Review by jillianhowarth — COMMENTED** [review]
The focus area jumps a second after the font-weight change for me

File: packages/react/src/components/Tabs/Tabs.js (hunk 1 above)
Comment (joshblack) [reply packages/react/src/components/Tabs/Tabs.js:160]: Just was speaking to figuring out the `nextIndex` and using a ring buffer instead of the current logic 👍

Comment (emyarod) [reply packages/react/src/components/Tabs/Tabs.js:160]: how does it account for disabled tab indices?

**Comment by emyarod** [comment]
@jillianhowarth is that the case with the full story view? https://deploy-preview-4784--carbon-components-react.netlify.com/iframe.html?id=tabs--default

seems the issue still persists with the normal story view but is likely storybook related

**Review by jillianhowarth — APPROVED** [review]
@emyarod  it works great with full story view. Thanks!

File: packages/react/src/components/Tabs/Tabs.js (hunk 1 above)
Comment (joshblack) [reply packages/react/src/components/Tabs/Tabs.js:160]: @emyarod if I understand correctly, the ring buffer would be done on a filtered down version of tabs, correct?

```js
const tabs = [
  {
    title: 'Tab A',
    disabled: false,
  },
  {
    title: 'Tab B',
    disabled: true,
  },
  {
    title: 'Tab B',
    disabled: false,
  },
];

const enabledTabs = tabs.filter(tab => !tab.disabled);
getNextIndex(ArrowRight, 0, enabledTabs.length); // 1
getNextIndex(ArrowRight, 1, enabledTabs.length); // 0
getNextIndex(ArrowLeft, 0, enabledTabs.length); // 1
```

Definitely get that it's not mapping exactly 1:1, but just was seeing if the pattern was worthwhile to match 👍

File: packages/react/src/components/Tabs/Tabs-test.js [hunk 3]
```diff
@@ -241,6 +252,48 @@ describe('Tabs', () => {
           expect(wrapper.state().selected).toEqual(1);
         });
       });
+
+      describe('ignore disabled child tab', () => {
+        const wrapper = mount(
```
Comment (joshblack) [inline packages/react/src/components/Tabs/Tabs-test.js]: Any chance we could move `mount` into either a `beforeEach` type block or into a generator function that creates the wrapper? This pattern can cause non-deterministic tests, unfortunately 😞

File: packages/react/src/components/Tabs/Tabs.js (hunk 1 above)
Comment (emyarod) [reply packages/react/src/components/Tabs/Tabs.js:160]: the returned index from that function corresponds to the element's location in the filtered array and not the full array. but if you are just referring to the pattern then I have implemented it already, I'm just also accounting for the fact that the component is expecting the full array and not only the enabled tabs

**Review by tw15egan — APPROVED** [review]
Performance fixes look good (in full view anyways, storybook still has issues). Confirmed no longer able to arrow through disabled tabs. 👍

**Comment by anibapat** [comment]
This fixes the issue with the keyboard nav on the disabled tab, but now creates another problem where it is not possible to come out from the Tabs, i.e when I hit Tab (instead of arrow keys), the focus should go to the content section. Now, it is not going to content. 

E.g  https://codesandbox.io/s/codesandbox-86xgt

I have a button under Tab3, which should take focus on pressing Tab,  which was working before the fix).

cc @joshblack @emyarod

**Comment by emyarod** [comment]
addressed in https://github.com/carbon-design-system/carbon/pull/5124
